import { StyleSheet } from "react-native";
import { DS_COLORS, DS_SPACING, DS_TYPOGRAPHY, DS_RADIUS } from "@/lib/design-system";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DS_COLORS.BG_PAGE },
  tabShell: { flex: 1 },
  scrollContent: { paddingBottom: 32 },
  screenTitle: {
    fontSize: 26,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    letterSpacing: -0.5,
    paddingHorizontal: 18,
    paddingTop: 8,
    marginBottom: 14,
  },
  mainSwitcher: {
    marginHorizontal: 12,
    marginBottom: 14,
    backgroundColor: DS_COLORS.ONBOARDING_BORDER,
    borderRadius: DS_RADIUS.MD,
    padding: 3,
    flexDirection: "row",
    gap: 3,
  },
  mainTab: { flex: 1, paddingVertical: 8, borderRadius: DS_RADIUS.MD, alignItems: "center" },
  mainTabOn: { backgroundColor: DS_COLORS.WHITE },
  mainTabText: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_MUTED },
  mainTabTextOn: { color: DS_COLORS.TEXT_PRIMARY },
  groupLabel: {
    fontSize: 10,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.TAB_INACTIVE,
    letterSpacing: 1.2,
    paddingHorizontal: 16,
    marginBottom: 8,
    marginTop: 4,
  },
  notifRow: {
    backgroundColor: DS_COLORS.WHITE,
    marginHorizontal: 12,
    marginBottom: 6,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 12,
    paddingRight: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  notifUnread: { borderLeftWidth: 3, borderLeftColor: DS_COLORS.DISCOVER_CORAL, paddingLeft: 10 },
  notifRead: { paddingLeft: 13 },
  avatarWrap: { position: "relative", flexShrink: 0, marginLeft: 4 },
  notifAvatar: {
    width: 36,
    height: 36,
    borderRadius: DS_RADIUS.XL,
    alignItems: "center",
    justifyContent: "center",
  },
  notifAvatarLetter: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  typeBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: DS_RADIUS.SM,
    borderWidth: 1.5,
    borderColor: DS_COLORS.BG_PAGE,
    alignItems: "center",
    justifyContent: "center",
  },
  typeBadgeText: { fontSize: 9, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  typeBadgeFollow: { color: DS_COLORS.WHITE, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  notifBody: { flex: 1 },
  notifMain: { fontSize: 12, color: DS_COLORS.grayDarker, lineHeight: 17 },
  notifBold: { fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  notifTime: { fontSize: 10, color: DS_COLORS.TEXT_MUTED, marginTop: 2, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  followBtn: {
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.PILL,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  followBtnText: { fontSize: 11, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  frActions: { flexDirection: "row", gap: 8, flexShrink: 0 },
  frAcceptBtn: {
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  frAcceptTxt: { fontSize: 12, fontWeight: "500", color: DS_COLORS.WHITE },
  frDeclineBtn: {
    borderWidth: 1,
    borderColor: DS_COLORS.BORDER,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  frDeclineTxt: { fontSize: 12, fontWeight: "500", color: DS_COLORS.TEXT_SECONDARY },
  frAccepted: { fontSize: 12, fontWeight: "500", color: DS_COLORS.PROFILE_SUCCESS },
  thumbPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: DS_RADIUS.SM,
    backgroundColor: DS_COLORS.BG_DARK,
    alignItems: "center",
    justifyContent: "center",
  },
  thumbEmoji: { fontSize: 16, opacity: 0.6 },
  scopeSwitcher: {
    marginHorizontal: 12,
    marginBottom: 14,
    backgroundColor: DS_COLORS.ONBOARDING_BORDER,
    borderRadius: DS_RADIUS.MD,
    padding: 3,
    flexDirection: "row",
    gap: 3,
  },
  scopeTab: { flex: 1, paddingVertical: 8, borderRadius: DS_RADIUS.MD, alignItems: "center" },
  scopeTabOn: { backgroundColor: DS_COLORS.WHITE },
  scopeTabText: { fontSize: 11, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_MUTED },
  scopeTabTextOn: { color: DS_COLORS.TEXT_PRIMARY },
  scoreNote: {
    backgroundColor: DS_COLORS.WHITE,
    borderRadius: DS_RADIUS.MD,
    marginHorizontal: 12,
    marginBottom: 12,
    paddingHorizontal: 13,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  scoreNoteWarm: {
    backgroundColor: DS_COLORS.FEATURED_BG,
    borderRadius: DS_RADIUS.MD,
    marginHorizontal: DS_SPACING.MD,
    marginBottom: 12,
    padding: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  scoreNoteIcon: { fontSize: 14, marginTop: 1 },
  scoreNoteText: { flex: 1, fontSize: 12, color: DS_COLORS.TEXT_SECONDARY, lineHeight: 18 },
  scoreNoteBold: { fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  crownCard: {
    backgroundColor: DS_COLORS.TEXT_PRIMARY,
    borderRadius: DS_RADIUS.XL,
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 16,
    position: "relative",
    overflow: "hidden",
  },
  crownEyebrow: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 10 },
  crownDot: { width: 5, height: 5, borderRadius: 2.5, backgroundColor: DS_COLORS.CELEB_BONUS_AMBER },
  crownEyebrowText: {
    fontSize: 9,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.CELEB_BONUS_AMBER,
    letterSpacing: 1.2,
  },
  crownMainRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 12 },
  crownRank: { fontSize: 22, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.CELEB_BONUS_AMBER, width: 28 },
  crownAvatar: { width: 38, height: 38, borderRadius: DS_RADIUS.XL, alignItems: "center", justifyContent: "center" },
  crownAvatarLetter: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  crownName: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  crownStreakPill: {
    backgroundColor: DS_COLORS.CELEB_BONUS_AMBER_BG,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: DS_RADIUS.PILL,
    opacity: 0.45,
  },
  crownStreakText: { fontSize: 9, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.CELEB_BONUS_AMBER },
  crownSubWrap: { marginTop: 2, opacity: 0.55 },
  crownSub: { fontSize: 11, color: DS_COLORS.TEXT_ON_DARK, lineHeight: 15 },
  crownPts: { fontSize: 20, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.CELEB_BONUS_AMBER, lineHeight: 20 },
  crownPtsLabelWrap: { opacity: 0.45 },
  crownPtsLabel: { fontSize: 9, color: DS_COLORS.TEXT_ON_DARK, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  regRow: {
    position: "relative",
    backgroundColor: DS_COLORS.WHITE,
    borderRadius: DS_RADIUS.button,
    marginHorizontal: 12,
    marginBottom: 6,
    paddingHorizontal: 13,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    overflow: "hidden",
  },
  rowSelfAccent: {
    position: "absolute",
    left: 0,
    top: 4,
    bottom: 4,
    width: 3,
    borderRadius: DS_RADIUS.SM,
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
  },
  regRank: { width: 24, textAlign: "center", fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  regAvatar: { width: 36, height: 36, borderRadius: DS_RADIUS.XL, alignItems: "center", justifyContent: "center" },
  regAvatarLetter: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  regName: { fontSize: 12, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  regStreakPill: {
    backgroundColor: DS_COLORS.ACCENT_TINT,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: DS_RADIUS.PILL,
  },
  regStreakText: { fontSize: 9, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.DISCOVER_CORAL },
  regSub: { fontSize: 10, color: DS_COLORS.TAB_INACTIVE, marginTop: 1 },
  regSubMuted: { fontSize: 11, color: DS_COLORS.TEXT_MUTED, marginTop: 2, lineHeight: 14 },
  regTrack: {
    height: 2,
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    borderRadius: DS_RADIUS.PILL,
    marginTop: 6,
    overflow: "hidden",
  },
  regFill: { height: 2, backgroundColor: DS_COLORS.DISCOVER_CORAL, borderRadius: DS_RADIUS.PILL },
  regPts: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  regPtsLabel: { fontSize: 9, color: DS_COLORS.TEXT_MUTED, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
  yourRankDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: DS_COLORS.DIVIDER },
  yourRankLabel: { fontSize: 10, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_MUTED },
  yourCard: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginHorizontal: 12,
    marginBottom: 12,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderRadius: DS_RADIUS.button,
    backgroundColor: DS_COLORS.ACCENT_TINT,
    borderWidth: 1.5,
    borderColor: DS_COLORS.ACCENT_TINT_BORDER,
    overflow: "hidden",
  },
  yourRankNum: { width: 24, textAlign: "center", fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.DISCOVER_CORAL },
  yourName: { fontSize: 12, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.DISCOVER_CORAL },
  yourSub: { fontSize: 10, color: DS_COLORS.TEXT_SECONDARY, marginTop: 1 },
  yourSubMuted: { fontSize: 11, color: DS_COLORS.TEXT_MUTED, marginTop: 2, lineHeight: 14 },
  yourPts: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.DISCOVER_CORAL },
  challengePills: { paddingHorizontal: 12, paddingBottom: 12, gap: 8 },
  challengePillsRow: {
    paddingHorizontal: DS_SPACING.MD,
    paddingBottom: 4,
    gap: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  challengePillNew: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: DS_RADIUS.XL,
    marginRight: 8,
    maxWidth: 220,
  },
  challengePillNewOn: { backgroundColor: DS_COLORS.DISCOVER_CORAL },
  challengePillNewOff: { backgroundColor: DS_COLORS.BG_CARD_TINTED },
  challengePillNewText: { fontSize: 12, fontWeight: "500" },
  challengePillNewTextOn: { color: DS_COLORS.WHITE },
  challengePillNewTextOff: { color: DS_COLORS.TEXT_SECONDARY },
  challengeScopeToggle: {
    flexDirection: "row",
    marginTop: 10,
    marginBottom: 10,
    marginHorizontal: DS_SPACING.MD,
  },
  challengeScopeTab: {
    flex: 1,
    alignItems: "center",
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: DS_COLORS.BORDER,
  },
  challengeScopeTabText: { fontSize: 12, fontWeight: "500" },
  soloChallengeHint: {
    alignItems: "center",
    paddingHorizontal: DS_SPACING.XL,
    paddingBottom: 24,
    gap: 6,
  },
  soloChallengeHintText: { fontSize: 13, color: DS_COLORS.TEXT_SECONDARY, textAlign: "center" },
  youBadge: {
    backgroundColor: DS_COLORS.ACCENT_TINT,
    borderRadius: DS_RADIUS.SM,
    paddingHorizontal: 5,
    paddingVertical: 1,
    marginLeft: 4,
  },
  youBadgeText: { fontSize: 10, color: DS_COLORS.DISCOVER_CORAL, fontWeight: "500" },
  youBadgeDark: {
    backgroundColor: DS_COLORS.CELEB_BONUS_AMBER_BG,
    borderRadius: DS_RADIUS.SM,
    paddingHorizontal: 5,
    paddingVertical: 1,
    marginLeft: 4,
    opacity: 0.9,
  },
  youBadgeDarkText: { fontSize: 10, color: DS_COLORS.CELEB_BONUS_AMBER, fontWeight: "500" },
  challengePill: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: DS_RADIUS.PILL,
    marginRight: 8,
    maxWidth: 200,
  },
  challengePillOn: { backgroundColor: DS_COLORS.DISCOVER_CORAL },
  challengePillOff: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: DS_COLORS.TEXT_SECONDARY,
  },
  challengePillText: { fontSize: 11, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_SECONDARY },
  challengePillTextOn: { color: DS_COLORS.WHITE },
  privacyPill: {
    marginHorizontal: 12,
    marginBottom: 10,
    alignSelf: "flex-start",
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: DS_RADIUS.XL,
  },
  privacyPillText: { fontSize: 10, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  teamEmpty: { paddingVertical: 40, alignItems: "center", paddingHorizontal: 24 },
  teamEmptyEmoji: { fontSize: 36, opacity: 0.25, marginBottom: 12 },
  teamEmptySub: { fontSize: 12, color: DS_COLORS.TEXT_SECONDARY, textAlign: "center", lineHeight: 18 },
  findTeamBtn: {
    marginTop: 16,
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.PILL,
    paddingVertical: 10,
    paddingHorizontal: 22,
  },
  findTeamBtnText: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  teamTitle: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  emptyLb: { paddingVertical: 24, alignItems: "center", paddingHorizontal: 20 },
  emptyState: { alignItems: "center", paddingVertical: 48, paddingHorizontal: 24 },
  emptyStateFill: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: DS_SPACING.XL,
    paddingVertical: 48,
    minHeight: 280,
  },
  emptyIconCircle: {
    width: 72,
    height: 72,
    borderRadius: DS_RADIUS.LG,
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitleStrong: {
    fontSize: 15,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    marginTop: 16,
    textAlign: "center",
  },
  emptyBodyNarrow: {
    fontSize: 13,
    color: DS_COLORS.TEXT_SECONDARY,
    textAlign: "center",
    lineHeight: 19,
    maxWidth: 280,
    marginTop: 6,
  },
  emptyFootnote: {
    fontSize: 12,
    color: DS_COLORS.TEXT_MUTED,
    marginTop: 4,
    textAlign: "center",
  },
  emptyTextCta: {
    marginTop: 20,
    fontSize: 13,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.DISCOVER_CORAL,
  },
  emptyInvitePill: {
    marginTop: 20,
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: 10,
    paddingHorizontal: 28,
  },
  emptyInvitePillText: { color: DS_COLORS.WHITE, fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: DS_COLORS.TEXT_PRIMARY,
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
  },
  emptySub: { fontSize: 12, color: DS_COLORS.TEXT_SECONDARY, textAlign: "center" },
  emptyBody: {
    fontSize: 14,
    color: DS_COLORS.TEXT_SECONDARY,
    textAlign: "center",
    lineHeight: 21,
  },
  emptyButton: {
    marginTop: 20,
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: DS_RADIUS.joinCta,
  },
  emptyButtonText: {
    color: DS_COLORS.WHITE,
    fontSize: 14,
    fontWeight: "500",
  },
  guestWrap: { padding: 24 },
  guestText: { fontSize: 14, color: DS_COLORS.TEXT_SECONDARY, textAlign: "center" },
  iconMuted: { opacity: 0.4 },
  lbSkeletonPad: { paddingHorizontal: 12, paddingTop: 8 },
  leaderboardFlatFlex: { flex: 1 },
  boardListSection: { marginBottom: 24 },
  flex1: { flex: 1 },
  alignEnd: { alignItems: "flex-end" },
});
