-- Draft only. Do not apply live.
-- Full house: a team challenge (participation_type = 'team', never 'group')
-- where this user's enrollment is completed and every enrolled member's
-- active_challenges.status = 'completed'. getRecord runs one bounded roster
-- query and awards the earliest ended_at.

-- select ac.challenge_id, ac.user_id, ac.status, ac.ended_at
-- from active_challenges mine
-- join challenges c on c.id = mine.challenge_id
-- join active_challenges ac on ac.challenge_id = mine.challenge_id
-- where mine.user_id = $1
--   and mine.status = 'completed'
--   and c.participation_type = 'team'
-- limit 200;
