import { StyleSheet } from "react-native";
import { DS_COLORS, DS_TYPOGRAPHY, DS_RADIUS } from "@/lib/design-system"

export const checkinStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DS_COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginBottom: 20,
  },
  requirementBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.darkSurface,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: DS_RADIUS.MD,
    marginBottom: 20,
  },
  requirementText: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.white,
    flex: 1,
  },
  statusCards: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  statusCard: {
    flex: 1,
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.button,
    padding: 16,
    alignItems: "center",
  },
  statusIcon: {
    width: 44,
    height: 44,
    borderRadius: DS_RADIUS.iconButton,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginBottom: 8,
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: DS_RADIUS.XL,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: DS_RADIUS.SM,
  },
  statusChipText: {
    fontSize: 12,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
  },
  violationBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.dangerLightBg,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: DS_RADIUS.MD,
    marginBottom: 20,
  },
  violationText: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.dangerMid,
    flex: 1,
  },
  sessionContainer: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.LG,
    padding: 20,
    marginBottom: 20,
  },
  sessionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sessionLive: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  liveDot: {
    width: 10,
    height: 10,
    borderRadius: DS_RADIUS.SM,
    backgroundColor: DS_COLORS.success,
  },
  liveText: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.success,
  },
  lockWarning: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.taskAmber,
  },
  timerDisplay: {
    alignItems: "center",
    marginBottom: 16,
  },
  timerValue: {
    fontSize: 56,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
  },
  timerComplete: {
    color: DS_COLORS.success,
  },
  timerLabel: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginTop: 4,
  },
  progressBarContainer: {
    marginBottom: 12,
  },
  progressBar: {
    height: 8,
    backgroundColor: DS_COLORS.grayLight,
    borderRadius: DS_RADIUS.SM,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: DS_COLORS.accent,
    borderRadius: DS_RADIUS.SM,
  },
  progressFillComplete: {
    backgroundColor: DS_COLORS.success,
  },
  continuousNote: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 8,
  },
  continuousNoteText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
  },
  startContainer: {
    alignItems: "center",
    paddingVertical: 32,
  },
  startButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: DS_COLORS.accent,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: DS_RADIUS.joinCta,
  },
  startButtonDisabled: {
    backgroundColor: DS_COLORS.silverRank,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.white,
  },
  startHint: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    marginTop: 16,
    textAlign: "center",
  },
  resetContainer: {
    alignItems: "center",
    paddingVertical: 24,
  },
  resetText: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center",
  },
  infoSection: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.button,
    padding: 16,
    marginTop: 8,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  infoNumber: {
    width: 24,
    height: 24,
    borderRadius: DS_RADIUS.MD,
    backgroundColor: DS_COLORS.accentSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  infoNumberText: {
    fontSize: 12,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.accent,
  },
  infoText: {
    fontSize: 13,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    flex: 1,
  },
  footer: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.background,
  },
  verifyButton: {
    backgroundColor: DS_COLORS.darkSurface,
    paddingVertical: 18,
    borderRadius: DS_RADIUS.button,
    alignItems: "center",
  },
  verifyButtonDisabled: {
    backgroundColor: DS_COLORS.grayLight,
  },
  verifyButtonText: {
    fontSize: 15,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.white,
    letterSpacing: 0.5,
  },
  verifyButtonTextDisabled: {
    color: DS_COLORS.textMuted,
  },
  verifiedContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  verifiedBadge: {
    width: 80,
    height: 80,
    borderRadius: DS_RADIUS.XL,
    backgroundColor: DS_COLORS.successSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  verifiedTitle: {
    fontSize: 24,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
  },
  verifiedSubtitle: {
    fontSize: 15,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 32,
  },
  backButton: {
    backgroundColor: DS_COLORS.surface,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: DS_RADIUS.MD,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  backButtonText: {
    fontSize: 15,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
  },
});
