// v48.1 patch from the build 75 device test. Runs after gen, b2, b3, b4: new Function(g1..g5+';return {build5, wrapFile};')
function build5(v47) {
  const pages4 = build4(v47);
  NEXT = 801;
  const FL5 = { patch:'GRIIT v48.1 Patch.dc.html', b4:'GRIIT v48 Atlas B4.dc.html' };
  CUR = FL5.patch;
  const B5 = []; const F5 = (k, m, html) => { B5.push(k); return F(k, m, html); };
  const KBA = 336, KBN = 300;
  const keyS = `border-radius:6px;background:#4A4A4C;display:flex;align-items:center;justify-content:center;font-size:21px;color:${C.t1};`;
  const kbA = (sugg) => d(`position:absolute;left:0;right:0;bottom:0;height:${KBA}px;z-index:25;background:#1C1C1E;display:flex;flex-direction:column;`,
    d('height:44px;display:flex;align-items:center;', sugg.map((s,i)=>d(`flex:1;text-align:center;${T.b}color:${C.t1};${i?'border-left:1px solid #3A3A3C;':''}`, s)).join('')) +
    d('padding:4px 3px 0;display:flex;flex-direction:column;gap:11px;', ['qwertyuiop','asdfghjkl'].map((r,ri)=>d(`display:flex;gap:6px;${ri?'padding:0 18px;':''}`, r.split('').map(c=>d(`flex:1;height:42px;${keyS}`, c)).join(''))).join('') +
      d('display:flex;gap:6px;', d(`width:42px;height:42px;${keyS}background:#2C2C2E;`, ic('cu',18)) + d('flex:1;display:flex;gap:6px;padding:0 8px;', 'zxcvbnm'.split('').map(c=>d(`flex:1;height:42px;${keyS}`, c)).join('')) + d(`width:42px;height:42px;${keyS}background:#2C2C2E;`, ic('del',20))) +
      d('display:flex;gap:6px;', d(`width:88px;height:42px;${keyS}background:#2C2C2E;font-size:15px;`, '123') + d(`flex:1;height:42px;${keyS}font-size:15px;`, 'space') + d(`width:88px;height:42px;${keyS}background:#2C2C2E;font-size:15px;`, 'return'))));
  const kbN = d(`position:absolute;left:0;right:0;bottom:0;height:${KBN}px;z-index:25;background:#1C1C1E;`,
    d(`height:44px;display:flex;align-items:center;justify-content:flex-end;padding:0 16px;background:#2C2C2E;border-top:1px solid #3A3A3C;`, sp(T.h+'color:'+C.t1+';','Done')) +
    d('display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:6px 6px 0;', ['1','2','3','4','5','6','7','8','9','','0','del'].map(k=>d(`height:48px;${k?keyS+'font-size:25px;':''}`, k==='del'?ic('del',22):k)).join('')));
  const kbLine = (h, label) => d(`position:absolute;left:0;right:0;bottom:${h}px;height:0;border-top:1px dashed ${C.t1};z-index:50;`, d(`position:absolute;right:10px;top:4px;height:22px;padding:0 8px;border-radius:6px;background:${C.t1};color:${C.ink};font-size:11px;line-height:22px;font-weight:600;white-space:nowrap;`, label));
  const above = (h, inner) => d(`position:absolute;left:0;right:0;top:59px;bottom:${h}px;display:flex;flex-direction:column;overflow:hidden;background:${C.ink};`, inner);
  const caret = sp(`display:inline-block;width:2px;height:19px;background:${C.t1};vertical-align:-3px;margin-left:1px;`);
  const dock = (x) => d('padding:8px 16px 12px;display:flex;flex-direction:column;gap:4px;', x);
  const kbPhone = (time, h, inner, kb, label, o={}) => phone({ time, full: above(h, inner) + (o.under||''), overlay: kb + kbLine(h, label) });
  const fa = (l) => d(`width:64px;flex:none;align-self:center;display:flex;flex-direction:column;align-items:center;gap:4px;`, ic('arrow',20,C.t1) + d(`${T.c}color:${C.t1};text-align:center;`, l));
  const P5 = (k) => frameWrap(k, 0.62, 1);
  const rules = (w, title, rows) => panel(w, tx('l',C.t2,title) + rows.map(([a,b])=>d('display:grid;grid-template-columns:150px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join(''));

  // ================= 1 · KEYBOARD STATES =================
  const K = [];
  const revHead = stepHead('Read 10 pages','Read 30 · Day 2 of 30');
  K.push(F5('kbRev', { route:'task/complete', comp:'ReviewStep', state:'Caption, keyboard open', src:'v47 239', b75:'differs · keyboard covers the caption field', fields:'caption ≤ 120 chars' },
    kbPhone('7:43', KBA, revHead + d('padding:8px 16px 0;display:flex;flex-direction:column;gap:12px;flex:1;',
      d('display:flex;align-items:center;gap:12px;', d('position:relative;width:64px;height:80px;border-radius:10px;overflow:hidden;flex:none;', img(0) + d('position:absolute;left:4px;top:4px;transform:scale(0.7);transform-origin:0 0;', seal())) + tx('s',C.t2,'The photo shrinks while you type. Tap it to see it full size.')) +
      d(`background:${C.surf};border-radius:14px;padding:12px 14px;display:flex;flex-direction:column;gap:6px;box-shadow:inset 0 0 0 1.5px ${C.t1};`, d(T.b+'color:'+C.t1+';', 'Chapter 4 done. Footnotes are the best part' + caret) + tx('c',C.t2,'43 / 120','text-align:right;'))) + dock(btnP('Save')), kbA(['part','parts','partly']), 'Keyboard top · Save docks 8pt above')));
  const cHead = stepHead('Read 10 pages','Read 30 · Day 2 of 30') + gateRow([[null,'10 pages'],['camera','Camera']]);
  K.push(F5('kbCount', { route:'task/complete', comp:'CountStep', state:'Type it · number pad with Done bar', src:'v47 229', b75:'differs · number pad has no Done; the count hides under it', fields:'count ← typed value (local) · target ← task.config.target' },
    kbPhone('7:42', KBN, cHead + d('flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;', tx('s',C.t2,'Pages read today') + d('display:flex;align-items:baseline;gap:8px;', d(`min-width:120px;height:72px;padding:0 16px;border-radius:16px;background:${C.surf};display:flex;align-items:center;justify-content:center;font-size:44px;font-weight:600;font-variant-numeric:tabular-nums;color:${C.t1};box-shadow:inset 0 0 0 2px ${C.t1};`, '7' + sp(`display:inline-block;width:2px;height:40px;background:${C.t1};margin-left:3px;`)) + tx('t',C.t2,'of 10')) + tx('s',C.t2,'3 to go. Then a photo.')) + dock(btnP('Log 7 of 10')), kbN, 'Number pad + Done bar · Log stays above')));
  const jt = "Slept late, still made the gym. Noticed I skip journaling on days I feel behind, which is exactly when it helps. Tomorrow: clothes out tonight, phone in the kitchen, alarm across the room. Week two is where I quit last time. One bad morning and I told myself the week was ruined. This time the rule is smaller";
  const wc = jt.trim().split(/\s+/).length;
  K.push(F5('kbWrite', { route:'task/complete', comp:'WriteStep', state:'Typing, keyboard open · caret line in view', src:'v47 232', b75:'differs · the last lines and the count sit under the keyboard', fields:'words ← client count · min ← task.config.min_words' },
    kbPhone('9:16', KBA, stepHead('Journal','Up by 5 · Day 5 of 7') + gateRow([[null,'Self-reported'],['type','100 words']]) +
      d('flex:1;position:relative;overflow:hidden;padding:0 20px;', d('position:absolute;left:20px;right:20px;bottom:6px;', d(T.b+'font-size:17px;line-height:24px;color:'+C.t1+';', jt + caret)) + d(`position:absolute;left:0;right:0;top:0;height:40px;background:linear-gradient(${C.ink},transparent);`)) +
      d('padding:6px 20px 0;display:flex;flex-direction:column;gap:6px;', d(`height:2px;background:${C.raised};border-radius:1px;overflow:hidden;`, d(`width:${wc}%;height:100%;background:${C.t1};`)) + tx('c',C.t2,`${wc} / 100 words · ${100-wc} to go`)) + dock(btnP(`${100-wc} words to go`,{off:true})), kbA(['smaller','small','smallest']), 'Keyboard top · count and button stay above')));
  K.push(F5('kbComment', { route:'post/[id]', comp:'CommentsSheet', state:'Composer on the keyboard', src:'v12 39', b75:'differs · the composer hides under the keyboard' },
    phone({ time:'7:21', body: postHead('yaseen','Read 30 · Day 2 of 30','14h') + d('width:393px;height:491px;', img('book1')), overlay: d('position:absolute;inset:0;z-index:30;background:rgba(0,0,0,0.6);') +
      d(`position:absolute;left:0;right:0;top:140px;bottom:${KBA}px;z-index:31;background:${C.surf};border-radius:24px 24px 0 0;display:flex;flex-direction:column;`, d(`width:36px;height:5px;border-radius:3px;background:${C.t3};margin:8px auto 4px;`) + tx('h',C.t1,'Comments','text-align:center;padding-bottom:4px;') +
        d('flex:1;overflow:hidden;padding:0 16px;display:flex;flex-direction:column;justify-content:flex-end;', comment('omar','Same book. Chapter 9 is the turn.','1h') + comment('khalid','Which edition?','2m')) +
        d(`padding:8px 12px;border-top:1px solid ${C.raised};display:flex;align-items:center;gap:10px;`, av('yaseen',32) + d(`flex:1;min-height:40px;border-radius:20px;background:${C.raised};display:flex;align-items:center;padding:0 14px;${T.b}color:${C.t1};`, 'Penguin. Footnotes at the back' + caret) + d(`height:36px;padding:0 14px;border-radius:999px;background:${C.t1};display:flex;align-items:center;${T.h}color:${C.ink};`, 'Post'))) +
      kbA(['back','backs','background']) + kbLine(KBA, 'Sheet shrinks to the keyboard · composer docks on it') })));
  K.push(F5('kbCreate', { route:'create/index', comp:'StepBasics', state:'Name field, keyboard open', src:'v44 169', b75:'differs · Continue hidden under the keyboard' },
    kbPhone('8:30', KBA, d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,'Step 1 of 3') + d('width:52px')) + d(`margin:0 16px;height:3px;border-radius:2px;background:${C.raised};`, d(`width:33%;height:100%;background:${C.t1};border-radius:2px;`)) +
      d('padding:16px 16px 0;display:flex;flex-direction:column;gap:10px;flex:1;', tx('tl',C.t1,'Name your challenge') + tx('h',C.t1,'Name') + d(`min-height:52px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;box-shadow:inset 0 0 0 1.5px ${C.t1};${T.b}color:${C.t1};`, 'Wake up at 5 every day' + caret) + d('display:flex;align-items:center;gap:6px;', ic('check',14,C.t1,{sw:3}) + tx('c',C.t2,'Looks good. Category and length are below.'))) + dock(btnP('Continue')), kbA(['day','days','daily']), 'Keyboard top · Continue docks above')));
  K.push(F5('kbEdit', { route:'edit-profile', comp:'EditProfile', state:'Bio field, keyboard open · scrolled into view', src:'v28 64', b75:'differs · the bio field opens under the keyboard' },
    kbPhone('9:10', KBA, d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('h',C.t1,'Edit profile') + tx('h',C.t1,'Save')) +
      d('flex:1;position:relative;overflow:hidden;', d('position:absolute;left:16px;right:16px;bottom:10px;display:flex;flex-direction:column;gap:12px;',
        d('display:flex;flex-direction:column;gap:4px;', tx('c',C.t2,'Name') + d(`min-height:48px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;${T.b}color:${C.t1};`, 'Yaseen Abdelaziz')) +
        d('display:flex;flex-direction:column;gap:4px;', tx('c',C.t2,'Username') + d(`min-height:48px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;${T.b}color:${C.t1};`, '@yaseen')) +
        d('display:flex;flex-direction:column;gap:4px;', tx('c',C.t2,'Bio') + d(`min-height:76px;border-radius:12px;background:${C.surf};padding:12px 14px;box-sizing:border-box;box-shadow:inset 0 0 0 1.5px ${C.t1};${T.b}color:${C.t1};`, 'Reading before work. Up before the city' + caret) + tx('c',C.t2,'40 / 150','text-align:right;'))) +
        d(`position:absolute;left:0;right:0;top:0;height:30px;background:linear-gradient(${C.ink},transparent);`)), kbA(['city','city.','cities']), 'Keyboard top · focused field ≥ 12pt above')));
  const kRules = rules(560, 'Keyboard rules (all text entry)', [
    ['Visible','The focused field and its last typed line stay at least 12pt above the keyboard. The screen scrolls the field into view on focus.'],
    ['Primary action','The screen’s one button docks 8pt above the keyboard and stays tappable while typing.'],
    ['Number pad','Every number pad gets a Done bar (input accessory). Done closes the pad; it never saves.'],
    ['Counts','Live counts (words, characters, n of N) sit between the field and the docked button.'],
    ['Sheets','A sheet shrinks to the keyboard top; its composer docks on the keyboard.'],
    ['Dismiss','Drag down or tap outside a field. Typed text is kept.'],
    ['Build','KeyboardAvoidingView behavior “padding” on iOS, keyboardShouldPersistTaps “handled”, InputAccessoryView for the number-pad Done bar.'] ]);

  // ================= 2 · STICKER =================
  const S = [];
  const raw = (n, f) => `<img src="assets/proofs/${n}.jpg" alt="" style="width:100%;height:100%;object-fit:cover;display:block;filter:${f};">`;
  const BRIGHT = 'brightness(1.15)', DARK = 'brightness(0.45)';
  const sticker = (v, s=1) => {
    const fx = v==='outline' ? `-webkit-text-stroke:${4*s}px ${C.ink};paint-order:stroke fill;` : 'text-shadow:0 1px 2px rgba(0,0,0,0.75),0 1px 4px rgba(0,0,0,0.6),0 3px 16px rgba(0,0,0,0.55);';
    const fl = v==='outline' ? `filter:drop-shadow(0 0 ${1.5*s}px ${C.ink}) drop-shadow(0 0 ${1.5*s}px ${C.ink});` : 'filter:drop-shadow(0 1px 3px rgba(0,0,0,0.7)) drop-shadow(0 3px 10px rgba(0,0,0,0.5));';
    return d(`display:flex;flex-direction:column;align-items:flex-start;gap:${2*s}px;color:${C.t1};${fx}`, d(`display:flex;align-items:center;gap:${6*s}px;`, d(fl, ic('flame',Math.round(40*s),C.or,{fill:C.or})) + sp(NUM+`font-size:${Math.round(72*s)}px;line-height:1;`, '8')) + d(`font-size:${Math.round(22*s)}px;line-height:1.2;font-weight:700;`, 'days secured') + d(`font-size:${Math.round(15*s)}px;line-height:1.3;font-weight:600;`, 'Read 30 · Day 2 of 30') + d(`font-size:${Math.round(12*s)}px;line-height:1.3;font-weight:700;letter-spacing:0.08em;margin-top:${4*s}px;`, 'GRIIT'));
  };
  const checker = 'repeating-conic-gradient(#2A2928 0 25%,#1F1E1D 0 50%) 0 0/16px 16px';
  const stickerSheet = (time, v, extra='') => phone({ time, body: d('display:flex;align-items:center;justify-content:space-between;padding:0 6px;height:52px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('x',22)) + tx('h',C.t1,'Sticker · 2 of 7') + d('width:44px')) +
    d('display:flex;justify-content:center;padding-top:4px;', d(`width:300px;height:300px;border-radius:16px;background:${checker};display:flex;align-items:center;justify-content:center;`, sticker(v, 1))) +
    tx('c',C.t2,'Transparent PNG, 1080 × 1080. The checks show where it’s see-through.','text-align:center;padding:8px 24px 0;') +
    d('display:flex;justify-content:center;gap:8px;padding-top:12px;', chip('Soft shadow', v==='shadow') + chip('Outline', v==='outline')) +
    tx('c',C.t2, v==='shadow' ? 'Reads on bright and mid photos.' : 'Reads on any photo, including white walls and sky.','text-align:center;padding-top:6px;') +
    d('display:flex;justify-content:space-around;padding:18px 8px 0;', [['copy','Copy sticker'],['ig','Instagram Story'],['download','Save'],['more','More']].map(([i,l],k)=>d('display:flex;flex-direction:column;align-items:center;gap:6px;width:80px;', d(`width:52px;height:52px;border-radius:999px;background:${k===0?C.t1:C.raised};display:flex;align-items:center;justify-content:center;`, ic(i,22,k===0?C.ink:C.t1)) + tx('c',C.t1,l,'text-align:center;'))).join('')), overlay: extra });
  const copiedToast = d(`position:absolute;left:16px;right:16px;bottom:46px;z-index:30;background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, ic('ccheck',18) + tx('s',C.t1,'Copied. Paste it in your Instagram story.','flex:1;'));
  S.push(F5('stkSheet', { route:'share', comp:'ShareSystemSheet', state:'Sticker · Copy sticker target', src:'v47 259', b75:'not built', fields:'png ← ShareSticker rendered at 1080², alpha; clipboard ← UIPasteboard image/png' }, stickerSheet('7:45','shadow')));
  S.push(F5('stkOutline', { route:'share', comp:'ShareSystemSheet', state:'Sticker · Outline variant', src:'new', b75:'not built' }, stickerSheet('7:45','outline')));
  S.push(F5('stkCopied', { route:'share', comp:'ShareSystemSheet', state:'Copied toast', src:'new', b75:'not built' }, stickerSheet('7:45','shadow', copiedToast)));
  const igChrome = (bg, inner) => phone({ time:'7:47', onPhoto:true, full: d('position:absolute;inset:0;', bg) + (inner||'') + d('position:absolute;right:16px;top:70px;display:flex;flex-direction:column;gap:18px;', ['type','sticker','more'].map(i=>d('filter:drop-shadow(0 1px 3px rgba(0,0,0,0.7));', ic(i,26))).join('')) + d(`position:absolute;left:16px;right:16px;bottom:44px;display:flex;justify-content:space-between;`, d(`height:44px;padding:0 16px;border-radius:999px;background:rgba(15,15,15,0.6);display:flex;align-items:center;${T.h}color:${C.t1};`, 'Your story') + d(`height:44px;padding:0 16px;border-radius:999px;background:${C.t1};display:flex;align-items:center;${T.h}color:${C.ink};`, 'Close Friends')) + d(`position:absolute;left:16px;top:66px;height:24px;padding:0 8px;border-radius:6px;background:rgba(15,15,15,0.6);${T.c}color:${C.t1};display:flex;align-items:center;`, 'Instagram UI · context only') });
  S.push(F5('igOwn', { route:'Instagram', comp:'Story editor', state:'Own photo, paste callout', src:'new', b75:'pending' }, igChrome(raw('food3', BRIGHT), d('position:absolute;left:130px;top:380px;display:flex;flex-direction:column;align-items:center;', d(`height:38px;padding:0 16px;border-radius:10px;background:#3A3A3C;display:flex;align-items:center;${T.h}color:${C.t1};`, 'Paste') + d('width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #3A3A3C;')))));
  S.push(F5('igBright', { route:'Instagram', comp:'Story editor', state:'Sticker pasted · bright photo · soft shadow', src:'new', b75:'pending' }, igChrome(raw('food3', BRIGHT), d('position:absolute;left:48px;top:330px;transform:rotate(-4deg);', sticker('shadow', 1.05)))));
  S.push(F5('igDark', { route:'Instagram', comp:'Story editor', state:'Sticker pasted · dark photo · soft shadow', src:'new', b75:'pending' }, igChrome(raw('run1', DARK), d('position:absolute;left:48px;top:330px;transform:rotate(-4deg);', sticker('shadow', 1.05)))));
  S.push(F5('igBrightOut', { route:'Instagram', comp:'Story editor', state:'Sticker pasted · bright photo · outline', src:'new', b75:'pending' }, igChrome(raw('water2', 'brightness(1.6) saturate(0.6) contrast(0.8)'), d('position:absolute;left:48px;top:330px;transform:rotate(-4deg);', sticker('outline', 1.05)))));
  const spec = panel(560, tx('l',C.t2,'Readability check · same sticker, four grounds') + d('display:grid;grid-template-columns:1fr 1fr;gap:10px;', [['food3',BRIGHT,'shadow','Bright · soft shadow'],['run1',DARK,'shadow','Dark · soft shadow'],['water2','brightness(1.6) saturate(0.6) contrast(0.8)','outline','Near-white · outline'],['run1',DARK,'outline','Dark · outline']].map(([p,f,v,l])=>d('display:flex;flex-direction:column;gap:6px;', d('position:relative;height:200px;border-radius:12px;overflow:hidden;', raw(p,f) + d('position:absolute;left:18px;top:28px;', sticker(v,0.62))) + tx('c',C.t2,l))).join('')) +
    tx('s',C.t2,'Soft shadow is the default. Outline is offered for very bright photos. Neither adds a background, so the sticker stays a clean cut-out.'));
  const sRules = rules(560, 'Sticker rules', [
    ['Format','Transparent PNG, 1080 × 1080, the sticker style only. No background, no frame.'],
    ['Copy sticker','Puts the PNG on the clipboard. Toast: “Copied. Paste it in your Instagram story.” Works without the Meta App ID.'],
    ['Instagram Story','Unchanged from frame ' + REG.ssSticker.n + '. Opens Instagram with the sticker layer; needs the Meta App ID before it can ship.'],
    ['Readable','White type with a soft shadow by default; an ink outline variant for near-white photos.'],
    ['Count copy','Pluralised: “1 day secured”, “8 days secured”.'] ]);

  // ================= 3 · SHARE CHOICE =================
  const H = [];
  const shareBtn = (ph) => d(`height:52px;border-radius:999px;background:${C.surf};box-shadow:inset 0 0 0 1.5px ${C.t1};display:flex;align-items:center;justify-content:center;gap:10px;padding:0 8px;`, d('width:32px;height:40px;border-radius:6px;overflow:hidden;flex:none;', img(ph)) + sp(T.h+'color:'+C.t1+';','Share this photo to the feed') + ic('share',18));
  const keepRow = d('display:flex;align-items:center;justify-content:space-between;', tx('c',C.t2,'No answer keeps it private.') + btnT('Keep it to the record', C.t2));
  const pToast = (o) => d(`position:absolute;left:10px;right:10px;bottom:95px;z-index:16;background:${C.raised};border-radius:18px;padding:12px 12px 4px;display:flex;flex-direction:column;gap:10px;box-shadow:0 8px 24px rgba(0,0,0,0.5);`,
    d('display:flex;gap:12px;align-items:center;', d('position:relative;width:64px;height:80px;border-radius:10px;overflow:hidden;flex:none;', img(o.ph) + d('position:absolute;left:4px;top:4px;transform:scale(0.7);transform-origin:0 0;', seal())) + d('flex:1;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,o.title) + tx('s',C.t2,o.sub))) + shareBtn(o.ph) + keepRow);
  const homeY = (x={}) => home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today.', primary:btnP('Out of bed',{icon:'check'}), sections:[secRead('done'), secBed('open')], ...x });
  H.push(F5('scToast', { route:'(tabs)/index', comp:'TaskCompleteToast', state:'Camera proof landed · share is the visible choice, nothing pre-selected', src:'v47 246', b75:'differs · share and keep look identical; testers missed it', fields:'visibility stays private unless share is tapped; toast holds 8 s for photo proofs' }, phone({ time:'4:52', tab:'home', body: homeY(), toast: pToast({ ph:'book1', title:'Read 10 pages is done', sub:'Camera · 1 of 2 left today.' }) })));
  const securedTop = d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:24px 16px 0;', d('display:flex;align-items:center;gap:8px;', flame(36) + sp(NUM+`font-size:56px;line-height:60px;color:${C.t1};`,'8')) + tx('t',C.t1,'Day secured.') + d('width:100%;', strip(['sec','sec','sec','sec','sec','sec','todayDone'])) + d('position:relative;width:200px;aspect-ratio:4/5;border-radius:12px;overflow:hidden;margin-top:6px;', img('book1') + d('position:absolute;left:6px;top:6px;transform:scale(0.85);transform-origin:0 0;', seal())) + d('width:100%;display:flex;flex-direction:column;gap:2px;', ['Read 30 · Day 2 of 30 · Camera','Up by 5 · Day 5 of 7 · Self-reported'].map(l=>d('display:flex;align-items:center;gap:10px;min-height:36px;', doneDot(24) + tx('s',C.t1,l))).join('')));
  H.push(F5('scSecured', { route:'task/secured', comp:'SecuredDayScreen', state:'Same share treatment when the camera proof secures the day', src:'v47 248', b75:'differs · same as above' }, phone({ time:'7:44', body: securedTop, sticky: shareBtn('book1') + keepRow + btnP('Done'), stickyH:172 })));
  const mine = { who:'yaseen', sub:'Read 30 · Day 2 of 30', time:'now', ph:['book1'], cap:'Chapter 4 done.', r:'', c:'' };
  H.push(F5('scFeed', { route:'(tabs)/index', comp:'HomeScreen · feed', state:'Right after sharing · my post on top', src:'new', b75:'not built', fields:'feed ← optimistic insert of the shared proof at index 0, then server order' }, phone({ time:'4:53', tab:'home', scroll:470, body: homeY({ feed: feedHead(0) + photoPost(mine) + photoPost(KH_POST) }), toast: d(`position:absolute;left:16px;right:16px;bottom:95px;z-index:16;background:${C.raised};border-radius:14px;padding:4px 6px 4px 14px;display:flex;align-items:center;gap:10px;`, ic('ccheck',18) + tx('s',C.t1,'Shared to the feed.','flex:1;') + btnT('Undo')) })));
  const hRules = rules(560, 'Share choice rules', [
    ['Visible','After a camera proof the share choice is the largest thing in the toast or sticky band: an outlined pill with the photo in it.'],
    ['Not pre-selected','Neither option starts selected. No answer within 8 s, or leaving the screen, keeps it private.'],
    ['Keep','“Keep it to the record” is a quiet text button on the same row as the privacy line.'],
    ['After sharing','Home’s feed shows my post at the top straight away (optimistic), with Undo for 6 s.'],
    ['Self-reported','No photo, no feed share. Those toasts offer “Share as a card” only (unchanged).'] ]);

  // ================= 4 · WHICH SCREEN APPEARS =================
  const R = [];
  const secY = (st) => ({ name:'Up by 5', day:'Day 5 of 7', done: st==='done'?1:0, total:1, tasks:[{ name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st }] });
  R.push(F5('rtSecured', { route:'task/secured', comp:'SecuredDayScreen', state:'Case 2 · last task of the day', src:'v47 248', b75:'pending', fields:'route only when secured_today flips false → true on this save' }, phone({ time:'4:53', body: securedTop.replace('Read 30 · Day 2 of 30 · Camera','Read 30 · Day 2 of 30 · Camera, done 4:52').replace('Up by 5 · Day 5 of 7 · Self-reported','Up by 5 · Out of bed · Self-reported, done now'), sticky: btnS('Share as a card',{icon:'share'}) + btnP('Done'), stickyH:120 })));
  R.push(F5('rtFinish', { route:'task/complete', comp:'FinishMomentV3', state:'Case 3 · final day done (Read 30, Nov 1)', src:'v47 250', b75:'differs · build 75 opened it after a counter hit its target', fields:'secured ← enrollment.secured_days (27) · longest ← enrollment.longest_streak (18) · held ← enrollment.held_days' }, phone({ time:'7:46', body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:90px 20px 0;text-align:center;', tx('l',C.t2,'Read 30 · finished') + sp(NUM+`font-size:56px;line-height:60px;color:${C.t1};`,'27') + tx('b',C.t1,'of 30 days secured') + d(`margin-top:12px;width:100%;background:${C.surf};border-radius:16px;padding:14px;display:grid;grid-template-columns:repeat(3,1fr);gap:8px;text-align:left;`, [['18','Longest streak'],['1','Held'],['28','Days done']].map(([n,l])=>d('display:flex;flex-direction:column;', sp(NUM+'font-size:28px;color:'+C.t1+';',n) + tx('c',C.t2,l))).join(''))), sticky: btnS('Share the finish',{icon:'share'}) + btnP('See the record'), stickyH:120 })));
  R.push(F5('rtCount', { route:'task/complete', comp:'CountStep', state:'Case 4 · counter at 30 of 30 pages (not the last day)', src:'v47 230', b75:'differs · build 75 routes this to FinishMoment' }, phone({ time:'7:30', body: stepHead('Read 30 pages','Long read 14 · Day 3 of 14') + gateRow([[null,'30 pages'],['camera','Camera']]) + d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:110px 24px 0;', d('display:flex;align-items:baseline;gap:8px;', d(`font-size:56px;line-height:60px;font-weight:600;font-variant-numeric:tabular-nums;color:${C.t1};`, '30') + tx('t',C.t2,'of 30 pages')) + tx('s',C.t2,'Target met. A live photo finishes the task.') + tx('c',C.t2,'Day 3 of 14. The challenge isn’t finished.','margin-top:8px;')), sticky: btnP('Take photo',{icon:'camera'}), stickyH:72 })));
  R.push(F5('rtCountLand', { route:'(tabs)/index', comp:'TaskCompleteToast', state:'Case 4 · lands on a toast, never FinishMoment', src:'new', b75:'differs · same' }, phone({ time:'7:31', tab:'home', body: home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today.', primary:btnP('Out of bed',{icon:'check'}), sections:[{ name:'Long read 14', day:'Day 3 of 14', done:1, total:1, tasks:[{ name:'Read 30 pages', gate:[[null,'30 pages'],G.cam], st:'done' }] }, secY('open')] }), toast: pToast({ ph:'book2', title:'Read 30 pages is done', sub:'Camera · Long read 14 continues tomorrow.' }) })));
  const finCard = d(`position:relative;width:300px;height:533px;border-radius:16px;background:${C.ink};box-shadow:0 0 0 1px ${C.hair};overflow:hidden;`, d('position:absolute;left:24px;right:24px;top:70px;display:flex;flex-direction:column;gap:4px;', tx('l',C.t2,'Read 30 · finished') + d('display:flex;align-items:center;gap:8px;margin-top:8px;', ic('flame',30,C.or,{fill:C.or}) + sp(NUM+`font-size:72px;line-height:1;color:${C.t1};`,'27')) + tx('t',C.t1,'days secured of 30') + d(`height:1px;background:${C.raised};margin:16px 0;`) + d('display:flex;gap:24px;', d('', sp(NUM+'font-size:32px;color:'+C.t1+';','18') + tx('c',C.t2,'Longest streak')) + d('', sp(NUM+'font-size:32px;color:'+C.t1+';','1') + tx('c',C.t2,'Held by a freeze')))) + d(`position:absolute;left:24px;bottom:72px;${T.c}color:${C.t2};`, '{INVITE_BASE}/i/{code}'));
  R.push(F5('rtCard', { route:'share', comp:'FinishTextCard', state:'Case 5 · reads real secured days and longest streak', src:'v44.1 F', b75:'differs · build 75 card shows the day index and the counter value', fields:'27 ← enrollment.secured_days · 18 ← enrollment.longest_streak · 30 ← duration_days' }, phone({ time:'7:47', body: d('display:flex;flex-direction:column;align-items:center;padding-top:30px;gap:14px;', finCard + tx('s',C.t2,'Numbers come from the server record, not from the screen that opened it.','text-align:center;padding:0 24px;')), sticky: btnP('Share to Instagram Story',{icon:'ig'}) + btnT('Save to Photos'), stickyH:116 })));
  const link = (k) => `<a href="#f${REG[k].n}" style="color:${C.t1};text-decoration:underline;">${REG[k].n}</a>`;
  const rRule = panel(620, tx('l',C.t2,'The rule · which screen appears after a save') + tx('s',C.t1,'After every save the client reads three facts from the completion response, then routes once. One screen per save, never two.') +
    [['1','challenge_finished','This save secured the last day of an enrollment (day_index = duration_days and the day is secured).','FinishMoment', link('rtFinish')],
     ['2','day_secured_now','secured_today flipped from false to true with this save.','Secured', link('rtSecured')],
     ['3','otherwise','Any other task done.','Toast on Home', link('scToast')]].map(([n,f,w,s,l])=>d(`display:grid;grid-template-columns:24px 150px 1fr 120px 40px;gap:10px;align-items:start;padding:10px 0;border-top:1px solid ${C.raised};`, tx('h',C.t1,n) + tx('h',C.t1,f) + tx('s',C.t2,w) + tx('h',C.t1,s) + tx('s',C.t1,l))).join('') +
    tx('s',C.t1,'Checked in that order. A counter reaching its target only completes the task: it lands on 3, or 2 if it was the last task of the day, never 1 (frames ' + link('rtCount') + ', ' + link('rtCountLand') + ').') +
    tx('s',C.t1,'If the final day also secures other challenges, FinishMoment shows once; “See the record”, then Home shows the day secured. No second Secured screen.') +
    tx('s',C.t1,'FinishMoment and its card read enrollment.secured_days and enrollment.longest_streak from the server (frame ' + link('rtCard') + '). Held days hold the streak but don’t add to it.'));

  // ================= 5 · PLURALS =================
  const PL = [];
  const bigNum = (n, line) => d(`width:260px;height:462px;border-radius:16px;background:${C.or};position:relative;overflow:hidden;`, d('position:absolute;left:22px;right:22px;bottom:92px;display:flex;flex-direction:column;gap:4px;', d('display:flex;align-items:center;gap:6px;', ic('flame',22,C.ink,{fill:C.ink}) + sp(NUM+`font-size:96px;line-height:1;color:${C.t1};`, n)) + d(`font-size:22px;line-height:1.2;font-weight:600;color:${C.t1};`, line) + d(`font-size:12px;font-weight:500;color:${C.t1};opacity:0.85;margin-top:4px;`, '{INVITE_BASE}/i/{code}')));
  PL.push(F5('plBig', { route:'share', comp:'ShareSystemSheet', state:'Big number at 1 · “1 day in a row”', src:'v44.1 174', b75:'differs · build 75 says “1 days in a row”' }, phone({ time:'9:13', body: d('display:flex;align-items:center;justify-content:space-between;padding:0 6px;height:52px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('x',22)) + tx('h',C.t1,'Big number · 5 of 7') + d('width:44px')) + d('display:flex;justify-content:center;padding-top:4px;', bigNum('1','day in a row')) + d('display:flex;justify-content:center;gap:8px;padding-top:14px;', chip('Ink') + chip('Orange',true) + chip('White')) + tx('c',C.t2,'Yaseen’s first secured day, Sep 27.','text-align:center;padding-top:10px;') })));
  const plTable = panel(620, tx('l',C.t2,'Every count string · singular and plural') + `<div style="display:grid;grid-template-columns:1fr 1fr 1fr;">` + [['Where','n = 1','n = 8']].concat([
    ['Share cards, Home milestone','1 day in a row','8 days in a row'],['Sticker, Secured','1 day secured','8 days secured'],['Streak','1-day streak','8-day streak'],['Home','1 task left today','2 tasks left today'],['Profile, day feed','1 proof','2 proofs'],['Freeze','1 freeze left','2 freezes left'],['Boards, roster','1 person','214 people'],['Profile','1 follower','128 followers'],['Badges','1 secured day','23 secured days'],['Words','1 word to go','36 words to go']]).map((r,ri)=>r.map(c=>d(`${ri?T.s:T.c}color:${ri?C.t1:C.t2};padding:8px 8px 8px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>' +
    tx('s',C.t2,'One helper in src/components/v48/copy.ts: count(n, "day") → “1 day” / “8 days”. Every number-plus-noun string goes through it; no template literal adds an “s” by hand. “n of N” forms (“1 of 2 left today”) don’t change.'));

  // ================= page =================
  const sec = (id, eyebrow, title, purpose, body) => `<div style="display:flex;flex-direction:column;gap:22px;">` + areaHead(id, eyebrow, title, purpose, '') + body + '</div>';
  const nav = d('display:flex;flex-wrap:wrap;gap:8px;', [['#p1','1 Keyboard'],['#p2','2 Sticker'],['#p3','3 Share choice'],['#p4','4 Which screen'],['#p5','5 Plurals'],[encodeURI(FL5.b4)+'#indexAll','Full atlas index']].map(([h,l])=>`<a href="${h}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">${l}</a>`).join(''));
  const intro = d('display:flex;flex-direction:column;gap:14px;max-width:1100px;', tx('l',C.t2,'GRIIT v48.1 · patch from the build 75 device test') + d(T.tl+'font-size:40px;line-height:46px;color:'+C.t1+';', 'Keyboard, sticker, share choice, routing, plurals') + tx('b',C.t2,`Small fixes on the approved atlas. Same system, same check strips. ${B5.length} new frames, numbered 801 onward, all in the full index. “Built in 75” records what the device test found.`) + nav);
  const supersede = panel(620, tx('l',C.t2,'Frames this patch supersedes') + [['kbRev','rev'],['kbCount','cntType'],['kbWrite','wShort'],['kbComment','postOwn'],['kbEdit','editOk'],['stkSheet','ssSticker'],['scToast','fYToast'],['scSecured','sec1'],['rtCard','finCard'],['plBig','fYBig']].filter(([a,b])=>REG[b]).map(([a,b])=>d('display:flex;gap:10px;', tx('s',C.t1,`${REG[a].n} ${REG[a].comp}`,'flex:1;') + tx('s',C.t2,`replaces the keyboard-closed or old copy of ${REG[b].n}`))).join('') + tx('s',C.t2,'The superseded frames stay in place for history; build from the 8xx frame.'));
  const stkFlow = `<div style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Flow · copy the sticker into my own story', 'Copy in GRIIT, open Instagram, take my own photo, paste. No Meta App ID needed.') + d('display:flex;gap:10px;align-items:flex-start;', [P5('stkSheet'), fa('Copy sticker'), P5('stkCopied'), fa('Open Instagram, take a photo'), P5('igOwn'), fa('Paste'), P5('igBright'), fa('Or on a dark photo'), P5('igDark')].join('')) + '</div>';
  const body = `<div style="filter:{{ filt }};font-family:${FONT};color:${C.t1};padding:48px;display:flex;flex-direction:column;gap:80px;background:${C.ink};">` + [intro, supersede,
    sec('p1','Patch 1 · Keyboard','Keyboard open','Typing never hides what you’re typing. Within 3 seconds: the field, the text, the count and the button are all on screen.', wrapRow(K.concat([kRules]))),
    sec('p2','Patch 2 · Sticker','Strava-style sticker','A transparent sticker for your own story. Within 3 seconds: copy it, and it reads on any photo.', wrapRow(S.slice(0,3).concat([sRules])) + stkFlow + wrapRow([S[3], S[4], S[5], S[6], spec])),
    sec('p3','Patch 3 · Share choice','Share after a camera proof','Sharing is easy to see and never assumed. Within 3 seconds: I can share this photo, and doing nothing keeps it private.', wrapRow(H.concat([hRules]))),
    sec('p4','Patch 4 · Which screen appears','Toast, Secured or FinishMoment','One rule decides the screen after every save. Within 3 seconds: the right moment, with the real numbers.', wrapRow([rRule, frameWrap('scToast',0,1)].concat(R))),
    sec('p5','Patch 5 · Plurals','“1 day in a row”','Every count reads as a sentence. One helper, every screen.', wrapRow(PL.concat([plTable]))) ].join('\n') + '</div>';

  // ----- full index, rebuilt to include 801+ -----
  const all = ORDER.filter(k => REG[k].n >= 301).sort((a,b)=>REG[a].n-REG[b].n);
  const batchOf = (n) => n>=801?'4.1':n>=701?'4':n>=601?'3':n>=501?'2':'1R';
  const counts = {}; const b75 = {}; all.forEach(k=>{ const b = batchOf(REG[k].n); counts[b]=(counts[b]||0)+1; const v = (REG[k].b75||'pending').split(' ')[0]; b75[v]=(b75[v]||0)+1; });
  const summary = d('display:flex;gap:12px;flex-wrap:wrap;', [['Frames', all.length],['Batch 1R',counts['1R']],['Batch 2',counts['2']],['Batch 3',counts['3']],['Batch 4',counts['4']],['Patch 4.1',counts['4.1']],['Not built', b75['not']||0],['Differs', b75['differs']||0],['Retire', b75['retire']||0]].map(([l,n])=>d(`background:${C.surf};border-radius:14px;padding:12px 16px;display:flex;flex-direction:column;min-width:110px;`, sp(NUM+'font-size:28px;color:'+C.t1+';', n) + tx('c',C.t2,l))).join(''));
  const rows = all.map(k=>{ const f = REG[k]; return [`<a href="${href(k)}" style="color:${C.t1};">${f.n}</a>`, batchOf(f.n), f.route, f.comp, f.state, f.src||'new', f.b75||'pending']; });
  const idxAll = `<div id="indexAll" data-screen-label="Full atlas index" style="display:flex;flex-direction:column;gap:14px;">` + stripHead(`The atlas index · every frame, batches 1R–4 and patch 4.1 (${all.length})`, 'Frame · batch · route · component · state · source frame · built in 75. Every number links to its frame. Patch 4.1 rows record the build 75 device test.') + summary +
    panel(1500, `<div style="display:grid;grid-template-columns:56px 44px 200px 230px 1fr 150px 230px;max-width:1460px;">` + [['#','Batch','Route','Component','State','Source','Built in 75']].concat(rows).map((r,ri)=>r.map((c,i)=>d(`${ri===0?T.c+'color:'+C.t2+';':(i===0?T.h:T.s)+'color:'+C.t1+';'}padding:8px 12px 8px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>') + '</div>';
  let hub = pages4[FL5.b4];
  const i0 = hub.indexOf('<div id="indexAll"');
  hub = hub.slice(0, i0) + idxAll + '\n</div>';
  hub = hub.replace(`>Area 14 System</a>`, `>Area 14 System</a><a href="${encodeURI(FL5.patch)}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">Patch 4.1</a>`);
  return { ...pages4, [FL5.b4]: hub, [FL5.patch]: body };
}
