// Batch 2 generator. Concatenate after v48-gen.js: new Function(gen + b2 + ';return {build2, wrapFile};')
Object.assign(P, {
  moon:'<path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>', leaf:'<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/>',
  target:'<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',
  sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>',
  gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>',
  copy:'<rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/>',
  flag:'<path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" x2="4" y1="22" y2="15"/>',
  award:'<circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/>',
  users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
  userplus:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/>',
  flagr:'<path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" x2="4" y1="22" y2="15"/>',
  ban:'<circle cx="12" cy="12" r="10"/><path d="m4.9 4.9 14.2 14.2"/>', eyeoff:'<path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/><path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68"/><path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7a9.74 9.74 0 0 0 5.39-1.61"/><line x1="2" x2="22" y1="2" y2="22"/>',
  send:'<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>', hand:'<path d="M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2"/><path d="M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2"/><path d="M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8"/><path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15"/>',
  crown:'<path d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z"/><path d="M5 21h14"/>',
  edit:'<path d="M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z"/>',
});
const CAT = { Fitness:['#2F4A66','dumbbell'], Faith:['#4A3A6B','moon'], Mind:['#2F5A4C','sun'], Health:['#1F5560','leaf'], Discipline:['#5E4A30','target'], Learning:['#5A5420','book'] };
const CH = { read:['Read 30','Learning',30,'Read 10 pages · Camera'], up5:['Up by 5','Discipline',7,'Out of bed by 5:30 · Self-reported'], hyd:['Hydrate 30','Health',30,'Drink 3 L · Self-reported'], fajr:['Fajr 30','Faith',30,'Fajr on time · Camera · 4:50–6:10 am'], ndo:['No Days Off 75','Discipline',75,'5 tasks · Strict'], show:['Show Up 7','Fitness',7,'Gym check-in · Location'], run:['Run 30','Fitness',30,'3 km run · Photo optional'], mind:['Mind 14','Mind',14,'Journal 100 words · Self-reported'], clean:['Clean 30','Health',30,'Meal photo · Camera'], fajr14:['Fajr 14','Faith',14,'Fajr on time · Camera'], morning:['Morning routine','Discipline',21,'3 tasks · Standard'], hyd14:['Hydrate 14','Health',14,'Drink 3 L · Camera'] };
function cover(k, w, h, o={}) {
  const c = CH[k], t = CAT[c[1]], big = w >= 200;
  if (w < 60) return d(`width:${w}px;height:${h}px;border-radius:${o.r??10}px;flex:none;background:linear-gradient(160deg,${t[0]} 0%,#151414 92%);display:flex;align-items:center;justify-content:center;`, sp(NUM+`font-size:${Math.round(w*0.42)}px;line-height:1;color:${C.t1};`, c[2]));
  return d(`position:relative;width:${w}px;height:${h}px;border-radius:${o.r??14}px;overflow:hidden;flex:none;background:linear-gradient(160deg,${t[0]} 0%,#151414 92%);`,
    d(`position:absolute;left:${big?16:10}px;top:${big?14:10}px;`, ic(t[1], big?22:16, C.t1)) +
    d(`position:absolute;left:${big?16:10}px;bottom:${big?14:10}px;display:flex;flex-direction:column;`, sp(NUM+`font-size:${Math.round(w*0.3)}px;line-height:1;color:${C.t1};`, c[2]) + sp(`font-size:${big?13:11}px;line-height:${big?16:13}px;font-weight:500;color:${C.t1};opacity:0.86;`, 'days')));
}
const chRow = (k, sub, right) => d(`display:flex;align-items:center;gap:12px;min-height:72px;`, cover(k,48,60,{r:10}) + d('flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,CH[k][0]) + tx('s',C.t2, sub || `${CH[k][2]} days · ${CH[k][3]}`)) + (right ?? ic('cr',18,C.t2)));
const rootHead = (title, right) => d(`display:flex;align-items:center;justify-content:space-between;padding:6px 16px 0;min-height:52px;`, tx('tl',C.t1,title) + (right||''));
const searchBar = (val, focus) => d(`margin:10px 16px 0;height:40px;border-radius:12px;background:${C.surf};display:flex;align-items:center;gap:8px;padding:0 12px;${focus?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:''}`, ic('search',17,C.t2) + tx('b', val?C.t1:C.t2, val||'Challenges and people','flex:1;') + (val?ic('x',16,C.t2):''));
const chips = (list, sel) => d('display:flex;gap:8px;padding:12px 16px 0;overflow:hidden;', list.map((l,i)=>chip(l,i===sel)).join(''));
const person = (k, sub, btn) => d(`display:flex;align-items:center;gap:12px;min-height:60px;`, av(k,44) + d('flex:1;min-width:0;', tx('h',C.t1,PPL[k][0],'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;') + tx('s',C.t2,sub)) + (btn||''));
const smallBtn = (l, on) => d(`height:36px;padding:0 14px;border-radius:999px;display:flex;align-items:center;flex:none;${on?`background:${C.t1};color:${C.ink};`:`background:${C.raised};color:${C.t1};`}${T.h}`, l);
const sectionH = (t, r) => d('display:flex;align-items:baseline;justify-content:space-between;padding:22px 16px 10px;', tx('t',C.t1,t) + (r?tx('s',C.t2,r):''));
const menuSheet = (title, rows) => sheet((title?tx('h',C.t2,title,'text-align:center;'):'') + d(`background:${C.raised};border-radius:14px;overflow:hidden;`, rows.map(([i,l,s],k)=>d(`display:flex;align-items:center;gap:12px;min-height:52px;padding:0 14px;${k?`border-top:1px solid ${C.surf};`:''}`, ic(i,20) + d('flex:1;', tx('b',C.t1,l) + (s?tx('c',C.t2,s):'')))).join('')) + btnS('Cancel'));
const comment = (k, text, time, o={}) => d(`display:flex;gap:10px;padding:8px 0;${o.dim?'opacity:0.55;':''}`, av(k,32) + d('flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;', d('display:flex;gap:6px;align-items:baseline;', tx('h',C.t1,PPL[k][0].split(' ')[0]) + tx('c',C.t2,time)) + tx('b',C.t1,text) + (o.foot||'')));
const composer = (val, o={}) => d(`position:absolute;left:0;right:0;bottom:${o.bottom??34}px;padding:8px 12px;background:${C.surf};display:flex;align-items:center;gap:10px;z-index:32;`, av('yaseen',32) + d(`flex:1;min-height:40px;border-radius:20px;background:${C.raised};display:flex;align-items:center;padding:0 14px;`, tx('b',val?C.t1:C.t2,val||'Add a comment')) + d(`width:44px;height:44px;border-radius:999px;display:flex;align-items:center;justify-content:center;background:${val?C.t1:C.raised};`, o.spin?spin(16):ic('send',18,val?C.ink:C.t2)));

const kb2 = (rows, cols=3) => d(`position:absolute;left:0;right:0;bottom:0;height:300px;z-index:25;background:${C.surf};padding:8px 6px 40px;box-sizing:border-box;display:grid;grid-template-columns:repeat(${cols},1fr);gap:${cols>3?'12px 6px':'7px'};`, rows.map(k=>d(`height:${cols>3?42:48}px;border-radius:8px;background:${k?C.raised:'transparent'};`)).join(''));
function build2(v47) {
  const pReadBtn = btnP('Read 10 pages', { icon:'camera' });
  build(v47);
  NEXT = 501;
  const FL2 = { hub:'GRIIT v48 Atlas B2.dc.html', feed:'GRIIT v48 Atlas 5 Feed.dc.html', disc:'GRIIT v48 Atlas 6 Discover.dc.html', ch:'GRIIT v48 Atlas 7 Challenge.dc.html', prof:'GRIIT v48 Atlas 8 Profile.dc.html', flows:'GRIIT v48 Atlas Flows B2.dc.html' };
  const B2 = []; const reg2 = (k) => { B2.push(k); return k; };
  const F2 = (k, m, html) => { reg2(k); return F(k, m, html); };
  // ================= AREA 5 · FEED AND POSTS =================
  CUR = FL2.feed;
  const longName = { who:'abd', sub:'Fajr 30 · Day 30 of 30', time:'3h', ph:['pray1'], cap:'Thirty mornings. Some of them were ugly: two alarms, a cold floor and a bad night before. Still here. Thank you to everyone in the room who nudged me on day 19.', r:'31', c:'8' };
  const textCard = (k, task, sub, words, time) => d(`margin:6px 16px;background:${C.surf};border-radius:16px;padding:12px;display:flex;flex-direction:column;gap:10px;`, d('display:flex;align-items:center;gap:10px;', av(k,32) + d('flex:1;', tx('h',C.t1,PPL[k][0]) + tx('s',C.t2,sub + ' · ' + time)) + ic('more',20,C.t2)) + d(`background:${C.raised};border-radius:12px;padding:14px;display:flex;flex-direction:column;gap:4px;`, d('display:flex;align-items:center;gap:8px;', ic('pen',16) + tx('h',C.t1,task)) + tx('s',C.t2,`${words} words · Self-reported · the words stay private`)) + d('display:flex;gap:8px;', d('display:flex;align-items:center;gap:5px;min-height:44px;min-width:44px;', ic('heart',22)) + d('display:flex;align-items:center;gap:5px;min-height:44px;min-width:44px;', ic('msg',22))));
  const A5 = [];
  A5.push(F2('pcLong', { route:'(tabs)/index', comp:'FeedPhotoPost', state:'Long name (32 chars), long caption, 4:5 with the caption over the image', src:'v44 164', b75:'pending', fields:'caption ≤ 120 shown in full on post/[id]; 3 lines in the feed' },
    phone({ time:'7:40', tab:'home', body: feedHead(0) + photoPost({ ...longName, cap: longName.cap.slice(0,118) + '…' }) })));
  A5.push(F2('pcMix', { route:'(tabs)/index', comp:'FeedRows', state:'Self-reported row, text completion, grouped activity, broken photo', src:'v46 186', b75:'pending' },
    phone({ time:'7:40', tab:'home', body: feedHead(0) + selfRow('omar','Drink 3 L','Self-reported · No Days Off 75','1h','2') + textCard('zayd','Journal','Mind 14 · Day 6 of 14',104,'2h') + actGroup(['bilal','khalid','hamza'],'Bilal, Khalid and Hamza finished Up by 5','3h') + photoPost({ who:'khalid', sub:'Show Up 7 · Day 4 of 7', time:'4h', ph:[], broken:true, task:'Gym check-in', r:'', c:'' }) })));
  const heartBurst = d('position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);', ic('heart',96,C.t1,{fill:C.t1}));
  A5.push(F2('pcRespect', { route:'(tabs)/index', comp:'FeedPhotoPost', state:'Double-tap respect · count appears at 1', src:'v42 121', b75:'pending', fields:'respects ← count(respects) · hidden at 0' },
    phone({ time:'7:41', tab:'home', body: feedHead(0) + photoPost({ who:'hamza', sub:'Fajr 30 · Day 21 of 30', time:'2h', ph:['pray2'], cap:'', r:'1', c:'' }).replace(img('pray2'), img('pray2') + heartBurst).replace(ic('heart',24,C.t1,{}), ic('heart',24,C.t1,{fill:C.t1})) })));
  A5.push(F2('pcZero', { route:'(tabs)/index', comp:'FeedPhotoPost', state:'Counts hidden at 0', src:'v44 164', b75:'differs · build 75 shows “0”', fields:'' },
    phone({ time:'7:41', tab:'home', body: feedHead(0) + photoPost({ who:'bilal', sub:'Clean 30 · Day 3 of 30', time:'5m', ph:['food1'], cap:'Prep for three days.', r:'', c:'' }) })));
  A5.push(F2('sealSheet', { route:'(tabs)/index', comp:'CameraSealSheet', state:'Tap the seal', src:'v42 seal', b75:'pending' },
    phone({ time:'7:41', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: sheet(d('display:flex;align-items:center;gap:10px;', seal() + tx('t',C.t1,'Taken in GRIIT')) + tx('b',C.t2,'Khalid took this with GRIIT’s camera at 7:12 am. It’s a live photo, never from the camera roll.') + tx('b',C.t2,'GRIIT doesn’t check what’s in the photo. Proof without a photo shows as Self-reported.') + btnS('Got it')) })));
  A5.push(F2('whoResp', { route:'(tabs)/index', comp:'WhoRespectedSheet', state:'12 respects', src:'v43', b75:'pending' },
    phone({ time:'7:41', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: sheet(tx('t',C.t1,'12 respects') + ['omar','bilal','zayd','hamza','abd'].map((k,i)=>person(k, ['Mutual','Follows you','Mutual','','Follows you'][i] || '@'+PPL[k][0].split(' ')[0].toLowerCase(), smallBtn(i===3?'Follow':'Following', i===3))).join(''), { h:600 }) })));
  const postBody = (withPhoto) => stepHead('Post','',{back:true, right: ic('more',20)}) + postHead('khalid','Read 30 · Day 15 of 30','12m').replace(/<div style="width:44px;height:44px;display:flex;align-items:center;justify-content:center;"><svg[^]*?<\/svg><\/div><\/div>$/, '</div>') +
    (withPhoto ? d('position:relative;width:393px;height:491px;', img('book1') + d('position:absolute;left:12px;top:12px;', seal())) : d(`margin:0 16px;background:${C.surf};border-radius:16px;padding:16px;display:flex;flex-direction:column;gap:4px;`, d('display:flex;align-items:center;gap:8px;', doneDot(28) + tx('h',C.t1,'Drink 3 L')) + tx('s',C.t2,'12 cups · Self-reported · 9:40 pm'))) +
    d('padding:10px 16px 0;display:flex;flex-direction:column;gap:6px;', (withPhoto?tx('b',C.t1,'Before work. Chapter 9.'):'') + tx('s',C.t2, withPhoto?'Read 10 pages · Camera · 7:12 am':'No Days Off 75 · Day 12 of 75')) + actions(withPhoto?'12':'2', withPhoto?'3':'');
  A5.push(F2('postPhoto', { route:'post/[id]', comp:'PostDetail', state:'With a photo · comments below', src:'v12 39', b75:'pending' },
    phone({ time:'7:42', body: postBody(true) + d('padding:0 16px;', comment('omar','Same book. Chapter 9 is the turn.','8m') + comment('bilal','Up before work every day this week.','5m')), overlay: composer('') })));
  A5.push(F2('postSelf', { route:'post/[id]', comp:'PostDetail', state:'Without a photo (self-reported)', src:'v12 39', b75:'pending' },
    phone({ time:'7:42', body: postBody(false).replace(postHead('khalid','Read 30 · Day 15 of 30','12m').slice(0,40), postHead('khalid','Read 30 · Day 15 of 30','12m').slice(0,40)).replace(/Khalid Noor/,'Omar Siddiqui').replace('Read 30 · Day 15 of 30','No Days Off 75 · 1h'), overlay: composer('') })));
  const cSheet = (inner, val, o={}) => sheet(tx('h',C.t1,'Comments','text-align:center;') + inner, { h:620 }) + composer(val, { bottom:34, spin:o.spin });
  A5.push(F2('cmEmpty', { route:'(tabs)/index', comp:'CommentsSheet', state:'Empty', src:'v12 51', b75:'pending' }, phone({ time:'7:42', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: cSheet(tx('s',C.t2,'No comments yet.','text-align:center;padding:60px 0;'), '') })));
  const cList = comment('omar','Same book. Chapter 9 is the turn.','8m') + comment('bilal','Up before work every day this week.','5m') + comment('abd','Which translation are you reading? Mine has terrible footnotes and I keep losing my place.','2m');
  A5.push(F2('cmList', { route:'(tabs)/index', comp:'CommentsSheet', state:'List', src:'v12 51', b75:'pending' }, phone({ time:'7:42', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: cSheet(cList, '') })));
  A5.push(F2('cmPosting', { route:'(tabs)/index', comp:'CommentsSheet', state:'Posting', src:'new', b75:'pending' }, phone({ time:'7:43', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: cSheet(cList + comment('yaseen','Penguin edition. Footnotes at the back.','now',{dim:true, foot: tx('c',C.t2,'Posting')}), '', {spin:true}) })));
  A5.push(F2('cmFailed', { route:'(tabs)/index', comp:'CommentsSheet', state:'Failed', src:'new', b75:'not built' }, phone({ time:'7:43', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: cSheet(cList + comment('yaseen','Penguin edition. Footnotes at the back.','now',{dim:true, foot: d('display:flex;align-items:center;gap:6px;min-height:32px;', ic('alert',14) + tx('c',C.t1,'Didn’t send. Tap to retry.'))}), '') })));
  A5.push(F2('cmDelete', { route:'(tabs)/index', comp:'CommentsSheet', state:'Deleting your own (long-press)', src:'new', b75:'pending' }, phone({ time:'7:44', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: cSheet(cList + comment('yaseen','Penguin edition. Footnotes at the back.','1m'), '') + dialog('Delete your comment?','It’s removed for everyone.', d('display:flex;gap:8px;', btnS('Cancel',{flex:1}) + btnS('Delete',{flex:1}))) })));
  const gone = (t, s) => phone({ time:'7:45', body: stepHead('Post','',{back:true}) + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:240px 32px 0;text-align:center;', ic(t==='d'?'trash':'lock',28,C.t2) + tx('t',C.t1, t==='d'?'This post was deleted':'This proof is private now') + tx('b',C.t2,s)), sticky: btnS('Back to the feed'), stickyH:68 });
  A5.push(F2('postDeleted', { route:'post/[id]', comp:'PostDetail', state:'Deleted post (opened from a push)', src:'new', b75:'not built' }, gone('d','Khalid removed it. Comments went with it.')));
  A5.push(F2('postPrivate', { route:'post/[id]', comp:'PostDetail', state:'Post is now private', src:'new', b75:'not built' }, gone('p','Khalid made it private after you saw it.')));
  A5.push(F2('ovOther', { route:'(tabs)/index', comp:'PostOverflow', state:'Someone else’s post', src:'v43', b75:'pending' }, phone({ time:'7:45', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: menuSheet('Khalid’s post', [['eyeoff','Hide this post','You won’t see it again'],['flag','Report','Tell us what’s wrong'],['ban','Block Khalid','He can’t see your profile or proofs']]) })));
  const reasons = ['Not a real proof','Nudity or sexual content','Hate or harassment','Violence or self-harm','Spam','Something else'];
  A5.push(F2('repReason', { route:'(tabs)/index', comp:'ReportSheet', state:'Reason picker', src:'new', b75:'not built', fields:'minimum handling: email to griit.health@gmail.com (reporter, post, reason, link)' }, phone({ time:'7:45', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: sheet(tx('t',C.t1,'Why are you reporting this?') + tx('s',C.t2,'Khalid won’t know it was you.') + d(`background:${C.raised};border-radius:14px;overflow:hidden;`, reasons.map((r,i)=>d(`display:flex;align-items:center;min-height:48px;padding:0 14px;${i?`border-top:1px solid ${C.surf};`:''}`, tx('b',C.t1,r,'flex:1;') + (i===0?ic('check',18,C.t1,{sw:3}):''))).join('')) + btnP('Send report'), { h:640 }) })));
  A5.push(F2('repDone', { route:'(tabs)/index', comp:'ReportSheet', state:'Sent', src:'new', b75:'not built' }, phone({ time:'7:46', tab:'home', body: feedHead(0) + selfRow('omar','Drink 3 L','Self-reported · No Days Off 75','1h','2'), overlay: sheet(d('display:flex;flex-direction:column;align-items:center;gap:6px;text-align:center;', ic('ccheck',32) + tx('t',C.t1,'Report sent') + tx('b',C.t2,'We hid the post for you. If it breaks the guidelines it comes down for everyone.')) + btnS('Block Khalid too') + btnT('Done')) })));
  A5.push(F2('blkConfirm', { route:'(tabs)/index', comp:'BlockConfirm', state:'Confirm', src:'new', b75:'pending' }, phone({ time:'7:46', tab:'home', body: feedHead(0) + photoPost(KH_POST), overlay: dialog('Block Khalid?','He won’t see your profile or proofs, and you won’t see his. He isn’t told. If you share a group, you both stay in it.', d('display:flex;gap:8px;', btnS('Cancel',{flex:1}) + btnS('Block',{flex:1}))) })));
  A5.push(F2('blkDone', { route:'(tabs)/index', comp:'Toast', state:'Blocked', src:'new', b75:'pending' }, phone({ time:'7:46', tab:'home', body: feedHead(0) + selfRow('omar','Drink 3 L','Self-reported · No Days Off 75','1h','2') + actGroup(['bilal','zayd','hamza'],'Bilal, Zayd and Hamza started Read 30','1h'), toast: d(`position:absolute;left:16px;right:16px;bottom:95px;z-index:16;background:${C.raised};border-radius:14px;padding:6px 6px 6px 14px;display:flex;align-items:center;gap:10px;`, ic('ban',18) + tx('s',C.t1,'Khalid is blocked. Undo in Settings, Privacy.','flex:1;') + btnT('Undo')) })));
  A5.push(F2('ovOwn', { route:'(tabs)/index', comp:'PostOverflow', state:'Your own post', src:'v43', b75:'pending' }, phone({ time:'7:47', tab:'home', body: feedHead(0) + photoPost({ who:'yaseen', sub:'Read 30 · Day 2 of 30', time:'5m', ph:['book1'], cap:'Chapter 4 done.', r:'3', c:'' }), overlay: menuSheet('Your post', [['share','Share','Instagram, Messages, Save'],['trash','Delete from the feed','The proof stays private in your record. The day stays secured.']]) })));
  A5.push(F2('viewer', { route:'(tabs)/index', comp:'ImageViewerModal', state:'Full screen, pinch to zoom', src:'v39', b75:'pending' }, phone({ time:'7:47', onPhoto:true, bg:'#000', full: d('position:absolute;left:0;right:0;top:180px;height:491px;', img('book1')) + d('position:absolute;left:12px;top:59px;width:44px;height:44px;border-radius:999px;background:rgba(15,15,15,0.5);display:flex;align-items:center;justify-content:center;', ic('x',20)) + d('position:absolute;left:16px;right:16px;bottom:54px;display:flex;flex-direction:column;gap:4px;', tx('h',C.t1,'Khalid Noor') + tx('s',C.t1,'Read 10 pages · Read 30 · Day 15 of 30 · 7:12 am')) })));

  // ================= AREA 6 · DISCOVER AND JOINING =================
  CUR = FL2.disc;
  const A6 = [];
  const catList = ['All','Fitness','Faith','Mind','Health','Discipline','Learning'];
  const featured = d('display:flex;gap:12px;padding:0 16px;overflow:hidden;', ['fajr','read','show'].map(k=>d('display:flex;flex-direction:column;gap:6px;width:160px;flex:none;', cover(k,160,200) + tx('h',C.t1,CH[k][0]) + tx('s',C.t2, {fajr:'214 people · Camera',read:'1,208 people · Camera',show:'96 people · Location'}[k]))).join(''));
  const grid = (ks) => d('display:grid;grid-template-columns:1fr 1fr;gap:16px 12px;padding:0 16px;', ks.map(k=>d('display:flex;flex-direction:column;gap:6px;', cover(k,174,218) + tx('h',C.t1,CH[k][0]) + tx('s',C.t2,`${CH[k][2]} days · ${CH[k][1]}`))).join(''));
  const peopleRow = d('display:flex;gap:14px;padding:0 16px;overflow:hidden;', [['khalid','7 days'],['omar','Day 12 of 75'],['bilal','3 days'],['hamza','21 days'],['zayd','Day 6 of 14']].map(([k,s])=>d('display:flex;flex-direction:column;align-items:center;gap:6px;width:76px;flex:none;', av(k,56) + tx('c',C.t1,PPL[k][0].split(' ')[0]) + tx('c',C.t2,s,'text-align:center;'))).join(''));
  A6.push(F2('discAll', { route:'(tabs)/discover', comp:'DiscoverScreen', state:'All', src:'v46 187', b75:'differs · build 75 hero shows the proof fallback “Task”', fields:'covers ← coverFor(category, duration) · counts ← challenges.member_count' },
    phone({ time:'12:10', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,0) + sectionH('Featured') + featured + sectionH('People you may know') + peopleRow + sectionH('Popular this week') + grid(['hyd','ndo']) })));
  A6.push(F2('discCat', { route:'(tabs)/discover', comp:'DiscoverScreen', state:'Category chip: Faith', src:'v46 187', b75:'pending' },
    phone({ time:'12:10', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,2) + sectionH('Faith','4 challenges') + grid(['fajr','fajr']).replace(/Fajr 30<\/div>([^]*?)Fajr 30/, 'Fajr 30</div>$1Quran daily') + d('height:16px') + d('padding:0 16px;', tx('s',C.t2,'Selected chips invert: light fill, ink text. No orange.')) })));
  A6.push(F2('discCovers', { route:'reference', comp:'CoverGenerator', state:'Six categories side by side, greyscale test below', src:'v41 122', b75:'differs · build 75 can fall back to a proof tile' },
    d('position:relative;width:393px;height:852px;border-radius:55px;overflow:hidden;background:'+C.ink+';box-shadow:0 0 0 1px #2A2928,0 0 0 6px #050505;padding:70px 16px 0;display:flex;flex-direction:column;gap:12px;', tx('l',C.t2,'Colour') + d('display:grid;grid-template-columns:repeat(3,1fr);gap:10px;', ['fajr','read','show','hyd','ndo','mind'].map(k=>d('display:flex;flex-direction:column;gap:4px;', cover(k,112,140,{r:12}) + tx('c',C.t2,CH[k][1]))).join('')) + tx('l',C.t2,'Greyscale: the icon and numeral still tell them apart') + d('display:grid;grid-template-columns:repeat(6,1fr);gap:6px;filter:grayscale(1);', ['fajr','read','show','hyd','ndo','mind'].map(k=>cover(k,54,68,{r:8})).join('')) + tx('s',C.t2,'Tints rise in chroma from tokens.v46 so six covers separate by colour alone (flag 199). Covers never use a proof photo.'))));
  A6.push(F2('discSearch', { route:'(tabs)/discover', comp:'DiscoverSearch', state:'Typing', src:'v43', b75:'pending' },
    phone({ time:'12:11', tab:'discover', body: rootHead('Discover') + searchBar('fa', true) + d('padding:8px 16px;', tx('l',C.t2,'Challenges','padding:10px 0 2px;') + chRow('fajr','30 days · Faith · 214 people')) + d('padding:0 16px;', tx('l',C.t2,'People','padding:10px 0 2px;') + person('abd','@abdurrahman · Fajr 30 · Day 30 of 30')), overlay: kb2(Array(30).fill(' '),10) })));
  A6.push(F2('discResults', { route:'(tabs)/discover', comp:'DiscoverSearch', state:'Results: challenges and people', src:'v43', b75:'pending', fields:'people never include you or test accounts' },
    phone({ time:'12:11', tab:'discover', body: rootHead('Discover') + searchBar('run') + d('padding:8px 16px;', tx('l',C.t2,'Challenges','padding:10px 0 2px;') + chRow('run','30 days · Fitness · 412 people') + chRow('show','7 days · Fitness · 96 people') + tx('l',C.t2,'People','padding:14px 0 2px;') + person('omar','Run 30 · Day 9 of 30', smallBtn('Following')) + person('zayd','12-day streak', smallBtn('Follow',true))) })));
  A6.push(F2('discNone', { route:'(tabs)/discover', comp:'DiscoverSearch', state:'No results', src:'v43', b75:'pending' },
    phone({ time:'12:12', tab:'discover', body: rootHead('Discover') + searchBar('ice bath 21') + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:160px 32px 0;text-align:center;', tx('t',C.t1,'Nothing called “ice bath 21”') + tx('b',C.t2,'Make it yourself. You set the days and what counts as proof.') + d('height:6px') + btnS('Create “ice bath 21”',{icon:'plus'})) })));
  const skel = (w,h,r=8) => d(`width:${w};height:${h}px;border-radius:${r}px;box-shadow:inset 0 0 0 1px ${C.hair};flex:none;`);
  A6.push(F2('discLoad', { route:'(tabs)/discover', comp:'DiscoverScreen', state:'Loading (after 1 s)', src:'v46 187', b75:'pending' },
    phone({ time:'12:10', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,0) + d('padding:22px 16px 0;display:flex;flex-direction:column;gap:12px;', skel('40%',22) + d('display:flex;gap:12px;', skel('160px',200,14) + skel('160px',200,14) + skel('40px',200,14)) + skel('50%',22) + d('display:flex;gap:12px;', skel('174px',218,14) + skel('174px',218,14))) })));
  A6.push(F2('discErr', { route:'(tabs)/discover', comp:'DiscoverScreen', state:'Error', src:'v46 187', b75:'pending' },
    phone({ time:'12:10', tab:'discover', body: rootHead('Discover') + searchBar() + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:200px 32px 0;text-align:center;', ic('alert',28,C.t2) + tx('t',C.t1,'Discover didn’t load') + tx('b',C.t2,'Check your connection. Your challenges are unaffected.') + d('height:6px') + btnS('Try again',{icon:'retry'})) })));
  A6.push(F2('discSparse', { route:'(tabs)/discover', comp:'DiscoverScreen', state:'Sparse: fewer than 5 community challenges', src:'v43.1 158', b75:'pending' },
    phone({ time:'12:10', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,0) + sectionH('Challenges','sorted by people in them') + d('padding:0 16px;', ['read','fajr','hyd','up5','show'].map(k=>chRow(k)).join('')) + d('padding:10px 16px;', btnS('Create your own',{icon:'plus'})) })));
  A6.push(F2('discSlug', { route:'discover/category/[slug]', comp:'CategoryScreen', state:'Fitness', src:'new', b75:'pending' },
    phone({ time:'12:13', body: stepHead('Fitness','6 challenges',{back:true}) + d('padding:4px 16px 0;', tx('s',C.t2,'Sorted by people in them. Community challenges are marked.','padding-bottom:6px;') + ['show','run','ndo','show','run'].map((k,i)=>chRow(k, i===3?'14 days · Community · by Khalid · 8 people':i===4?'5K in 21 days · Community · 23 people':null)).join('')) })));
  const preview = (k) => sheet(d('display:flex;gap:14px;align-items:center;', cover(k,96,120) + d('flex:1;', tx('t',C.t1,CH[k][0]) + tx('s',C.t2,`${CH[k][2]} days · ${CH[k][1]} · 214 people`))) + tx('b',C.t1,'Pray Fajr on time for 30 days. A live photo, between 4:50 and 6:10 am.') + d(`background:${C.raised};border-radius:14px;padding:4px 12px;`, taskRow({name:'Fajr on time', gate:[G.cam,['clock','4:50–6:10 am']], st:'open', right:''})) + tx('s',C.t2,'Standard: a freeze can cover a missed day.') + btnP('Join Fajr 30') + btnT('See full details'));
  A6.push(F2('preview', { route:'(tabs)/discover', comp:'ChallengePreviewSheet', state:'Before joining', src:'v44 168', b75:'pending' }, phone({ time:'12:14', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,0) + sectionH('Featured') + featured, overlay: preview('fajr'), inset:'sheet' })));
  // challenge/[id]
  const detail = (k, o={}) => {
    const c = CH[k];
    return d('position:relative;height:300px;overflow:hidden;', cover(k,393,300,{r:0}) + d('position:absolute;left:6px;top:4px;width:44px;height:44px;border-radius:999px;background:rgba(15,15,15,0.45);display:flex;align-items:center;justify-content:center;', ic('cl',22)) + d('position:absolute;right:6px;top:4px;width:44px;height:44px;border-radius:999px;background:rgba(15,15,15,0.45);display:flex;align-items:center;justify-content:center;', ic('share',20))) +
      d('padding:16px 16px 0;display:flex;flex-direction:column;gap:6px;', tx('tl',C.t1,o.title||c[0]) + tx('s',C.t2, o.facts || `${c[2]} days · ${c[1]} · ${o.solo===false?'Group':'Solo'} · ${o.people||'214 people'}`) + (o.by?tx('s',C.t2,o.by):'') + (o.notice||'')) +
      d('padding:16px 16px 0;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,'Every day') + (o.tasks || taskRow({name:'Fajr on time', gate:[G.cam,['clock','4:50–6:10 am']], st:'open', right:''}))) +
      d('padding:8px 16px 0;', tx('s',C.t2, o.rule || 'Standard. A freeze can cover a missed day.')) +
      (o.people2 ? d('padding:16px 16px 0;display:flex;flex-direction:column;gap:8px;', tx('h',C.t1,'People in it') + d('display:flex;align-items:center;gap:8px;', d('display:flex;', ['khalid','hamza','abd'].map((p,i)=>d(i?'margin-left:-8px;':'', av(p,28,C.ink))).join('')) + tx('s',C.t2,'Khalid, Hamza and 211 others'))) : '');
  };
  A6.push(F2('chCatalog', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Catalog, not joined', src:'v46 189 / v29', b75:'pending', fields:'people ← member_count · never you, never test accounts' }, phone({ time:'12:15', body: detail('fajr',{people2:true}), sticky: btnP('Join Fajr 30') + tx('c',C.t2,'Day 1 is today. The window opens at 4:50 am tomorrow if today’s has closed.','text-align:center;'), stickyH:96 })));
  A6.push(F2('chCommunity', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Community (made by a user)', src:'v43', b75:'pending' }, phone({ time:'12:16', body: detail('show',{title:'Gym 14', facts:'14 days · Fitness · Solo · 8 people', by:'Made by Khalid Noor', tasks: taskRow({name:'Gym check-in', gate:[G.loc], st:'open', right:''}) + taskRow({name:'Log the session', gate:[[null,'Text · 20 words'],G.self], st:'open', right:''}), people2:true}), sticky: btnP('Join Gym 14'), stickyH:72 })));
  A6.push(F2('chStrict', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Strict (no freezes)', src:'v29', b75:'pending' }, phone({ time:'12:17', body: detail('ndo',{facts:'75 days · Discipline · Solo · 1,840 people', tasks: [['Progress photo',[G.cam,G.by7]],['Workout 45 min',[[null,'45 min'],G.self]],['Drink 3 L',[[null,'12 cups'],G.self]],['Read 10 pages',[[null,'10 pages'],G.opt]],['Journal',[[null,'100 words'],G.self]]].map(([n,g])=>taskRow({name:n, gate:g, st:'open', right:''})).join(''), rule:'Strict. A missed day resets your streak in this challenge to 0. No freezes.'}), sticky: btnP('Join No Days Off 75'), stickyH:72 })));
  A6.push(F2('chEnded', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Ended (community, creator closed it)', src:'v29', b75:'pending' }, phone({ time:'12:18', body: detail('show',{title:'Gym 14', facts:'14 days · Fitness · Ended Sep 30', by:'Made by Khalid Noor', tasks: taskRow({name:'Gym check-in', gate:[G.loc], st:'open', right:''})}), sticky: tx('s',C.t2,'This challenge ended on Sep 30. You can still see it, but not join.','text-align:center;') + btnS('Find a similar one'), stickyH:96 })));
  A6.push(F2('chJoined', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Already joined', src:'v29', b75:'pending' }, phone({ time:'12:18', body: detail('read',{facts:'30 days · Learning · Solo · 1,208 people', tasks: taskRow({name:'Read 10 pages', gate:[[null,'10 pages'],G.cam], st:'open', right:''}), notice: tx('s',C.t1,'You’re in it · Day 2 of 30')}), sticky: btnS('Go to my Read 30'), stickyH:68 })));
  A6.push(F2('chInvite', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Invite-only group (invited)', src:'v45 / v12 37', b75:'pending' }, phone({ time:'12:19', body: detail('up5',{facts:'7 days · Discipline · Group · 3 of 10', tasks: taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}), notice: d('display:flex;align-items:center;gap:8px;padding-top:4px;', av('khalid',24) + tx('s',C.t1,'Khalid invited you. Only invited people can see this room.'))}), sticky: btnP('Accept') + btnT('Not now'), stickyH:116 })));
  A6.push(F2('chLimit', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Free-tier limit reached (Yaseen)', src:'v29', b75:'differs · build 75 opens a blank page' }, phone({ time:'12:30', body: detail('fajr',{}), sticky: tx('s',C.t2,'You’re in 3 challenges, the Free limit.','text-align:center;') + btnP('Leave one or go Pro'), stickyH:96 })));
  A6.push(F2('joinConfirm', { route:'challenge/[id]', comp:'JoinConfirmSheet', state:'Confirm', src:'v44', b75:'pending' }, phone({ time:'12:20', body: detail('fajr',{}), overlay: sheet(tx('t',C.t1,'Join Fajr 30?') + d(`background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;flex-direction:column;gap:4px;`, tx('h',C.t1,'Day 1 is tomorrow') + tx('s',C.t2,'Today’s window (4:50–6:10 am) has closed, so today can’t be lost to it.')) + tx('s',C.t2,'A live photo every morning. Private until you share it.') + btnP('Join, start tomorrow') + btnT('Cancel')) })));
  const errSheet = (t, b, btn) => sheet(d('display:flex;flex-direction:column;gap:6px;align-items:center;text-align:center;', ic('alert',28,C.t2) + tx('t',C.t1,t) + tx('b',C.t2,b)) + btn + btnT('Close'));
  A6.push(F2('joinErrs', { route:'challenge/[id]', comp:'JoinErrorSheet', state:'4 errors: full · ended · already in · offline', src:'v41 120', b75:'pending' }, d('display:grid;grid-template-columns:repeat(2,190px);gap:12px;', [['Group is full','Up by 5 has 10 of 10 people. Ask Khalid to make room, or start your own.',btnS('Start my own')],['This challenge ended','Gym 14 closed on Sep 30. Nothing was joined.',btnS('Find a similar one')],['You’re already in it','Read 30 is on your Home, Day 2 of 30.',btnS('Go to Read 30')],['You’re offline','Nothing was joined. Try again when you’re back.',btnS('Try again')]].map(([a,b,c])=>d('width:190px;height:412px;overflow:hidden;', d('transform:scale(0.483);transform-origin:0 0;width:393px;', phone({ time:'12:21', body: detail('fajr',{}), overlay: errSheet(a,b,c) })))).join(''))));
  const gymBody = (sel, typed) => stepHead('Set your gym','Show Up 7 · step 2 of 2',{back:true}) + d('padding:8px 16px 0;display:flex;flex-direction:column;gap:12px;', tx('b',C.t2,'Check-ins only count within this distance of your gym.') + searchBar(typed||'', !!typed).replace('margin:10px 16px 0;','margin:0;').replace('Challenges and people','Search for your gym') +
    (typed ? d(`background:${C.surf};border-radius:14px;padding:4px 12px;`, ['Iron Works Gym · 1.2 km','Iron Works Annex · 3.8 km'].map((r,i)=>d(`display:flex;align-items:center;gap:10px;min-height:52px;${i?`border-top:1px solid ${C.raised};`:''}`, ic('pin',18) + tx('b',C.t1,r,'flex:1;') + (i===0?ic('check',18,C.t1,{sw:3}):''))).join('')) : btnS('Use where I am now',{icon:'nav'})) +
    tx('h',C.t1,'Distance') + d('display:flex;gap:8px;', ['100 m','250 m','500 m'].map(l=>chip(l, l===sel)).join('')) + tx('s',C.t2,'No map: GRIIT stores one point and a radius, nothing else.'));
  A6.push(F2('gym', { route:'challenge/set-gym', comp:'SetGymScreen', state:'Search and radius', src:'v44.1 177', b75:'pending', fields:'task.place {lat,lng}, task.radius_m (250 default)' }, phone({ time:'12:22', body: gymBody('250 m','iron w'), sticky: btnP('Save gym') + btnT('Skip, set it at the first check-in'), stickyH:116 })));
  A6.push(F2('lateJoin', { route:'(tabs)/index', comp:'HomeScreen', state:'After a late join: Day 1 is tomorrow', src:'v41 116', b75:'pending' }, phone({ time:'12:23', tab:'home', body: home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today. Fajr 30 starts tomorrow.', primary:pReadBtn, sections:[secRead('open'), secBed('done'), { name:'Fajr 30', day:'Day 1 is tomorrow', done:0, total:1, collapsed:true, tasks:[] }], feed:'' }), toast: toast({ title:'You joined Fajr 30', sub:'Day 1 is tomorrow. Window opens 4:50 am.', share:false }) })));
  const peopleRule = panel(393, tx('l',C.t2,'People row rules') + tx('s',C.t1,'Never shows you. Never shows test accounts (is_test or username null), filtered server-side.') + tx('s',C.t1,'Sub-label is one fact: a streak (“7 days”) or a position (“Day 12 of 75”). Never a follower count.') + peopleRow.replace('padding:0 16px;','padding:0;'));
  A6.push(peopleRule);

  // ================= AREA 7 · A CHALLENGE YOU'RE IN =================
  CUR = FL2.ch;
  const A7 = [];
  const board = (rows) => d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, rows.map(([r,k,n,you])=>d(`display:flex;align-items:center;gap:12px;min-height:52px;${you?`background:${C.raised};margin:0 -14px;padding:0 14px;border-radius:12px;`:''}`, sp(NUM+'font-size:15px;width:18px;color:'+C.t1+';', r) + av(k,32) + tx('h',C.t1, you?'You':PPL[k][0].split(' ')[0],'flex:1;') + d('display:flex;align-items:baseline;gap:4px;', sp(NUM+'font-size:17px;color:'+C.t1+';', n) + tx('c',C.t2,'secured')))).join(''));
  const active = (o={}) => stepHead(o.name||'Up by 5', '', {back:true, right: ic('more',20)}) +
    d('padding:4px 16px 0;display:flex;flex-direction:column;gap:12px;', d('display:flex;align-items:baseline;gap:8px;', sp(NUM+`font-size:40px;line-height:44px;color:${C.t1};`, o.day||'Day 5') + tx('t',C.t2, o.of||'of 7')) + tx('s',C.t2, o.dd||'4 days done · 4 secured') + strip(o.week||['sec','sec','sec','sec','today','fut','fut'],{prog:o.prog||0, letters:'TWTFSSM', today:o.ti??4}) + (o.freeze||'') + (o.line?tx('b',C.t1,o.line):'')) +
    d('padding:14px 16px 0;display:flex;flex-direction:column;gap:8px;', tx('h',C.t1,'Today') + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, o.tasks || taskRow(Y.bed(o.taskSt||'open',[G.self,['clock','4:30–5:30 am · 21 min left']])))) +
    (o.after||'');
  const recentProofs = d('padding:16px 16px 0;display:flex;flex-direction:column;gap:8px;', tx('h',C.t1,'Recent proofs') + d('display:grid;grid-template-columns:repeat(4,1fr);gap:4px;', [0,1,2,3].map(i=>d(`aspect-ratio:4/5;border-radius:8px;background:${C.surf};display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;`, tx('c',C.t1,'Day '+(4-i)) + tx('c',C.t2,'Self-rep.'))).join('')));
  const record = d('padding:16px 16px 0;', d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:flex;justify-content:space-between;align-items:center;min-height:52px;`, tx('h',C.t1,'Your record') + d('display:flex;align-items:center;gap:6px;', tx('s',C.t2,'4 of 4 days secured') + ic('cr',16,C.t2))));
  A7.push(F2('actSolo', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Solo · top', src:'v46 189', b75:'differs · build 75 text touches the left edge', fields:'Day 5 of 7 ← day_index · days done ← days_done · secured ← day_secures in range' }, phone({ time:'5:09', body: active({ after: recentProofs + record + d('padding:14px 16px;', btnS('Invite someone',{icon:'userplus'})) }), inset:'pushed' })));
  A7.push(F2('actSoloB', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Solo · scrolled: board, proofs, record, invite', src:'v44 166', b75:'pending' }, phone({ time:'5:09', scroll:330, body: active({ after: d('padding:16px 16px 0;display:flex;flex-direction:column;gap:8px;', tx('h',C.t1,'This week') + tx('s',C.t2,'A board needs two. Invite someone to compare weeks.')) + recentProofs + record + d('padding:14px 16px 0;display:flex;flex-direction:column;gap:8px;', btnS('Invite someone',{icon:'userplus'}) + tx('c',C.t2,'Up to 10 people. Each keeps their own streak.','text-align:center;')) }) })));
  const groupAfter = d('padding:16px 16px 0;display:flex;flex-direction:column;gap:8px;', d('display:flex;justify-content:space-between;align-items:baseline;', tx('h',C.t1,'This week') + tx('s',C.t2,'Secured days since Monday')) + board([['1','khalid','5'],['2','yaseen','4',true],['3','abd','4'],['4','bilal','3']]) + d(`display:flex;align-items:center;gap:10px;min-height:52px;background:${C.surf};border-radius:16px;padding:0 14px;`, ic('users',18) + tx('b',C.t1,'4 people · group streak 3','flex:1;') + ic('cr',16,C.t2)));
  A7.push(F2('actGroup', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Group (4 people)', src:'v45 179', b75:'pending' }, phone({ time:'5:09', body: active({ after: groupAfter }) })));
  A7.push(F2('actDone', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Done for today', src:'v42.1 145', b75:'pending' }, phone({ time:'5:02', body: active({ week:['sec','sec','sec','sec','todayDone','fut','fut'], dd:'5 days done · 4 secured', line:'Done for today. Read 30 still needs today’s pages before the day is secured.', taskSt:'done', after: groupAfter }) })));
  A7.push(F2('actMissed', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Missed yesterday · freeze row = Home copy', src:'v41 119', b75:'differs · build 75 copy contradicts Home', fields:'FREEZE from v48/copy.ts' }, phone({ time:'5:12', body: active({ week:['sec','sec','sec','miss','today','fut','fut'], dd:'4 days done · 3 secured', freeze: freezeRow({}).replace('Saturday','Saturday'), after: groupAfter }) })));
  A7.push(F2('actLast', { route:'challenge/active/[id]', comp:'ActiveChallenge', state:'Last day', src:'v44', b75:'pending' }, phone({ time:'4:41', body: active({ day:'Day 7', week:['sec','sec','sec','sec','sec','sec','today'], ti:6, dd:'6 days done · 6 secured', line:'Last day. Finish Out of bed to finish Up by 5.' , after: groupAfter }) })));
  const endScreen = (title, big, sub, line, cells, btns) => phone({ time:'9:00', body: stepHead('Up by 5','',{back:true}) + d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:40px 20px 0;text-align:center;', tx('l',C.t2,title) + sp(NUM+`font-size:56px;line-height:60px;color:${C.t1};`, big) + tx('b',C.t1,sub) + d('display:grid;grid-template-columns:repeat(7,1fr);gap:6px;width:100%;margin-top:10px;', cells.map(s=>dayCircle(s,38)).join('')) + tx('s',C.t2,line,'margin-top:6px;')), sticky: btns, stickyH:116 });
  A7.push(F2('endFinished', { route:'challenge/end', comp:'ChallengeEnd', state:'Finished', src:'v28.2 / Chunk T', b75:'pending' }, endScreen('Finished Oct 6','7 of 7','days done · 7 secured','Every day self-reported: Out of bed has no camera gate.',Array(7).fill('sec'), btnP('Start Up by 5, 14 days') + btnT('Done'))));
  A7.push(F2('endFailed', { route:'challenge/end', comp:'ChallengeEnd', state:'Failed (Strict)', src:'Chunk T', b75:'pending' }, endScreen('Failed on day 5','4 of 7','days done · 4 secured','Strict: a missed day ends the challenge. Your other streaks are unaffected.',['sec','sec','sec','sec','miss','fut','fut'], btnP('Start again') + btnT('Done'))));
  A7.push(F2('endQuit', { route:'challenge/end', comp:'ChallengeEnd', state:'Left on day 5', src:'Chunk T', b75:'pending' }, endScreen('Left on day 5','4 of 7','days done · 4 secured','You left at midnight on Oct 4. It stays in Profile, Challenges.',['sec','sec','sec','sec','sec','pre','pre'], btnS('Rejoin from Day 1') + btnT('Done'))));
  A7.push(F2('actMenu', { route:'challenge/active/[id]', comp:'ChallengeOverflow', state:'Overflow', src:'new', b75:'pending' }, phone({ time:'9:28', body: active({}), overlay: menuSheet('Up by 5', [['userplus','Invite someone','Up to 10 people'],['share','Share challenge',''],['logout','Leave','Takes effect at midnight']]) })));
  A7.push(F2('creatorLeave', { route:'challenge/active/[id]', comp:'ChallengeOverflow', state:'Creator leaves · ownership passes to the longest-standing member', src:'v45', b75:'pending' }, phone({ time:'9:28', body: active({}), overlay: sheet(tx('t',C.t1,'Leave Up by 5?') + tx('b',C.t2,'You made this room. When you leave at midnight, Khalid becomes the owner: he’s been in it longest. Your days stay in your record.') + btnS('Leave at midnight') + btnT('Stay')) })));
  const rosterRow = (k, st, streak, o={}) => d(`display:flex;align-items:center;gap:12px;min-height:60px;`, av(k,40) + d('flex:1;min-width:0;', tx('h',C.t1, (o.you?'You':PPL[k][0]) + (o.crown?'':''),'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;') + tx('s',C.t2, st + ' · ' + streak)) + (o.state==='done'?doneDot(28):o.state==='closed'?closedDot(28):o.state==='nudge'?smallBtn('Nudge'):openDot(28)));
  A7.push(F2('roster', { route:'challenge/[id]/members', comp:'MembersRoster', state:'Today: secured, not yet, closed, joined today, missed yesterday', src:'v45 179', b75:'pending', fields:'group streak ← consecutive days every member secured' }, phone({ time:'5:20', body: stepHead('People','Up by 5 · 5 of 10',{back:true}) + d('padding:4px 16px 0;display:flex;flex-direction:column;gap:4px;', d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, sp(NUM+'font-size:28px;color:'+C.t1+';','3') + d('flex:1;', tx('h',C.t1,'day group streak') + tx('s',C.t2,'Days every member secured or held with a freeze. Bilal missed yesterday with no freeze, so it restarted.'))) + tx('l',C.t2,'Today','padding:14px 0 2px;') +
    rosterRow('yaseen','Secured','7-day streak',{you:true,state:'done'}) + rosterRow('khalid','Secured','12-day streak',{state:'done'}) + rosterRow('abd','Not yet · 10 min left','4-day streak',{state:'nudge'}) + rosterRow('bilal','Missed yesterday · not yet','0 days',{state:'nudge'}) + rosterRow('hamza','Joined today · starts tomorrow','—',{state:'pre'})), sticky: btnS('Invite someone',{icon:'userplus'}), stickyH:68 })));
  A7.push(F2('invitePick', { route:'challenge/[id]/invite', comp:'InvitePicker', state:'Picker plus link', src:'v45 / 35', b75:'pending' }, phone({ time:'9:30', body: stepHead('Invite to Up by 5','5 of 10',{}) + searchBar().replace('Challenges and people','Search people you follow') + d('padding:12px 16px 0;', d(`display:flex;align-items:center;gap:10px;min-height:52px;background:${C.surf};border-radius:14px;padding:0 6px 0 14px;`, ic('link',18) + tx('b',C.t1,'{INVITE_BASE}/i/UP5K7Q2','flex:1;') + smallBtn('Copy')) + tx('l',C.t2,'Mutual','padding:16px 0 2px;') + person('omar','Mutual · not in a group', smallBtn('Invite',true)) + person('zayd','Mutual', smallBtn('Invited')) + person('hamza','Follows you', smallBtn('Invite',true))), sticky: btnP('Send 2 invites'), stickyH:72 })));
  const inviteScreen = (state) => phone({ time:'18:05'.replace('18:05','6:05'), body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:90px 24px 0;text-align:center;', cover('up5',160,200) + d('display:flex;align-items:center;gap:8px;margin-top:6px;', av('khalid',24) + tx('s',C.t2,'Khalid invited you')) + tx('tl',C.t1,'Up by 5') + tx('s',C.t2,'7 days · Out of bed by 5:30 · Self-reported') + tx('b',C.t1, state==='ok'?'5 of 10 people. You start at Day 1; your streak stays yours.':state==='exp'?'This invite expired on Oct 1.':'The room is full: 10 of 10.')),
    sticky: state==='ok' ? btnP('Accept') + d('display:flex;gap:8px;', btnS('Not now',{flex:1}) + btnS('Decline',{flex:1})) : btnS(state==='exp'?'Ask Khalid for a new link':'Find a similar challenge') + btnT('Close'), stickyH: 116 });
  A7.push(F2('invOk', { route:'invite/[code]', comp:'InviteScreen', state:'Accept · Not now · Decline', src:'v45', b75:'pending' }, inviteScreen('ok')));
  A7.push(F2('invExp', { route:'invite/[code]', comp:'InviteScreen', state:'Expired', src:'v45', b75:'not built' }, inviteScreen('exp')));
  A7.push(F2('invFull', { route:'invite/[code]', comp:'InviteScreen', state:'Full (10 of 10)', src:'v45', b75:'pending' }, inviteScreen('full')));
  A7.push(F2('nudgeSend', { route:'challenge/[id]/members', comp:'NudgeSheet', state:'Sender: three fixed lines', src:'v45 180', b75:'pending' }, phone({ time:'5:20', body: stepHead('People','Up by 5 · 5 of 10',{back:true}), overlay: sheet(tx('t',C.t1,'Nudge Abdurrahman') + tx('s',C.t2,'Once a day. He sees your name and the line you pick.') + ['Still time today.','10 minutes left.','I’m done. Your turn.'].map((l,i)=>d(`min-height:52px;border-radius:14px;padding:0 14px;display:flex;align-items:center;background:${i===1?C.t1:C.raised};`, tx('b',i===1?C.ink:C.t1,l))).join('') + btnP('Send nudge')) })));
  A7.push(F2('nudgeGet', { route:'lock screen', comp:'Push · nudge', state:'Recipient', src:'v45 181', b75:'pending' }, phone({ time:'5:21', onPhoto:true, bg:'#101418', full: d('position:absolute;inset:0;background:linear-gradient(180deg,#1B2430,#0F0F0F);') + d('position:absolute;left:0;right:0;top:110px;text-align:center;font-size:84px;line-height:1;font-weight:600;color:'+C.t1+';letter-spacing:-0.02em;', '5:21') + d('position:absolute;left:0;right:0;top:92px;text-align:center;'+T.h+'color:'+C.t1+';', 'Sunday 4 October') +
    d(`position:absolute;left:12px;right:12px;top:420px;border-radius:20px;background:rgba(36,35,34,0.85);padding:12px 14px;display:flex;gap:10px;`, d(`width:38px;height:38px;border-radius:9px;background:${C.ink};display:flex;align-items:center;justify-content:center;flex:none;`, flame(22)) + d('flex:1;', d('display:flex;justify-content:space-between;', tx('h',C.t1,'GRIIT') + tx('c',C.t2,'now')) + tx('b',C.t1,'Yaseen: 10 minutes left.') + tx('s',C.t2,'Up by 5 · Out of bed closes at 5:30 am'))) })));
  A7.push(F2('convert', { route:'challenge/active/[id]', comp:'ConvertToGroupSheet', state:'Solo → group', src:'v45 182', b75:'pending' }, phone({ time:'9:31', body: active({}), overlay: sheet(tx('t',C.t1,'Bring people into Up by 5?') + tx('b',C.t2,'It becomes a private room of up to 10. You stay on Day 5. People you invite start at Day 1 and keep their own streaks.') + btnP('Make it a group') + btnT('Keep it solo')) })));

  // ================= AREA 8 · YOUR PROFILE =================
  CUR = FL2.prof;
  const A8 = [];
  const profTabs = (sel) => d(`display:flex;margin-top:14px;`, [['grid','Proofs'],['flag','Challenges'],['award','Badges']].map(([i,l],k)=>d(`flex:1;height:44px;display:flex;align-items:center;justify-content:center;gap:6px;border-bottom:2px solid ${k===sel?C.t1:'transparent'};`, ic(i,18,k===sel?C.t1:C.t2) + tx('c',k===sel?C.t1:C.t2,l))).join(''));
  const profHead = (o={}) => d('display:flex;align-items:center;justify-content:space-between;height:44px;padding:0 6px 0 16px;', tx('h',C.t1,'@'+(o.handle||'yaseen')) + d('display:flex;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('share',20)) + d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('gear',20)))) +
    d('padding:8px 16px 0;display:flex;flex-direction:column;gap:12px;', d('display:flex;align-items:center;gap:16px;', av(o.who||'yaseen',80) + d('flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:4px;', [[o.streak??'7','Streak'],[o.best??'18','Best'],[o.secured??'23','Days secured']].map(([n,l])=>d('display:flex;flex-direction:column;', sp(NUM+'font-size:24px;line-height:28px;color:'+C.t1+';', n) + tx('c',C.t2,l))).join(''))) +
      d('display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,PPL[o.who||'yaseen'][0]) + (o.bio!==''?tx('b',C.t1,o.bio||'Reading before work. Up before the city.'):'') + tx('s',C.t2,(o.fol||'128 followers · 96 following'))) +
      d('display:flex;gap:8px;', btnS('Edit profile',{flex:1}) + btnS('Find people',{flex:1,icon:'userplus'})));
  const tile = (o) => d(`position:relative;aspect-ratio:4/5;overflow:hidden;background:${o.self?C.surf:C.raised};${o.today?`box-shadow:inset 0 0 0 1.5px ${C.t3};background:transparent;`:''}`,
    (o.ph?img(o.ph):'') + (o.self?d('position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding:8px;gap:2px;', tx('c',C.t1,o.self) + tx('c',C.t2,'Self-reported')):'') + (o.today?d('position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;', ic('plus',18,C.t2) + tx('c',C.t2,'Today')):'') +
    (o.date?d(`position:absolute;left:6px;bottom:5px;${T.c}font-size:11px;color:${C.t1};text-shadow:0 1px 2px rgba(0,0,0,0.6);`, o.date):'') + (o.multi?d('position:absolute;right:6px;top:6px;', ic('copy',14)):'') + (o.lock?d('position:absolute;right:6px;top:6px;width:20px;height:20px;border-radius:999px;background:rgba(15,15,15,0.7);display:flex;align-items:center;justify-content:center;', ic('lock',11)):''));
  const gridTiles = [ {today:true}, {ph:'book1',date:'Oct 4'}, {ph:'book3',date:'Oct 3',lock:true}, {self:'Out of bed',date:'Oct 2'}, {self:'Out of bed',date:'Oct 1'}, {ph:'water1',date:'Sep 29'}, {ph:'pray2',date:'Sep 26',multi:true}, {ph:'pray1',date:'Sep 25'}, {ph:'water2',date:'Sep 24'}, {self:'Drink 3 L',date:'Sep 23'}, {ph:'pray4',date:'Sep 22',lock:true}, {ph:'water3',date:'Sep 21'} ];
  const pgrid = d('display:grid;grid-template-columns:repeat(3,1fr);gap:2px;', gridTiles.map(tile).join(''));
  A8.push(F2('profActive', { route:'(tabs)/profile', comp:'ProfileScreen', state:'Active user · Proofs grid', src:'v46 188 / v43', b75:'pending', fields:'Streak ← current_streak · Best ← best_streak · Days secured ← count(day_secures)' }, phone({ time:'9:00', tab:'profile', body: profHead() + profTabs(0) + d('display:flex;justify-content:space-between;align-items:center;padding:6px 16px;', tx('s',C.t2,'Newest first') + d('display:flex;gap:4px;', d(`width:36px;height:32px;border-radius:999px;background:${C.t1};display:flex;align-items:center;justify-content:center;`, ic('grid',16,C.ink)) + d(`width:36px;height:32px;border-radius:999px;background:${C.surf};display:flex;align-items:center;justify-content:center;`, ic('calendar',16)))) + pgrid })));
  A8.push(F2('profNew', { route:'(tabs)/profile', comp:'ProfileScreen', state:'New user, zero data (Yaseen on Day 0)', src:'v44 170', b75:'pending' }, phone({ time:'9:00', tab:'profile', body: profHead({handle:'yaseen', who:'yaseen', streak:'0', best:'0', secured:'0', bio:'', fol:'0 followers · 0 following'}) + profTabs(0) + d('display:grid;grid-template-columns:repeat(3,1fr);gap:2px;', tile({today:true})) + d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:28px 32px;text-align:center;', tx('h',C.t1,'Your proofs land here') + tx('s',C.t2,'Each day you finish a task, its proof shows in this grid. Private unless you share it.') + d('height:6px') + btnS('Find a challenge',{icon:'compass'})) })));
  const dayBlock = (date, n, items, idx) => { const it = items[idx||0]; return d('display:flex;flex-direction:column;', d('display:flex;justify-content:space-between;align-items:baseline;padding:12px 16px 8px;', tx('h',C.t1,date) + tx('s',C.t2, n===1?'1 proof':n+' proofs')) +
    d('position:relative;width:393px;height:491px;', (it.ph?img(it.ph):d(`position:absolute;inset:0;background:${C.surf};display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;`, doneDot(36) + tx('h',C.t1,it.task) + tx('s',C.t2,'Self-reported'))) + (it.ph?d('position:absolute;left:12px;top:12px;', seal()):'') +
      (items.length>1?d(`position:absolute;right:12px;top:12px;height:26px;padding:0 10px;border-radius:999px;background:rgba(15,15,15,0.62);${T.c}color:${C.t1};display:flex;align-items:center;`, `${(idx||0)+1} of ${items.length}`) + d('position:absolute;left:12px;right:12px;bottom:12px;display:flex;gap:4px;', items.map((x,i)=>d(`flex:1;height:2px;border-radius:1px;background:${i===(idx||0)?C.t1:'rgba(242,240,235,0.35)'};`)).join('')):'')) +
    d('padding:10px 16px 4px;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,it.task) + tx('s',C.t2,it.meta) + d('display:flex;align-items:center;justify-content:space-between;min-height:44px;', d('display:flex;align-items:center;gap:6px;', ic(it.priv?'lock':'users',14,C.t2) + tx('s',C.t2,it.priv?'Private':'Shared to the feed')) + (it.priv?btnT('Share this proof'):btnT('Share')))));
  };
  const sep26 = [{ph:'pray2',task:'Fajr on time',meta:'Fajr 14 · Day 9 of 14 · Camera · 5:41 am'},{ph:'water1',task:'Drink 3 L',meta:'Hydrate 14 · Day 9 of 14 · Camera · 8:10 pm',priv:true}];
  A8.push(F2('dayFeed', { route:'proof/[id] · day feed', comp:'ProofDayFeed', state:'Tapped Oct 3 · vertical feed of days, newest first', src:'v39 112', b75:'not built' }, phone({ time:'9:01', body: stepHead('Proofs','',{}) + dayBlock('Saturday 3 October',1,[{ph:'book3',task:'Read 10 pages',meta:'Read 30 · Day 1 of 30 · Camera · 7:12 am',priv:true}]) + dayBlock('Friday 2 October',1,[{task:'Out of bed',meta:'Up by 5 · Day 3 of 7 · Self-reported · 4:58 am'}]) })));
  A8.push(F2('dayFeed2a', { route:'proof/[id] · day feed', comp:'ProofDayFeed', state:'Two-proof day · 1 of 2', src:'v39 112', b75:'not built' }, phone({ time:'9:02', scroll:120, body: stepHead('Proofs','',{}) + d('height:120px') + dayBlock('Saturday 26 September',2,sep26,0) })));
  A8.push(d('align-self:center;', arrow('Swipe left')));
  A8.push(F2('dayFeed2b', { route:'proof/[id] · day feed', comp:'ProofDayFeed', state:'Two-proof day · 2 of 2 · private, shareable', src:'v39 112', b75:'not built' }, phone({ time:'9:02', scroll:120, body: stepHead('Proofs','',{}) + d('height:120px') + dayBlock('Saturday 26 September',2,sep26,1) })));
  const calCells = (() => { const st = ['pre','pre','pre','sec','sec','sec','sec','sec','held','sec','sec','sec','sec','sec','sec','sec','miss','sec','sec','sec','sec','sec','sec','sec','sec','sec','miss','sec','sec','sec']; return d('display:grid;grid-template-columns:repeat(7,1fr);gap:8px 0;justify-items:center;', 'MTWTFSS'.split('').map(l=>tx('c',C.t2,l)).join('') + d('width:30px') + st.map(s=>dayCircle(s,30)).join('')); })();
  A8.push(F2('profCal', { route:'(tabs)/profile', comp:'ProofsCalendar', state:'Calendar toggle', src:'v41 117', b75:'pending' }, phone({ time:'9:03', tab:'profile', scroll:250, body: profHead() + profTabs(0) + d('display:flex;justify-content:space-between;align-items:center;padding:6px 16px;', tx('h',C.t1,'September') + d('display:flex;gap:4px;', d(`width:36px;height:32px;border-radius:999px;background:${C.surf};display:flex;align-items:center;justify-content:center;`, ic('grid',16)) + d(`width:36px;height:32px;border-radius:999px;background:${C.t1};display:flex;align-items:center;justify-content:center;`, ic('calendar',16,C.ink)))) + d('padding:6px 16px;', calCells) + d('padding:8px 16px;', tx('s',C.t2,'Tap a day to open it in the day feed.')) })));
  const chItem = (k, line, week, o={}) => d(`display:flex;flex-direction:column;gap:10px;background:${C.surf};border-radius:16px;padding:12px 14px;`, d('display:flex;align-items:center;gap:12px;', cover(k,40,50,{r:8}) + d('flex:1;', tx('h',C.t1,CH[k][0]) + tx('s',C.t2,line)) + ic('cr',18,C.t2)) + d('display:flex;gap:4px;', week.map(s=>dayCircle(s,20,C.surf)).join('')));
  A8.push(F2('profCh', { route:'(tabs)/profile', comp:'ProfileChallenges', state:'Running, finished, ended', src:'v42 118', b75:'pending' }, phone({ time:'9:04', tab:'profile', scroll:250, body: profHead() + profTabs(1) + d('padding:12px 16px;display:flex;flex-direction:column;gap:8px;', tx('l',C.t2,'Running') + chItem('read','Day 2 of 30',['sec','today']) + chItem('up5','Day 5 of 7',['sec','sec','sec','sec','today','fut','fut']) + tx('l',C.t2,'Finished','padding-top:8px;') + chItem('fajr14','14 of 14 days secured',Array(14).fill('sec').map((s,i)=>i===8?'held':s)) + tx('l',C.t2,'Ended','padding-top:8px;') + chItem('hyd14','Left on day 6',['sec','sec','miss','sec','sec','sec'])) })));
  const badges = [['First proof',1],['7-day streak',1],['14-day streak',1],['First finish',1],['10 days secured',1],['30 days secured',0],['30-day streak',0],['100 days secured',0],['5 shared proofs',0],['First group',0],['Early riser',0],['75-day finish',0]];
  const badge = (n, on) => d('display:flex;flex-direction:column;align-items:center;gap:6px;text-align:center;', d(`width:64px;height:64px;border-radius:999px;display:flex;align-items:center;justify-content:center;${on?`background:${C.raised};box-shadow:inset 0 0 0 2px ${C.t1};`:`box-shadow:inset 0 0 0 1.5px ${C.t3};`}`, on?ic('award',26,C.t1):ic('lock',20,C.t2)) + tx('c',on?C.t1:C.t2,n));
  A8.push(F2('profBadges', { route:'(tabs)/profile', comp:'Badges', state:'Earned, locked, next badge (this tab only)', src:'v42 Badges', b75:'pending', fields:'each badge ← one server fact (badges.rule_key)' }, phone({ time:'9:05', tab:'profile', scroll:250, body: profHead() + profTabs(2) + d('padding:12px 16px;display:flex;flex-direction:column;gap:14px;', d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:flex;align-items:center;gap:12px;`, badge('',0).replace(/<div style="font-size:12px[^]*?<\/div>/,'') + d('flex:1;', tx('l',C.t2,'Next') + tx('h',C.t1,'30 days secured') + tx('s',C.t2,'23 of 30. 7 to go.'))) + tx('s',C.t2,'5 of 12 earned') + d('display:grid;grid-template-columns:repeat(3,1fr);gap:16px 8px;', badges.map(([n,o])=>badge(n,o)).join(''))) })));
  A8.push(F2('badgeSheet', { route:'(tabs)/profile', comp:'BadgeDetailSheet', state:'Earned badge', src:'v42', b75:'pending' }, phone({ time:'9:05', tab:'profile', body: profHead() + profTabs(2), overlay: sheet(d('display:flex;flex-direction:column;align-items:center;gap:8px;text-align:center;', d(`width:88px;height:88px;border-radius:999px;background:${C.raised};box-shadow:inset 0 0 0 2px ${C.t1};display:flex;align-items:center;justify-content:center;`, ic('award',36)) + tx('t',C.t1,'14-day streak') + tx('b',C.t2,'Earned Sep 18 for securing 14 days in a row. Your best is 18.')) + btnS('Share badge',{icon:'share'}) + btnT('Close')) })));
  const proofView = (o) => phone({ time:'9:06', body: stepHead(o.title||'Proof','',{back:true, right: o.own?ic('more',20):''}) + d('position:relative;width:393px;height:491px;', (o.broken?brokenTile('Read 10 pages').replace('Photo didn’t load', o.brokenText||'Photo didn’t load'):img(o.ph||'book1')) + (o.broken?'':d('position:absolute;left:12px;top:12px;', seal())) + (o.priv?d(`position:absolute;right:12px;top:12px;height:26px;padding:0 10px;border-radius:999px;background:rgba(15,15,15,0.62);display:flex;align-items:center;gap:5px;${T.c}color:${C.t1};`, ic('lock',12) + 'Private'):'')) +
    d('padding:12px 16px;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,'Read 10 pages') + tx('s',C.t2,o.meta||'Read 30 · Day 2 of 30 · Camera · 7:43 am') + (o.cap?tx('b',C.t1,o.cap,'padding-top:6px;'):'') + (o.own&&!o.priv?d('display:flex;align-items:center;gap:6px;padding-top:8px;', ic('users',14,C.t2) + tx('s',C.t2,'Shared to the feed · 3 respects')):'')), sticky:o.sticky, stickyH:o.sh||72 });
  A8.push(F2('proofOwnShared', { route:'proof/[id]', comp:'ProofViewer', state:'Own · shared', src:'v39 112', b75:'pending' }, proofView({ own:true, cap:'Chapter 4 done.', sticky: btnS('Share to Instagram',{icon:'ig'}), sh:68 })));
  A8.push(F2('proofOwnPriv', { route:'proof/[id]', comp:'ProofViewer', state:'Own · private · Share this proof', src:'v39 112', b75:'differs · build 75 has no share action' }, proofView({ own:true, priv:true, ph:'book3', meta:'Read 30 · Day 1 of 30 · Camera · 7:12 am', sticky: btnP('Share this proof',{icon:'share'}) })));
  A8.push(F2('proofVisitor', { route:'proof/[id]', comp:'ProofViewer', state:'Visitor (Khalid viewing Yaseen) · shared only', src:'v39 112', b75:'pending' }, proofView({ title:'Yaseen', cap:'Chapter 4 done.', sticky: d('display:flex;gap:8px;', btnS('Respect',{flex:1,icon:'heart'}) + btnS('Comment',{flex:1,icon:'msg'})), sh:68 })));
  A8.push(F2('proofLost', { route:'proof/[id]', comp:'ProofViewer', state:'Photo not saved', src:'v39 112', b75:'pending' }, proofView({ own:true, broken:true, brokenText:'The photo didn’t upload. The task still counts.', meta:'Read 30 · Day 2 of 30 · counted as self-reported' })));
  A8.push(F2('profDay', { route:'profile/day', comp:'DayDetail', state:'Oct 3: one proof, one self-reported', src:'v28', b75:'pending' }, phone({ time:'9:07', body: stepHead('Saturday 3 October','Secured',{back:true}) + d('padding:8px 16px;display:flex;flex-direction:column;gap:8px;', d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Read 10 pages', gate:[[null,'Read 30 · Day 1 of 30'],G.cam], st:'done', right: d('width:40px;height:50px;border-radius:8px;overflow:hidden;', img('book3'))}) + taskRow({name:'Out of bed', gate:[[null,'Up by 5 · Day 4 of 7'],G.self], st:'done'})) + tx('s',C.t2,'Every required task was done, so the day is secured.')) })));
  const recRow = (date, s, label) => d('display:flex;align-items:center;gap:12px;min-height:48px;', dayCircle(s,30) + tx('b',C.t1,date,'flex:1;') + tx('s',C.t2,label));
  A8.push(F2('consist', { route:'profile/consistency', comp:'ConsistencyScreen', state:'Record with held and open', src:'v36 91', b75:'pending', fields:'23 ← days secured · 26 ← due days closed since first join' }, phone({ time:'9:08', body: stepHead('Record','',{back:true}) + d('padding:8px 16px;display:flex;flex-direction:column;gap:4px;', d('display:flex;align-items:baseline;gap:8px;', sp(NUM+'font-size:40px;color:'+C.t1+';','23 of 26') + tx('s',C.t2,'due days secured')) + tx('s',C.t2,'A due day is one where any challenge you’re in had a required task.','padding-bottom:10px;') + recRow('Today, Sun 4 Oct','today','Open') + recRow('Sat 3 Oct','sec','Secured · 1 photo') + recRow('Fri 2 Oct','sec','Secured · self-reported') + recRow('Sun 13 Sep','held','Held by a freeze') + recRow('Tue 8 Sep','miss','Missed · Drink 3 L') + recRow('Wed 2 Sep','miss','Missed · Fajr on time')) })));
  const field = (l, v, o={}) => d('display:flex;flex-direction:column;gap:4px;', tx('c',C.t2,l) + d(`min-height:48px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;gap:8px;${o.focus?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:''}`, tx('b',C.t1,v,'flex:1;') + (o.right||'')) + (o.note?tx('c',o.err?C.t1:C.t2,o.note):''));
  const editBody = (uname, note, err, right) => stepHead('Edit profile','',{}) + d('padding:8px 16px;display:flex;flex-direction:column;gap:14px;', d('display:flex;flex-direction:column;align-items:center;gap:8px;', av('yaseen',88) + btnT('Change photo')) + field('Name','Yaseen Abdelaziz') + field('Username','@'+uname,{focus:true, note, err, right}) + field('Bio','Reading before work. Up before the city.',{note:'38 / 150'}));
  A8.push(F2('editOk', { route:'edit-profile', comp:'EditProfile', state:'Username available', src:'v28 64', b75:'pending' }, phone({ time:'9:09', body: editBody('yaseen.m','Available.',false, ic('check',16,C.t1,{sw:3})), sticky: btnP('Save'), stickyH:72 })));
  A8.push(F2('editTaken', { route:'edit-profile', comp:'EditProfile', state:'Username taken · Save disabled', src:'v28 64', b75:'pending' }, phone({ time:'9:09', body: editBody('yaseen','@yaseen is taken. Try yaseen.m or yaseen5.',true, ic('alert',16)), sticky: btnP('Save',{off:true}), stickyH:72 })));
  A8.push(F2('editSaving', { route:'edit-profile', comp:'EditProfile', state:'Saving, then error', src:'new', b75:'pending' }, phone({ time:'9:10', body: editBody('yaseen.m','Available.',false, ic('check',16,C.t1,{sw:3})), toast: d(`position:absolute;left:16px;right:16px;top:70px;z-index:16;background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, ic('alert',18) + tx('s',C.t1,'Didn’t save. Your changes are still here.','flex:1;')), sticky: btnP('Try again',{icon:'retry'}), stickyH:72 })));
  const folBody = (sel, rows) => stepHead('@yaseen','',{back:true}) + d('padding:0 16px;', seg(['Followers 128','Following 96'], sel).replace('display:inline-flex;','display:flex;') ) + d('padding:8px 16px;', rows);
  A8.push(F2('folList', { route:'follow-list', comp:'FollowList', state:'Followers, with mutual', src:'v43', b75:'pending' }, phone({ time:'9:11', body: folBody(0, person('khalid','Mutual', smallBtn('Following')) + person('omar','Mutual', smallBtn('Following')) + person('abd','Follows you', smallBtn('Follow back',true)) + person('bilal','Mutual', smallBtn('Following')) + person('hamza','Follows you', smallBtn('Follow back',true))) })));
  A8.push(F2('folEmpty', { route:'follow-list', comp:'FollowList', state:'Empty (Yaseen on Day 0, following)', src:'v43', b75:'pending' }, phone({ time:'9:11', body: folBody(1, d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:120px 24px;text-align:center;', tx('h',C.t1,'You don’t follow anyone yet') + tx('s',C.t2,'Follow people from your challenges to see their proofs on Home.') + d('height:6px') + btnS('Find people',{icon:'userplus'}))).replace('Followers 128','Followers 0').replace('Following 96','Following 0') })));
  A8.push(F2('shareProfile', { route:'(tabs)/profile', comp:'ShareProfileSheet', state:'Link and card', src:'new', b75:'pending' }, phone({ time:'9:12', tab:'profile', body: profHead() + profTabs(0) + pgrid, overlay: sheet(tx('t',C.t1,'Share your profile') + d(`background:${C.raised};border-radius:16px;padding:16px;display:flex;align-items:center;gap:14px;`, av('yaseen',56) + d('flex:1;', tx('h',C.t1,'Yaseen Abdelaziz') + tx('s',C.t2,'@yaseen · 7-day streak'))) + d(`display:flex;align-items:center;gap:10px;min-height:52px;background:${C.raised};border-radius:14px;padding:0 6px 0 14px;`, ic('link',18) + tx('b',C.t1,'{INVITE_BASE}/i/YSN7M2','flex:1;') + smallBtn('Copy')) + tx('s',C.t2,'Strangers see only proofs you shared.') + btnS('Share to Instagram',{icon:'ig'})) })));

  // ================= FLOWS 5–8, 11 =================
  CUR = FL2.hub;
  const homeAfterJoin = F2('fJoinHome', { route:'(tabs)/index', comp:'HomeScreen', state:'After joining Show Up 7 (today)', src:'new', b75:'pending' }, phone({ time:'12:24', tab:'home', body: home({ streak:7, week:W_B, prog:0.3, line:'2 of 3 left today.', primary:pReadBtn, sections:[secRead('open'), secBed('done'), { name:'Show Up 7', day:'Day 1 of 7', done:0, total:1, tasks:[{name:'Gym check-in', gate:[G.loc], st:'open'}] }], feed:'' }), toast: toast({ title:'You joined Show Up 7', sub:'Day 1 is today. Check in at your gym.', share:false }) }));
  const cStep = (step, title, body, btn) => phone({ time:'8:30', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 6px 0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,`Step ${step} of 3`) + d('width:60px')) + d(`margin:0 16px;height:3px;border-radius:2px;background:${C.raised};`, d(`width:${step*33.3}%;height:100%;background:${C.t1};border-radius:2px;`)) + d('padding:16px 16px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,title) + body), sticky: btnP(btn), stickyH:72 });
  const packs = [['No Days Off','5 tasks · Workout, water, reading, journal, photo'],['Athlete','3 tasks · Training, steps, sleep'],['Faith','3 tasks · Fajr, Quran, dhikr'],['Morning routine','3 tasks · Up by 6, cold shower, plan'],['Entrepreneur','3 tasks · Deep work, read, outreach']];
  const showTask = taskRow({name:'Gym check-in', gate:[G.loc], st:'open', right:''});
  const fShowPrev = F2('fShowPrev', { route:'(tabs)/discover', comp:'ChallengePreviewSheet', state:'Show Up 7 preview', src:'v44 168', b75:'pending' }, phone({ time:'12:14', tab:'discover', body: rootHead('Discover') + searchBar() + chips(catList,0) + sectionH('Featured') + featured, overlay: sheet(d('display:flex;gap:14px;align-items:center;', cover('show',96,120) + d('flex:1;', tx('t',C.t1,'Show Up 7') + tx('s',C.t2,'7 days · Fitness · 96 people'))) + tx('b',C.t1,'Check in at your gym every day for 7 days.') + d(`background:${C.raised};border-radius:14px;padding:4px 12px;`, showTask) + tx('s',C.t2,'Standard: a freeze can cover a missed day.') + btnP('Join Show Up 7') + btnT('See full details')) }));
  const fShowDetail = F2('fShowDetail', { route:'challenge/[id]', comp:'ChallengeDetail', state:'Show Up 7, not joined', src:'v29', b75:'pending' }, phone({ time:'12:15', body: detail('show',{facts:'7 days · Fitness · Solo · 96 people', tasks: showTask, rule:'Standard. A freeze can cover a missed day. You set your gym after joining.', people2:true}), sticky: btnP('Join Show Up 7') + tx('c',C.t2,'Day 1 is today. Next you set your gym.','text-align:center;'), stickyH:96 }));
  const fShowConfirm = F2('fShowConfirm', { route:'challenge/[id]', comp:'JoinConfirmSheet', state:'Show Up 7 confirm', src:'v44', b75:'pending' }, phone({ time:'12:16', body: detail('show',{facts:'7 days · Fitness · Solo · 96 people', tasks: showTask}), overlay: sheet(tx('t',C.t1,'Join Show Up 7?') + d(`background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;flex-direction:column;gap:4px;`, tx('h',C.t1,'Day 1 is today') + tx('s',C.t2,'Check in at your gym before midnight.')) + tx('s',C.t2,'Next: set your gym. Check-ins count within the distance you choose.') + btnP('Join and set my gym') + btnT('Cancel')) }));
  const fPack = F2('fPack', { route:'create/index', comp:'StepTasks', state:'Starter pack selected (Morning routine)', src:'v44 169', b75:'pending' }, cStep(2,'What do you do each day?', tx('s',C.t2,'Start from a pack or build your own.') + packs.map(([a,b],i)=>d(`border-radius:14px;padding:12px 14px;background:${i===3?C.t1:C.surf};display:flex;flex-direction:column;gap:2px;`, tx('h',i===3?C.ink:C.t1,a) + tx('s',i===3?'#3A3836':C.t2,b))).join('') + btnS('Build my own',{icon:'plus'}), 'Continue'));
  const fRules = F2('fRules', { route:'create/index', comp:'StepRules', state:'Standard / Strict, visibility', src:'v44 169', b75:'pending' }, cStep(3,'Rules', tx('h',C.t1,'When a day is missed') + d('display:flex;gap:8px;', chip('Standard',true) + chip('Strict',false)) + tx('s',C.t2,'Standard: a freeze can cover a missed day. Strict: a miss resets the streak in this challenge to 0.') + tx('h',C.t1,'Who can join','padding-top:8px;') + d('display:flex;gap:8px;', chip('Anyone',false) + chip('Invite only',true)) + tx('s',C.t2,'Invite only: a private room of up to 10. It never shows on Discover.'), 'Review'));
  const fReview = F2('fReview', { route:'create/index', comp:'StepReview', state:'Review', src:'v44 169', b75:'pending' }, phone({ time:'8:31', body: stepHead('Review','',{back:true}) + d('padding:8px 16px;display:flex;flex-direction:column;gap:10px;', d('display:flex;gap:14px;align-items:center;', cover('morning',72,90) + d('flex:1;', tx('t',C.t1,'Morning routine') + tx('s',C.t2,'21 days · Discipline · Invite only · Standard'))) + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Up by 6', gate:[G.self,['clock','By 6:00 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''}) + taskRow({name:'Plan the day', gate:[[null,'Text · 20 words'],G.self], st:'open', right:''})) + tx('s',C.t2,'Day 1 is tomorrow: “By 6:00 am” has passed today.')), sticky: btnP('Launch'), stickyH:72 }));
  const fLaunched = F2('fLaunched', { route:'create/index', comp:'LaunchedScreen', state:'Group launch with invite link', src:'v44 169', b75:'pending' }, phone({ time:'8:32', body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:110px 24px 0;text-align:center;', cover('morning',140,175) + tx('tl',C.t1,'Morning routine is live') + tx('b',C.t2,'Day 1 is tomorrow. Invite up to 9 people.') + d(`width:100%;display:flex;align-items:center;gap:10px;min-height:52px;background:${C.surf};border-radius:14px;padding:0 6px 0 14px;margin-top:8px;`, ic('link',18) + tx('b',C.t1,'{INVITE_BASE}/i/MRN4F2A','flex:1;text-align:left;') + smallBtn('Copy'))), sticky: btnP('Invite people') + btnT('Go to Home'), stickyH:116 }));
  const fHomeLaunch = F2('fHomeLaunch', { route:'(tabs)/index', comp:'HomeScreen', state:'After launch: starts tomorrow', src:'new', b75:'pending' }, phone({ time:'8:33', tab:'home', body: home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today. Morning routine starts tomorrow.', primary:pReadBtn, sections:[secRead('open'), secBed('done'), { name:'Morning routine', day:'Day 1 is tomorrow', done:0, total:3, collapsed:true, tasks:[] }], feed:'' }) }));
  const fPaywall = F2('fPaywall', { route:'paywall', comp:'Paywall', state:'Arriving from the free limit · prices from RevenueCat', src:'new (batch 3 owns paywall)', b75:'pending', fields:'price ← offerings.current.annual.product.priceString · trial ← introPrice · monthly equiv ← pricePerMonthString' }, phone({ time:'12:31', body: stepHead('','',{}) + d('padding:0 16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'GRIIT Pro') + tx('b',C.t2,'Run more than 3 challenges. 4 freezes every 30 days instead of 1.') + [['Annual','$29.99 a year','$2.50 a month · 7-day free trial',true],['Monthly','$4.99 a month','',false]].map(([a,b,c,on])=>d(`border-radius:16px;padding:14px;background:${on?C.t1:C.surf};display:flex;flex-direction:column;gap:2px;`, tx('h',on?C.ink:C.t1,a) + tx('t',on?C.ink:C.t1,b) + (c?tx('s',on?'#3A3836':C.t2,c):''))).join('') + tx('s',C.t2,'Free for 7 days, then $29.99 a year. Cancel in Settings at least a day before it renews.') + d(`display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:10px;box-shadow:inset 0 0 0 1px ${C.raised};`, ic('alert',14,C.t2) + tx('c',C.t2,'Spec: every price and the trial come from RevenueCat offerings (store price, user’s currency). USD shown as example; nothing hard-coded.'))), sticky: btnP('Start free trial') + d('display:flex;justify-content:center;gap:16px;', btnT('Restore') + btnT('Terms') + btnT('Privacy')), stickyH:116 }));
  const fHomeLeft = F2('fHomeLeft', { route:'(tabs)/index', comp:'HomeScreen', state:'Yaseen after leaving Hydrate 30 to join Fajr 30', src:'new', b75:'pending' }, phone({ time:'12:33', tab:'home', body: home({ streak:7, week:W_B, prog:0.3, line:'2 of 3 left today. Fajr 30 starts tomorrow.', primary:pReadBtn, sections:[secRead('open'), secBed('done'), {name:'Hydrate 30', day:'Day 9 of 30 · leaving at midnight', done:0, total:1, tasks:[{name:'Drink 3 L', gate:[[null,'12 cups'],G.self], st:'open'}]}], feed:'' }), toast: toast({ title:'Fajr 30 starts tomorrow', sub:'Hydrate 30 ends at midnight, freeing the slot.', share:false }) }));
  const P = (k) => frameWrap(k, 0.62);
  const fa = (l) => d(`width:64px;flex:none;align-self:center;display:flex;flex-direction:column;align-items:center;gap:4px;`, ic('arrow',20,C.t1) + d(`${T.c}color:${C.t1};text-align:center;`, l));
  const flow = (id, title, note, steps) => `<div id="${id}" data-screen-label="${title}" style="display:flex;flex-direction:column;gap:14px;">` + stripHead(title, note) + d('display:flex;gap:10px;align-items:flex-start;', steps.join('')) + '</div>';
  const flowsB2 = [
    flow('flow5','Flow 5 · Joining','Discover to a joined challenge on Home.', [P('discAll'), fa('Show Up 7 cover'), P('fShowPrev'), fa('See full details'), P('fShowDetail'), fa('Join Show Up 7'), P('fShowConfirm'), fa('Join and set my gym'), P('gym'), fa('Save gym'), P('fJoinHome')]),
    flow('flow6','Flow 6 · Creating from a starter pack','Create, pick a pack, set rules, launch, back to Home.', [P('fPack'), fa('Continue'), P('fRules'), fa('Review'), P('fReview'), fa('Launch'), P('fLaunched'), fa('Go to Home'), P('fHomeLaunch')]),
    flow('flow7','Flow 7 · The free limit','Yaseen joins a fourth challenge.', [P('chLimit'), fa('Leave one or go Pro'), frameWrap('limit',0.62), fa('Leave Hydrate 30'), P('fHomeLeft'), fa('or See Pro'), P('fPaywall')]),
    flow('flow8','Flow 8 · Leaving a challenge','Takes effect at midnight; today still counts it.', [P('actSolo'), fa('Overflow'), P('actMenu'), fa('Leave'), frameWrap('leave',0.62), fa('Leave at midnight'), frameWrap('hK',0.62)]),
    flow('flow11','Flow 11 · Profile history','Grid to day feed, swipe a two-photo day, share a private proof.', [P('profActive'), fa('Tap Oct 3'), P('dayFeed'), fa('Scroll to Sep 26'), P('dayFeed2a'), fa('Swipe left'), P('dayFeed2b'), fa('Share this proof'), frameWrap('ssPhoto',0.62)]) ];

  // ================= hub B2 =================
  const L = (k) => REG[k] ? `<a href="${href(k)}" style="color:${C.t1};text-decoration:underline;">${REG[k].n}</a>` : k;
  const nav = d('display:flex;flex-wrap:wrap;gap:8px;', [[FL2.hub,'Batch 2 overview'],[FL2.feed,'Area 5 Feed'],[FL2.disc,'Area 6 Discover'],[FL2.ch,'Area 7 Challenge'],[FL2.prof,'Area 8 Profile'],[FL2.flows,'Flows 5–8, 11'],[FL.hub,'Batch 1R overview']].map(([h,l])=>`<a href="${encodeURI(h)}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">${l}</a>`).join(''));
  const intro2 = d('display:flex;flex-direction:column;gap:14px;max-width:1100px;', tx('l',C.t2,'GRIIT v48 · Atlas · Batch 2 of 4') + d(T.tl+'font-size:40px;line-height:46px;color:'+C.t1+';', 'Feed, Discover, Challenge, Profile') + tx('b',C.t2,'Areas 5–8 and flows 5–8 and 11. Same system, same seeded people, same check strip. Home, Profile and Feed freeze when this batch is approved.') + nav);
  const changes2 = `<div id="changes2" style="display:flex;gap:24px;flex-wrap:wrap;align-items:flex-start;">` + panel(640, tx('l',C.t2,'What changed and why') + [
    ['Profile like Instagram','Grid of 4:5 tiles (Today first, self-reported tiles honest) → a vertical feed of days, newest first. A two-proof day swipes with “1 of 2”. Every proof names challenge, task, gate and Shared or Private; private ones offer “Share this proof”.'],
    ['Feed and posts','Full-bleed cards, double-tap respect, counts hidden at 0, the camera seal explained in a sheet, comments in a sheet with posting, failed and delete states. Report (not built) is a reason picker and a confirmation.'],
    ['Discover','Covers only from the generator; six categories now separate by colour alone (tints raised in chroma). Search covers challenges and people. Sparse, loading, error and no-results states.'],
    ['Challenge you’re in','Day hero, “days done · secured”, the same freeze row as Home, This week board (only in groups), recent proofs, record, invite. Leave takes effect at midnight.'],
    ['Groups','Roster with today’s state per person and the group streak defined. Invite picker with a link. Invite accept, expired, full. Nudge from three fixed lines, and what the recipient sees.'],
    ['Decisions applied','Strictness is “Strict”. Leaving takes effect tomorrow. Photos are varied real-looking proofs.'] ].map(([a,b])=>d('display:grid;grid-template-columns:150px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) +
    panel(420, tx('l',C.t2,'Self-score') + d('display:flex;align-items:baseline;gap:8px;', sp(NUM+'font-size:56px;line-height:60px;color:'+C.t1+';','8.6') + tx('t',C.t2,'/ 10')) + tx('s',C.t2,'Short of 9: build 75 screenshots still aren’t in the project, so “Built in 75” reads pending / not built / differs-by-description. Set your gym has no map: the brief asks for one, but GRIIT stores a point and a radius and has no map component (flag 200).','text-wrap:pretty;')) + '</div>';
  const CON2 = [
    ['199 Cover tints','Decided: raised tints accepted; tokens.v46 categoryTint updated.'],
    ['200 Set your gym map','Decided: no map. Search plus radius.'],
    ['201 Board in solo','A solo challenge shows “A board needs two” instead of a board, per v46 190.'],
    ['202 Group streak after a miss','Decided: a member’s freeze holds the group streak for that day. Roster copy updated.'],
    ['203 Creator leaving','Decided: ownership passes automatically to the longest-standing member. No picker.'],
    ['204 Delete post','Decided: Delete removes the post from the feed only. The proof stays private in the record; the day stays secured. “Make private” merged into it.'],
    ['205 Week count on detail','The challenge board counts “secured days since Monday”, the StreakSheet definition. No second count on the screen.'],
    ['194 Offline posting','Still flagged for engineering.'] ];
  const contra2 = `<div id="contra2" data-screen-label="Contradictions B2" style="display:flex;flex-direction:column;gap:12px;">` + stripHead('Contradictions and flags, batch 2') + panel(1100, CON2.map(([a,b])=>d('display:grid;grid-template-columns:260px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) + '</div>';
  const idx2 = `<div id="index2" data-screen-label="Index B2" style="display:flex;flex-direction:column;gap:12px;">` + stripHead(`Atlas index, batch 2 (${B2.length} frames)`,'Frame · route · component · state · source · built in 75.') + panel(1300, `<div style="display:grid;grid-template-columns:60px 190px 220px 1fr 140px 220px;max-width:1260px;">` + [['#','Route','Component','State','Source','Built in 75']].concat(B2.map(k=>{const f=REG[k]; return [`<a href="${href(k)}" style="color:${C.t1};">${f.n}</a>`, f.route, f.comp, f.state, f.src||'new', f.b75||'pending'];})).map((r,ri)=>r.map((c,i)=>d(`${ri===0?T.c+'color:'+C.t2+';':(i===0?T.h:T.s)+'color:'+C.t1+';'}padding:10px 12px 10px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>') + '</div>';
  const flowFrames = d('display:flex;flex-direction:column;gap:22px;', stripHead('Frames drawn for the flows','Create and Paywall are batch 3; these are the minimum the flows need.') + wrapRow([fShowPrev, fShowDetail, fShowConfirm, homeAfterJoin, fPack, fRules, fReview, fLaunched, fHomeLaunch, fPaywall, fHomeLeft]));
  const sec = (id, eyebrow, title, purpose, note, body) => `<div style="display:flex;flex-direction:column;gap:22px;">` + areaHead(id, eyebrow, title, purpose, note) + body + '</div>';
  const wrapDoc = (parts) => `<div style="filter:{{ filt }};font-family:${FONT};color:${C.t1};padding:48px;display:flex;flex-direction:column;gap:80px;background:${C.ink};">` + parts.join('\n') + '</div>';
  return {
    [FL2.hub]: wrapDoc([intro2, changes2, contra2, flowFrames, idx2]),
    [FL2.feed]: wrapDoc([intro2, sec('a5','Area 5 · Feed and posts','Feed and posts','A post is for seeing what someone did. Within 3 seconds: who, which task, and whether a camera saw it.','Cards are the batch 1R family. Counts hide at 0. Double-tap respects; the heart toggles.', wrapRow(A5))]),
    [FL2.disc]: wrapDoc([intro2, sec('a6','Area 6 · Discover and joining','Discover and joining','Discover is for finding the next challenge. Within 3 seconds: what it is, how long, and what counts as proof.','Covers come only from the generator. Joining always states when Day 1 is.', wrapRow(A6))]),
    [FL2.ch]: wrapDoc([intro2, sec('a7','Area 7 · A challenge you’re in','A challenge you’re in','This screen is for one challenge. Within 3 seconds: which day, what’s left today, and how the week went.','16pt gutter on every block. The freeze row is the Home string.', wrapRow(A7))]),
    [FL2.prof]: wrapDoc([intro2, sec('a8','Area 8 · Your profile','Your profile','Profile is your record. Within 3 seconds: streak, best, days secured, and your proofs.','Grid → day feed → carousel. Handle in the nav bar. Next badge only on the Badges tab.', wrapRow(A8))]),
    [FL2.flows]: wrapDoc([intro2, d('display:flex;flex-direction:column;gap:48px;', flowsB2.join(''))]),
  };
}
