-- DRAFT. DO NOT APPLY.
-- v44 featured catalog. Generated by lib/featured-catalog-seed.ts.
-- Task rows go through payloadFromDraft → mapWizardTaskToCreateInput → buildTaskInsertPayload,
-- the same path challenges.create uses for a standard solo challenge.
-- Catalog overrides vs that path: fixed id, creator_id NULL, is_featured true, participants_count 0.
-- difficulty is medium because create writes medium for Standard (not easy).
-- require_same_rules and show_replay_label are false because the wizard sends those for Standard.
-- location_* columns are NULL. The builder does not write them; these eight tasks have no place.
-- Preview first. The INSERTs are the seed an operator would run later.

SELECT id, title, duration_days, category, status, visibility, creator_id, is_featured, participants_count
FROM public.challenges
WHERE id IN (
  'e44f0001-4000-4000-8000-000000000001',
  'e44f0001-4000-4000-8000-000000000002',
  'e44f0001-4000-4000-8000-000000000003',
  'e44f0001-4000-4000-8000-000000000004',
  'e44f0001-4000-4000-8000-000000000005',
  'e44f0001-4000-4000-8000-000000000006',
  'e44f0001-4000-4000-8000-000000000007',
  'e44f0001-4000-4000-8000-000000000008'
);

INSERT INTO public.challenges (
  id, creator_id, title, description, duration_days, duration_type,
  visibility, difficulty, category, status, is_featured, participants_count,
  participation_type, team_size, run_status, is_hard_mode,
  live_date, replay_policy, require_same_rules, show_replay_label
) VALUES
  ('e44f0001-4000-4000-8000-000000000001', NULL, 'Show Up 7', '', 7, 'multi_day', 'PUBLIC', 'medium', 'fitness', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000002', NULL, '7K Steps', '', 7, 'multi_day', 'PUBLIC', 'medium', 'health', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000003', NULL, 'Early Riser 7', '', 7, 'multi_day', 'PUBLIC', 'medium', 'discipline', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000004', NULL, 'Fajr Before Sunrise', '', 7, 'multi_day', 'PUBLIC', 'medium', 'faith', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000005', NULL, '3 Good Things', '', 7, 'multi_day', 'PUBLIC', 'medium', 'mind', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000006', NULL, '10 Pages a Day', '', 14, 'multi_day', 'PUBLIC', 'medium', 'learning', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000007', NULL, 'Quran Daily', '', 30, 'multi_day', 'PUBLIC', 'medium', 'faith', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false),
  ('e44f0001-4000-4000-8000-000000000008', NULL, '30-Second Cold Finish', '', 14, 'multi_day', 'PUBLIC', 'medium', 'discipline', 'published', true, 0, 'solo', 1, NULL, false, NULL, 'allow_replay', false, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.challenge_tasks (
  challenge_id, title, task_type, order_index, require_photo, config,
  target_mode, start_value, start_duration_minutes, routine_anchor, routine_anchor_custom,
  require_location, location_name, location_latitude, location_longitude, location_radius_meters,
  gate_time_mode, gate_time_start, gate_time_end
)
SELECT v.challenge_id, v.title, v.task_type, v.order_index, v.require_photo, v.config,
  v.target_mode, v.start_value, v.start_duration_minutes, v.routine_anchor, v.routine_anchor_custom,
  v.require_location, v.location_name, v.location_latitude, v.location_longitude, v.location_radius_meters,
  v.gate_time_mode, v.gate_time_start, v.gate_time_end
FROM (VALUES
  ('e44f0001-4000-4000-8000-000000000001'::uuid, 'Get to the gym', 'check_off', 0, true, '{"required":true,"photo_mode":"required","require_photo_proof":true,"photo_required":true,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('e44f0001-4000-4000-8000-000000000002'::uuid, 'Walk 7,000 steps', 'check_off', 0, false, '{"required":true,"photo_mode":"none","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('e44f0001-4000-4000-8000-000000000003'::uuid, 'Up and out of bed', 'check_off', 0, true, '{"required":true,"photo_mode":"required","require_photo_proof":true,"photo_required":true,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'by', '06:30', NULL),
  ('e44f0001-4000-4000-8000-000000000004'::uuid, 'Pray Fajr', 'check_off', 0, false, '{"required":true,"photo_mode":"optional","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, 'by', '07:00', NULL),
  ('e44f0001-4000-4000-8000-000000000005'::uuid, 'Write 3 good things from today', 'text', 0, false, '{"required":true,"min_words":0,"photo_mode":"none","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('e44f0001-4000-4000-8000-000000000006'::uuid, 'Read 10 pages', 'counter', 0, false, '{"required":true,"target_count":10,"unit_label":"pages","photo_mode":"none","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false,"unit":"pages"}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('e44f0001-4000-4000-8000-000000000007'::uuid, 'Read at least 1 page of Quran', 'check_off', 0, false, '{"required":true,"photo_mode":"none","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('e44f0001-4000-4000-8000-000000000008'::uuid, 'End your shower with 30 seconds cold', 'check_off', 0, false, '{"required":true,"photo_mode":"none","require_photo_proof":false,"photo_required":false,"hard_mode":false,"require_camera_only":false,"require_strava":false}'::jsonb, 'fixed', NULL, NULL, NULL, NULL, false, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
) AS v(
  challenge_id, title, task_type, order_index, require_photo, config,
  target_mode, start_value, start_duration_minutes, routine_anchor, routine_anchor_custom,
  require_location, location_name, location_latitude, location_longitude, location_radius_meters,
  gate_time_mode, gate_time_start, gate_time_end
)
WHERE EXISTS (SELECT 1 FROM public.challenges c WHERE c.id = v.challenge_id)
  AND NOT EXISTS (
    SELECT 1 FROM public.challenge_tasks ct WHERE ct.challenge_id = v.challenge_id
  );
