/**
 * GRIIT Design System — Rork visual spec.
 * Base palette from constants/theme.ts; extended tokens here.
 */
import {
  BASE_COLORS,
  COMMITMENT_BUTTON_BG,
  EXPLORE_BUTTON_BG,
  SURFACE_SUBTLE,
  SURFACE_MUTED,
  ACCENT_LIGHT,
  ACCENT_SOFT,
  SUCCESS_LIGHT,
  WARNING_COLOR,
  WARNING_LIGHT,
  DANGER_COLOR,
  DANGER_LIGHT,
  NAVY_DARK,
  GOLD,
  BLACK_BTN,
  CHIP_FILL,
  PILL,
  BADGE_GREEN_BG,
  BADGE_GREEN_TEXT,
  BADGE_YELLOW_BG,
  BADGE_YELLOW_TEXT,
  BADGE_ORANGE_BG,
  BADGE_ORANGE_TEXT,
  BADGE_RED_BG,
  BADGE_RED_TEXT,
  CATEGORY_FITNESS,
  CATEGORY_MIND,
  CATEGORY_DISCIPLINE,
} from "@/constants/theme";

// ─── COLORS (GRIIT — Rork spec, light only) ─────────────────────────────────
export const DS_COLORS = {
  background: BASE_COLORS.background,
  surface: BASE_COLORS.surface,
  card: BASE_COLORS.card,
  textPrimary: BASE_COLORS.textPrimary,
  textSecondary: BASE_COLORS.textSecondary,
  textMuted: BASE_COLORS.textMuted,
  accent: BASE_COLORS.accent,
  border: BASE_COLORS.border,
  success: BASE_COLORS.success,
  tabInactive: BASE_COLORS.tabInactive,
  tabActive: BASE_COLORS.tabActive,

  surfaceSubtle: SURFACE_SUBTLE,
  surfaceMuted: SURFACE_MUTED,
  accentLight: ACCENT_LIGHT,
  accentSoft: ACCENT_SOFT,
  accentBorder: BASE_COLORS.accent,
  successLight: SUCCESS_LIGHT,
  warning: WARNING_COLOR,
  warningLight: WARNING_LIGHT,
  danger: DANGER_COLOR,
  dangerLight: DANGER_LIGHT,
  navyDark: NAVY_DARK,
  gold: GOLD,
  blackBtn: BLACK_BTN,
  chipFill: CHIP_FILL,
  pill: PILL,
  white: "#FFFFFF",
  borderStrong: BASE_COLORS.textPrimary,
  shadow: "rgba(0,0,0,0.04)",
  shadowMedium: "rgba(0,0,0,0.08)",
  badgeGreenBg: BADGE_GREEN_BG,
  badgeGreenText: BADGE_GREEN_TEXT,
  badgeYellowBg: BADGE_YELLOW_BG,
  badgeYellowText: BADGE_YELLOW_TEXT,
  badgeOrangeBg: BADGE_ORANGE_BG,
  badgeOrangeText: BADGE_ORANGE_TEXT,
  badgeRedBg: BADGE_RED_BG,
  badgeRedText: BADGE_RED_TEXT,
  categoryFitness: CATEGORY_FITNESS,
  categoryMind: CATEGORY_MIND,
  categoryDiscipline: CATEGORY_DISCIPLINE,

  backgroundAlt: BASE_COLORS.background,
  surfaceWarm: BASE_COLORS.background,
  textPrimaryAlt: BASE_COLORS.textPrimary,
  textSecondaryAlt: BASE_COLORS.textSecondary,
  textTertiary: BASE_COLORS.textMuted,
  borderAlt: BASE_COLORS.border,
  borderFocus: BASE_COLORS.accent,
  filterPillInactiveBorder: "#E0DDD6",
  accentDark: "#C2663E",
  cardSelectedBg: ACCENT_LIGHT,

  // Commitment / CTA
  commitmentButtonBg: COMMITMENT_BUTTON_BG,
  exploreButtonBg: EXPLORE_BUTTON_BG,
  buttonDisabledBg: "#C4C0B8",
  buttonDisabledText: "#FFFFFF",
  selectedBorder: BASE_COLORS.textPrimary,

  // Auth / form
  errorText: "#DC4A3C",
  green: "#2D7A4F",
  createChallengeGreen: "#2D5A3E",

  // Semantic
  successSoft: SUCCESS_LIGHT,
  warningSoft: WARNING_LIGHT,
  dangerSoft: DANGER_LIGHT,
  dangerDark: "#B91C1C",
  dangerMid: "#DC2626",
  dangerDarkest: "#7F1D1D",
  materialRed: "#F44336",
  materialGreen: "#4CAF50",

  // Onboarding (cream — Design DNA)
  onboardingBg: BASE_COLORS.background,
  borderDark: "#E8E5DE",
  darkCard: "#FFFFFF",
  darkTextSecondary: "#A0A0A0",
  darkTextTertiary: "#737373",
  darkTextMuted: "#525252",
  darkBorder: "#2A2A2A",
  darkPill: "#262626",
  darkCategoryMind: "#8B7CD4",
  darkStreakPlatinum: "#71717A",
  darkMilestoneSilver: "#A8A8A8",
  darkMilestoneGold: "#EAB308",
  darkMilestoneDiamond: "#67E8F1",

  // Task type / semantic accents
  milestoneGold: "#D4A017",
  milestoneBronze: "#CD7F32",
  milestoneSilver: "#C0C0C0",
  milestoneDiamond: "#B9F2FF",
  crownGold: "#B8860B",
  linkBlue: "#0EA5E9",
  journalPurple: "#8E44AD",
  runOrange: "#FF6B35",
  taskIndigo: "#6366F1",
  taskPhotoPink: "#EC4899",
  taskAmber: "#F59E0B",
  taskEmerald: "#10B981",
  silverRank: "#9CA3AF",

  // Controls
  switchThumbInactive: "#f4f3f4",
  toggleTrackOn: "#FDDCB5",
  skeletonBg: "#E8E6E1",
  overlayDark: "#111",
  overlayDarker: "#0f0f0f",
  modalBackdrop: "rgba(0,0,0,0.5)",
  grayMuted: "#7A7A6D",
  grayMedium: "#6B7280",
  filterChipActiveBg: "#444",

  // UI
  black: "#1A1A1A",
  chipStroke: "#E0DDD6",
  inputPlaceholder: "#888884",
  centerButtonBg: "#1C1C1E",

  // Difficulty badges
  difficultyMediumBg: "#FFF0E8",
  difficultyMediumText: "#C85A20",
  difficultyHardBg: "#FFEAEA",
  difficultyHardText: "#C83030",
  difficultyExtremeBg: "#FFE5E5",
  difficultyExtremeText: "#AA1111",
  featuredLabelBg: "#EAF5F0",
  featuredLabelText: "#2F7A52",
  badgeYellowGreenText: "#7C9B2E",
  badgeYellowGreenBg: "#ECFCCB",
  purpleStripe: "#7C6BC4",
  blueStripe: "#2563EB",
  activeTodayText: "#2F7A52",
  challengePausedBg: "#FFF0EE",
  challengePausedTitle: "#C84030",
  rebuildModeText: "#E07B4A",

  // Settings (Design DNA — cream)
  settingsPageBg: BASE_COLORS.background,
  settingsBackCircle: "#E8E4DD",

  // Challenge detail 24h header
  challenge24hHeaderBg: "#3E7A55",
  difficultyEasyHeader: "#1B5E20",
  challengeHeaderDark: "#1A1A2E",
  alertRedBorder: "#F8D7DA",

  // Shadows
  shadowBlack: "#000",

  // Tints / one-off UI
  purpleTintLight: "#F5ECFF",
  purpleTintWarm: "#FFEFEB",
  journalStartBlue: "#6B8BFF",
  avatarPurple: "#D1C4E9",
  avatarPurpleText: "#7E57C2",
  emeraldDark: "#059669",
  activityOrange: "#FC4C02",
  rankGoldBg: "#D4A853",
  photoThumbBg: "#eeeeee",
  acceptGreen: "#22c55e",
  createErrorBg: "#FEF3EE",
  createErrorText: "#C86A3A",
  darkSurface: "#1F1F1F",
  amberDarkText: "#92400E",
  amberLightBg: "#FEF3C7",
  dangerLightBg: "#FEE2E2",
  grayLight: "#E5E5E5",
  stepperGray: "#D0CEC8",
  journalPurpleLight: "#F3E8FF",
  photoPinkBg: "#FFF0F5",
  runGreenBg: "#F0FFF4",
  checkinBlue: "#3B82F6",
  checkinBlueBg: "#EFF6FF",
  surfaceAlt: "#F2F2F1",
  syncingBannerBg: "#FFF8E1",
  packBorderFaith: "#93C5FD",
  packBorderOrange: "#FDBA74",
  taskIndigoBg: "#6366F115",
  grayDark: "#7A7A6D",
  grayDarker: "#2D3A2E",
  grayMid: "#CCCCCC",
  surfaceGray: "#EEEEEE",
  surfaceGrayDark: "#DDDDDD",
  moodYellow: "#EAB308",
  journalCardBg: "#FAF8F6",
  taskIndigoAlpha: "#6366F10D",
  taskAmberAlpha: "#F59E0B14",
  avatarColor1: "#E8733A",
  avatarColor2: "#2E7D32",
  avatarColor3: "#5C6BC0",
  avatarColor4: "#EF5350",
  avatarColor5: "#26A69A",
  avatarColor6: "#FFA726",
  avatarColor7: "#8D6E63",
  avatarColor8: "#66BB6A",
  confettiCyan: "#00CED1",
  confettiPurple: "#9B59B6",
  journalPurpleVivid: "#A855F7",
  chipGrayBg: "#F3F4F6",
} as const;

// ─── TYPOGRAPHY (Rork) ─────────────────────────────────────────────────────
export const DS_TYPOGRAPHY = {
  screenTitle: { fontSize: 30, fontWeight: "800" as const, color: "#1A1A1A", letterSpacing: -0.5 },
  screenSubtitle: { fontSize: 15, fontWeight: "400" as const, color: "#888884" },
  sectionHeader: { fontSize: 17, fontWeight: "700" as const, color: "#1A1A1A" },
  cardTitle: { fontSize: 18, fontWeight: "700" as const, color: "#1A1A1A" },
  cardSubtitle: { fontSize: 14, fontWeight: "400" as const, color: "#888884" },
  metaRow: { fontSize: 12, fontWeight: "400" as const, color: "#AAAAAA" },
  featuredLabel: { fontSize: 11, fontWeight: "700" as const, letterSpacing: 1, color: "#2F7A52" },
  difficultyBadge: { fontSize: 12, fontWeight: "600" as const },
  tabLabel: { fontSize: 10, fontWeight: "400" as const },
  ctaButton: { fontSize: 16, fontWeight: "600" as const, color: "#FFFFFF" },
  activeTodayCount: { fontSize: 13, fontWeight: "600" as const, color: "#2F7A52" },

  wordmark: { fontSize: 16, fontWeight: "800" as const, letterSpacing: 3, lineHeight: 20 },
  wordmarkSubtitle: { fontSize: 13, fontWeight: "500" as const, lineHeight: 18 },
  pageTitleLarge: { fontSize: 44, fontWeight: "800" as const, letterSpacing: -0.8, lineHeight: 50 },
  pageTitle: { fontSize: 28, fontWeight: "800" as const, letterSpacing: -0.5, lineHeight: 34 },
  sectionTitle: { fontSize: 20, fontWeight: "700" as const, letterSpacing: -0.2, lineHeight: 26 },

  body: { fontSize: 16, fontWeight: "500" as const, lineHeight: 24 },
  bodySmall: { fontSize: 15, fontWeight: "400" as const, lineHeight: 22 },
  secondary: { fontSize: 14, fontWeight: "400" as const, lineHeight: 20 },
  metadata: { fontSize: 13, fontWeight: "500" as const, lineHeight: 18 },
  eyebrow: { fontSize: 12, fontWeight: "600" as const, letterSpacing: 1, lineHeight: 16 },
  button: { fontSize: 17, fontWeight: "700" as const, lineHeight: 22 },
  buttonSmall: { fontSize: 16, fontWeight: "600" as const },
  chip: { fontSize: 15, fontWeight: "600" as const },
  statValue: { fontSize: 28, fontWeight: "700" as const },
  statLabel: { fontSize: 12, fontWeight: "600" as const, letterSpacing: 0.5 },
} as const;

// ─── SPACING (Rork) ────────────────────────────────────────────────────────
export const DS_SPACING = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
  section: 40,
  screenHorizontal: 20,
  screenHorizontalAlt: 20,
  screenTopPadding: 16,
  sectionGap: 12,
  sectionGapLarge: 32,
  cardPadding: 16,
  cardGap: 12,
  inputLabelGap: 8,
  listItemGap: 12,
} as const;

// ─── RADIUS (Rork) ─────────────────────────────────────────────────────────
export const DS_RADIUS = {
  input: 12,
  card: 16,
  cardAlt: 16,
  pill: 999,
  button: 14,
  buttonPill: 14,
  chip: 999,
  iconButton: 22,
  centerNavButton: 999,
  searchBar: 12,
  filterPill: 999,
  ctaButton: 14,
  featuredBadge: 6,
  modal: 24,
} as const;

// ─── BORDERS ───────────────────────────────────────────────────────────────
export const DS_BORDERS = {
  width: 1,
  widthStrong: 2,
  color: DS_COLORS.border,
  colorStrong: DS_COLORS.textPrimary,
} as const;

// ─── SHADOWS (Design DNA: very subtle card — opacity 0.04, radius 6) ───────────
export const DS_SHADOWS = {
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  button: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  centerButton: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
} as const;

// ─── COMPONENT MEASURES (Rork) ─────────────────────────────────────────────
export const DS_MEASURES = {
  ctaHeight: 56,
  ctaHeightCompact: 52,
  inputHeight: 56,
  searchHeight: 44,
  searchBarRadius: 12,
  filterPillHeight: 36,
  tabBarHeight: 88,
  centerNavButtonSize: 56,
  headerHeight: 56,
  progressBarHeight: 6,
  featuredStripeWidth: 4,
  sectionHeaderIconSize: 18,
} as const;

export type DSColors = typeof DS_COLORS;
export type DSTypography = typeof DS_TYPOGRAPHY;
export type DSSpacing = typeof DS_SPACING;
export type DSRadius = typeof DS_RADIUS;
