/**
 * Onboarding v2 launch routing and step resolution.
 * Pure — no I/O. AuthRedirector and OnboardingFlowV2 call these.
 */

export const ONBOARDING_V2_ORDER = [
  "welcome",
  "goals",
  "why_proof",
  "why_circle",
  "commitment",
  "first_challenge",
  "reminders",
  "account",
  "profile",
] as const;

export type OnboardingV2Step = (typeof ONBOARDING_V2_ORDER)[number];

/** Dots after welcome. No "of 9." */
export const ONBOARDING_V2_PROGRESS_SEGMENTS = 8;

export type SessionKind = "none" | "guest" | "real";

export type OnboardingLaunchDestination = "home" | "resume" | "welcome" | "retry";

const ORDER_SET = new Set<string>(ONBOARDING_V2_ORDER);

/** Stale v4 / paywall-era keys resume on the Chunk A step. */
const STEP_ALIASES: Record<string, OnboardingV2Step> = {
  proof: "why_proof",
  circle: "why_circle",
  challenge: "first_challenge",
  reminder: "reminders",
  invite: "account",
  dayone: "profile",
  paywall: "first_challenge",
};

export function resolveV2Step(raw: string | null | undefined): OnboardingV2Step {
  if (raw && ORDER_SET.has(raw)) return raw as OnboardingV2Step;
  if (raw && raw in STEP_ALIASES) return STEP_ALIASES[raw] ?? "welcome";
  return "welcome";
}

export function v2StepIndex(step: OnboardingV2Step): number {
  return ONBOARDING_V2_ORDER.indexOf(step);
}

/** PositionBar index. Goals is 0. Welcome is not on the bar. */
export function chromeStep(step: OnboardingV2Step): number {
  return Math.max(0, v2StepIndex(step) - 1);
}

/** Segment i (1..8) is filled when the current step index is >= i. */
export function v2SegmentFilled(step: OnboardingV2Step, segment: number): boolean {
  return v2StepIndex(step) >= segment;
}

export function v2ProgressLabel(step: OnboardingV2Step): string {
  if (step === "welcome") return "";
  return "";
}

export function sessionKindFromUser(user: { is_anonymous?: boolean } | null | undefined): SessionKind {
  if (!user) return "none";
  if (user.is_anonymous === true) return "guest";
  return "real";
}

/**
 * ensure-profile / handle_new_user: `user_` + first 8 hex of the uuid
 * (`backend/lib/guest-username.ts`). Never a chosen handle.
 */
export const AUTO_GENERATED_USERNAME_RE = /^user_[0-9a-f]{8}$/;

export function isAutoGeneratedUsername(username: string): boolean {
  return AUTO_GENERATED_USERNAME_RE.test(username.trim().toLowerCase());
}

export function hasUsableOnboardingUsername(
  username: string | null | undefined
): boolean {
  if (typeof username !== "string") return false;
  const trimmed = username.trim();
  if (!trimmed) return false;
  return !isAutoGeneratedUsername(trimmed);
}

/**
 * Whether this session has finished onboarding.
 *
 * `profiles.onboarding_completed === true` OR a chosen username.
 * Auto-generated `user_` + 8 hex handles never count, for any session kind.
 * Local ONBOARDING_COMPLETED is a cache write only — never an input here.
 */
export function resolveOnboardingCompleted(input: {
  sessionKind: SessionKind;
  dbCompleted: boolean | null;
  username?: string | null;
}): boolean {
  if (input.sessionKind === "none") return false;
  if (input.dbCompleted === true) return true;
  return hasUsableOnboardingUsername(input.username);
}

/** True when we should write the flag because username already implies done. */
export function shouldSelfHealOnboardingFlag(input: {
  sessionKind: SessionKind;
  dbCompleted: boolean | null;
  username?: string | null;
}): boolean {
  return (
    input.sessionKind !== "none" &&
    input.dbCompleted !== true &&
    hasUsableOnboardingUsername(input.username)
  );
}

export function resolveOnboardingLaunch(input: {
  sessionKind: SessionKind;
  dbCompleted: boolean | null;
  username?: string | null;
}): OnboardingLaunchDestination {
  if (input.sessionKind === "none") return "welcome";
  if (resolveOnboardingCompleted(input)) return "home";
  if (input.dbCompleted === null) return "retry";
  return "resume";
}

/**
 * After launch dest is "home" (completed), where to send them.
 * `null` = stay put — a completed guest already on Discover must not bounce to Home.
 */
export function resolveCompletedLeaveHref(input: {
  inOnboarding: boolean;
  inAuth: boolean;
  onCreateProfile: boolean;
  inTabs: boolean;
  exitHref?: string | null;
}): string | null {
  if (input.inTabs) return null;
  if (input.inOnboarding || input.inAuth || input.onCreateProfile) {
    return input.exitHref ?? "/(tabs)";
  }
  return null;
}

/** In-memory exit chosen by completeOnboardingV2. Not persisted. */
let pendingExitHref: string | null = null;

export function setOnboardingV2Exit(href: string): void {
  pendingExitHref = href;
}

export function peekOnboardingV2Exit(): string | null {
  return pendingExitHref;
}

/**
 * Confirmed `profiles.onboarding_completed` from a write this session,
 * scoped to the user it was written for.
 * Breaks stale-fetch ties in AuthRedirector only — never a routing gate
 * on its own. Not the AsyncStorage ONBOARDING_COMPLETED cache.
 */
let knownDbCompleted: { userId: string; value: boolean } | null = null;

export function setKnownOnboardingCompleted(userId: string, value: boolean): void {
  knownDbCompleted = { userId, value };
}

export function clearKnownOnboardingCompleted(): void {
  knownDbCompleted = null;
}

/** `null` when empty, or when the stored userId is not `userId`. */
export function peekKnownOnboardingCompleted(
  userId: string | null | undefined
): boolean | null {
  if (!userId || !knownDbCompleted || knownDbCompleted.userId !== userId) return null;
  return knownDbCompleted.value;
}

/** Writer wins when it has confirmed true; otherwise the last fetch. */
export function dbCompletedForLaunch(input: {
  fetched: boolean | null;
  written: boolean | null;
}): boolean | null {
  if (input.written === true) return true;
  return input.fetched;
}
