/** Display helpers — avoid showing auto-generated `user_<hex>` as the primary name. */

function isAutoGeneratedUsername(u: string | null | undefined): boolean {
  if (!u || typeof u !== "string") return false;
  return /^user_[0-9a-f]{8}$/i.test(u.trim());
}

export function profilePrimaryName(
  p: { username?: string | null; display_name?: string | null },
  /** @deprecated Ignored. Real accounts never greet with the email local-part. */
  _emailLocalPart?: string | null
): string {
  const rawUser = p.username?.trim() ?? "";
  const rawDisplay = p.display_name?.trim() ?? "";
  if (rawDisplay) return rawDisplay;
  if (rawUser && !isAutoGeneratedUsername(rawUser)) return rawUser;
  return "";
}
