/** Display helpers — avoid showing auto-generated `user_<hex>` as the primary name. */

export function isAutoGeneratedUsername(u: string | null | undefined): boolean {
  if (!u || typeof u !== "string") return false;
  return /^user_[0-9a-f]{8}$/i.test(u.trim());
}

export function profilePrimaryName(
  p: { username?: string | null; display_name?: string | null },
  emailLocalPart?: string | null
): string {
  const rawUser = p.username?.trim() ?? "";
  const rawDisplay = p.display_name?.trim() ?? "";
  if (rawDisplay) return rawDisplay;
  if (rawUser && !isAutoGeneratedUsername(rawUser)) return rawUser;
  const local = emailLocalPart?.trim();
  if (local) return local;
  return "User";
}

/** `@handle` only for real usernames (not `user_xxxxxxxx`). */
export function profileHandleAt(p: { username?: string | null }): string | null {
  const rawUser = p.username?.trim() ?? "";
  if (!rawUser || isAutoGeneratedUsername(rawUser)) return null;
  return `@${rawUser}`;
}
