/**
 * tRPC procedure paths as constants to avoid typos and enable find-usages.
 * Add new paths here as you add or use procedures.
 */
export const TRPC = {
  auth: {
    signUp: 'auth.signUp',
    signIn: 'auth.signIn',
    signOut: 'auth.signOut',
    getSession: 'auth.getSession',
  },
  profiles: {
    get: 'profiles.get',
    getPublicByUsername: 'profiles.getPublicByUsername',
    create: 'profiles.create',
    update: 'profiles.update',
    updatePushToken: 'profiles.updatePushToken',
    validateSubscription: 'profiles.validateSubscription',
    getStats: 'profiles.getStats',
    getCompletedChallenges: 'profiles.getCompletedChallenges',
    getSecuredDateKeys: 'profiles.getSecuredDateKeys',
    setWeeklyGoal: 'profiles.setWeeklyGoal',
    getWeeklyProgress: 'profiles.getWeeklyProgress',
    getWeeklyTrend: 'profiles.getWeeklyTrend',
    search: 'profiles.search',
    deleteAccount: 'profiles.deleteAccount',
    followUser: 'profiles.followUser',
    unfollowUser: 'profiles.unfollowUser',
    sendFollowRequest: 'profiles.sendFollowRequest',
    getFollowStatus: 'profiles.getFollowStatus',
    acceptFollowRequest: 'profiles.acceptFollowRequest',
    declineFollowRequest: 'profiles.declineFollowRequest',
    getPendingFollowRequests: 'profiles.getPendingFollowRequests',
    getBadges: 'profiles.getBadges',
    getFollowCounts: 'profiles.getFollowCounts',
    getFollowers: 'profiles.getFollowers',
    getFollowing: 'profiles.getFollowing',
    isFollowing: 'profiles.isFollowing',
  },
  challenges: {
    list: 'challenges.list',
    getFeatured: 'challenges.getFeatured',
    getDiscoverFeed: 'challenges.getDiscoverFeed',
    getRecommended: 'challenges.getRecommended',
    getCategoryCounts: 'challenges.getCategoryCounts',
    getStarterPack: 'challenges.getStarterPack',
    getById: 'challenges.getById',
    join: 'challenges.join',
    leave: 'challenges.leave',
    getActive: 'challenges.getActive',
    listMyActive: 'challenges.listMyActive',
    getPublicChallenges: 'challenges.getPublicChallenges',
    create: 'challenges.create',
    startTeamChallenge: 'challenges.startTeamChallenge',
    getTeamMembers: 'challenges.getTeamMembers',
  },
  sharedGoal: {
    logProgress: 'sharedGoal.logProgress',
    getRecentLogs: 'sharedGoal.getRecentLogs',
    getContributions: 'sharedGoal.getContributions',
  },
  checkins: {
    getTodayCheckins: 'checkins.getTodayCheckins',
    getTodayCheckinsForUser: 'checkins.getTodayCheckinsForUser',
    complete: 'checkins.complete',
    secureDay: 'checkins.secureDay',
    markAsShared: 'checkins.markAsShared',
    getShareStats: 'checkins.getShareStats',
    setMilestoneShared: 'checkins.setMilestoneShared',
    getMilestoneShared: 'checkins.getMilestoneShared',
  },
  starters: {
    getChallengeIdByStarterId: 'starters.getChallengeIdByStarterId',
    join: 'starters.join',
  },
  streaks: {
    useFreeze: 'streaks.useFreeze',
  },
  leaderboard: {
    getWeekly: 'leaderboard.getWeekly',
    getFriendsBoard: 'leaderboard.getFriendsBoard',
    getChallengeBoard: 'leaderboard.getChallengeBoard',
  },
  respects: {
    give: 'respects.give',
    getForUser: 'respects.getForUser',
  },
  nudges: {
    send: 'nudges.send',
    getForUser: 'nudges.getForUser',
  },
  notifications: {
    registerToken: 'notifications.registerToken',
    getReminderSettings: 'notifications.getReminderSettings',
    updateReminderSettings: 'notifications.updateReminderSettings',
    getAll: 'notifications.getAll',
    markAllRead: 'notifications.markAllRead',
  },
  accountability: {
    listMine: 'accountability.listMine',
    invite: 'accountability.invite',
    respond: 'accountability.respond',
    remove: 'accountability.remove',
  },
  user: {
    completeOnboarding: 'user.completeOnboarding',
  },
  referrals: {
    recordOpen: 'referrals.recordOpen',
    markJoinedChallenge: 'referrals.markJoinedChallenge',
  },
  feed: {
    list: 'feed.list',
    listMine: 'feed.listMine',
    getMySummary: 'feed.getMySummary',
    getLiveFeed: 'feed.getLiveFeed',
    react: 'feed.react',
    comment: 'feed.comment',
    deleteComment: 'feed.deleteComment',
    getComments: 'feed.getComments',
    shareCompletion: 'feed.shareCompletion',
    deletePost: 'feed.deletePost',
    getReactions: 'feed.getReactions',
    getPost: 'feed.getPost',
    getUserPosts: 'feed.getUserPosts',
    getRecentCompletions: 'feed.getRecentCompletions',
  },
  achievements: {
    getForUser: 'achievements.getForUser',
  },
  integrations: {
    getStravaAuthUrl: 'integrations.getStravaAuthUrl',
    isStravaEnabled: 'integrations.isStravaEnabled',
    getStravaConnection: 'integrations.getStravaConnection',
    getStravaActivities: 'integrations.getStravaActivities',
    getStravaAthlete: 'integrations.getStravaAthlete',
    disconnectStrava: 'integrations.disconnectStrava',
    verifyStravaTask: 'integrations.verifyStravaTask',
  },
} as const;
