import { StyleSheet } from "react-native";
import { DS_COLORS, GRIIT_COLORS, DS_RADIUS, DS_SPACING, DS_TYPOGRAPHY } from "@/lib/design-system";
import { CREATE_SELECTION } from "@/lib/create-selection";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS_COLORS.background },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: DS_SPACING.lg,
    paddingVertical: 10,
    backgroundColor: DS_COLORS.ACCENT_TINT,
  },
  bannerText: { fontSize: 13, color: DS_COLORS.TEXT_PRIMARY, flex: 1 },
  bannerBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: DS_RADIUS.SM, backgroundColor: GRIIT_COLORS.primary },
  bannerBtnText: { color: DS_COLORS.TEXT_ON_DARK, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, fontSize: 12 },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: DS_SPACING.lg,
    paddingBottom: 8,
  },
  cancel: { fontSize: 16, color: DS_COLORS.TEXT_SECONDARY },
  topTitle: { fontSize: 17, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  stepperRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 8, gap: 4 },
  stepperItem: { flexDirection: "row", alignItems: "center" },
  stepDot: { width: 10, height: 10, borderRadius: DS_RADIUS.SM, backgroundColor: DS_COLORS.border },
  stepDotOn: { backgroundColor: GRIIT_COLORS.primary },
  stepLine: { width: 24, height: 2, backgroundColor: DS_COLORS.border },
  stepLineOn: { backgroundColor: GRIIT_COLORS.primary },
  scroll: { paddingHorizontal: DS_SPACING.lg },
  h1: {
    fontSize: 28,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    letterSpacing: -0.5,
    color: DS_COLORS.TEXT_PRIMARY,
    marginBottom: 4,
  },
  sub: { fontSize: 16, fontWeight: "400", color: DS_COLORS.textSecondary, marginBottom: 20 },
  fieldLabel: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.textSecondary, marginBottom: 8 },
  light: { color: DS_COLORS.TEXT_MUTED, fontWeight: "400" },
  input: {
    backgroundColor: DS_COLORS.surface,
    borderWidth: 1.5,
    borderColor: DS_COLORS.border,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: DS_COLORS.TEXT_PRIMARY,
  },
  inputErr: { borderColor: DS_COLORS.errorText },
  errText: { color: DS_COLORS.errorText, fontSize: 12, marginTop: 6 },
  whoRow: { flexDirection: "row", gap: 8 },
  whoCard: {
    flex: 1,
    backgroundColor: DS_COLORS.surface,
    borderWidth: 1.5,
    borderColor: DS_COLORS.border,
    borderRadius: DS_RADIUS.LG,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  whoCardSel: {
    borderColor: CREATE_SELECTION.border,
    backgroundColor: CREATE_SELECTION.background,
  },
  whoTitle: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY, marginTop: 6 },
  whoSub: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, textAlign: "center", marginTop: 4 },
  customRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  daysLabel: { fontSize: 15, color: DS_COLORS.TEXT_SECONDARY },
  typeRow: { flexDirection: "row", gap: 8 },
  typeCard: {
    flex: 1,
    padding: 12,
    borderRadius: DS_RADIUS.LG,
    borderWidth: 1.5,
    borderColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.surface,
  },
  typeCardSel: { borderColor: CREATE_SELECTION.border, backgroundColor: CREATE_SELECTION.background },
  typeCardTitle: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  typeCardSub: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, marginTop: 4 },
  packsHead: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_MUTED, marginBottom: 8 },
  packCard: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.LG,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
    padding: 12,
  },
  packCardSel: { borderColor: CREATE_SELECTION.border, backgroundColor: CREATE_SELECTION.background },
  packEmoji: { fontSize: 24, marginBottom: 6 },
  packName: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: GRIIT_COLORS.primary },
  packDesc: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, marginTop: 4 },
  packCount: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, marginTop: 6 },
  listHead: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY, marginTop: 16, marginBottom: 8 },
  taskRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: DS_COLORS.chipFill,
    gap: 8,
  },
  taskTitleRow: { flex: 1, flexDirection: "row", alignItems: "center", minWidth: 0, gap: 6 },
  taskTitle: { flexShrink: 1, fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  hardBadge: {
    backgroundColor: DS_COLORS.ACCENT_TINT,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: DS_RADIUS.MD,
    flexShrink: 0,
  },
  hardBadgeText: { fontSize: 11, fontWeight: "500", color: DS_COLORS.PRIMARY },
  empty: { alignItems: "center", padding: 24 },
  emptyTitle: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  emptySub: { fontSize: 13, color: DS_COLORS.TEXT_MUTED, marginTop: 4 },
  dashedAdd: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: DS_COLORS.border,
    borderRadius: DS_RADIUS.button,
    padding: 14,
    alignItems: "center",
    marginTop: 12,
  },
  dashedAddErr: { borderColor: DS_COLORS.errorText },
  dashedAddText: { color: GRIIT_COLORS.primary, fontWeight: "500" },
  catPillWrap: {
    borderRadius: DS_RADIUS.button,
    borderWidth: 1.5,
    borderColor: "transparent",
    padding: 0,
  },
  catPillWrapErr: { borderColor: DS_COLORS.errorText },
  ruleCard: {
    flex: 1,
    padding: 10,
    borderRadius: DS_RADIUS.button,
    borderWidth: 1.5,
    borderColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.surface,
  },
  ruleCardSel: { borderColor: CREATE_SELECTION.border, backgroundColor: CREATE_SELECTION.background },
  ruleTitle: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, marginBottom: 6, color: DS_COLORS.TEXT_PRIMARY },
  caption: { fontSize: 13, fontWeight: "400", color: DS_COLORS.TEXT_HINT, marginTop: 6 },
  outlineBtn: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: GRIIT_COLORS.primary,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: 12,
    alignItems: "center",
  },
  outlineBtnTxt: { color: GRIIT_COLORS.primary, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  lockHint: { fontSize: 13, fontWeight: "400", color: DS_COLORS.TEXT_HINT, textAlign: "center", marginTop: 16 },
  footer: {
    paddingHorizontal: DS_SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.background,
  },
  primary: {
    backgroundColor: GRIIT_COLORS.primary,
    height: 52,
    borderRadius: DS_RADIUS.joinCta,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  primaryTxt: { color: DS_COLORS.TEXT_ON_DARK, fontSize: 17, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  primaryDisabled: { backgroundColor: DS_COLORS.buttonDisabledBg },
  primaryTxtDisabled: { color: DS_COLORS.buttonDisabledText },
  charCount: {
    fontSize: 11,
    color: DS_COLORS.TEXT_TERTIARY,
    textAlign: "right",
    marginTop: 4,
  },
  backOut: {
    height: 54,
    paddingHorizontal: 24,
    borderRadius: DS_RADIUS.joinCta,
    borderWidth: 1.5,
    borderColor: DS_COLORS.BORDER,
    backgroundColor: DS_COLORS.CARD_BG,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  backOutTxt: { fontSize: 16, fontWeight: "500", color: DS_COLORS.TEXT_SECONDARY },
  rowFooter: { flexDirection: "row", gap: 10, alignItems: "center", marginTop: 8 },
  launch: {
    flex: 1,
    backgroundColor: DS_COLORS.TEXT_PRIMARY,
    height: 54,
    borderRadius: DS_RADIUS.joinCta,
    alignItems: "center",
    justifyContent: "center",
  },
  launchTxt: { color: DS_COLORS.TEXT_ON_DARK, fontSize: 17, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  topBarSpacer: { width: 56 },
  inviteSection: { marginTop: 16 },
  draftExitBackdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    backgroundColor: DS_COLORS.modalBackdrop,
  },
  draftExitCard: {
    backgroundColor: DS_COLORS.card,
    borderRadius: DS_RADIUS.LG,
    padding: 20,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  draftExitTitle: {
    fontSize: 18,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    marginBottom: 16,
    textAlign: "center",
  },
  draftExitPrimary: {
    backgroundColor: DS_COLORS.accent,
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
  },
  draftExitPrimaryTxt: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
  draftExitDanger: {
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: DS_COLORS.alertRedBorder,
    backgroundColor: DS_COLORS.dangerLight,
  },
  draftExitDangerTxt: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.dangerDark },
  draftExitSecondary: {
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  draftExitSecondaryTxt: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  flex1: { flex: 1 },
  shakeWrap: {},
  saveDraftText: { fontSize: 15, fontWeight: "500", color: DS_COLORS.TEXT_SECONDARY },
  colGapSm: { flexDirection: "column", gap: DS_SPACING.SM },
  rowGapSm: { flexDirection: "row", gap: DS_SPACING.SM },
  colGap10: { flexDirection: "column", gap: 10 },
  rowGap10: { flexDirection: "row", gap: 10 },
  rowStartGap8Mb4: { flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 4 },
  mt2: { marginTop: 2 },
  rowBetweenStartMb8: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  text14SecondaryMt4: { fontSize: 14, color: DS_COLORS.TEXT_SECONDARY, marginTop: 4 },
  text13SemiboldPrimary: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.PRIMARY },
  mt12ColGap6: { marginTop: 12, flexDirection: "column", gap: 6 },
  rowGap6: { flexDirection: "row", gap: 6 },
  text13MediumSecondary: { fontSize: 13, fontWeight: "500", color: DS_COLORS.TEXT_SECONDARY },
  dividerMv16: { height: 1, backgroundColor: DS_COLORS.DIVIDER, marginVertical: 16 },
  rowBetweenCenter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  text13Hint: { fontSize: 13, color: DS_COLORS.TEXT_HINT },
  text18BoldPrimaryMt2: { fontSize: 18, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY, marginTop: 2 },
  itemsEnd: { alignItems: "flex-end" },
  text18: { fontSize: 18 },
  text16SemiboldPrimary: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  text13HintMt2: { fontSize: 13, color: DS_COLORS.TEXT_HINT, marginTop: 2 },
  text13: { fontSize: 13 },
  text13HintMt8Lh20: { fontSize: 13, color: DS_COLORS.TEXT_HINT, marginTop: 8, lineHeight: 20 },
  hardWarningBox: {
    backgroundColor: DS_COLORS.CREATE_HARD_WARNING_BG,
    borderWidth: 1.5,
    borderColor: DS_COLORS.CREATE_HARD_WARNING_BORDER,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 16,
    marginTop: 4,
  },
  hardWarningText: { fontSize: 14, color: DS_COLORS.CREATE_HARD_WARNING_TEXT, lineHeight: 21 },
  saveDraftBtn: {
    width: "100%",
    height: 48,
    borderRadius: DS_RADIUS.modal,
    borderWidth: 1.5,
    borderColor: DS_COLORS.BORDER,
    backgroundColor: DS_COLORS.CARD_BG,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
  },
  saveDraftBtnDisabled: { opacity: 0.6 },
});
