import { StyleSheet } from "react-native";
import { DS_COLORS, DS_TYPOGRAPHY, DS_RADIUS } from "@/lib/design-system"

export const journalScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DS_COLORS.journalCardBg,
  },
  flex: {
    flex: 1,
  },
  draftExitBackdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    backgroundColor: DS_COLORS.modalBackdrop,
  },
  draftExitCard: {
    backgroundColor: DS_COLORS.card,
    borderRadius: DS_RADIUS.LG,
    padding: 20,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  draftExitTitle: {
    fontSize: 18,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
    textAlign: "center",
  },
  draftExitBody: {
    fontSize: 14,
    color: DS_COLORS.textSecondary,
    marginBottom: 20,
    textAlign: "center",
  },
  draftExitBtnPrimary: {
    backgroundColor: DS_COLORS.accent,
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
  },
  draftExitBtnPrimaryText: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.textPrimary },
  draftExitBtnDanger: {
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: DS_COLORS.alertRedBorder,
    backgroundColor: DS_COLORS.dangerLight,
  },
  draftExitBtnDangerText: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.dangerDark },
  draftExitBtnSecondary: {
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  draftExitBtnSecondaryText: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.textPrimary },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(0,0,0,0.06)",
    backgroundColor: DS_COLORS.journalCardBg,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: DS_RADIUS.XL,
    backgroundColor: DS_COLORS.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    gap: 4,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
  },
  headerTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: DS_COLORS.taskIndigoBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: DS_RADIUS.featuredBadge,
  },
  headerTagText: {
    fontSize: 10,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.taskIndigo,
  },
  headerRight: {
    width: 36,
  },

  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },

  promptCard: {
    backgroundColor: DS_COLORS.white,
    borderRadius: DS_RADIUS.LG,
    padding: 20,
    marginBottom: 20,
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: DS_COLORS.taskIndigo,
  },
  promptLabel: {
    fontSize: 11,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.taskIndigo,
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  promptText: {
    fontSize: 17,
    fontWeight: "500" as const,
    color: DS_COLORS.textPrimary,
    lineHeight: 24,
  },
  typeChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 14,
  },
  typeChip: {
    backgroundColor: DS_COLORS.taskIndigoAlpha,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: DS_RADIUS.featuredBadge,
  },
  typeChipText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.taskIndigo,
  },

  checkinSection: {
    marginBottom: 20,
  },
  checkinLabel: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 10,
  },
  moodRow: {
    flexDirection: "row",
    gap: 8,
  },
  moodItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderRadius: DS_RADIUS.MD,
    backgroundColor: DS_COLORS.white,
    borderWidth: 1.5,
    borderColor: "transparent",
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  moodLabel: {
    fontSize: 11,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginTop: 4,
  },

  energyRow: {
    flexDirection: "row",
    gap: 8,
  },
  energyItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: DS_RADIUS.MD,
    backgroundColor: DS_COLORS.white,
    borderWidth: 1.5,
    borderColor: "transparent",
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  energyNumber: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textMuted,
    marginTop: 4,
  },

  bodyRow: {
    flexDirection: "row",
    gap: 8,
  },
  bodyChip: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: DS_RADIUS.MD,
    backgroundColor: DS_COLORS.white,
    borderWidth: 1.5,
    borderColor: "transparent",
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  bodyChipText: {
    fontSize: 13,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textMuted,
  },

  entrySection: {
    marginBottom: 20,
  },
  entryLabel: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 10,
  },
  textArea: {
    backgroundColor: DS_COLORS.white,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
    borderRadius: DS_RADIUS.button,
    padding: 16,
    fontSize: 15,
    color: DS_COLORS.textPrimary,
    lineHeight: 22,
    minHeight: 160,
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  entryMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    paddingHorizontal: 4,
  },
  wordCount: {
    fontSize: 12,
    color: DS_COLORS.textMuted,
  },
  wordCountWarn: {
    color: DS_COLORS.dangerMid,
  },
  wordCountNear: {
    color: DS_COLORS.taskAmber,
  },
  wordLimitRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  limitReached: {
    fontSize: 11,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.taskAmber,
    backgroundColor: DS_COLORS.taskAmberAlpha,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: DS_RADIUS.SM,
  },
  charCount: {
    fontSize: 12,
    color: DS_COLORS.textMuted,
  },

  footerSafe: {
    backgroundColor: DS_COLORS.journalCardBg,
  },
  footer: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(0,0,0,0.06)",
  },
  photoProofPreview: {
    marginTop: 8,
    gap: 10,
  },
  photoProofThumb: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: DS_RADIUS.MD,
    backgroundColor: DS_COLORS.photoThumbBg,
  },
  photoProofActions: {
    flexDirection: "row",
    gap: 12,
  },
  photoProofBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: DS_COLORS.white,
    borderRadius: DS_RADIUS.MD,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  photoProofBtnText: {
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
  },
  photoProofEmpty: {
    marginTop: 8,
    gap: 10,
  },
  photoProofPrimaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: DS_COLORS.taskIndigo,
    borderRadius: DS_RADIUS.MD,
    paddingVertical: 14,
  },
  photoProofPrimaryBtnText: {
    fontSize: 15,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.white,
  },
  photoProofSecondaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: DS_RADIUS.MD,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.white,
  },
  photoProofSecondaryBtnText: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
  },
  submitBtn: {
    backgroundColor: DS_COLORS.taskIndigo,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: DS_COLORS.taskIndigo,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  submitBtnDisabled: {
    opacity: 0.4,
    shadowOpacity: 0,
  },
  submitBtnInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  submitBtnText: {
    fontSize: 16,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.white,
  },

  successContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  successContent: {
    alignItems: "center",
    marginBottom: 40,
  },
  successIconWrap: {
    width: 72,
    height: 72,
    borderRadius: DS_RADIUS.LG,
    backgroundColor: DS_COLORS.acceptGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: DS_COLORS.acceptGreen,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
  },
  successSubtitle: {
    fontSize: 15,
    color: DS_COLORS.textSecondary,
    textAlign: "center" as const,
  },
  successActions: {
    width: "100%",
    gap: 12,
  },
  successPrimaryBtn: {
    backgroundColor: DS_COLORS.textPrimary,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 16,
    alignItems: "center",
  },
  successPrimaryBtnText: {
    fontSize: 16,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.white,
  },
});
