import { StyleSheet } from "react-native";
import { DS_COLORS, DS_SPACING, DS_RADIUS, DS_TYPOGRAPHY, DS_BORDERS, DS_SHADOWS, DS_MEASURES, GRIIT_COLORS } from "@/lib/design-system";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  scroll: { flex: 1 },
  scrollContent: { padding: DS_SPACING.cardPadding, paddingBottom: DS_SPACING.section },
  screenTitle: {
    fontSize: DS_TYPOGRAPHY.SIZE_LG,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    marginBottom: DS_SPACING.xs,
  },
  headerSubtitle: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS.TEXT_MUTED, marginBottom: DS_SPACING.md },
  taskMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: DS_SPACING.md,
  },
  pillDay: {
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  pillDayText: {
    fontSize: 11,
    fontWeight: "600",
    color: DS_COLORS.TEXT_SECONDARY,
  },
  pillStreak: {
    backgroundColor: DS_COLORS.amberLightBg,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  pillStreakText: {
    fontSize: 11,
    fontWeight: "600",
    color: DS_COLORS.amberDarkText,
  },
  muted: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS.TEXT_MUTED, marginBottom: DS_SPACING.md },
  mutedCenter: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS.TEXT_MUTED, textAlign: "center", marginTop: DS_SPACING.sm },
  card: {
    backgroundColor: DS_COLORS.WHITE,
    borderRadius: DS_RADIUS.card,
    padding: DS_SPACING.lg,
    marginTop: DS_SPACING.lg,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.BORDER,
  },
  sectionLabel: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY, marginBottom: DS_SPACING.sm },
  journalPromptText: {
    fontSize: 15,
    fontWeight: "500",
    fontStyle: "italic",
    color: DS_COLORS.TEXT_PRIMARY,
    marginBottom: 12,
    lineHeight: 22,
  },
  hintSmall: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, marginBottom: DS_SPACING.md },
  warnSmall: { fontSize: 12, color: DS_COLORS.danger, textAlign: "center", marginTop: DS_SPACING.sm },
  manualPress: { alignItems: "center", paddingVertical: DS_SPACING.xl },
  manualCircle: {
    width: 120,
    height: 120,
    borderRadius: DS_RADIUS.PILL,
    borderWidth: 3,
    borderColor: DS_COLORS.DISCOVER_GREEN,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: DS_COLORS.GREEN_BG,
  },
  manualHint: { marginTop: DS_SPACING.lg, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  journalInput: {
    backgroundColor: DS_COLORS.WHITE,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
    borderRadius: DS_RADIUS.button,
    padding: 16,
    paddingTop: 14,
    fontSize: 15,
    color: DS_COLORS.TEXT_PRIMARY,
    minHeight: 200,
    textAlignVertical: "top",
    lineHeight: 22,
  },
  wordCountRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  wordRing: { flex: 1, height: 4, backgroundColor: DS_COLORS.chipFill, borderRadius: DS_RADIUS.SM, overflow: "hidden" },
  wordRingFill: { height: "100%", borderRadius: DS_RADIUS.SM },
  wordCountText: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, minWidth: 80, textAlign: "right" },
  wordCount: { fontSize: 12, color: DS_COLORS.TEXT_MUTED, marginTop: DS_SPACING.sm },
  hardModeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: DS_COLORS.ACCENT_TINT,
    paddingHorizontal: DS_SPACING.md,
    paddingVertical: 8,
    borderRadius: DS_RADIUS.input / 2,
    marginBottom: DS_SPACING.md,
  },
  hardModeText: { fontSize: 12, color: GRIIT_COLORS.primary, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  timerDisplay: {
    fontSize: 56,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_EXTRABOLD,
    color: DS_COLORS.TEXT_PRIMARY,
    fontVariant: ["tabular-nums"],
    textAlign: "center",
  },
  progressBar: {
    height: DS_MEASURES.progressBarHeight,
    backgroundColor: DS_COLORS.BORDER,
    borderRadius: DS_RADIUS.SM,
    marginTop: DS_SPACING.lg,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: DS_RADIUS.SM },
  timerRow: { flexDirection: "row", justifyContent: "center", marginTop: DS_SPACING.lg },
  secondaryBtnSmall: {
    paddingVertical: DS_SPACING.md,
    paddingHorizontal: DS_SPACING.xxl,
    borderRadius: DS_RADIUS.joinCta,
    backgroundColor: DS_COLORS.chipFill,
  },
  stravaBtn: {
    marginTop: DS_SPACING.md,
    paddingVertical: DS_SPACING.sm,
    alignItems: "center",
  },
  stravaBtnText: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_MUTED },
  stravaNote: {
    marginTop: DS_SPACING.md,
    padding: DS_SPACING.md,
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    borderRadius: 10,
    alignItems: "center",
  },
  stravaNoteText: {
    fontSize: 11,
    color: DS_COLORS.TEXT_MUTED,
  },
  hrBox: { alignItems: "center", gap: DS_SPACING.sm },
  hrRow: { flexDirection: "row", justifyContent: "space-around", width: "100%" },
  hrValue: { fontSize: 28, fontWeight: DS_TYPOGRAPHY.WEIGHT_EXTRABOLD, textAlign: "center" },
  locBox: { alignItems: "center", gap: DS_SPACING.sm },
  locStatus: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  locCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: DS_SPACING.sm,
    padding: DS_SPACING.lg,
    borderRadius: DS_RADIUS.card,
    backgroundColor: DS_COLORS.ACCENT_TINT,
  },
  locCtaText: { fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_PRIMARY },
  photoPreview: { width: "100%", height: 200, borderRadius: DS_RADIUS.card, backgroundColor: DS_COLORS.BG_CARD_TINTED },
  photoBig: {
    minHeight: 160,
    borderRadius: DS_RADIUS.card,
    borderWidth: 2,
    borderColor: DS_COLORS.BORDER,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
  },
  photoBigText: { marginTop: DS_SPACING.sm, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_SECONDARY },
  photoGrid: {
    flexDirection: "row",
    gap: 8,
  },
  photoGridBtn: {
    flex: 1,
    height: 80,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: DS_COLORS.BORDER,
    borderStyle: "dashed",
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  photoGridLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: DS_COLORS.TEXT_SECONDARY,
  },
  galleryLink: { marginTop: DS_SPACING.md, alignItems: "center" },
  link: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: GRIIT_COLORS.primary, marginTop: DS_SPACING.sm },
  textField: {
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.BORDER,
    borderRadius: DS_RADIUS.input,
    padding: DS_SPACING.md,
    fontSize: DS_TYPOGRAPHY.SIZE_BASE,
    color: DS_COLORS.TEXT_PRIMARY,
    marginBottom: DS_SPACING.sm,
  },
  hardGatesDimmed: { opacity: 0.45 },
  missedWindowCard: {
    backgroundColor: DS_COLORS.BADGE_HARD_BG,
    borderRadius: DS_RADIUS.LG,
    padding: DS_SPACING.lg,
    marginTop: DS_SPACING.md,
    borderWidth: 1,
    borderColor: DS_COLORS.BADGE_HARD_RED,
    alignItems: "center",
    gap: DS_SPACING.sm,
  },
  missedWindowTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: DS_COLORS.BADGE_HARD_RED,
    textAlign: "center",
  },
  missedWindowSub: {
    fontSize: 13,
    fontWeight: "400",
    color: DS_COLORS.TEXT_SECONDARY,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: DS_SPACING.sm,
  },
  missedRedirectCard: {
    backgroundColor: DS_COLORS.GREEN_BG,
    borderRadius: 12,
    padding: DS_SPACING.md,
    marginTop: DS_SPACING.lg,
    alignItems: "center",
  },
  missedRedirectTitle: {
    fontSize: 12,
    fontWeight: "500",
    color: DS_COLORS.GREEN,
  },
  missedRedirectSub: {
    fontSize: 11,
    color: DS_COLORS.TEXT_SECONDARY,
    marginTop: 2,
  },
  missedGoBackBtn: {
    backgroundColor: DS_COLORS.WHITE,
    borderRadius: DS_RADIUS.joinCta,
    borderWidth: 1,
    borderColor: DS_COLORS.BORDER,
    paddingVertical: DS_SPACING.md,
    paddingHorizontal: DS_SPACING.xxl,
    alignItems: "center",
    marginTop: DS_SPACING.sm,
  },
  missedGoBackBtnText: {
    color: DS_COLORS.TEXT_SECONDARY,
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
  },
  submitSection: { marginTop: DS_SPACING.xxl, paddingBottom: DS_SPACING.xxl },
  offscreenCapture: {
    position: "absolute",
    left: -9999,
    top: 0,
    width: 1080,
  },
  primaryBtn: {
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: DS_SPACING.lg,
    alignItems: "center",
    ...DS_SHADOWS.button,
  },
  primaryBtnDisabled: { opacity: 0.4 },
  primaryBtnText: { color: DS_COLORS.WHITE, fontSize: 16, fontWeight: "500" },
  pickerLabel: {
    fontSize: 13,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.TEXT_SECONDARY,
    marginBottom: 6,
    marginTop: DS_SPACING.sm,
  },
  runPickerContainer: {
    height: 120,
    backgroundColor: DS_COLORS.BG_CARD_TINTED,
    borderRadius: DS_RADIUS.input,
    overflow: "hidden",
    marginBottom: DS_SPACING.sm,
    position: "relative",
  },
  runPickerHighlightBand: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 40,
    height: 40,
    backgroundColor: DS_COLORS.ACCENT_TINT,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: DS_COLORS.BORDER,
    zIndex: 1,
  },
  runPickerColumns: { flexDirection: "row", height: 120, zIndex: 2 },
  runPickerColumnsSingle: { flexDirection: "row", height: 120, zIndex: 2 },
  paceHint: { fontSize: 13, color: DS_COLORS.TEXT_SECONDARY, marginBottom: DS_SPACING.sm },
  kindChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: DS_RADIUS.XL,
    borderWidth: 1,
    borderColor: DS_COLORS.BORDER,
    backgroundColor: DS_COLORS.WHITE,
  },
  kindChipOn: { borderColor: DS_COLORS.DISCOVER_CORAL, backgroundColor: DS_COLORS.ACCENT_TINT },
  kindChipText: { fontSize: 12, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.TEXT_SECONDARY },
  kindChipTextOn: { color: DS_COLORS.DISCOVER_CORAL },
  secondaryBtn: {
    backgroundColor: DS_COLORS.BORDER,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: DS_SPACING.lg,
    alignItems: "center",
  },
  secondaryBtnText: { color: DS_COLORS.TEXT_PRIMARY, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  successWrap: { flex: 1, padding: DS_SPACING.xl, justifyContent: "center", alignItems: "center" },
  successIconCircle: {
    width: 96,
    height: 96,
    borderRadius: DS_RADIUS.PILL,
    backgroundColor: DS_COLORS.GREEN,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: DS_SPACING.xl,
  },
  successTitle: { fontSize: 20, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.TEXT_PRIMARY },
});

export const celebStyles = StyleSheet.create({
  wrap: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 40,
  },
  fireEmoji: { fontSize: 48, marginBottom: 12 },
  title: { fontSize: 28, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  subtitle: { fontSize: 14, color: DS_COLORS.TEXT_ON_DARK_50, marginTop: 6 },
  rewardPill: {
    marginTop: 16,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: DS_RADIUS.XL,
  },
  rewardText: { fontSize: 13, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD },
  ctaRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 32,
  },
  shareCta: {
    backgroundColor: GRIIT_COLORS.primary,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: DS_RADIUS.joinCta,
  },
  shareCtaText: { fontSize: 15, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS.WHITE },
  nextCta: {
    backgroundColor: DS_COLORS.OVERLAY_WHITE_8,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: DS_RADIUS.joinCta,
  },
  nextCtaText: { fontSize: 15, fontWeight: "500", color: DS_COLORS.TEXT_ON_DARK_60 },
  doneBtn: { marginTop: 20 },
  doneBtnText: {
    fontSize: 14,
    color: DS_COLORS.TEXT_ON_DARK_50,
    fontWeight: "500",
    paddingVertical: 8,
  },
  photoSection: {
    alignSelf: "stretch",
    marginTop: 20,
    marginBottom: 4,
  },
  photoPreview: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: DS_RADIUS.button,
    overflow: "hidden",
    position: "relative",
    backgroundColor: DS_COLORS.OVERLAY_BLACK_30,
  },
  photoImage: {
    width: "100%",
    height: "100%",
  },
  photoChangeBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: DS_COLORS.FEED_GRADIENT_END,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: DS_RADIUS.SM,
  },
  photoChangeBadgeText: {
    fontSize: 11,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.WHITE,
  },
  photoPickerRow: {
    flexDirection: "row",
    gap: 10,
  },
  photoPickerBtn: {
    flex: 1,
    height: 80,
    borderRadius: DS_RADIUS.button,
    borderWidth: 1.5,
    borderColor: DS_COLORS.OVERLAY_WHITE_15,
    borderStyle: "dashed",
    backgroundColor: DS_COLORS.OVERLAY_WHITE_4,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  photoPickerText: {
    fontSize: 11,
    color: DS_COLORS.TEXT_ON_DARK_45,
    fontWeight: "500",
  },
  captionLabel: {
    alignSelf: "stretch",
    fontSize: 12,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.TEXT_ON_DARK_45,
    marginTop: 20,
    marginBottom: 8,
  },
  captionInput: {
    alignSelf: "stretch",
    borderWidth: 1,
    borderColor: DS_COLORS.OVERLAY_WHITE_22,
    borderRadius: DS_RADIUS.button,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: DS_COLORS.WHITE,
    backgroundColor: DS_COLORS.OVERLAY_WHITE_6,
    marginBottom: 12,
  },
  postedOk: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.GREEN, marginBottom: 8 },
  postedErr: { fontSize: 13, color: DS_COLORS.ERROR_RED, marginBottom: 8, textAlign: "center" },
  shareToFeedBtn: {
    alignSelf: "stretch",
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 8,
  },
  shareToFeedText: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.WHITE },
  shareStoriesBtn: {
    marginTop: 10,
    alignSelf: "stretch",
    borderRadius: DS_RADIUS.button,
    borderWidth: 1.5,
    borderColor: DS_COLORS.OVERLAY_WHITE_15,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  shareStoriesBtnText: {
    fontSize: 14,
    fontWeight: "500",
    color: DS_COLORS.TEXT_ON_DARK_60,
  },
  shareCardBtn: {
    marginTop: 12,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: DS_RADIUS.joinCta,
    backgroundColor: DS_COLORS.DISCOVER_CORAL,
    paddingVertical: 16,
  },
  shareCardBtnText: {
    fontSize: 16,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.WHITE,
  },
});
