import { StyleSheet } from "react-native";
import {
  DS_COLORS_V2,
  DS_SPACING,
  DS_RADIUS,
  DS_TYPOGRAPHY,
  DS_BORDERS,
  DS_SHADOWS,
  DS_MEASURES,
} from "@/lib/design-system";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  scroll: { flex: 1 },
  scrollContent: { padding: DS_SPACING.cardPadding, paddingBottom: DS_SPACING.section },
  screenTitle: {
    fontSize: DS_TYPOGRAPHY.SIZE_LG,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS_V2.text.primary,
    marginBottom: DS_SPACING.xs,
  },
  headerSubtitle: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS_V2.text.tertiary, marginBottom: DS_SPACING.md },
  taskMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    marginBottom: DS_SPACING.md,
  },
  pillDay: {
    backgroundColor: DS_COLORS_V2.surface.cardSubtle,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  pillDayText: {
    fontSize: 11,
    fontWeight: "600",
    color: DS_COLORS_V2.text.secondary,
  },
  pillStreak: {
    backgroundColor: DS_COLORS_V2.semantic.warningSoft,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
  },
  pillStreakText: {
    fontSize: 11,
    fontWeight: "600",
    color: DS_COLORS_V2.semantic.warning,
  },
  muted: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS_V2.text.tertiary, marginBottom: DS_SPACING.md },
  mutedCenter: { fontSize: DS_TYPOGRAPHY.SIZE_SM, color: DS_COLORS_V2.text.tertiary, textAlign: "center", marginTop: DS_SPACING.sm },
  card: {
    backgroundColor: DS_COLORS_V2.surface.card,
    borderRadius: DS_RADIUS.card,
    padding: DS_SPACING.lg,
    marginTop: DS_SPACING.lg,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS_V2.surface.divider,
  },
  sectionLabel: { fontSize: 14, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS_V2.text.primary, marginBottom: DS_SPACING.sm },
  journalPromptText: {
    fontSize: 15,
    fontWeight: "500",
    fontStyle: "italic",
    color: DS_COLORS_V2.text.primary,
    marginBottom: 12,
    lineHeight: 22,
  },
  hintSmall: { fontSize: 12, color: DS_COLORS_V2.text.tertiary, marginBottom: DS_SPACING.md },
  warnSmall: { fontSize: 12, color: DS_COLORS_V2.semantic.danger, textAlign: "center", marginTop: DS_SPACING.sm },
  manualPress: { alignItems: "center", paddingVertical: DS_SPACING.xl },
  manualCircle: {
    width: 120,
    height: 120,
    borderRadius: DS_RADIUS.PILL,
    borderWidth: 3,
    borderColor: DS_COLORS_V2.semantic.success,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: DS_COLORS_V2.semantic.successSoft,
  },
  manualHint: { marginTop: DS_SPACING.lg, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.text.primary },
  journalInput: {
    backgroundColor: DS_COLORS_V2.surface.card,
    borderWidth: 1,
    borderColor: DS_COLORS_V2.surface.divider,
    borderRadius: DS_RADIUS.button,
    padding: 16,
    paddingTop: 14,
    fontSize: 15,
    color: DS_COLORS_V2.text.primary,
    minHeight: 200,
    textAlignVertical: "top",
    lineHeight: 22,
  },
  wordCountRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
  wordRing: { flex: 1, height: 4, backgroundColor: DS_COLORS_V2.surface.cardChipNeutral, borderRadius: DS_RADIUS.SM, overflow: "hidden" },
  wordRingFill: { height: "100%", borderRadius: DS_RADIUS.SM },
  wordCountText: { fontSize: 12, color: DS_COLORS_V2.text.tertiary, minWidth: 80, textAlign: "right" },
  wordCount: { fontSize: 12, color: DS_COLORS_V2.text.tertiary, marginTop: DS_SPACING.sm },
  hardModeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: DS_COLORS_V2.brand.primarySoft,
    paddingHorizontal: DS_SPACING.md,
    paddingVertical: 8,
    borderRadius: DS_RADIUS.input / 2,
    marginBottom: DS_SPACING.md,
  },
  hardModeText: { fontSize: 12, color: DS_COLORS_V2.brand.primary, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  timerDisplay: {
    fontSize: 56,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_EXTRABOLD,
    color: DS_COLORS_V2.text.primary,
    fontVariant: ["tabular-nums"],
    textAlign: "center",
  },
  progressBar: {
    height: DS_MEASURES.progressBarHeight,
    backgroundColor: DS_COLORS_V2.surface.divider,
    borderRadius: DS_RADIUS.SM,
    marginTop: DS_SPACING.lg,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: DS_RADIUS.SM },
  timerRow: { flexDirection: "row", justifyContent: "center", marginTop: DS_SPACING.lg },
  secondaryBtnSmall: {
    paddingVertical: DS_SPACING.md,
    paddingHorizontal: DS_SPACING.xxl,
    borderRadius: DS_RADIUS.joinCta,
    backgroundColor: DS_COLORS_V2.surface.cardChipNeutral,
  },
  stravaBtn: {
    marginTop: DS_SPACING.md,
    paddingVertical: DS_SPACING.sm,
    alignItems: "center",
  },
  stravaBtnText: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.text.tertiary },
  stravaNote: {
    marginTop: DS_SPACING.md,
    padding: DS_SPACING.md,
    backgroundColor: DS_COLORS_V2.surface.cardSubtle,
    borderRadius: 10,
    alignItems: "center",
  },
  stravaNoteText: {
    fontSize: 11,
    color: DS_COLORS_V2.text.tertiary,
  },
  hrBox: { alignItems: "center", gap: DS_SPACING.sm },
  hrRow: { flexDirection: "row", justifyContent: "space-around", width: "100%" },
  hrValue: { fontSize: 28, fontWeight: DS_TYPOGRAPHY.WEIGHT_EXTRABOLD, textAlign: "center" },
  locBox: { alignItems: "center", gap: DS_SPACING.sm },
  locStatus: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  locCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: DS_SPACING.sm,
    padding: DS_SPACING.lg,
    borderRadius: DS_RADIUS.card,
    backgroundColor: DS_COLORS_V2.brand.primarySoft,
  },
  locCtaText: { fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.text.primary },
  photoPreview: { width: "100%", height: 200, borderRadius: DS_RADIUS.card, backgroundColor: DS_COLORS_V2.surface.cardSubtle },
  photoBig: {
    minHeight: 160,
    borderRadius: DS_RADIUS.card,
    borderWidth: 2,
    borderColor: DS_COLORS_V2.surface.divider,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: DS_COLORS_V2.surface.cardSubtle,
  },
  photoBigText: { marginTop: DS_SPACING.sm, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.text.secondary },
  photoGrid: {
    flexDirection: "row",
    gap: 8,
  },
  photoGridBtn: {
    flex: 1,
    height: 80,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: DS_COLORS_V2.surface.divider,
    borderStyle: "dashed",
    backgroundColor: DS_COLORS_V2.surface.cardSubtle,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  photoGridLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: DS_COLORS_V2.text.secondary,
  },
  galleryLink: { marginTop: DS_SPACING.md, alignItems: "center" },
  link: { fontSize: DS_TYPOGRAPHY.SIZE_SM, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.brand.primary, marginTop: DS_SPACING.sm },
  textField: {
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS_V2.surface.divider,
    borderRadius: DS_RADIUS.input,
    padding: DS_SPACING.md,
    fontSize: DS_TYPOGRAPHY.SIZE_BASE,
    color: DS_COLORS_V2.text.primary,
    marginBottom: DS_SPACING.sm,
  },
  hardGatesDimmed: { opacity: 0.45 },
  missedWindowCard: {
    backgroundColor: DS_COLORS_V2.difficulty.hard.bg,
    borderRadius: DS_RADIUS.LG,
    padding: DS_SPACING.lg,
    marginTop: DS_SPACING.md,
    borderWidth: 1,
    borderColor: DS_COLORS_V2.difficulty.hard.fg,
    alignItems: "center",
    gap: DS_SPACING.sm,
  },
  missedWindowTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: DS_COLORS_V2.difficulty.hard.fg,
    textAlign: "center",
  },
  missedWindowSub: {
    fontSize: 13,
    fontWeight: "400",
    color: DS_COLORS_V2.text.secondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: DS_SPACING.sm,
  },
  missedRedirectCard: {
    backgroundColor: DS_COLORS_V2.semantic.successSoft,
    borderRadius: 12,
    padding: DS_SPACING.md,
    marginTop: DS_SPACING.lg,
    alignItems: "center",
  },
  missedRedirectTitle: {
    fontSize: 12,
    fontWeight: "500",
    color: DS_COLORS_V2.semantic.success,
  },
  missedRedirectSub: {
    fontSize: 11,
    color: DS_COLORS_V2.text.secondary,
    marginTop: 2,
  },
  missedGoBackBtn: {
    backgroundColor: DS_COLORS_V2.surface.card,
    borderRadius: DS_RADIUS.joinCta,
    borderWidth: 1,
    borderColor: DS_COLORS_V2.surface.divider,
    paddingVertical: DS_SPACING.md,
    paddingHorizontal: DS_SPACING.xxl,
    alignItems: "center",
    marginTop: DS_SPACING.sm,
  },
  missedGoBackBtnText: {
    color: DS_COLORS_V2.text.secondary,
    fontSize: 14,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
  },
  submitSection: { marginTop: DS_SPACING.xxl, paddingBottom: DS_SPACING.xxl },
  minimumDividerWrap: {
    marginTop: DS_SPACING.lg,
    marginBottom: DS_SPACING.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: DS_SPACING.sm,
  },
  minimumDivider: {
    flex: 1,
    height: 1,
    backgroundColor: DS_COLORS_V2.surface.divider,
  },
  minimumDividerText: {
    fontSize: DS_TYPOGRAPHY.SIZE_SM,
    color: DS_COLORS_V2.text.tertiary,
  },
  minimumCopy: {
    fontSize: DS_TYPOGRAPHY.SIZE_SM,
    color: DS_COLORS_V2.text.secondary,
    marginBottom: DS_SPACING.sm,
  },
  offscreenCapture: {
    position: "absolute",
    left: -9999,
    top: 0,
    width: 1080,
  },
  primaryBtn: {
    backgroundColor: DS_COLORS_V2.brand.primary,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: DS_SPACING.lg,
    alignItems: "center",
    ...DS_SHADOWS.button,
  },
  primaryBtnDisabled: { opacity: 0.4 },
  primaryBtnText: { color: DS_COLORS_V2.brand.primaryText, fontSize: 16, fontWeight: "500" },
  pickerLabel: {
    fontSize: 13,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS_V2.text.secondary,
    marginBottom: 6,
    marginTop: DS_SPACING.sm,
  },
  runPickerContainer: {
    height: 120,
    backgroundColor: DS_COLORS_V2.surface.cardSubtle,
    borderRadius: DS_RADIUS.input,
    overflow: "hidden",
    marginBottom: DS_SPACING.sm,
    position: "relative",
  },
  runPickerHighlightBand: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 40,
    height: 40,
    backgroundColor: DS_COLORS_V2.brand.primarySoft,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: DS_COLORS_V2.surface.divider,
    zIndex: 1,
  },
  runPickerColumns: { flexDirection: "row", height: 120, zIndex: 2 },
  runPickerColumnsSingle: { flexDirection: "row", height: 120, zIndex: 2 },
  paceHint: { fontSize: 13, color: DS_COLORS_V2.text.secondary, marginBottom: DS_SPACING.sm },
  kindChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: DS_RADIUS.XL,
    borderWidth: 1,
    borderColor: DS_COLORS_V2.surface.divider,
    backgroundColor: DS_COLORS_V2.surface.card,
  },
  kindChipOn: { borderColor: DS_COLORS_V2.brand.primary, backgroundColor: DS_COLORS_V2.brand.primarySoft },
  kindChipText: { fontSize: 12, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS_V2.text.secondary },
  kindChipTextOn: { color: DS_COLORS_V2.brand.primary },
  secondaryBtn: {
    backgroundColor: DS_COLORS_V2.surface.divider,
    borderRadius: DS_RADIUS.joinCta,
    paddingVertical: DS_SPACING.lg,
    alignItems: "center",
  },
  secondaryBtnText: { color: DS_COLORS_V2.text.primary, fontSize: DS_TYPOGRAPHY.SIZE_MD, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD },
  successWrap: { flex: 1, padding: DS_SPACING.xl, justifyContent: "center", alignItems: "center" },
  successIconCircle: {
    width: 96,
    height: 96,
    borderRadius: DS_RADIUS.PILL,
    backgroundColor: DS_COLORS_V2.semantic.success,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: DS_SPACING.xl,
  },
  successTitle: { fontSize: 20, fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD, color: DS_COLORS_V2.text.primary },
});