import { StyleSheet } from "react-native";
import { DS_COLORS, DS_SPACING, DS_RADIUS, DS_TYPOGRAPHY, DS_BORDERS } from "@/lib/design-system";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: DS_COLORS.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: DS_COLORS.border,
  },
  backBtn: { padding: 4 },
  backBtnCircle: {
    width: 40,
    height: 40,
    borderRadius: DS_RADIUS.XL,
    backgroundColor: DS_COLORS.settingsBackCircle,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
  },
  headerSpacer: { width: 40 },
  scroll: { flex: 1 },
  scrollContent: { padding: DS_SPACING.screenHorizontal },
  section: { marginBottom: DS_SPACING.xxl },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: DS_SPACING.sm,
    marginBottom: DS_SPACING.md,
  },
  sectionTitle: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
  },
  sectionTitleLarge: {
    fontSize: DS_TYPOGRAPHY.sectionTitle.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: DS_SPACING.sm,
  },
  sectionTitleFriends: {
    fontSize: DS_TYPOGRAPHY.cardTitle.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
    marginBottom: DS_SPACING.md,
  },
  privacyDesc: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    marginBottom: DS_SPACING.md,
    lineHeight: 22,
    color: DS_COLORS.textSecondary,
  },
  card: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.cardAlt,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
    padding: DS_SPACING.cardPadding,
  },
  deleteModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: DS_COLORS.MODAL_BACKDROP,
  },
  deleteModalCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: DS_SPACING.screenHorizontal,
  },
  deleteModalCard: { width: "100%", maxWidth: 340 },
  deleteConfirmInput: {
    borderWidth: 1,
    borderRadius: DS_RADIUS.button,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 16,
  },
  deleteConfirmBtn: {
    borderRadius: DS_RADIUS.button,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  deleteConfirmBtnText: { fontSize: 16, fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD, color: DS_COLORS.white },
  deleteCancelBtn: {
    borderWidth: 1,
    borderRadius: DS_RADIUS.button,
    paddingVertical: 12,
    alignItems: "center",
  },
  friendsCard: {},
  friendsTwoCol: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: DS_SPACING.md,
  },
  friendsRow: { flexDirection: "row", marginBottom: DS_SPACING.md },
  friendsCol: { flex: 1, alignItems: "center" },
  friendsColDivider: {
    width: 1,
    height: 40,
    marginHorizontal: DS_SPACING.sm,
  },
  friendsNum: {
    fontSize: DS_TYPOGRAPHY.statValue.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_BOLD,
    color: DS_COLORS.textPrimary,
  },
  friendsLabel: {
    fontSize: DS_TYPOGRAPHY.statLabel.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    letterSpacing: 0.5,
    marginTop: 2,
  },
  friendsDesc: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    lineHeight: 20,
  },
  cardDivider: {
    height: 1,
    marginVertical: DS_SPACING.md,
    backgroundColor: DS_COLORS.border,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  toggleTextWrap: { flex: 1, marginRight: DS_SPACING.md },
  toggleTitle: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: "500",
    color: DS_COLORS.textPrimary,
  },
  toggleSub: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    color: DS_COLORS.textMuted,
    marginTop: 2,
  },
  consequenceCard: { gap: DS_SPACING.lg },
  consequenceRow: { flexDirection: "row", alignItems: "flex-start" },
  consequenceRowBordered: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingTop: DS_SPACING.lg,
    marginTop: DS_SPACING.lg,
    borderTopWidth: 0,
    borderTopColor: "transparent",
  },
  bullet: {
    width: 12,
    height: 12,
    borderRadius: DS_RADIUS.featuredBadge,
    marginTop: 4,
    marginRight: DS_SPACING.md,
  },
  consequenceTextWrap: { flex: 1 },
  consequenceTitle: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
    color: DS_COLORS.textPrimary,
  },
  reminderPill: {
    paddingHorizontal: DS_SPACING.lg,
    paddingVertical: DS_SPACING.sm,
    borderRadius: 999,
  },
  reminderPillActive: {},
  reminderPillText: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    color: DS_COLORS.textSecondary,
  },
  reminderPillTextActive: {
    color: DS_COLORS.white,
    fontWeight: DS_TYPOGRAPHY.WEIGHT_SEMIBOLD,
  },
  consequenceSub: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    color: DS_COLORS.textMuted,
    marginTop: 2,
  },
  bottomSpacer: { height: DS_SPACING.xxxl },
  chevronDisclosure: { position: "absolute", right: 16, top: 18, transform: [{ rotate: "-90deg" }] },
  chevronInline: { transform: [{ rotate: "-90deg" }] },
  reminderPillsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
});
