import { Platform, StyleSheet } from "react-native";
import { DS_COLORS, DS_SPACING, DS_RADIUS, DS_TYPOGRAPHY, DS_BORDERS, DS_MEASURES } from "@/lib/design-system";

export const challengeDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DS_COLORS.background,
  },
  flex: { flex: 1 },
  warningIconInline: { marginRight: 8 },
  scroll: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: DS_SPACING.lg,
  },

  loadingContainer: {
    flex: 1,
    backgroundColor: DS_COLORS.background,
  },
  skeletonHeader: {
    height: 260,
    backgroundColor: DS_COLORS.borderAlt,
  },
  skeletonBody: {
    padding: DS_SPACING.cardPadding,
  },
  skeletonChipRow: {
    flexDirection: "row",
    gap: DS_SPACING.sm,
    marginBottom: DS_SPACING.xxl,
    marginTop: DS_SPACING.lg,
  },
  skeletonChip: {
    width: 80,
    height: 32,
    borderRadius: DS_RADIUS.chip,
    backgroundColor: DS_COLORS.surfaceMuted,
  },
  skeletonBlock: {
    height: 80,
    borderRadius: DS_RADIUS.cardAlt,
    backgroundColor: DS_COLORS.surfaceMuted,
    marginBottom: DS_SPACING.xl,
  },
  skeletonMission: {
    height: 64,
    borderRadius: DS_RADIUS.cardAlt,
    backgroundColor: DS_COLORS.surfaceMuted,
    marginBottom: DS_SPACING.md,
  },

  emptyWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: DS_SPACING.xxxl,
  },
  emptyText: {
    fontSize: DS_TYPOGRAPHY.body.fontSize,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    marginBottom: DS_SPACING.lg,
  },
  emptySubtext: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    marginBottom: DS_SPACING.lg,
    textAlign: "center",
    color: DS_COLORS.textSecondary,
  },
  emptyBtn: {
    paddingHorizontal: DS_SPACING.xxl,
    paddingVertical: DS_SPACING.md,
    backgroundColor: DS_COLORS.accent,
    borderRadius: DS_RADIUS.button,
  },
  emptyBtnText: {
    fontSize: DS_TYPOGRAPHY.buttonSmall.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.white,
  },

  heroHeader: {
    minHeight: 280,
    paddingBottom: DS_SPACING.xxl + DS_SPACING.lg,
    borderBottomLeftRadius: DS_RADIUS.card,
    borderBottomRightRadius: DS_RADIUS.card,
  },
  heroHeader24h: {
    backgroundColor: DS_COLORS.challenge24hHeaderBg,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  heroSafeArea: {
    paddingHorizontal: 20,
  },
  topNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: DS_SPACING.sm,
    marginBottom: DS_SPACING.xxl,
  },
  backPill: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  backPill24h: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  topNavTitle: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.white,
    letterSpacing: 0.5,
  },
  topNavTitle24h: {
    fontSize: 15,
    fontWeight: "400" as const,
  },
  morePill: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroContent: {
    paddingTop: DS_SPACING.xs,
  },
  activeBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(232,89,60,0.2)",
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: 10,
    gap: 6,
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#E8593C",
  },
  activeBadgeText: {
    fontSize: 11,
    fontWeight: "600" as const,
    color: "#E8A87C",
    letterSpacing: 0.5,
  },
  heroEyebrow: {
    fontSize: DS_TYPOGRAPHY.eyebrow.fontSize,
    fontWeight: DS_TYPOGRAPHY.eyebrow.fontWeight,
    letterSpacing: DS_TYPOGRAPHY.eyebrow.letterSpacing,
    color: "rgba(255,255,255,0.85)",
    marginBottom: DS_SPACING.sm,
  },
  dailyLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: DS_SPACING.sm,
  },
  dailyLabelText: {
    fontSize: 11,
    fontWeight: "600" as const,
    color: "rgba(255,255,255,0.9)",
    letterSpacing: 1.5,
    textTransform: "uppercase" as const,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
    letterSpacing: -0.3,
    lineHeight: 34,
    marginBottom: DS_SPACING.sm,
  },
  heroTagline: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 20,
    marginBottom: DS_SPACING.lg,
  },
  referrerLabel: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    fontWeight: "500" as const,
    color: "rgba(255,255,255,0.85)",
    marginBottom: DS_SPACING.sm,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: DS_SPACING.sm,
  },
  visibilityChip: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 5,
  },
  difficultyPill: {
    paddingHorizontal: DS_SPACING.md,
    paddingVertical: DS_SPACING.sm,
    borderRadius: 100,
  },
  difficultyPillText: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    fontWeight: "600" as const,
  },
  infoChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  infoChipText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: "rgba(255,255,255,0.85)",
    letterSpacing: 0.1,
  },
  body: {
    backgroundColor: DS_COLORS.background,
    borderTopLeftRadius: DS_RADIUS.card,
    borderTopRightRadius: DS_RADIUS.card,
    marginTop: -DS_RADIUS.card * 0.5,
    paddingTop: DS_SPACING.xxl,
    paddingHorizontal: 20,
    paddingBottom: DS_SPACING.lg,
    borderWidth: 0,
    shadowColor: DS_COLORS.shadowBlack,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 4,
  },
  socialProofCard: {
    backgroundColor: "#FFFFFF",
    marginTop: -14,
    marginHorizontal: 0,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 14,
  },
  socialProofTitle: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#2B3A2E",
  },
  socialProofSub: {
    fontSize: 11,
    color: "#8B8680",
    marginTop: 2,
  },
  todayGoalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    borderColor: "rgba(232,89,60,0.12)",
    marginBottom: 16,
  },
  dayCounterText: {
    fontSize: 12,
    fontWeight: "600" as const,
    color: "#E8593C",
    marginBottom: 10,
  },
  todayGoalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  todayGoalCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2.5,
    borderColor: "#E8593C",
    alignItems: "center",
    justifyContent: "center",
  },
  todayGoalCircleInner: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(232,89,60,0.08)",
  },
  todayGoalTextWrap: {
    flex: 1,
  },
  todayGoalTitle: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: "#2B3A2E",
  },
  todayGoalSubtitle: {
    fontSize: 12,
    color: "#8B8680",
    marginTop: 2,
  },
  todayGoalArrowWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(232,89,60,0.08)",
  },
  progressSectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  progressTrack: {
    height: 8,
    borderRadius: 6,
    backgroundColor: "#ECEAE4",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 6,
    backgroundColor: "#E8593C",
  },
  progressDotsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: -9,
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ECEAE4",
    borderWidth: 2,
    borderColor: "#D4D1CB",
  },
  progressDotFilled: {
    backgroundColor: "#E8593C",
    borderWidth: 0,
  },
  progressLabelsRow: {
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressLabel: {
    fontSize: 10,
    color: "#A8A49E",
  },
  progressLabelStart: {
    fontSize: 10,
    color: "#E8593C",
    fontWeight: "600" as const,
  },

  countdownCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: DS_COLORS.white,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: DS_SPACING.lg,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  countdownLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: DS_SPACING.sm,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  countdownLabel: {
    fontSize: 15,
    fontWeight: "500" as const,
    color: DS_COLORS.textPrimary,
  },
  countdownValue: {
    fontSize: 24,
    fontWeight: "700" as const,
    fontVariant: ["tabular-nums"] as const,
    letterSpacing: 0.5,
  },

  expiredBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: DS_COLORS.dangerSoft,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  expiredText: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.dangerDark,
  },

  progressSimpleCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  progressSimpleText: {
    fontSize: 13,
  },
  progressSection: {
    marginBottom: DS_SPACING.xl,
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: DS_SPACING.sm,
  },
  sectionLabel: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
  },
  progressValue: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    fontVariant: ["tabular-nums"] as const,
  },
  progressBarBg: {
    height: DS_MEASURES.progressBarHeight,
    borderRadius: DS_RADIUS.input / 2,
    overflow: "hidden" as const,
    marginBottom: DS_SPACING.sm,
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  streakAlert: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 6,
  },
  streakAlertText: {
    fontSize: 13,
    fontWeight: "500" as const,
  },
  failAlert: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 4,
  },
  failAlertText: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: DS_COLORS.dangerDark,
  },
  failCtaWrap: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
    marginBottom: 16,
  },
  failCtaText: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    marginBottom: 12,
  },
  failCtaBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  failCtaBtnText: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: DS_COLORS.white,
  },

  participantStatsCard: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.cardAlt,
    padding: DS_SPACING.cardPadding,
    marginBottom: DS_SPACING.lg,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  statsRowCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS_COLORS.surfaceMuted,
    borderRadius: 14,
    padding: 16,
    marginBottom: DS_SPACING.lg,
    borderWidth: 0,
  },
  statsRowCol: {
    flex: 1,
    alignItems: "center",
  },
  statsRowValue: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: DS_COLORS.accent,
    marginBottom: DS_SPACING.xs,
  },
  statsRowLabel: {
    fontSize: 13,
    fontWeight: "400" as const,
    color: DS_COLORS.textSecondary,
  },
  statsRowDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: DS_COLORS.border,
    marginVertical: DS_SPACING.xs,
  },
  progressStatsCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS_COLORS.white,
    borderRadius: 16,
    padding: DS_SPACING.cardPadding,
    marginBottom: DS_SPACING.lg,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  progressStatItem: {
    flex: 1,
    alignItems: "center",
  },
  progressStatValue: {
    fontSize: 24,
    fontWeight: "800" as const,
    color: DS_COLORS.accent,
    marginBottom: DS_SPACING.xs,
  },
  progressStatLabel: {
    fontSize: DS_TYPOGRAPHY.statLabel.fontSize,
    fontWeight: DS_TYPOGRAPHY.statLabel.fontWeight,
    color: DS_COLORS.textSecondary,
  },
  progressStatDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: DS_COLORS.border,
    marginVertical: DS_SPACING.xs,
  },
  socialRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: DS_SPACING.lg,
  },
  avatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  stackAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: DS_COLORS.white,
  },
  socialTextWrap: {
    flex: 1,
  },
  socialPrimary: {
    fontSize: 15,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    letterSpacing: -0.1,
  },
  socialSecondary: {
    fontSize: 13,
    fontWeight: "400" as const,
    color: DS_COLORS.textSecondary,
    marginTop: DS_SPACING.xs,
  },

  statItem: {
    flex: 1,
    backgroundColor: DS_COLORS.surfaceMuted,
    borderRadius: DS_RADIUS.cardAlt,
    paddingVertical: DS_SPACING.lg,
    paddingHorizontal: DS_SPACING.cardPadding,
    alignItems: "center",
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  statNumber: {
    fontSize: DS_TYPOGRAPHY.statValue.fontSize,
    fontWeight: "800" as const,
    letterSpacing: -0.5,
    marginBottom: DS_SPACING.xs,
  },
  statLabel: {
    fontSize: DS_TYPOGRAPHY.statLabel.fontSize,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center" as const,
  },

  missionsSection: {
    marginBottom: DS_SPACING.xxl,
  },
  sectionTitle: {
    fontSize: DS_TYPOGRAPHY.sectionTitle.fontSize,
    fontWeight: DS_TYPOGRAPHY.sectionTitle.fontWeight,
    color: DS_COLORS.textPrimary,
    letterSpacing: DS_TYPOGRAPHY.sectionTitle.letterSpacing,
    marginBottom: DS_SPACING.md,
  },
  missionsCard: {
    backgroundColor: DS_COLORS.white,
    borderRadius: 16,
    overflow: "hidden" as const,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  missionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: DS_SPACING.cardPadding,
    paddingVertical: DS_SPACING.lg,
    gap: DS_SPACING.lg,
    minHeight: 72,
  },
  missionRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: DS_COLORS.border,
  },
  missionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  missionContent: {
    flex: 1,
  },
  missionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  journalPill: {
    backgroundColor: DS_COLORS.avatarPurple,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  journalPillText: {
    fontSize: 10,
    fontWeight: "600" as const,
    color: DS_COLORS.avatarPurpleText,
  },
  timePill: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 3,
    backgroundColor: "rgba(14,165,233,0.10)",
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  timePillText: {
    fontSize: 10,
    fontWeight: "600" as const,
    color: DS_COLORS.linkBlue,
  },
  proBadge: {
    backgroundColor: DS_COLORS.ACCENT_PRIMARY,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  proBadgeText: {
    fontSize: 10,
    fontWeight: "700" as const,
    color: DS_COLORS.WHITE,
  },
  missionTitle: {
    fontSize: DS_TYPOGRAPHY.cardTitle.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
    letterSpacing: -0.1,
  },
  missionTitleDone: {
    color: DS_COLORS.textSecondary,
    textDecorationLine: "line-through" as const,
  },
  missionMeta: {
    fontSize: DS_TYPOGRAPHY.metadata.fontSize,
    fontWeight: "400" as const,
    color: DS_COLORS.textSecondary,
    marginTop: DS_SPACING.xs,
  },
  missionMetaActive: {
    color: DS_COLORS.emeraldDark,
    fontWeight: "500" as const,
  },
  missionMetaMissed: {
    color: DS_COLORS.dangerMid,
    fontWeight: "500" as const,
  },
  reqChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: DS_SPACING.xs,
    maxWidth: "78%" as const,
  },
  reqChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: DS_COLORS.CARD_ALT_BG,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  reqChipText: {
    fontSize: 10,
    color: DS_COLORS.TEXT_MUTED,
  },
  startAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  startActionText: {
    fontSize: 14,
    fontWeight: "600" as const,
  },
  completedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: DS_COLORS.successSoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  completedBadgeText: {
    fontSize: 12,
    fontWeight: "600" as const,
    color: DS_COLORS.success,
  },

  rulesSection: {
    marginBottom: DS_SPACING.xxl,
  },
  rulesCard: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.cardAlt,
    overflow: "hidden" as const,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  ruleRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: DS_SPACING.cardPadding,
    paddingVertical: DS_SPACING.lg,
    gap: DS_SPACING.md,
  },
  ruleRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: DS_COLORS.border,
  },
  ruleBullet: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: DS_COLORS.successSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  ruleBulletOrange: {
    backgroundColor: DS_COLORS.accentLight,
  },
  ruleBulletWarning: {
    backgroundColor: DS_COLORS.dangerSoft,
  },
  ruleText: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: "500" as const,
    color: DS_COLORS.textPrimary,
    flex: 1,
    lineHeight: DS_TYPOGRAPHY.bodySmall.lineHeight,
  },
  ruleTextWarning: {
    color: DS_COLORS.danger,
    fontWeight: "600" as const,
  },
  aboutSection: {
    marginBottom: DS_SPACING.lg,
  },
  aboutText: {
    fontSize: DS_TYPOGRAPHY.bodySmall.fontSize,
    fontWeight: "400" as const,
    color: DS_COLORS.textSecondary,
    lineHeight: 24,
    letterSpacing: -0.1,
  },
  aboutDetailsCard: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: DS_RADIUS.card,
    padding: DS_SPACING.BASE,
    marginTop: DS_SPACING.BASE,
    borderWidth: DS_BORDERS.width,
    borderColor: DS_COLORS.border,
  },
  aboutDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    gap: DS_SPACING.md,
  },
  aboutDetailRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: DS_COLORS.borderAlt,
  },
  aboutDetailLabel: {
    width: 120,
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
  },
  aboutDetailValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
    textAlign: "right" as const,
  },

  leaveBtn: {
    alignItems: "center",
    paddingVertical: DS_SPACING.md,
    marginBottom: DS_SPACING.sm,
  },
  leaveBtnText: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    fontWeight: "500" as const,
    color: DS_COLORS.danger,
    opacity: 0.9,
  },
  leaveBtnInFlow: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
    paddingVertical: 15,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: "#D4D1CB",
    backgroundColor: "transparent",
    marginTop: 8,
  },
  leaveBtnInFlowText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#8B8680",
  },
  commitCtaInFlow: {
    marginTop: 8,
    minHeight: 56,
    borderRadius: 28,
    backgroundColor: "#E8593C",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 17,
  },
  commitCtaInFlowText: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: "#FFFFFF",
  },
  ctaMicroInFlow: {
    fontSize: 11,
    color: "#A8A49E",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 8,
  },

  stickyFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: DS_SPACING.screenHorizontal,
    paddingTop: DS_SPACING.lg,
    backgroundColor: DS_COLORS.surface,
    borderTopWidth: 1,
    borderTopColor: DS_COLORS.border,
    alignItems: "center",
  },
  ctaButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 52,
    paddingVertical: 14,
    borderRadius: DS_RADIUS.joinCta,
    backgroundColor: DS_COLORS.accent,
    width: Platform.OS === "web" ? 400 : undefined,
    alignSelf: "stretch" as const,
    minWidth: 280,
  },
  ctaText: {
    fontSize: 17,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
  },
  inviteLink: {
    marginTop: DS_SPACING.sm,
    paddingVertical: DS_SPACING.sm,
    minHeight: 44,
    justifyContent: "center",
  },
  inviteLinkText: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.accent,
  },
  ctaMicro: {
    fontSize: 13,
    fontWeight: "400" as const,
    color: DS_COLORS.textSecondary,
    marginTop: DS_SPACING.sm,
    textAlign: "center",
  },
  disabledCta: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: DS_SPACING.lg,
    borderRadius: DS_RADIUS.button,
    backgroundColor: DS_COLORS.chipFill,
    alignSelf: "stretch" as const,
  },
  disabledCtaText: {
    fontSize: DS_TYPOGRAPHY.button.fontSize,
    fontWeight: "600" as const,
    color: DS_COLORS.textMuted,
  },

  commitmentOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  commitmentCenter: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  commitmentCard: {
    backgroundColor: DS_COLORS.BG_PRIMARY,
    borderRadius: 24,
    padding: 24,
    width: "100%",
    maxWidth: 360,
    alignItems: "center",
    borderWidth: 0,
  },
  commitmentClose: {
    position: "absolute",
    top: DS_SPACING.lg,
    right: DS_SPACING.lg,
    zIndex: 1,
    padding: DS_SPACING.xs,
  },
  commitmentCloseText: {
    fontSize: 20,
    color: DS_COLORS.textMuted,
    fontWeight: "600",
  },
  commitmentShieldWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: DS_COLORS.GRAY_CARD_BG,
    alignItems: "center",
    justifyContent: "center",
    marginTop: DS_SPACING.sm,
  },
  commitmentTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: DS_COLORS.textPrimary,
    textAlign: "center",
    marginTop: DS_SPACING.xl,
    paddingHorizontal: DS_SPACING.sm,
  },
  commitmentDetails: {
    width: "100%",
    marginTop: DS_SPACING.xl,
    backgroundColor: DS_COLORS.BG_PRIMARY,
    borderRadius: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  commitmentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: DS_SPACING.lg,
  },
  commitmentRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: DS_COLORS.border,
  },
  commitmentCheckCard: {
    width: "100%",
    marginTop: DS_SPACING.xl,
    backgroundColor: DS_COLORS.surfaceSubtle,
    borderRadius: 12,
    padding: DS_SPACING.cardPadding,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  commitmentCheckCardTitle: {
    fontSize: 11,
    fontWeight: "700" as const,
    color: DS_COLORS.textMuted,
    letterSpacing: 1,
    marginBottom: DS_SPACING.md,
    textTransform: "uppercase" as const,
  },
  commitmentCheckCardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: DS_SPACING.sm,
  },
  commitmentCheckCardLabel: {
    fontSize: 14,
    color: DS_COLORS.textSecondary,
  },
  commitmentCheckCardValue: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textPrimary,
  },
  commitmentLabel: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    color: DS_COLORS.textMuted,
  },
  commitmentValue: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    fontWeight: "600",
    color: DS_COLORS.textPrimary,
    textAlign: "right",
    flex: 1,
    marginLeft: DS_SPACING.lg,
  },
  commitmentWarning: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS_COLORS.ERROR_BG,
    borderRadius: 12,
    padding: DS_SPACING.lg,
    marginTop: DS_SPACING.xl,
    width: "100%",
  },
  commitmentWarningText: {
    fontSize: 14,
    fontWeight: "500",
    color: DS_COLORS.ERROR_RED,
    flex: 1,
  },
  commitmentCheckRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginTop: DS_SPACING.lg,
    gap: 12,
  },
  commitmentCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: DS_COLORS.border,
    alignItems: "center",
    justifyContent: "center",
  },
  commitmentCheckboxChecked: {
    backgroundColor: DS_COLORS.DARK_GREEN_HEADER,
    borderColor: DS_COLORS.DARK_GREEN_HEADER,
  },
  commitmentCheckLabel: {
    fontSize: 14,
    fontWeight: "400",
    color: DS_COLORS.textPrimary,
    flex: 1,
  },
  commitmentConfirmBtn: {
    backgroundColor: DS_COLORS.PRESSED_ORANGE,
    borderRadius: 12,
    paddingVertical: 16,
    minHeight: 50,
    alignItems: "center",
    width: "100%",
    marginTop: DS_SPACING.xl,
  },
  commitmentConfirmDisabled: {
    backgroundColor: DS_COLORS.accent,
    opacity: 0.5,
  },
  commitmentConfirmText: {
    fontSize: DS_TYPOGRAPHY.button.fontSize,
    fontWeight: "700",
    color: DS_COLORS.white,
  },
  commitmentCancelBtn: {
    marginTop: DS_SPACING.lg,
    paddingVertical: DS_SPACING.sm,
  },
  commitmentCancelText: {
    fontSize: DS_TYPOGRAPHY.secondary.fontSize,
    color: DS_COLORS.textMuted,
  },
});
