// Batch 4 generator: Area 1 (onboarding, auth), Area 14 (system), and the full atlas index.
// Runs after v48-gen.js + b2 + b3: new Function(g1+g2+g3+g4+';return {build4, wrapFile};')
function build4(v47) {
  build3(v47);
  NEXT = 701;
  const pReadBtn = btnP('Read 10 pages', { icon:'camera' });
  const FL4 = { hub:'GRIIT v48 Atlas B4.dc.html', onb:'GRIIT v48 Atlas 1 Onboarding.dc.html', sys:'GRIIT v48 Atlas 14 System.dc.html' };
  const B4 = []; const F4 = (k, m, html) => { B4.push(k); return F(k, m, html); };
  // ---------- shared onboarding chrome ----------
  const onbBar = (i, skip) => d('display:flex;align-items:center;height:52px;padding:0 6px;gap:8px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', i>1?ic('cl',22):'') + d('flex:1;display:flex;gap:4px;', [...Array(8)].map((_,k)=>d(`flex:1;height:3px;border-radius:2px;background:${k<i?C.t1:C.raised};`)).join('')) + d('width:56px;height:44px;display:flex;align-items:center;justify-content:center;', skip?tx('h',C.t1,'Skip'):''));
  const onb = (i, title, sub, body, btn, o={}) => phone({ time:o.time||'9:00', body: onbBar(i, o.skip) + d('padding:12px 20px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,title) + (sub?tx('b',C.t2,sub):'') + (body||'')), sticky: btn, stickyH:o.sh||72, overlay:o.overlay, inset:o.inset });
  const optRow = (l, s, on, icon) => d(`display:flex;align-items:center;gap:12px;min-height:56px;padding:0 14px;border-radius:14px;background:${on?C.t1:C.surf};`, (icon?ic(icon,20,on?C.ink:C.t1):'') + d('flex:1;', tx('h',on?C.ink:C.t1,l) + (s?tx('s',on?'#3A3836':C.t2,s):'')) + (on?ic('check',18,C.ink,{sw:3}):''));
  const appleBtn = d(`height:50px;border-radius:999px;background:${C.t1};display:flex;align-items:center;justify-content:center;gap:8px;`, d(`width:16px;height:18px;border-radius:5px 5px 7px 7px;background:${C.ink};`) + sp(T.h+'color:'+C.ink+';', 'Continue with Apple'));
  const googleBtn = btnS('Continue with Google');
  const fieldA = (l, v, o={}) => d('display:flex;flex-direction:column;gap:6px;', tx('c',C.t2,l) + d(`min-height:50px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;gap:8px;${o.focus?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:''}`, tx('b',v?C.t1:C.t2,v||o.ph||'','flex:1;') + (o.right||'')) + (o.note?d('display:flex;align-items:center;gap:6px;', (o.ok?ic('check',14,C.t1,{sw:3}):o.err?ic('alert',14):'') + tx('c',o.err?C.t1:C.t2,o.note)):''));
  const kbT = d(`position:absolute;left:0;right:0;bottom:0;height:300px;z-index:25;background:${C.surf};padding:8px 6px 40px;box-sizing:border-box;display:grid;grid-template-columns:repeat(10,1fr);gap:12px 6px;`, [...Array(30)].map(()=>d(`height:42px;border-radius:8px;background:${C.raised};`)).join(''));

  // ================= AREA 1 · ONBOARDING AND AUTH =================
  CUR = FL4.onb;
  const A1 = [];
  A1.push(F4('splash', { route:'app launch', comp:'Splash', state:'Launch screen', src:'v42', b75:'pending' }, phone({ time:'9:00', body: d('display:flex;align-items:center;justify-content:center;height:700px;', flame(64)) })));
  A1.push(frameWrap('fWelcome',0,1));
  A1.push(F4('whyProof', { route:'onboarding/index', comp:'WhyProof', state:'Real UI, not a paragraph', src:'v42 onboarding', b75:'pending' }, onb(2,'Proof, not promises','A live photo from GRIIT’s camera, or an honest “Self-reported”. Nothing else counts.', d(`background:${C.surf};border-radius:16px;padding:4px 14px;margin-top:8px;`, taskRow({name:'Read 10 pages', gate:[[null,'10 pages'],G.cam], st:'done'}) + taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'done'})) + d('position:relative;width:200px;height:250px;border-radius:16px;overflow:hidden;align-self:center;margin-top:8px;', img('book1') + d('position:absolute;left:10px;top:10px;', seal())), btnP('Continue'))));
  A1.push(F4('whyCircle', { route:'onboarding/index', comp:'WhyCircle', state:'Groups and the feed', src:'v42 onboarding', b75:'pending' }, onb(3,'Do it with people','Invite up to 9 friends into a challenge. Everyone keeps their own streak. Proofs are private until you share them.', d(`background:${C.surf};border-radius:16px;padding:6px 14px;margin-top:8px;`, ['khalid','omar','abd'].map((k,i)=>d('display:flex;align-items:center;gap:12px;min-height:56px;', av(k,36) + tx('h',C.t1,PPL[k][0].split(' ')[0],'flex:1;') + (i<2?doneDot(26):openDot(26)))).join('')), btnP('Continue'))));
  A1.push(F4('goals', { route:'onboarding/index', comp:'Goals', state:'Multi-select', src:'v42 onboarding', b75:'pending' }, onb(4,'What do you want to get consistent at?','Pick any. This picks your first challenge.', d('display:flex;flex-direction:column;gap:8px;', [['Fitness','dumbbell',1],['Faith','moon',0],['Mind','sun',0],['Health','leaf',1],['Discipline','target',1],['Learning','book',1]].map(([l,i,on])=>optRow(l,'',on,i)).join('')), btnP('Continue'), {skip:true})));
  A1.push(F4('dayTarget', { route:'onboarding/index', comp:'DayTarget', state:'Length', src:'v42 onboarding', b75:'pending' }, onb(5,'How long for your first one?','Shorter is fine. Finishing beats starting big.', d('display:flex;flex-direction:column;gap:8px;', [['7 days','A week to prove it to yourself',0],['14 days','Two weeks',0],['30 days','A month. Most people pick this.',1],['75 days','Long haul',0]].map(([a,b,on])=>optRow(a,b,on)).join('')), btnP('Continue'))));
  const pick = (k, sub, st) => d(`display:flex;align-items:center;gap:12px;padding:10px;border-radius:16px;background:${st==='sel'?C.t1:C.surf};`, cover(k,48,60,{r:10}) + d('flex:1;', tx('h',st==='sel'?C.ink:C.t1,CH[k][0]) + tx('s',st==='sel'?'#3A3836':C.t2,sub)) + (st==='sel'?ic('check',18,C.ink,{sw:3}):st==='joined'?d('display:flex;align-items:center;gap:4px;', ic('check',14,C.t1,{sw:3}) + tx('c',C.t1,'Joined')):''));
  const fcBody = (st) => tx('s',C.t2,'From your goals. Day 1 is today.') + pick('read','30 days · Read 10 pages · Camera', st) + pick('hyd','30 days · Drink 3 L · Self-reported','') + pick('show','7 days · Gym check-in · Location','') + btnT('Browse all');
  A1.push(F4('fcDefault', { route:'onboarding/index', comp:'FirstChallenge', state:'Pick card default', src:'v42 onboarding', b75:'pending' }, onb(6,'Pick your first challenge','', fcBody(''), btnP('Start a challenge',{off:true}))));
  A1.push(frameWrap('fFirst',0,1));
  A1.push(F4('fcJoined', { route:'onboarding/index', comp:'FirstChallenge', state:'Joined (after tap, before Next)', src:'v42 onboarding', b75:'pending' }, onb(6,'Pick your first challenge','', fcBody('joined'), btnP('Next'))));
  A1.push(F4('fcBrowse', { route:'onboarding/index', comp:'BrowseAllPicker', state:'Sheet, by category', src:'v42', b75:'pending' }, onb(6,'Pick your first challenge','', fcBody(''), btnP('Start a challenge',{off:true}), { overlay: sheet(tx('t',C.t1,'All challenges') + d('display:flex;gap:8px;overflow:hidden;', ['All','Fitness','Faith','Mind','Health'].map((c,i)=>chip(c,i===0)).join('')) + ['read','fajr','hyd','up5','show','run'].map(k=>chRow(k)).join(''), { h:700 }) })));
  const remHero = d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:flex;gap:10px;margin-top:6px;`, d(`width:38px;height:38px;border-radius:9px;background:${C.ink};display:flex;align-items:center;justify-content:center;flex:none;`, flame(22)) + d('flex:1;', d('display:flex;justify-content:space-between;', tx('h',C.t1,'GRIIT') + tx('c',C.t2,'8:00 pm')) + tx('b',C.t1,'Read 10 pages is still open today.')));
  A1.push(F4('remPre', { route:'onboarding/index', comp:'Reminders', state:'Pre-prompt, one Continue', src:'v42 onboarding', b75:'pending' }, onb(7,'One reminder, when it matters','Only when a task is still open. At most 3 a day, never with an exclamation mark.', remHero, btnP('Continue') + btnT('Not now'), {skip:false, sh:116})));
  A1.push(F4('remIOS', { route:'onboarding/index', comp:'Reminders', state:'iOS alert (context)', src:'iOS', b75:'pending' }, onb(7,'One reminder, when it matters','Only when a task is still open. At most 3 a day, never with an exclamation mark.', remHero, btnP('Continue') + btnT('Not now'), { sh:116, overlay: d(`position:absolute;inset:0;z-index:30;background:rgba(0,0,0,0.55);display:flex;align-items:center;justify-content:center;`, d(`width:270px;border-radius:14px;background:#2C2C2E;overflow:hidden;text-align:center;`, d('padding:18px 16px 14px;', tx('h',C.t1,'“GRIIT” Would Like to Send You Notifications') + tx('s',C.t1,'Notifications may include alerts, sounds and icon badges.','margin-top:4px;')) + d('display:flex;border-top:1px solid #3A3A3C;', d('flex:1;height:44px;display:flex;align-items:center;justify-content:center;font-size:17px;color:#0A84FF;border-right:1px solid #3A3A3C;', 'Don’t Allow') + d('flex:1;height:44px;display:flex;align-items:center;justify-content:center;font-size:17px;font-weight:600;color:#0A84FF;', 'Allow')))) })));
  A1.push(F4('remDenied', { route:'onboarding/index', comp:'Reminders', state:'Denied', src:'new', b75:'not built' }, onb(7,'Reminders are off','You can still use GRIIT. Turn them on in Settings if a window ever slips past you.', '', btnS('Open Settings') + btnP('Continue'), { sh:120 })));
  A1.push(F4('accChoose', { route:'onboarding/index', comp:'Account', state:'Save your progress (delayed sign-up) · 13+ check', src:'v42 onboarding', b75:'pending' }, onb(8,'Save your streak','Your first day is on this phone. An account keeps it if you switch phones.', d('display:flex;flex-direction:column;gap:10px;margin-top:8px;', appleBtn + googleBtn + btnS('Continue with email')) + d('display:flex;align-items:center;gap:10px;min-height:44px;', d(`width:22px;height:22px;border-radius:6px;background:${C.t1};display:flex;align-items:center;justify-content:center;flex:none;`, ic('check',14,C.ink,{sw:3})) + tx('b',C.t1,'I’m 13 or older')) + tx('c',C.t2,'By continuing you agree to the Terms and Privacy Policy. Google shows only if it already works in the build; otherwise Apple and email.','text-align:center;'), btnT('I already have an account'), { sh:68 })));
  A1.push(F4('accEmail', { route:'onboarding/index', comp:'Account', state:'Email · field errors', src:'v33', b75:'pending' }, phone({ time:'9:06', body: onbBar(8) + d('padding:12px 20px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'Create your account') + fieldA('Email','yaseen@hey',{focus:true, err:true, note:'That email looks incomplete.'}) + fieldA('Password','••••',{err:true, note:'Use at least 8 characters.'}) + d('display:flex;align-items:center;gap:10px;min-height:44px;', d(`width:22px;height:22px;border-radius:6px;background:${C.t1};display:flex;align-items:center;justify-content:center;flex:none;`, ic('check',14,C.ink,{sw:3})) + tx('b',C.t1,'I’m 13 or older'))) + d('position:absolute;left:16px;right:16px;bottom:318px;z-index:26;', btnP('Create account',{off:true})), overlay: kbT })));
  A1.push(F4('accLoading', { route:'onboarding/index', comp:'Account', state:'Loading (in-button)', src:'v33', b75:'pending' }, phone({ time:'9:07', body: onbBar(8) + d('padding:12px 20px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'Create your account') + fieldA('Email','yaseen@hey.com',{ok:true}) + fieldA('Password','••••••••••',{ok:true})), sticky: btnP('Creating account',{spin:true}), stickyH:72 })));
  const unameBody = (v, note, st) => tx('s',C.t2,'How people find you.') + fieldA('Username','@'+v,{focus:true, ok:st==='ok', err:st==='err', note, right: st==='saving'?spin(14):st==='ok'?ic('check',16,C.t1,{sw:3}):st==='err'?ic('alert',16):''}) + fieldA('Name','Yaseen Abdelaziz') + d(`display:flex;align-items:center;gap:8px;padding:10px 12px;border-radius:12px;background:${C.surf};`, ic('users',16,C.t2) + tx('s',C.t2,'Accounts are public by default. Proofs stay private until you share them. Change it in Settings, Privacy.'));
  A1.push(F4('unOk', { route:'onboarding/index', comp:'Profile', state:'Username available', src:'v42 onboarding', b75:'pending' }, onb(8,'Pick a username','', unameBody('yaseen','Available.','ok'), btnP('Finish'))));
  A1.push(F4('unTaken', { route:'onboarding/index', comp:'Profile', state:'Taken', src:'v42 onboarding', b75:'pending' }, onb(8,'Pick a username','', unameBody('khalid','@khalid is taken. Try khalid.n or khalid5.','err'), btnP('Finish',{off:true}))));
  A1.push(F4('unInvalid', { route:'onboarding/index', comp:'Profile', state:'Invalid', src:'v42 onboarding', b75:'pending' }, onb(8,'Pick a username','', unameBody('yaseen!!','Letters, numbers, dots and underscores. 3 to 20 characters.','err'), btnP('Finish',{off:true}))));
  A1.push(F4('unSaving', { route:'onboarding/index', comp:'Profile', state:'Saving', src:'v42 onboarding', b75:'pending' }, onb(8,'Pick a username','', unameBody('yaseen','Checking…','saving'), btnP('Saving',{spin:true}))));
  const authPage = (title, inner, btns, o={}) => phone({ time:o.time||'9:10', body: stepHead('','',{back:true}) + d('padding:4px 20px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,title) + inner), sticky: btns, stickyH:o.sh||116, overlay:o.overlay, toast:o.toast });
  A1.push(F4('login', { route:'auth/login', comp:'SignIn', state:'Default · Sign in disabled until both fields', src:'v33 74', b75:'pending' }, authPage('Welcome back', appleBtn + googleBtn + d('display:flex;align-items:center;gap:10px;', d(`flex:1;height:1px;background:${C.raised};`) + tx('c',C.t2,'or') + d(`flex:1;height:1px;background:${C.raised};`)) + fieldA('Email','yaseen@hey.com') + fieldA('Password','',{ph:'Password', right: tx('c',C.t2,'Show')}) + d('display:flex;justify-content:flex-end;', btnT('Forgot password?')), btnP('Sign in',{off:true}) + btnT('New here? Create an account'))));
  A1.push(F4('loginErr', { route:'auth/login', comp:'SignIn', state:'Wrong password', src:'v33', b75:'pending' }, authPage('Welcome back', fieldA('Email','yaseen@hey.com') + fieldA('Password','•••••••••',{err:true, note:'That password doesn’t match. Try again or reset it.', right: tx('c',C.t2,'Show')}) + d('display:flex;justify-content:flex-end;', btnT('Forgot password?')), btnP('Sign in') + btnT('New here? Create an account'))));
  A1.push(F4('signup', { route:'auth/signup', comp:'SignUp', state:'Email sign-up (from “I have no account”)', src:'v33', b75:'pending' }, authPage('Create your account', appleBtn + googleBtn + fieldA('Email','',{ph:'you@example.com'}) + fieldA('Password','',{ph:'At least 8 characters'}), btnP('Create account',{off:true}) + btnT('I already have an account'))));
  A1.push(F4('forgot', { route:'auth/forgot-password', comp:'ForgotPassword', state:'Enter email', src:'v33', b75:'pending' }, authPage('Reset your password', tx('b',C.t2,'We’ll email you a link. It works for an hour.') + fieldA('Email','yaseen@hey.com',{focus:true}), btnP('Send link'), { sh:72 })));
  A1.push(F4('forgotSent', { route:'auth/forgot-password', comp:'ForgotPassword', state:'Sent · resend locked 60 s', src:'v33', b75:'pending', fields:'resend_available_at = sent_at + 60s (client timer)' }, authPage('Check your email', tx('b',C.t2,'We sent a link to yaseen@hey.com. It works for an hour. Check spam if it isn’t there.') + btnS('Open Mail'), btnS('Resend in 0:42').replace(`background:${C.raised}`, `background:${C.raised};opacity:0.5`) + btnT('Use a different email'))));
  A1.push(F4('reset', { route:'auth/reset-password', comp:'ResetPassword', state:'New password', src:'v33', b75:'pending' }, authPage('Set a new password', fieldA('New password','••••••••••',{focus:true, ok:true, note:'Strong enough.'}) + fieldA('Confirm','••••••••••',{ok:true, note:'Matches.'}), btnP('Save and sign in'), { sh:72 })));
  A1.push(F4('resetExpired', { route:'auth/reset-password', comp:'ResetPassword', state:'Link expired', src:'new', b75:'pending' }, authPage('This link expired', tx('b',C.t2,'Reset links work for an hour. Send a new one.'), btnP('Send a new link') + btnT('Back to sign in'))));
  A1.push(F4('createProfile', { route:'create-profile', comp:'CreateProfile (legacy)', state:'Retire: merged into onboarding Profile', src:'legacy', b75:'retire' }, phone({ time:'9:12', body: d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:220px 32px 0;text-align:center;', d(`height:28px;padding:0 12px;border-radius:999px;box-shadow:inset 0 0 0 1.5px ${C.t1};display:flex;align-items:center;${T.c}color:${C.t1};`, 'RETIRE') + tx('t',C.t1,'create-profile') + tx('b',C.t2,'Duplicates onboarding Profile (frames above). Old links redirect to onboarding/index at the Profile step.')) })));
  A1.push(F4('authGate', { route:'(any)', comp:'AuthGateModal', state:'Guest tries to share or follow', src:'v42', b75:'pending' }, phone({ time:'9:30', tab:'home', body: home({ streak:1, week:['pre','pre','pre','pre','pre','pre','todayDone'], line:'Day secured. Come back tomorrow.', primary:btnS('Share today',{icon:'share'}), sections:[{...secRead('done'), day:'Day 1 of 30', collapsed:true}], feed:'' }), overlay: sheet(tx('t',C.t1,'Save your streak first') + tx('b',C.t2,'Sharing and following need an account, so your proofs aren’t lost if you change phones.') + appleBtn + btnS('Continue with email') + btnT('Not now')) })));
  A1.push(F4('sessionExp', { route:'(any)', comp:'SessionExpiredBanner', state:'Signed out remotely', src:'new', b75:'pending' }, phone({ time:'9:31', tab:'home', body: d(`margin:6px 16px 0;background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, ic('alert',18) + tx('s',C.t1,'You were signed out. Sign in to keep posting.','flex:1;') + smallBtn('Sign in',true)) + home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today.', primary:btnP('Read 10 pages',{icon:'camera',off:true}), sections:[secRead('open'), secBed('done')], feed:'' }) })));

  // ================= AREA 14 · SYSTEM =================
  CUR = FL4.sys;
  const A14 = [];
  A14.push(F4('sysOffline', { route:'(any)', comp:'OfflineBanner', state:'Offline on a pushed screen', src:'v47 204', b75:'not built' }, phone({ time:'7:41', body: stepHead('Read 30','',{back:true}) + d(`margin:0 16px;display:flex;align-items:center;gap:8px;padding:10px 12px;border-radius:12px;background:${C.surf};`, ic('wifioff',16,C.t2) + tx('s',C.t2,'Offline. Showing what was saved at 7:38 am.')) + d('padding:12px 16px;', strip(W_B,{prog:0.5})) })));
  A14.push(F4('sysError', { route:'(any)', comp:'ErrorState', state:'Generic error with retry', src:'v12 11', b75:'pending' }, phone({ time:'7:42', body: stepHead('Read 30','',{back:true}) + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:200px 32px 0;text-align:center;', ic('alert',28,C.t2) + tx('t',C.t1,'This didn’t load') + tx('b',C.t2,'Your streak and proofs are safe. Try again in a moment.') + d('height:6px') + btnS('Try again',{icon:'retry'})) })));
  A14.push(frameWrap('notFound',0,1));
  A14.push(F4('sysForce', { route:'(launch)', comp:'ForceUpdate', state:'Blocking update', src:'new', b75:'not built', fields:'min_supported_build from remote config' }, phone({ time:'9:00', body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:240px 32px 0;text-align:center;', flame(44) + tx('t',C.t1,'Update GRIIT to keep going') + tx('b',C.t2,'This version can’t save proofs anymore. Your streak is safe; it’s waiting in the new version.')), sticky: btnP('Open the App Store'), stickyH:72 })));
  A14.push(F4('sysConfirm', { route:'(any)', comp:'ConfirmDialog', state:'Destructive confirm', src:'v28', b75:'pending' }, phone({ time:'9:01', body: stepHead('Settings','',{back:true}), overlay: dialog('Log out?','You’ll need to sign in again. Proofs not yet uploaded stay on this phone until you do.', d('display:flex;gap:8px;', btnS('Cancel',{flex:1}) + btnS('Log out',{flex:1}))) })));
  const toastS = (i, t, act) => d(`background:${C.raised};border-radius:14px;padding:${act?'6px 6px 6px 14px':'12px 14px'};display:flex;align-items:center;gap:10px;`, ic(i,18) + tx('s',C.t1,t,'flex:1;') + (act?btnT(act):''));
  A14.push(F4('sysToasts', { route:'(any)', comp:'Toast / Snackbar', state:'Specimen: 4 kinds', src:'v47', b75:'pending' }, phone({ time:'9:02', tab:'home', body: d('padding:12px 16px;display:flex;flex-direction:column;gap:10px;', tx('l',C.t2,'Toast · 3 s, no action') + toastS('ccheck','Saved to Photos.') + tx('l',C.t2,'Snackbar · 6 s, one action') + toastS('ban','Khalid is blocked.','Undo') + tx('l',C.t2,'Error · stays until dismissed') + toastS('alert','Didn’t save. Your changes are still here.','Retry') + tx('l',C.t2,'Task done · Area 3, with the share choice') + tx('s',C.t2,'Toasts sit 12pt above the tab bar (95pt from the bottom), or 12pt above the home indicator where there’s no tab bar. One at a time; a new one replaces the old.')) })));
  A14.push(F4('sysPull', { route:'(tabs)/index', comp:'PullToRefresh', state:'Pulling', src:'new', b75:'pending' }, phone({ time:'9:03', tab:'home', body: d('display:flex;justify-content:center;padding:14px 0;', spin(20)) + home({ streak:7, week:W_B, prog:0.5, line:'1 of 2 left today.', primary:pReadBtn, sections:[secRead('open'), secBed('done')], feed:'' }) })));
  A14.push(panel(393, tx('l',C.t2,'Loading rules') + [['Under 1 s','Show nothing. No skeleton flash.'],['Full page','Skeleton outlines (hairline, no grey fills), shown after 1 s.'],['One module','A 16pt spinner in that module only.'],['Saving','In the button first; a full-screen takeover only past 800 ms.'],['Images','Surface fill, then the photo. A failed photo shows the designed tile with the task name.']].map(([a,b])=>d('display:grid;grid-template-columns:96px 1fr;gap:10px;', tx('h',C.t1,a) + tx('s',C.t2,b))).join('')));
  const push = (title, body, sub, time) => d(`border-radius:20px;background:rgba(36,35,34,0.9);padding:12px 14px;display:flex;gap:10px;`, d(`width:38px;height:38px;border-radius:9px;background:${C.ink};display:flex;align-items:center;justify-content:center;flex:none;`, flame(22)) + d('flex:1;min-width:0;', d('display:flex;justify-content:space-between;', tx('h',C.t1,'GRIIT') + tx('c',C.t2,time)) + tx('b',C.t1,body) + (sub?tx('s',C.t2,sub):'')));
  const pushes = [['Reminder','Out of bed closes at 5:30 am.','Up by 5 · 22 minutes left','5:08 am'],['Streak at risk','Your 7-day streak is at risk. Read 10 pages is left today.','','8:00 pm'],['Respected','Khalid respected your proof.','Read 10 pages','now'],['Commented','Khalid commented: “Which edition?”','','now'],['Followed','Hamza started following you.','','1h'],['Nudged','Abdurrahman: 10 minutes left.','Up by 5 · Out of bed','5:20 am'],['Group invite','Khalid invited you to Gym 14.','Tap to see it','6:05 am'],['Joined your group','Bilal joined Up by 5.','5 of 10','9:30 am'],['Finished','Khalid finished Up by 5. 7 of 7 days.','','7:02 am']];
  A14.push(F4('sysPushes', { route:'lock screen', comp:'Push previews', state:'Every push type', src:'v45 181', b75:'pending' }, phone({ time:'9:41', onPhoto:true, full: d('position:absolute;inset:0;background:linear-gradient(180deg,#1B2430,#0F0F0F);') + d('position:absolute;left:0;right:0;top:66px;text-align:center;font-size:64px;line-height:1;font-weight:600;color:'+C.t1+';', '9:41') + d('position:absolute;left:10px;right:10px;top:150px;display:flex;flex-direction:column;gap:8px;', pushes.slice(0,6).map(p=>push(...p)).join('')) })));
  A14.push(panel(393, tx('l',C.t2,'Push rules') + tx('s',C.t1,'At most 3 a day per person, reminders included. Quiet hours hold them until morning.') + tx('s',C.t1,'Factual, no exclamation marks, no emoji. The task or challenge name is always in the body or subtitle.') + pushes.slice(6).map(p=>push(...p)).join('')));
  A14.push(F4('sysIcon', { route:'springboard', comp:'App icon', state:'Home screen and launch', src:'v42', b75:'pending' }, phone({ time:'9:41', onPhoto:true, full: d('position:absolute;inset:0;background:linear-gradient(180deg,#26303C,#121416);') + d('position:absolute;left:24px;right:24px;top:90px;display:grid;grid-template-columns:repeat(4,1fr);gap:26px 0;justify-items:center;', [...Array(16)].map((_,i)=>d('display:flex;flex-direction:column;align-items:center;gap:6px;', i===5?d(`width:62px;height:62px;border-radius:15px;background:${C.ink};display:flex;align-items:center;justify-content:center;box-shadow:0 0 0 1px #2A2928;`, flame(36)) + tx('c',C.t1,'GRIIT'):d('width:62px;height:62px;border-radius:15px;background:rgba(242,240,235,0.12);') + d('width:40px;height:10px;border-radius:4px;background:rgba(242,240,235,0.12);'))).join('')) })));

  // ================= hub · full index =================
  const RET = [['create-challenge','legacy wizard','Retire: replaced by create/index (CreateWizardV2). Redirect.'],['(tabs)/teams','hidden placeholder','Retire: groups live on challenges. Remove the hidden tab.'],['JeopardyModal','streak-at-risk modal','Retired: the 8:00 pm push and the strip cover it.'],['create-profile','legacy profile step','Retire: merged into onboarding Profile (frame ' + REG.createProfile.n + ').'],['Global board','leaderboard scope','Not shipping (decision 206).']];
  const all = ORDER.filter(k => REG[k].n >= 301);
  all.sort((a,b)=>REG[a].n-REG[b].n);
  const batchOf = (n) => n>=701?'4':n>=601?'3':n>=501?'2':'1R';
  const counts = { '1R':0,'2':0,'3':0,'4':0 }; const b75 = {}; all.forEach(k=>{ counts[batchOf(REG[k].n)]++; const v = (REG[k].b75||'pending').split(' ')[0]; b75[v]=(b75[v]||0)+1; });
  const summary = d('display:flex;gap:12px;flex-wrap:wrap;', [['Frames', all.length],['Batch 1R',counts['1R']],['Batch 2',counts['2']],['Batch 3',counts['3']],['Batch 4',counts['4']],['Not built', b75['not']||0],['Differs', b75['differs']||0],['Retire', b75['retire']||0]].map(([l,n])=>d(`background:${C.surf};border-radius:14px;padding:12px 16px;display:flex;flex-direction:column;min-width:110px;`, sp(NUM+'font-size:28px;color:'+C.t1+';', n) + tx('c',C.t2,l))).join(''));
  const rows = all.map(k=>{ const f = REG[k]; return [`<a href="${href(k)}" style="color:${C.t1};">${f.n}</a>`, batchOf(f.n), f.route, f.comp, f.state, f.src||'new', f.b75||'pending']; });
  const idxAll = `<div id="indexAll" data-screen-label="Full atlas index" style="display:flex;flex-direction:column;gap:14px;">` + stripHead(`The atlas index · every frame, batches 1R–4 (${all.length})`, 'Frame · batch · route · component · state · source frame · built in 75. Every number links to its frame. “pending” = in code, not yet compared against build 75 screenshots (not in the project).') + summary +
    panel(1500, `<div style="display:grid;grid-template-columns:56px 44px 200px 230px 1fr 150px 230px;max-width:1460px;">` + [['#','Batch','Route','Component','State','Source','Built in 75']].concat(rows).map((r,ri)=>r.map((c,i)=>d(`${ri===0?T.c+'color:'+C.t2+';':(i===0?T.h:T.s)+'color:'+C.t1+';'}padding:8px 12px 8px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>') + '</div>';
  const retire = `<div style="display:flex;flex-direction:column;gap:12px;">` + stripHead('Retire list') + panel(1100, RET.map(([a,b,c])=>d('display:grid;grid-template-columns:200px 200px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b) + tx('s',C.t1,c))).join('')) + '</div>';
  const nav = d('display:flex;flex-wrap:wrap;gap:8px;', [[FL4.hub,'Batch 4 overview · full index'],[FL4.onb,'Area 1 Onboarding and auth'],[FL4.sys,'Area 14 System'],[FL.hub,'Batch 1R'],['GRIIT v48 Atlas B2.dc.html','Batch 2'],['GRIIT v48 Atlas B3.dc.html','Batch 3']].map(([h,l])=>`<a href="${encodeURI(h)}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">${l}</a>`).join(''));
  const intro4 = d('display:flex;flex-direction:column;gap:14px;max-width:1100px;', tx('l',C.t2,'GRIIT v48 · Atlas · Batch 4 of 4') + d(T.tl+'font-size:40px;line-height:46px;color:'+C.t1+';', 'Onboarding, auth, system, and the index') + tx('b',C.t2,'Area 1 and Area 14, then every frame from batches 1R–4 in one index. Batch 3 decisions applied: no Global board; reports email the founder; contact griit.health@gmail.com; paywall benefits corrected.') + nav);
  const changes4 = `<div style="display:flex;gap:24px;flex-wrap:wrap;align-items:flex-start;">` + panel(640, tx('l',C.t2,'What changed and why') + [
    ['Delayed sign-up','Welcome → WhyProof → WhyCircle → Goals → DayTarget → FirstChallenge → Reminders → Account → Profile. Account comes after the first challenge so day one isn’t gated.'],
    ['Real UI as illustration','WhyProof and WhyCircle use the actual task rows, seal and roster, not paragraphs.'],
    ['Honest permission prompts','One “Continue” before the iOS alert, a designed denied state, and a skip that works.'],
    ['Auth','Apple first, then Google and email. Inline field errors, in-button loading, the 60 s resend lock, an expired-link state.'],
    ['System','Offline, error, not found, force update, confirm, toasts, pull to refresh, loading rules, every push on the lock screen, splash and icon.'],
    ['Index','Every frame across the four batches, linked, with source and Built in 75. A retire list closes out legacy routes.'] ].map(([a,b])=>d('display:grid;grid-template-columns:150px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) +
    panel(420, tx('l',C.t2,'Self-score') + d('display:flex;align-items:baseline;gap:8px;', sp(NUM+'font-size:56px;line-height:60px;color:'+C.t1+';','8.8') + tx('t',C.t2,'/ 10')) + tx('s',C.t2,'Short of 9 for the same reason as every batch: no build 75 screenshots in the project, so the Built in 75 column is unverified. Once they’re uploaded, one pass fills it.','text-wrap:pretty;')) + '</div>';
  const CON4 = [['212 Google sign-in','Decided: ships only if it already works; otherwise Apple and email.'],['213 Guest limits','Decided: accepted. Engineering confirms guest proofs merge on sign-up.'],['214 Minimum age','Decided: “I’m 13 or older” checkbox on the Account step, required to continue.'],['215 Force update','Decided: accepted. Needs remote config min_supported_build.'],['194 Offline posting','Still flagged for engineering.']];
  const contra4 = `<div style="display:flex;flex-direction:column;gap:12px;">` + stripHead('Contradictions and flags, batch 4') + panel(1100, CON4.map(([a,b])=>d('display:grid;grid-template-columns:260px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) + '</div>';
  const sec = (id, eyebrow, title, purpose, note, body) => `<div style="display:flex;flex-direction:column;gap:22px;">` + areaHead(id, eyebrow, title, purpose, note) + body + '</div>';
  const wrapDoc = (parts) => `<div style="filter:{{ filt }};font-family:${FONT};color:${C.t1};padding:48px;display:flex;flex-direction:column;gap:80px;background:${C.ink};">` + parts.join('\n') + '</div>';
  return {
    [FL4.hub]: wrapDoc([intro4, changes4, contra4, retire, idxAll]),
    [FL4.onb]: wrapDoc([intro4, sec('a1','Area 1 · Onboarding and auth','Onboarding and auth','Onboarding is for reaching a first secured day. Within 3 seconds: what GRIIT asks of me, and the one next step.','Eight-segment progress, no step numbers. Skip only where it’s truly optional. The user owns nothing yet, so no earned numbers until the first secured day.', wrapRow(A1))]),
    [FL4.sys]: wrapDoc([intro4, sec('a14','Area 14 · System','System states','System states are for when something goes wrong or arrives from outside. Within 3 seconds: what happened, whether anything was lost, and what to do.','Every state says your streak and proofs are safe when they are.', wrapRow(A14))]),
  };
}
