// Batch 3 generator. Runs after v48-gen.js + v48-gen-b2.js: new Function(g1+g2+g3+';return {build3, wrapFile};')
Object.assign(CH, { wake:['Wake up at 5 every day','Discipline',30,'Out of bed · 4:30–5:30 am'] });
const swt = (on, dis) => d(`width:51px;height:31px;border-radius:999px;flex:none;position:relative;background:${on?C.t1:C.raised};${dis?'opacity:0.4;':''}`, d(`position:absolute;top:2px;${on?'right:2px':'left:2px'};width:27px;height:27px;border-radius:999px;background:${on?C.ink:C.t2};`));
const grp = (rows) => d(`background:${C.surf};border-radius:16px;overflow:hidden;`, rows.map((r,i)=>d(`display:flex;align-items:center;gap:12px;min-height:52px;padding:0 14px;${i?`border-top:1px solid ${C.ink};`:''}`, (r.i?ic(r.i,20,C.t1):'') + d('flex:1;min-width:0;padding:8px 0;', tx('b',C.t1,r.l) + (r.s?tx('c',C.t2,r.s):'')) + (r.v?tx('s',C.t2,r.v,'text-align:right;'):'') + (r.sw!==undefined?swt(r.sw,r.dis):r.btn?r.btn:r.nochev?'':ic('cr',16,C.t2)))).join(''));
const lab = (t) => tx('l',C.t2,t,'padding:6px 4px 0;');
const page = (title, inner, o={}) => stepHead(title, o.sub||'', {back:o.back!==false, right:o.right}) + d('padding:8px 16px 24px;display:flex;flex-direction:column;gap:12px;', inner);
const nrow = (k, html, time, o={}) => d(`display:flex;align-items:flex-start;gap:12px;padding:10px 16px;min-height:60px;`, d(`width:8px;height:8px;border-radius:999px;margin-top:16px;flex:none;background:${o.unread?C.t1:'transparent'};`) + (k==='sys'?d(`width:40px;height:40px;border-radius:999px;background:${C.raised};display:flex;align-items:center;justify-content:center;flex:none;`, o.icon||flame(20)):av(k,40)) +
  d('flex:1;min-width:0;display:flex;flex-direction:column;gap:6px;', d(T.b+'color:'+C.t1+';', html + sp(T.s+'color:'+C.t2+';', ' · ' + time)) + (o.below||'')) + (o.thumb?d('width:44px;height:55px;border-radius:8px;overflow:hidden;flex:none;', img(o.thumb)):''));
const B = (n) => sp(T.h, n);
const actHead = (sel) => rootHead('Activity') + d('padding:6px 16px 4px;', seg(['Notifications','Leaderboard'], sel).replace('display:inline-flex;','display:flex;'));
const lbRow = (r, k, n, o={}) => d(`display:flex;align-items:center;gap:12px;min-height:56px;padding:0 12px;border-radius:12px;${o.you?`background:${C.raised};`:''}`, sp(NUM+'font-size:15px;min-width:28px;color:'+C.t1+';', r) + av(k,36) + d('flex:1;min-width:0;', tx('h',C.t1, o.you?'You':PPL[k][0],'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;') + (o.sub?tx('c',C.t2,o.sub):'')) + d('display:flex;align-items:baseline;gap:4px;', sp(NUM+'font-size:20px;color:'+C.t1+';', n) + tx('c',C.t2,'secured')));
const lbChips = (sel) => d('display:flex;gap:8px;padding:10px 0 0 16px;overflow:hidden;', ['Read 30','Up by 5','Wake up at 5 every day','Hydrate 30'].map((l,i)=>chip(l,i===sel)).join(''));
const cStep3 = (step, title, body, btn, o={}) => phone({ time:o.time||'8:30', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,`Step ${step} of 3`) + d('width:52px')) + d(`margin:0 16px;height:3px;border-radius:2px;background:${C.raised};`, d(`width:${step*33.3}%;height:100%;background:${C.t1};border-radius:2px;`)) + d('padding:16px 16px 0;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,title) + body), sticky: btn, stickyH:o.sh||72, overlay:o.overlay });
const fieldB = (l, v, o={}) => d('display:flex;flex-direction:column;gap:6px;', tx('h',C.t1,l) + d(`min-height:52px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;gap:8px;${o.focus?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:''}`, tx('b',v?C.t1:C.t2,v||o.ph||'','flex:1;') + (o.right||'')) + (o.note?d('display:flex;align-items:center;gap:6px;', (o.ok?ic('check',14,C.t1,{sw:3}):o.err?ic('alert',14):'') + tx('c',o.err?C.t1:C.t2,o.note)):''));

function build3(v47) {
  build2(v47);
  NEXT = 601;
  const FL3 = { hub:'GRIIT v48 Atlas B3.dc.html', prof:'GRIIT v48 Atlas 9 Profiles.dc.html', act:'GRIIT v48 Atlas 10 Activity.dc.html', cr:'GRIIT v48 Atlas 11 Create.dc.html', set:'GRIIT v48 Atlas 12 Settings.dc.html', pay:'GRIIT v48 Atlas 13 Paywall.dc.html', flows:'GRIIT v48 Atlas Flows B3.dc.html' };
  const B3 = []; const F3 = (k, m, html) => { B3.push(k); return F(k, m, html); };
  const pReadBtn = btnP('Read 10 pages', { icon:'camera' });

  // ================= AREA 9 · SOMEONE ELSE'S PROFILE =================
  CUR = FL3.prof;
  const A9 = [];
  const vHead = (o={}) => d('display:flex;align-items:center;justify-content:space-between;height:44px;padding:0 6px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('cl',22)) + tx('h',C.t1,'@'+(o.handle||'khalid')) + d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('more',20))) +
    (o.bare ? '' : d('padding:8px 16px 0;display:flex;flex-direction:column;gap:12px;', d('display:flex;align-items:center;gap:16px;', av(o.who||'khalid',80) + d('flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:4px;', [[o.streak??'12','Streak'],[o.best??'31','Best'],[o.sec??'58','Days secured']].map(([n,l])=>d('display:flex;flex-direction:column;', sp(NUM+'font-size:24px;line-height:28px;color:'+C.t1+';', n) + tx('c',C.t2,l))).join(''))) +
      d('display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,PPL[o.who||'khalid'][0]) + (o.bio!==''?tx('b',C.t1,o.bio||'Gym at 6. Reading on the train.'):'') + tx('s',C.t2,o.fol||'212 followers · 180 following' + (o.mutual?' · follows you':''))) + (o.btns||'')));
  const vTabs = d('display:flex;margin-top:14px;', [['grid','Proofs'],['flag','Challenges'],['award','Badges']].map(([i,l],k)=>d(`flex:1;height:44px;display:flex;align-items:center;justify-content:center;gap:6px;border-bottom:2px solid ${k===0?C.t1:'transparent'};`, ic(i,18,k===0?C.t1:C.t2) + tx('c',k===0?C.t1:C.t2,l))).join(''));
  const vt = (ph, date, multi) => d('position:relative;aspect-ratio:4/5;overflow:hidden;', img(ph) + d(`position:absolute;left:6px;bottom:5px;${T.c}font-size:11px;color:${C.t1};text-shadow:0 1px 2px rgba(0,0,0,0.6);`, date) + (multi?d('position:absolute;right:6px;top:6px;', ic('copy',14)):''));
  const vgrid = d('display:grid;grid-template-columns:repeat(3,1fr);gap:2px;', [['gym1','Oct 4'],['book2','Oct 3',1],['gym2','Oct 1'],['run1','Sep 30'],['gym3','Sep 28'],['food3','Sep 27'],['book1','Sep 26'],['gym1','Sep 24'],['water2','Sep 23']].map(([p,dt,m])=>vt(p,dt,m)).join(''));
  const note = (t) => tx('s',C.t2,t,'padding:6px 16px 0;');
  A9.push(F3('vPublic', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Public, not following', src:'v43 visitor', b75:'pending', fields:'proofs ← shared only (server filter)' }, phone({ time:'12:40', body: vHead({ btns: d('display:flex;gap:8px;', btnP('Follow',{w:0}).replace('flex:none;','flex:1;') + btnS('Share',{flex:1,icon:'share'})) }) + vTabs + vgrid })));
  const privPanel = (who, t) => d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:48px 32px;text-align:center;', d(`width:56px;height:56px;border-radius:999px;background:${C.surf};display:flex;align-items:center;justify-content:center;`, ic('lock',24)) + tx('h',C.t1,'This account is private') + tx('s',C.t2,t));
  A9.push(F3('vPrivate', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Private, not following', src:'v43 visitor', b75:'pending' }, phone({ time:'12:41', body: vHead({ handle:'bilal', who:'bilal', streak:'3', best:'9', sec:'14', bio:'', fol:'40 followers · 52 following', btns: btnP('Request to follow') }) + privPanel('bilal','Follow Bilal to see his proofs and challenges. His streak and badges are always visible.') })));
  A9.push(F3('vRequested', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Requested', src:'v43', b75:'pending' }, phone({ time:'12:41', body: vHead({ handle:'bilal', who:'bilal', streak:'3', best:'9', sec:'14', bio:'', fol:'40 followers · 52 following', btns: btnS('Requested · tap to cancel') }) + privPanel('bilal','Bilal sees your request in Activity. You’ll see his proofs once he accepts.') })));
  A9.push(F3('vFollowing', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Following', src:'v43', b75:'pending' }, phone({ time:'12:42', body: vHead({ btns: d('display:flex;gap:8px;', btnS('Following',{flex:1}) + btnS('Share',{flex:1,icon:'share'})) }) + vTabs + vgrid })));
  A9.push(F3('vMutual', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Mutual', src:'v43', b75:'pending' }, phone({ time:'12:42', body: vHead({ mutual:true, btns: d('display:flex;gap:8px;', btnS('Following',{flex:1}) + btnS('Invite',{flex:1,icon:'userplus'})) }) + vTabs + vgrid })));
  A9.push(F3('vDayFeed', { route:'profile/[username] · day feed', comp:'ProofDayFeed (visitor)', state:'Shared proofs only, two-proof day', src:'v39 112', b75:'not built' }, phone({ time:'12:43', body: stepHead('Khalid’s proofs','',{}) + d('display:flex;justify-content:space-between;padding:12px 16px 8px;', tx('h',C.t1,'Saturday 3 October') + tx('s',C.t2,'2 proofs')) + d('position:relative;width:393px;height:491px;', img('book2') + d('position:absolute;left:12px;top:12px;', seal()) + d(`position:absolute;right:12px;top:12px;height:26px;padding:0 10px;border-radius:999px;background:rgba(15,15,15,0.62);${T.c}color:${C.t1};display:flex;align-items:center;`, '1 of 2') + d('position:absolute;left:12px;right:12px;bottom:12px;display:flex;gap:4px;', d(`flex:1;height:2px;background:${C.t1};`) + d('flex:1;height:2px;background:rgba(242,240,235,0.35);'))) + d('padding:10px 16px;display:flex;flex-direction:column;gap:2px;', tx('h',C.t1,'Read 10 pages') + tx('s',C.t2,'Read 30 · Day 14 of 30 · Camera · 6:50 am') + actions('6','1')) + note('Visitors see shared proofs only. A day with nothing shared is left out.') })));
  A9.push(F3('vBlockedByMe', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Blocked by me', src:'new', b75:'not built' }, phone({ time:'12:44', body: vHead({ bare:true }) + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:120px 32px 0;text-align:center;', av('khalid',80) + tx('t',C.t1,'You blocked Khalid') + tx('b',C.t2,'He can’t see your profile or proofs, and you don’t see his.') + d('height:6px') + btnS('Unblock')) })));
  A9.push(F3('vNotFound', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'Blocked me, or deleted', src:'new', b75:'pending' }, phone({ time:'12:44', body: vHead({ bare:true, handle:'user' }).replace('@user','') + d('display:flex;flex-direction:column;align-items:center;gap:8px;padding:220px 32px 0;text-align:center;', ic('user',28,C.t2) + tx('t',C.t1,'User not found') + tx('b',C.t2,'This account isn’t available.')), sticky: btnS('Back'), stickyH:68 })));
  A9.push(F3('vNew', { route:'profile/[username]', comp:'ProfileScreen (visitor)', state:'New user, no proofs', src:'new', b75:'pending' }, phone({ time:'12:45', body: vHead({ handle:'zayd', who:'zayd', streak:'0', best:'0', sec:'0', bio:'', fol:'3 followers · 8 following', btns: btnP('Follow') }) + vTabs + d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:40px 32px;text-align:center;', tx('h',C.t1,'No shared proofs yet') + tx('s',C.t2,'Zayd joined Mind 14 today.')) })));
  A9.push(F3('vMenu', { route:'profile/[username]', comp:'ProfileOverflow', state:'Overflow', src:'new', b75:'pending' }, phone({ time:'12:45', body: vHead({ btns: btnS('Following') }) + vTabs + vgrid, overlay: menuSheet('@khalid', [['share','Share profile',''],['flag','Report @khalid','Tell us what’s wrong'],['ban','Block Khalid','He isn’t told']]) })));
  A9.push(F3('vReport', { route:'profile/[username]', comp:'ReportUserSheet', state:'Reason picker (not built)', src:'new', b75:'not built', fields:'minimum handling: email to griit.health@gmail.com (reporter, target, reason, link)' }, phone({ time:'12:46', body: vHead({ btns: btnS('Following') }) + vTabs + vgrid, overlay: sheet(tx('t',C.t1,'Why are you reporting @khalid?') + tx('s',C.t2,'He won’t know it was you.') + d(`background:${C.raised};border-radius:14px;overflow:hidden;`, ['Fake proofs','Impersonation','Hate or harassment','Nudity or sexual content','Spam','Something else'].map((r,i)=>d(`display:flex;align-items:center;min-height:48px;padding:0 14px;${i?`border-top:1px solid ${C.surf};`:''}`, tx('b',C.t1,r,'flex:1;') + (i===2?ic('check',18,C.t1,{sw:3}):''))).join('')) + btnP('Send report'), { h:640 }) })));

  // ================= AREA 10 · ACTIVITY =================
  CUR = FL3.act;
  const A10 = [];
  const inlineInv = d('display:flex;gap:8px;', smallBtn('Accept',true) + smallBtn('Not now'));
  const notifs = [
    nrow('khalid', B('Khalid')+' respected your proof', '2m', {unread:true, thumb:'book1'}),
    nrow('omar', B('Omar')+' commented: “Same book. Chapter 9 is the turn.”', '8m', {unread:true, thumb:'book1'}),
    nrow('hamza', B('Hamza')+' started following you', '1h', {unread:true, below: smallBtn('Follow back',true)}),
    nrow('abd', B('Abdurrahman')+' nudged you: “10 minutes left.”', '5:20 am', {unread:true}),
    nrow('khalid', B('Khalid')+' invited you to Gym 14', '6:05 am', {unread:true, below: inlineInv}),
    nrow('bilal', B('Bilal')+' joined your group Up by 5', 'Yesterday'),
    nrow('khalid', B('Khalid')+' finished Up by 5. 7 of 7 days.', 'Yesterday'),
    nrow('sys', 'Your 7-day streak is at risk. Read 10 pages is left today.', 'Sat 8:00 pm', {icon: flame(20)}) ];
  A10.push(F3('nEmpty', { route:'(tabs)/activity', comp:'Notifications', state:'Empty', src:'v12 3', b75:'pending' }, phone({ time:'12:50', tab:'activity', dot:false, body: actHead(0) + d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:180px 32px 0;text-align:center;', ic('bell',28,C.t2) + tx('t',C.t1,'Nothing yet') + tx('b',C.t2,'Respects, comments, follows and group news show up here.')) })));
  A10.push(F3('nList', { route:'(tabs)/activity', comp:'Notifications', state:'Unread on top, read below · every type', src:'v45 181', b75:'pending', fields:'unread ← notifications.read_at is null' }, phone({ time:'12:50', tab:'activity', body: actHead(0) + tx('l',C.t2,'New','padding:12px 16px 0;') + notifs.slice(0,5).join('') + tx('l',C.t2,'Earlier','padding:12px 16px 0;') + notifs.slice(5).join('') })));
  A10.push(F3('nRead', { route:'(tabs)/activity', comp:'Notifications', state:'All read (after opening)', src:'v45 181', b75:'pending' }, phone({ time:'12:52', tab:'activity', dot:false, body: actHead(0) + notifs.map(n=>n.replace(`background:${C.t1};`, 'background:transparent;')).join('') })));
  const dest = panel(560, tx('l',C.t2,'Every notification · copy · where a tap goes') + `<div style="display:grid;grid-template-columns:120px 1fr 150px;">` + [['Type','Copy','Tap goes to'],['Respected','{name} respected your proof','post/[id]'],['Commented','{name} commented: “{first 60 chars}”','post/[id] + CommentsSheet'],['Followed','{name} started following you · Follow back','profile/[username]'],['Nudged','{name} nudged you: “{line}”','challenge/active/[id]'],['Group invite','{name} invited you to {challenge} · Accept / Not now inline','invite/[code]'],['Joined your group','{name} joined your group {challenge}','challenge/[id]/members'],['Finished','{name} finished {challenge}. {n} of {N} days.','profile/[username]'],['Streak at risk','Your {n}-day streak is at risk. {task} is left today.','(tabs)/index']].map((r,ri)=>r.map((c,i)=>d(`${ri?(i?T.s:T.h):T.c}color:${ri?C.t1:C.t2};padding:8px 8px 8px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>' + tx('s',C.t2,'At most 3 pushes a day, reminders included. No exclamation marks. Streak at risk is a push and a row, never a modal.'));
  A10.push(dest);
  const lbFoot = (t) => tx('c',C.t2,t,'padding:10px 16px;');
  A10.push(F3('lbRanked', { route:'(tabs)/activity', comp:'Leaderboard', state:'Challenge board, me ranked', src:'v46 190', b75:'pending', fields:'score ← secured days since Monday, same array as the strip' }, phone({ time:'12:53', tab:'activity', body: actHead(1) + lbChips(0) + d('padding:14px 16px 0;display:flex;justify-content:space-between;', tx('h',C.t1,'This week') + tx('s',C.t2,'Mon–Sat closed')) + d('padding:6px 4px;', lbRow('1','khalid','6') + lbRow('2','omar','6') + lbRow('3','yaseen','5',{you:true}) + lbRow('4','abd','4') + lbRow('5','bilal','3')) + lbFoot('Secured days since Monday. Ties share a rank. 8 people, all shown.') })));
  A10.push(F3('lbTies', { route:'(tabs)/activity', comp:'Leaderboard', state:'Ties', src:'new', b75:'pending' }, phone({ time:'12:53', tab:'activity', body: actHead(1) + lbChips(1) + d('padding:14px 16px 0;', tx('h',C.t1,'This week')) + d('padding:6px 4px;', lbRow('1=','khalid','5') + lbRow('1=','yaseen','5',{you:true}) + lbRow('1=','abd','5') + lbRow('4','bilal','2')) + lbFoot('Same secured days, same rank. Order within a tie is alphabetical.') })));
  A10.push(F3('lbUnranked', { route:'(tabs)/activity', comp:'Leaderboard', state:'Me outside the top · neighbours shown', src:'Chunk U B', b75:'pending' }, phone({ time:'12:54', tab:'activity', body: actHead(1) + lbChips(2) + d('padding:14px 16px 0;', tx('h',C.t1,'This week')) + d('padding:6px 4px;', lbRow('1','hamza','6') + lbRow('2','khalid','6') + lbRow('3','omar','6') + d('padding:6px 16px;', tx('c',C.t2,'…')) + lbRow('13','zayd','3') + lbRow('14','yaseen','2',{you:true}) + lbRow('15','bilal','2')) + lbFoot('40 people. Showing the top 3 and the people either side of you; rank 16 and below aren’t shown.') })));
  A10.push(F3('lbSolo', { route:'(tabs)/activity', comp:'Leaderboard', state:'Solo: “A board needs two”', src:'v46 190', b75:'pending' }, phone({ time:'12:55', tab:'activity', body: actHead(1) + lbChips(3) + d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:120px 32px 0;text-align:center;', tx('t',C.t1,'A board needs two') + tx('b',C.t2,'Hydrate 30 is just you. Invite someone and their days count from the day they join.') + d('height:6px') + btnS('Invite to Hydrate 30',{icon:'userplus'})) })));
  A10.push(F3('lbChipsSpec', { route:'(tabs)/activity', comp:'Leaderboard', state:'Chip row scrolls, never truncates', src:'new', b75:'differs · build 75 clips “Wake up at 5 everyda”' }, phone({ time:'12:57', tab:'activity', body: actHead(1) + lbChips(2) + d(`margin:8px 16px 0;height:0;border-top:1px dashed ${C.t3};`) + tx('c',C.t2,'Full challenge names; the row scrolls sideways. A chip that runs off the edge is the scroll cue.','padding:8px 16px;') + d('padding:6px 4px;', lbRow('1','hamza','6') + lbRow('2','khalid','6') + lbRow('3','yaseen','5',{you:true})) })));

  // ================= AREA 11 · CREATE =================
  CUR = FL3.cr;
  const A11 = [];
  const catChips = (sel) => d('display:flex;flex-wrap:wrap;gap:8px;', ['Fitness','Faith','Mind','Health','Discipline','Learning'].map(c=>chip(c, c===sel, CAT[c][1])).join(''));
  const lenChips = (sel) => d('display:flex;flex-wrap:wrap;gap:8px;', ['7','14','30','75','Custom'].map(c=>chip(c==='Custom'?c:c+' days', c===sel)).join(''));
  A11.push(F3('cbFilled', { route:'create/index', comp:'StepBasics', state:'Name “Looks good”, category, length, cover preview', src:'v44 169', b75:'pending' }, cStep3(1,'Name your challenge', fieldB('Name','Wake up at 5 every day',{focus:true, ok:true, note:'Looks good.'}) + tx('h',C.t1,'Category') + catChips('Discipline') + tx('h',C.t1,'Length') + lenChips('30') + d('display:flex;align-items:center;gap:12px;padding-top:4px;', cover('wake',72,90) + tx('s',C.t2,'Your cover. It comes from the category and length.')), btnP('Continue'))));
  A11.push(F3('cbEmpty', { route:'create/index', comp:'StepBasics', state:'Disabled Continue · chips clearly tappable', src:'v44 169', b75:'pending' }, cStep3(1,'Name your challenge', fieldB('Name','',{ph:'What will you do every day?'}) + tx('h',C.t1,'Category') + catChips('') + tx('h',C.t1,'Length') + lenChips(''), btnP('Continue',{off:true}) + tx('c',C.t2,'Add a name and pick a length.','text-align:center;'), {sh:96})));
  A11.push(F3('cbInvalid', { route:'create/index', comp:'StepBasics', state:'Validation: name too short / taken', src:'v44 169', b75:'pending' }, cStep3(1,'Name your challenge', fieldB('Name','Up',{focus:true, err:true, note:'Use at least 3 characters.'}) + fieldB('Or','Read 30',{err:true, note:'There’s a catalog challenge called Read 30. Join it, or add a word to yours.'}) + tx('h',C.t1,'Category') + catChips('Learning') + tx('h',C.t1,'Length') + lenChips('30'), btnP('Continue',{off:true}))));
  const packRow = (name, sub, o={}) => d(`border-radius:14px;padding:12px 14px;background:${o.sel?C.t1:C.surf};display:flex;flex-direction:column;gap:6px;`, d('display:flex;align-items:center;gap:10px;', d('flex:1;', tx('h',o.sel?C.ink:C.t1,name) + tx('s',o.sel?'#3A3836':C.t2,sub)) + (o.sel?ic('check',18,C.ink,{sw:3}):ic(o.open?'cu':'cd',18,C.t2))) + (o.open?d(`background:${C.raised};border-radius:12px;padding:2px 12px;margin-top:4px;`, o.tasks.map(t=>taskRow({...t, st:'open', right:''})).join('')) + btnS('Use this pack'):''));
  const packs = [['No Days Off','5 tasks · Workout, water, reading, journal, photo'],['Athlete','3 tasks · Training, steps, sleep'],['Faith','3 tasks · Fajr, Quran, dhikr'],['Morning routine','3 tasks · Up by 6, cold shower, plan'],['Entrepreneur','3 tasks · Deep work, read, outreach']];
  A11.push(F3('ctPacks', { route:'create/index', comp:'StepTasks', state:'Starter packs collapsed', src:'v44 169', b75:'pending' }, cStep3(2,'What do you do each day?', tx('s',C.t2,'Start from a pack or build your own.') + packs.map(([a,b])=>packRow(a,b)).join('') + btnS('Build my own',{icon:'plus'}), btnP('Continue',{off:true}))));
  A11.push(F3('ctExpanded', { route:'create/index', comp:'StepTasks', state:'Pack expanded (Faith)', src:'v44 169', b75:'pending' }, cStep3(2,'What do you do each day?', packRow('No Days Off',packs[0][1]) + packRow('Athlete',packs[1][1]) + packRow('Faith',packs[2][1],{open:true, tasks:[{name:'Fajr on time',gate:[G.cam,['clock','4:50–6:10 am']]},{name:'Quran',gate:[[null,'2 pages'],G.self]},{name:'Dhikr',gate:[[null,'10 min'],G.self]}]}) + packRow('Morning routine',packs[3][1]), btnP('Continue',{off:true}))));
  A11.push(F3('ctCustom', { route:'create/index', comp:'StepTasks', state:'Custom: task list', src:'v44 169', b75:'pending' }, cStep3(2,'What do you do each day?', d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:ic('more',18,C.t2)}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:ic('more',18,C.t2)})) + btnS('Add a task',{icon:'plus'}) + tx('s',C.t2,'Every task is required each day. Up to 6.'), btnP('Continue'))));
  const typeGrid = (sel) => d('display:grid;grid-template-columns:repeat(3,1fr);gap:8px;', [['check','Check-off'],['timer','Timer'],['hash','Counter'],['type','Text'],['run','Run']].map(([i,l])=>d(`height:64px;border-radius:12px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;${l===sel?`background:${C.t1};`:`background:${C.raised};`}`, ic(i,18,l===sel?C.ink:C.t1) + tx('c',l===sel?C.ink:C.t1,l))).join(''));
  const atTop = tx('t',C.t1,'Add a task') + tx('h',C.t1,'Common tasks') + d('display:flex;gap:8px;flex-wrap:wrap;', ['Out of bed','Read','Workout','Drink water','Journal'].map((c,i)=>chip(c,i===0)).join('')) + fieldB('Name','Out of bed',{ok:true}) + tx('h',C.t1,'Type') + typeGrid('Check-off');
  const atBottom = tx('h',C.t1,'Photo') + seg(['Required','Optional','None'],2).replace('display:inline-flex;','display:flex;') + tx('s',C.t2,'None: it counts as self-reported.') + tx('h',C.t1,'Limits','padding-top:4px;') + d(`background:${C.raised};border-radius:14px;overflow:hidden;`, d('display:flex;align-items:center;gap:12px;min-height:52px;padding:0 14px;', ic('clock',18) + tx('b',C.t1,'Time window','flex:1;') + tx('s',C.t2,'4:30–5:30 am') + ic('cr',16,C.t2)) + d(`display:flex;align-items:center;gap:12px;min-height:52px;padding:0 14px;border-top:1px solid ${C.surf};`, ic('pin',18) + tx('b',C.t1,'Place','flex:1;') + tx('s',C.t2,'Set place') + ic('cr',16,C.t2))) + tx('h',C.t1,'On Home','padding-top:4px;') + d(`background:${C.ink};border-radius:14px;padding:2px 12px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open'}));
  const atSheet = (inner, scroll) => d('position:absolute;inset:0;z-index:30;background:rgba(0,0,0,0.6);') + d(`position:absolute;left:0;right:0;top:71px;bottom:0;z-index:31;background:${C.surf};border-radius:24px 24px 0 0;overflow:hidden;`, d(`width:36px;height:5px;border-radius:3px;background:${C.t3};margin:8px auto 0;`) + d(`position:absolute;left:0;right:0;top:20px;bottom:106px;overflow:hidden;`, d(`margin-top:${-scroll}px;padding:6px 16px 24px;display:flex;flex-direction:column;gap:12px;`, inner)) + d(`position:absolute;left:0;right:0;bottom:0;height:106px;padding:12px 16px 46px;background:${C.surf};`, btnP('Add task')));
  const behind = cStep3(2,'What do you do each day?', '', btnP('Continue'));
  A11.push(F3('atTop', { route:'create/index', comp:'AddTaskSheet', state:'Common tasks, name, type', src:'v44 / 42', b75:'pending' }, phone({ time:'8:34', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,'Step 2 of 3') + d('width:52px')) + d('padding:16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'What do you do each day?') + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''}))), overlay: atSheet(atTop + atBottom, 0), inset:'sheet' })));
  A11.push(F3('atBottom', { route:'create/index', comp:'AddTaskSheet', state:'Scrolled: photo, limits, On Home preview, clear of the sticky button', src:'v44 / 42', b75:'differs · build 75 hides the last field under the button' }, phone({ time:'8:34', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,'Step 2 of 3') + d('width:52px')) + d('padding:16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'What do you do each day?') + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''}))), overlay: atSheet(atTop + atBottom, 420) })));
  const wheel = (cols) => d('display:flex;justify-content:center;gap:4px;position:relative;height:200px;', d(`position:absolute;left:0;right:0;top:80px;height:40px;border-radius:10px;background:${C.raised};`) + cols.map(c=>d('position:relative;width:70px;display:flex;flex-direction:column;align-items:center;', c.map((v,i)=>d(`height:40px;display:flex;align-items:center;font-size:${i===2?22:18}px;color:${i===2?C.t1:C.t2};opacity:${[0.35,0.6,1,0.6,0.35][i]};font-variant-numeric:tabular-nums;`, v)).join(''))).join(''));
  A11.push(F3('atWheel', { route:'create/index', comp:'TimeWindowSheet', state:'Wheel picker, same-day only', src:'v41 115', b75:'pending', fields:'window_start / window_end stored 24h, shown 12h' }, phone({ time:'8:35', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,'Step 2 of 3') + d('width:52px')) + d('padding:16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'What do you do each day?') + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''}))), overlay: sheet(tx('t',C.t1,'Time window') + seg(['From','To'],0).replace('display:inline-flex;','display:flex;') + wheel([['2','3','4','5','6'],['20','25','30','35','40'],['','','am','pm','']]) + tx('s',C.t2,'4:30–5:30 am. Windows stay within one day.') + btnP('Done')) })));
  A11.push(frameWrap('fRules',0,1));
  A11.push(F3('crReview', { route:'create/index', comp:'StepReview', state:'Solo, Standard, Anyone', src:'v44 169', b75:'pending' }, phone({ time:'8:36', body: stepHead('Review','',{back:true}) + d('padding:8px 16px;display:flex;flex-direction:column;gap:10px;', d('display:flex;gap:14px;align-items:center;', cover('wake',72,90) + d('flex:1;', tx('t',C.t1,'Wake up at 5 every day') + tx('s',C.t2,'30 days · Discipline · Anyone · Standard'))) + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''})) + tx('s',C.t2,'Anyone can find it on Discover and join. Day 1 is tomorrow: today’s window has closed.') + d('display:flex;gap:16px;', btnT('Edit tasks') + btnT('Edit rules'))), sticky: btnP('Launch'), stickyH:72 })));
  A11.push(F3('crLaunchedSolo', { route:'create/index', comp:'LaunchedScreen', state:'Solo launch', src:'v44 169', b75:'pending' }, phone({ time:'8:37', body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:130px 24px 0;text-align:center;', cover('wake',140,175) + tx('tl',C.t1,'It’s live') + tx('b',C.t2,'Wake up at 5 every day starts tomorrow. It’s on Discover now.')), sticky: btnP('Go to Home') + btnT('Share it'), stickyH:116 })));
  A11.push(frameWrap('fLaunched',0,1));
  A11.push(F3('crDiscard', { route:'create/index', comp:'DiscardDraftSheet', state:'Cancel with changes', src:'v28', b75:'pending' }, phone({ time:'8:38', body: d('display:flex;align-items:center;justify-content:space-between;height:52px;padding:0 16px;', tx('h',C.t1,'Cancel') + tx('c',C.t2,'Step 2 of 3') + d('width:52px')) + d('padding:16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'What do you do each day?') + d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, taskRow({name:'Out of bed', gate:[G.self,['clock','4:30–5:30 am']], st:'open', right:''}) + taskRow({name:'Cold shower', gate:[G.self], st:'open', right:''}))), overlay: sheet(tx('t',C.t1,'Discard this challenge?') + tx('b',C.t2,'Wake up at 5 every day and its 2 tasks will be lost.') + btnS('Discard') + btnT('Keep editing')) }).replace('<div style="position:absolute;left:0;right:0;top:59px;', '<div style="position:absolute;left:0;right:0;top:59px;') ));
  A11.push(frameWrap('limit',0,1));

  // ================= AREA 12 · SETTINGS =================
  CUR = FL3.set;
  const A12 = [];
  A12.push(F3('stIndex', { route:'settings/index', comp:'Settings', state:'Index', src:'v12 6', b75:'pending' }, phone({ time:'1:00', body: page('Settings', grp([{i:'user',l:'Account',s:'yaseen@hey.com'},{i:'crown',l:'Subscription',v:'Free'}]) + grp([{i:'lock',l:'Privacy',v:'Public'},{i:'bell',l:'Notifications'},{i:'camera',l:'Permissions'}]) + grp([{i:'file',l:'About',v:'1.0 (75)'}]) + btnS('Log out',{icon:'logout'})) })));
  A12.push(F3('stAccount', { route:'settings/account', comp:'AccountSettings', state:'Email, password, Apple, log out, delete', src:'v12 6', b75:'pending' }, phone({ time:'1:01', body: page('Account', grp([{l:'Email',v:'yaseen@hey.com'},{l:'Password',v:'Change'},{l:'Sign in with Apple',v:'Linked',nochev:true}]) + grp([{i:'logout',l:'Log out',nochev:true}]) + grp([{i:'trash',l:'Delete account',s:'Removes your account and everything in it'}])) })));
  A12.push(F3('delExplain', { route:'settings/account', comp:'DeleteAccount', state:'1 · What gets deleted', src:'v12', b75:'pending' }, phone({ time:'1:02', body: page('Delete account', tx('t',C.t1,'This deletes everything') + d('display:flex;flex-direction:column;gap:8px;', ['Your profile, proofs, streak and badges','Your comments and respects','Your place in 2 challenges. Up by 5 passes to Khalid, who’s been in it longest.'].map(t=>d('display:flex;gap:10px;', ic('minus',16,C.t2) + tx('b',C.t1,t))).join('')) + tx('b',C.t2,'It can’t be undone, and we can’t restore it later.')), sticky: btnS('Continue') + btnT('Keep my account'), stickyH:116 })));
  A12.push(F3('delSub', { route:'settings/account', comp:'DeleteAccount', state:'2 · Subscription warning', src:'new', b75:'not built' }, phone({ time:'1:02', body: page('Delete account', tx('t',C.t1,'Cancel GRIIT Pro first') + tx('b',C.t2,'Your Pro subscription is billed by Apple. Deleting your account doesn’t stop it. Cancel it in your App Store subscriptions, then come back.') + btnS('Manage subscription')), sticky: btnS('I’ve cancelled, continue') + btnT('Keep my account'), stickyH:116 })));
  A12.push(F3('delConfirm', { route:'settings/account', comp:'DeleteAccount', state:'3 · Confirm', src:'new', b75:'pending' }, phone({ time:'1:03', body: page('Delete account', tx('t',C.t1,'Type DELETE to confirm') + fieldB('','DELETE',{focus:true}) + tx('s',C.t2,'Signed in with Apple: you’ll confirm with Face ID next.')), sticky: btnS('Delete my account') + btnT('Keep my account'), stickyH:116 })));
  A12.push(F3('delDone', { route:'onboarding/index', comp:'Welcome', state:'4 · Signed out after deletion', src:'v42 onboarding', b75:'pending' }, phone({ time:'1:04', body: d('display:flex;flex-direction:column;gap:12px;padding:220px 24px 0;', flame(44) + d(`font-size:40px;line-height:44px;font-weight:500;color:${C.t1};letter-spacing:-0.02em;`, 'Do what you said.<br>Prove it.') + tx('b',C.t2,'Daily challenges, honest proof, a streak that grows.')), toast: d(`position:absolute;left:16px;right:16px;top:70px;z-index:16;background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, ic('ccheck',18) + tx('s',C.t1,'Your account was deleted.','flex:1;')), sticky: btnP('Get started') + btnT('I have an account'), stickyH:116 })));
  A12.push(F3('stSub', { route:'settings/index', comp:'SubscriptionSettings', state:'Free · and Pro', src:'new', b75:'pending', fields:'status ← RevenueCat customerInfo.entitlements.pro' }, phone({ time:'1:05', body: page('Subscription', tx('l',C.t2,'Free') + grp([{l:'Plan',v:'Free',nochev:true},{l:'Active challenges',v:'3 of 3',nochev:true},{l:'Freezes',v:'1 every 30 days',nochev:true}]) + btnP('See Pro') + tx('l',C.t2,'If you’re Pro','padding-top:10px;') + grp([{l:'Plan',v:'Pro · annual',nochev:true},{l:'Renews',v:'Nov 4, 2026',nochev:true},{l:'Manage in the App Store'}]) + btnT('Restore purchases')) })));
  const whoSees = (priv) => d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:grid;grid-template-columns:1fr auto auto;gap:8px 14px;`, ['','Followers','Everyone'].map(h=>tx('c',C.t2,h)).join('') + [['Name, photo, streak, badges',1,1],['Shared proofs',1,priv?0:1],['Challenges',1,priv?0:1],['Board rank',1,priv?0:1]].map(([l,a,b])=>tx('s',C.t1,l) + d('display:flex;justify-content:center;', a?ic('check',16,C.t1,{sw:3}):ic('minus',16,C.t2)) + d('display:flex;justify-content:center;', b?ic('check',16,C.t1,{sw:3}):ic('minus',16,C.t2))).join(''));
  A12.push(F3('stPrivacy', { route:'settings/privacy', comp:'PrivacySettings', state:'One switch, who sees what', src:'v43 privacy', b75:'pending', fields:'writes profiles.is_private, proofs.default_visibility, boards.visible' }, phone({ time:'1:06', body: page('Privacy', grp([{l:'Private account',s:'Only followers you approve see your proofs',sw:false}]) + whoSees(false) + grp([{i:'eyeoff',l:'See how a stranger sees you'}]) + lab('Proofs') + grp([{l:'After each proof',v:'Ask me',s:'Share to the feed, or keep it to the record'}]) + lab('Boards') + grp([{l:'Show me on challenge boards',sw:true}]) + grp([{i:'ban',l:'Blocked users',v:'1'}])) })));
  A12.push(F3('stPrivacyOn', { route:'settings/privacy', comp:'PrivacySettings', state:'Private on', src:'v43', b75:'pending' }, phone({ time:'1:06', body: page('Privacy', grp([{l:'Private account',s:'Only followers you approve see your proofs',sw:true}]) + whoSees(true) + tx('s',C.t2,'People who already follow you keep seeing your proofs. New followers need your approval.')) })));
  A12.push(F3('stStranger', { route:'settings/privacy', comp:'StrangerPreview', state:'How a stranger sees you', src:'v43', b75:'pending' }, phone({ time:'1:07', body: d(`height:40px;display:flex;align-items:center;justify-content:center;background:${C.raised};`, tx('c',C.t1,'Preview · this is what a stranger sees')) + vHead({ handle:'yaseen', who:'yaseen', streak:'7', best:'18', sec:'23', bio:'Reading before work. Up before the city.', fol:'128 followers · 96 following', btns: btnP('Follow') }) + vTabs + d('display:grid;grid-template-columns:repeat(3,1fr);gap:2px;', [['book1','Oct 4'],['water1','Sep 29'],['pray1','Sep 25'],['water3','Sep 21']].map(([p,dt])=>vt(p,dt)).join('')) + note('Only proofs you shared show here. Private ones and self-reported days don’t.') , sticky: btnS('Close preview'), stickyH:68 })));
  A12.push(F3('stBlocked', { route:'settings/privacy', comp:'BlockedUsers', state:'List (not built)', src:'new', b75:'not built' }, phone({ time:'1:08', body: page('Blocked users', d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, person('khalid','Blocked Oct 4', smallBtn('Unblock'))) + tx('s',C.t2,'Blocked people can’t see your profile or proofs, and you don’t see theirs. They aren’t told.')) })));
  A12.push(F3('stUnblock', { route:'settings/privacy', comp:'BlockedUsers', state:'Unblock confirm', src:'new', b75:'not built' }, phone({ time:'1:08', body: page('Blocked users', d(`background:${C.surf};border-radius:16px;padding:4px 14px;`, person('khalid','Blocked Oct 4', smallBtn('Unblock')))), overlay: dialog('Unblock Khalid?','He’ll be able to see your public profile again. You won’t follow each other automatically.', d('display:flex;gap:8px;', btnS('Cancel',{flex:1}) + btnS('Unblock',{flex:1}))) })));
  A12.push(F3('stBlockedEmpty', { route:'settings/privacy', comp:'BlockedUsers', state:'Empty, after unblocking', src:'new', b75:'not built' }, phone({ time:'1:09', body: page('Blocked users', d('display:flex;flex-direction:column;align-items:center;gap:6px;padding:140px 24px;text-align:center;', ic('ban',26,C.t2) + tx('h',C.t1,'No one blocked') + tx('s',C.t2,'Block someone from their profile or a post’s menu.'))), toast: d(`position:absolute;left:16px;right:16px;bottom:46px;z-index:16;background:${C.raised};border-radius:14px;padding:12px 14px;`, tx('s',C.t1,'Khalid is unblocked.')) })));
  const notifRows = (dis) => grp([{l:'Reminders',s:'For tasks with a time window',sw:true,dis},{l:'Streak at risk',s:'8:00 pm if today is still open',sw:true,dis},{l:'Respects',sw:false,dis},{l:'Comments',sw:true,dis},{l:'New followers',sw:true,dis},{l:'Group activity',s:'Joins, finishes, invites',sw:true,dis},{l:'Nudges',sw:true,dis}]);
  A12.push(F3('stNotif', { route:'settings/notifications', comp:'NotificationSettings', state:'Every category, quiet hours', src:'v45 181', b75:'differs · “Circle activity” renamed “Group activity”' }, phone({ time:'1:10', body: page('Notifications', tx('s',C.t2,'At most 3 pushes a day, reminders included.') + notifRows(false) + grp([{i:'moon',l:'Quiet hours',v:'10:00 pm–7:00 am'}])) })));
  A12.push(F3('stNotifOff', { route:'settings/notifications', comp:'NotificationSettings', state:'Off in iOS Settings', src:'new', b75:'pending' }, phone({ time:'1:10', body: page('Notifications', d(`background:${C.surf};border-radius:16px;padding:14px;display:flex;flex-direction:column;gap:8px;`, tx('h',C.t1,'Notifications are off for GRIIT') + tx('s',C.t2,'Turn them on in iOS Settings to get reminders before a window closes.') + btnS('Open iOS Settings')) + notifRows(true)) })));
  A12.push(F3('stPerms', { route:'settings/index', comp:'PermissionsSettings', state:'Camera, location, notifications, Health (not built)', src:'new', b75:'not built' }, phone({ time:'1:11', body: page('Permissions', grp([{i:'camera',l:'Camera',s:'Needed for proof photos',v:'Allowed'},{i:'pin',l:'Location',s:'Only when you check in',v:'While using'},{i:'bell',l:'Notifications',v:'Off'},{i:'run',l:'Apple Health',s:'Import runs (not built)',v:'Not asked'}]) + tx('s',C.t2,'Each row opens GRIIT in iOS Settings. GRIIT never reads your camera roll.')) })));
  A12.push(F3('stAbout', { route:'settings/about', comp:'About', state:'Version, legal, contact', src:'v12 6', b75:'pending' }, phone({ time:'1:12', body: page('About', grp([{l:'Version',v:'1.0 (75)',nochev:true}]) + grp([{l:'Terms of Service'},{l:'Privacy Policy'},{l:'Community guidelines',s:'Not built'}]) + grp([{l:'Contact',v:'griit.health@gmail.com'}])) })));
  A12.push(F3('stTerms', { route:'legal/terms', comp:'LegalPage', state:'Dark reader', src:'new', b75:'differs · build 75 opens a light web view' }, phone({ time:'1:13', body: page('Terms of Service', tx('c',C.t2,'Updated Sep 1, 2026') + tx('t',C.t1,'1. Using GRIIT') + tx('b',C.t1,'You must be 13 or older. Proofs you take are yours; by sharing one to the feed you let GRIIT show it to the people your privacy setting allows.') + tx('t',C.t1,'2. Honest proof') + tx('b',C.t1,'Camera proofs must be taken live in the app. GRIIT doesn’t check what a photo shows, and self-reported tasks are labelled as such.')) })));

  // ================= AREA 13 · PAYWALL =================
  CUR = FL3.pay;
  const A13 = [];
  const rcNote = d(`display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:10px;box-shadow:inset 0 0 0 1px ${C.raised};`, ic('alert',14,C.t2) + tx('c',C.t2,'Spec: prices, trial and period from RevenueCat offerings (store price, user’s currency). USD shown as an example.'));
  const plan = (on, name, billed, sub) => d(`border-radius:16px;padding:14px;background:${on?C.t1:C.surf};display:flex;align-items:center;gap:12px;`, d('flex:1;display:flex;flex-direction:column;gap:2px;', tx('h',on?C.ink:C.t1,name) + d(`font-size:22px;line-height:28px;font-weight:600;color:${on?C.ink:C.t1};`, billed) + (sub?tx('s',on?'#3A3836':C.t2,sub):'')) + d(`width:22px;height:22px;border-radius:999px;${on?`background:${C.ink};display:flex;align-items:center;justify-content:center;`:`box-shadow:inset 0 0 0 1.5px ${C.t3};`}`, on?ic('check',13,C.t1,{sw:3}):''));
  const payBody = (sel, o={}) => d('display:flex;justify-content:flex-end;padding:0 6px;height:44px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('x',22))) + d('padding:0 16px;display:flex;flex-direction:column;gap:12px;', (o.ctx||'') + tx('tl',C.t1,'GRIIT Pro') + d('display:flex;flex-direction:column;gap:8px;', [['flag','More than 3 challenges at once'],['snow','4 freezes every 30 days instead of 1']].map(([i,t])=>d('display:flex;align-items:center;gap:10px;', ic(i,18) + tx('b',C.t1,t))).join('')) +
    plan(sel==='a','Annual','$29.99 a year', '$2.50 a month · 7-day free trial') + plan(sel==='m','Monthly','$4.99 a month','') + tx('s',C.t2, sel==='a'?'Free for 7 days, then $29.99 a year. Renews yearly. Cancel in the App Store at least 24 hours before renewal.':'$4.99 a month. Renews monthly. Cancel in the App Store at least 24 hours before renewal.') + rcNote);
  const payFoot = (label, o={}) => btnP(label,{spin:o.spin, off:o.off}) + d('display:flex;justify-content:center;gap:16px;', btnT('Restore') + btnT('Terms') + btnT('Privacy'));
  A13.push(F3('payAnnual', { route:'paywall', comp:'Paywall', state:'Annual selected (default)', src:'new', b75:'pending', fields:'priceString, introductoryPrice, subscriptionPeriod ← RevenueCat package.product' }, phone({ time:'1:20', body: payBody('a'), sticky: payFoot('Start free trial'), stickyH:116 })));
  A13.push(F3('payMonthly', { route:'paywall', comp:'Paywall', state:'Monthly selected', src:'new', b75:'pending' }, phone({ time:'1:20', body: payBody('m'), sticky: payFoot('Subscribe for $4.99 a month'), stickyH:116 })));
  A13.push(F3('payBusy', { route:'paywall', comp:'Paywall', state:'Purchasing (App Store sheet up)', src:'new', b75:'pending' }, phone({ time:'1:21', body: payBody('a'), sticky: payFoot('Waiting for the App Store',{spin:true}), stickyH:116, overlay: d(`position:absolute;left:0;right:0;bottom:0;height:330px;z-index:30;background:#2C2C2E;border-radius:14px 14px 0 0;padding:18px;display:flex;flex-direction:column;gap:8px;`, tx('h',C.t1,'App Store') + tx('s',C.t1,'GRIIT Pro (Annual)') + tx('s',C.t2,'7-day free trial, then $29.99/year') + tx('c',C.t2,'iOS sheet, context only')) })));
  A13.push(F3('paySuccess', { route:'paywall', comp:'Paywall', state:'Success', src:'new', b75:'pending' }, phone({ time:'1:22', body: d('display:flex;flex-direction:column;align-items:center;gap:10px;padding:200px 28px 0;text-align:center;', d(`width:64px;height:64px;border-radius:999px;background:${C.raised};display:flex;align-items:center;justify-content:center;`, ic('crown',28)) + tx('tl',C.t1,'You’re Pro') + tx('b',C.t2,'You can run more than 3 challenges and get 4 freezes every 30 days. Your trial ends Oct 11; you won’t be charged before then.')), sticky: btnP('Join Fajr 30'), stickyH:72 })));
  A13.push(F3('payFailed', { route:'paywall', comp:'Paywall', state:'Failed', src:'new', b75:'pending' }, phone({ time:'1:22', body: payBody('a'), toast: d(`position:absolute;left:16px;right:16px;top:70px;z-index:16;background:${C.raised};border-radius:14px;padding:12px 14px;display:flex;align-items:center;gap:10px;`, ic('alert',18) + tx('s',C.t1,'The purchase didn’t go through. You weren’t charged.','flex:1;')), sticky: payFoot('Try again'), stickyH:116 })));
  A13.push(F3('payCancelled', { route:'paywall', comp:'Paywall', state:'Cancelled', src:'new', b75:'pending' }, phone({ time:'1:22', body: payBody('a'), toast: d(`position:absolute;left:16px;right:16px;top:70px;z-index:16;background:${C.raised};border-radius:14px;padding:12px 14px;`, tx('s',C.t1,'Cancelled. Nothing was charged.')), sticky: payFoot('Start free trial'), stickyH:116 })));
  A13.push(F3('payPro', { route:'paywall', comp:'Paywall', state:'Already Pro', src:'new', b75:'pending' }, phone({ time:'1:23', body: d('display:flex;justify-content:flex-end;padding:0 6px;height:44px;', d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('x',22))) + d('padding:0 16px;display:flex;flex-direction:column;gap:12px;', tx('tl',C.t1,'You’re Pro') + grp([{l:'Plan',v:'Annual',nochev:true},{l:'Renews',v:'Nov 4, 2026 · $29.99',nochev:true}]) + tx('s',C.t2,'Billed by Apple. Change or cancel in the App Store.')), sticky: btnS('Manage in the App Store') + btnT('Close'), stickyH:116 })));
  A13.push(F3('payLimit', { route:'paywall', comp:'Paywall', state:'Arriving from the free limit', src:'v48 B2 flow 7', b75:'pending' }, phone({ time:'12:31', body: payBody('a',{ctx: d(`background:${C.surf};border-radius:14px;padding:10px 12px;display:flex;align-items:center;gap:10px;`, cover('fajr',36,45,{r:8}) + tx('s',C.t1,'To join Fajr 30 while keeping your 3 challenges.','flex:1;'))}), sticky: payFoot('Start free trial'), stickyH:116 })));

  // ================= FLOWS 9, 10, 12, 13 =================
  CUR = FL3.hub;
  const khalidNotif = F3('fKhalidAct', { route:'(tabs)/activity', comp:'Notifications', state:'Khalid’s phone: group invite with Accept', src:'v45 181', b75:'pending' }, phone({ time:'6:05', tab:'activity', body: actHead(0) + tx('l',C.t2,'New','padding:12px 16px 0;') + nrow('yaseen', B('Yaseen')+' invited you to Morning routine', 'now', {unread:true, below: inlineInv}) + nrow('omar', B('Omar')+' respected your proof','1h',{thumb:'gym1'}) }));
  const pushSocial = F3('fPushSocial', { route:'lock screen', comp:'Push · comment', state:'Yaseen’s phone', src:'v45 181', b75:'pending' }, phone({ time:'7:20', onPhoto:true, full: d('position:absolute;inset:0;background:linear-gradient(180deg,#1B2430,#0F0F0F);') + d('position:absolute;left:0;right:0;top:92px;text-align:center;'+T.h+'color:'+C.t1+';', 'Monday 5 October') + d('position:absolute;left:0;right:0;top:110px;text-align:center;font-size:84px;line-height:1;font-weight:600;color:'+C.t1+';letter-spacing:-0.02em;', '7:20') +
    d(`position:absolute;left:12px;right:12px;top:420px;border-radius:20px;background:rgba(36,35,34,0.85);padding:12px 14px;display:flex;gap:10px;`, d(`width:38px;height:38px;border-radius:9px;background:${C.ink};display:flex;align-items:center;justify-content:center;flex:none;`, flame(22)) + d('flex:1;', d('display:flex;justify-content:space-between;', tx('h',C.t1,'GRIIT') + tx('c',C.t2,'now')) + tx('b',C.t1,'Khalid commented: “Which edition?”') + tx('s',C.t2,'Khalid and 2 others respected it'))) }));
  const actSocial = F3('fActSocial', { route:'(tabs)/activity', comp:'Notifications', state:'Respect and comment, unread', src:'v45 181', b75:'pending' }, phone({ time:'7:21', tab:'activity', body: actHead(0) + tx('l',C.t2,'New','padding:12px 16px 0;') + nrow('khalid', B('Khalid')+' commented: “Which edition?”','1m',{unread:true, thumb:'book1'}) + nrow('khalid', B('Khalid')+', '+B('Omar')+' and 1 other respected your proof','3m',{unread:true, thumb:'book1'}) + tx('l',C.t2,'Earlier','padding:12px 16px 0;') + notifs.slice(5).join('') }));
  const postOwn = F3('fPostOwn', { route:'post/[id]', comp:'PostDetail', state:'Your post, comments sheet open', src:'v12 39', b75:'pending' }, phone({ time:'7:21', body: stepHead('Post','',{back:true, right: ic('more',20)}) + postHead('yaseen','Read 30 · Day 2 of 30','14h') + d('position:relative;width:393px;height:491px;', img('book1') + d('position:absolute;left:12px;top:12px;', seal())) + actions('3','1'), overlay: sheet(tx('h',C.t1,'Comments','text-align:center;') + comment('khalid','Which edition?','1m'), { h:420 }) + composer('Penguin. Footnotes at the back.') }));
  const P3 = (k) => frameWrap(k, 0.62);
  const fa = (l) => d(`width:64px;flex:none;align-self:center;display:flex;flex-direction:column;align-items:center;gap:4px;`, ic('arrow',20,C.t1) + d(`${T.c}color:${C.t1};text-align:center;`, l));
  const flow = (id, title, note, steps) => `<div id="${id}" data-screen-label="${title}" style="display:flex;flex-direction:column;gap:14px;">` + stripHead(title, note) + d('display:flex;gap:10px;align-items:flex-start;', steps.join('')) + '</div>';
  const flows3 = [
    flow('flow9','Flow 9 · Groups','Yaseen makes a group, Khalid accepts on his phone, Yaseen sees the roster and nudges.', [P3('fRules'), fa('Invite only, Review, Launch'), P3('fLaunched'), fa('Invite people'), P3('invitePick'), fa('Send · Khalid’s phone'), P3('fKhalidAct'), fa('Accept'), P3('invOk'), fa('Back on Yaseen’s phone'), P3('roster'), fa('Nudge'), P3('nudgeSend'), fa('Send · recipient'), P3('nudgeGet')]),
    flow('flow10','Flow 10 · Social','Khalid respects and comments; Yaseen gets one push, opens Activity, lands on the post.', [P3('fPushSocial'), fa('Tap push'), P3('fActSocial'), fa('Tap the comment'), P3('fPostOwn')]),
    flow('flow12','Flow 12 · Safety','Report a post, block, then undo it in Settings.', [P3('ovOther'), fa('Report'), P3('repReason'), fa('Send report'), P3('repDone'), fa('Block Khalid too'), P3('blkConfirm'), fa('Block'), P3('blkDone'), fa('Settings, Privacy'), P3('stPrivacy'), fa('Blocked users'), P3('stBlocked'), fa('Unblock'), P3('stUnblock'), fa('Unblock'), P3('stBlockedEmpty')]),
    flow('flow13','Flow 13 · Account deletion','Settings to signed out, with the subscription warning.', [P3('stIndex'), fa('Account'), P3('stAccount'), fa('Delete account'), P3('delExplain'), fa('Continue'), P3('delSub'), fa('I’ve cancelled'), P3('delConfirm'), fa('Delete, Face ID'), P3('delDone')]) ];

  // ================= hub =================
  const nav = d('display:flex;flex-wrap:wrap;gap:8px;', [[FL3.hub,'Batch 3 overview'],[FL3.prof,'Area 9 Profiles'],[FL3.act,'Area 10 Activity'],[FL3.cr,'Area 11 Create'],[FL3.set,'Area 12 Settings'],[FL3.pay,'Area 13 Paywall'],[FL3.flows,'Flows 9, 10, 12, 13']].map(([h,l])=>`<a href="${encodeURI(h)}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">${l}</a>`).join(''));
  const intro3 = d('display:flex;flex-direction:column;gap:14px;max-width:1100px;', tx('l',C.t2,'GRIIT v48 · Atlas · Batch 3 of 4') + d(T.tl+'font-size:40px;line-height:46px;color:'+C.t1+';', 'Profiles, Activity, Create, Settings, Paywall') + tx('b',C.t2,'Areas 9–13 and flows 9, 10, 12 and 13. Home, Profile and Feed are frozen; this batch builds on their parts.') + nav);
  const changes3 = `<div style="display:flex;gap:24px;flex-wrap:wrap;align-items:flex-start;">` + panel(640, tx('l',C.t2,'What changed and why') + [
    ['Someone else’s profile','Same header and grid as your own. Visitors see shared proofs only, in the same day feed. Eight relationship states, each with one button.'],
    ['Activity','Every notification type with its copy and destination. Group invites accept inline. Boards: challenge boards only, ranked, unranked with neighbours, ties, solo, and a chip row that scrolls instead of clipping.'],
    ['Create','StepBasics with a live name check and the generated cover. Packs collapse and expand. The add-task sheet keeps its last field clear of the sticky button. Same-day wheel picker.'],
    ['Settings','Account with the full delete flow and the Apple subscription warning. Privacy as one switch with a who-sees-what table and a stranger preview. Blocked users, permissions and quiet hours. “Circle activity” is now “Group activity”.'],
    ['Paywall','USD examples, every string from RevenueCat. The billed amount is the biggest price; the monthly equivalent is secondary. Every purchase state.'],
    ['Batch 2 decisions','Tints in tokens; no map; a freeze holds the group streak; creator ownership passes to the longest-standing member; Delete removes from the feed only. The phone owner is Yaseen Abdelaziz (@yaseen) everywhere.'] ].map(([a,b])=>d('display:grid;grid-template-columns:150px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) +
    panel(420, tx('l',C.t2,'Self-score') + d('display:flex;align-items:baseline;gap:8px;', sp(NUM+'font-size:56px;line-height:60px;color:'+C.t1+';','8.7') + tx('t',C.t2,'/ 10')) + tx('s',C.t2,'Short of 9: build 75 screenshots still aren’t in the project, so “Built in 75” reads pending / not built / differs-by-description.','text-wrap:pretty;')) + '</div>';
  const CON3 = [
    ['206 Global board','Decided: Global doesn’t ship. Challenge boards only.'],
    ['207 Private account scope','Decided: accepted as drawn.'],
    ['208 Delete with Pro','Deleting doesn’t cancel an Apple subscription; the flow says so and links out. Apple requires the warning.'],
    ['209 Report reasons','Decided: reasons accepted. Minimum handling: every report emails the founder (griit.health@gmail.com) with the reporter, target, reason and a link. No queue yet.'],
    ['210 Board visibility','Turning off “Show me on challenge boards” hides you from boards but your days still count for the group streak.'],
    ['211 Contact address','Decided: griit.health@gmail.com until the domain is decided.'],
    ['194 Offline posting','Still flagged for engineering.'] ];
  const contra3 = `<div style="display:flex;flex-direction:column;gap:12px;">` + stripHead('Contradictions and flags, batch 3') + panel(1100, CON3.map(([a,b])=>d('display:grid;grid-template-columns:260px 1fr;gap:12px;', tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join('')) + '</div>';
  const idx3 = `<div style="display:flex;flex-direction:column;gap:12px;">` + stripHead(`Atlas index, batch 3 (${B3.length} frames)`) + panel(1300, `<div style="display:grid;grid-template-columns:60px 190px 220px 1fr 140px 220px;max-width:1260px;">` + [['#','Route','Component','State','Source','Built in 75']].concat(B3.map(k=>{const f=REG[k]; return [`<a href="${href(k)}" style="color:${C.t1};">${f.n}</a>`, f.route, f.comp, f.state, f.src||'new', f.b75||'pending'];})).map((r,ri)=>r.map((c,i)=>d(`${ri===0?T.c+'color:'+C.t2+';':(i===0?T.h:T.s)+'color:'+C.t1+';'}padding:10px 12px 10px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>') + '</div>';
  const flowFrames = d('display:flex;flex-direction:column;gap:22px;', stripHead('Frames drawn for the flows') + wrapRow([khalidNotif, pushSocial, actSocial, postOwn]));
  const sec = (id, eyebrow, title, purpose, note, body) => `<div style="display:flex;flex-direction:column;gap:22px;">` + areaHead(id, eyebrow, title, purpose, note) + body + '</div>';
  const wrapDoc = (parts) => `<div style="filter:{{ filt }};font-family:${FONT};color:${C.t1};padding:48px;display:flex;flex-direction:column;gap:80px;background:${C.ink};">` + parts.join('\n') + '</div>';
  return {
    [FL3.hub]: wrapDoc([intro3, changes3, contra3, flowFrames, idx3]),
    [FL3.prof]: wrapDoc([intro3, sec('a9','Area 9 · Someone else’s profile','Someone else’s profile','A visitor profile is for deciding whether to follow. Within 3 seconds: who this is, how consistent they are, and the one thing I can do.','Seen from Yaseen’s phone. Visitors see shared proofs only.', wrapRow(A9))]),
    [FL3.act]: wrapDoc([intro3, sec('a10','Area 10 · Activity','Activity','Activity is for what happened to me. Within 3 seconds: what’s new, and where a tap takes me.','The bell is the tab; its dot clears when Notifications is opened.', wrapRow(A10))]),
    [FL3.cr]: wrapDoc([intro3, sec('a11','Area 11 · Create','Create','Create is for setting up a challenge in under a minute. Within 3 seconds: which step, what’s missing, and the one button.','Tab bar hidden; the sticky button sits above the home indicator; sheets keep content above it.', wrapRow(A11))]),
    [FL3.set]: wrapDoc([intro3, sec('a12','Area 12 · Settings','Settings','Settings is for control. Within 3 seconds: where a setting lives and what it changes.','Plain rows on surface groups. No orange except the one primary where a screen has one.', wrapRow(A12))]),
    [FL3.pay]: wrapDoc([intro3, sec('a13','Area 13 · Paywall','Paywall','The paywall is for one honest decision. Within 3 seconds: what Pro adds, what it costs, and when I’m billed.','Every price string comes from RevenueCat. The billed amount is the largest price on screen.', wrapRow(A13))]),
    [FL3.flows]: wrapDoc([intro3, d('display:flex;flex-direction:column;gap:48px;', flows3.join(''))]),
  };
}
