// v49 · feed post, Your data, Apple Health, Home top. Runs after gen..b6: new Function(g1..g7+';return {build7, wrapFile};')
Object.assign(P, { bar:'<path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>' });
function build7(v47) {
  const pages6 = build6(v47);
  NEXT = 1001; BUILD_N = '77';
  const FL7 = { page:'GRIIT v49.dc.html', feed:'GRIIT v49 1 Feed.dc.html', data:'GRIIT v49 2 Your Data.dc.html', health:'GRIIT v49 3 Apple Health.dc.html', home:'GRIIT v49 4 Home Top.dc.html', b4:'GRIIT v48 Atlas B4.dc.html' };
  CUR = FL7.feed;
  const B7 = []; const F7 = (k, m, html) => { B7.push(k); return F(k, { b75:'pending', ...m }, html); };
  const HD = { yaseen:'yaseen', khalid:'khalidnoor', omar:'omar.s', bilal:'bilal.a', zayd:'zaydr', abd:'abdurrahman.af', sami:'sami', hamza:'hamza.idris' };
  const flex = (s, x) => d('display:flex;' + s, x);
  const panelR = (w, title, rows, cols='130px 1fr') => panel(w, tx('l',C.t2,title) + rows.map(([a,b])=>d(`display:grid;grid-template-columns:${cols};gap:12px;`, tx('h',C.t1,a) + tx('s',C.t2,b,'text-wrap:pretty;'))).join(''));

  // ================= 1 · FEED POST =================
  const actX = (p) => flex('align-items:center;margin-left:-10px;', [['heart',p.r,p.rOn],['msg',p.c],['share',p.s]].map(([i,n,on])=>flex('align-items:center;gap:6px;min-height:44px;min-width:76px;padding:0 10px;box-sizing:border-box;', ic(i,20,on?C.t1:C.t2,on?{fill:C.t1}:{}) + sp(`font-size:13px;line-height:18px;font-weight:500;font-variant-numeric:tabular-nums;color:${on?C.t1:C.t2};`, n||''))).join(''));
  const ctxLine = (p) => d(T.s+'color:'+C.t2+';', sp(`color:${C.t1};font-weight:500;`, p.ch) + ' · ' + p.day + ' · ' + p.task);
  const healthCard = (h) => d(`margin-top:4px;border-radius:12px;background:${C.surf};padding:14px;display:flex;flex-direction:column;gap:10px;`,
    flex('align-items:baseline;gap:6px;', sp(NUM+`font-size:40px;line-height:44px;color:${C.t1};`, h.dist) + tx('h',C.t2,h.unit)) +
    flex('gap:20px;', [[h.time,'Time'],[h.pace,'Pace'],[h.start,'Started']].map(([v,l])=>flex('flex-direction:column;', sp(NUM+`font-size:17px;line-height:22px;font-weight:700;color:${C.t1};`, v) + tx('c',C.t2,l))).join('')) +
    flex(`align-items:center;gap:6px;padding-top:10px;border-top:1px solid ${C.raised};`, ic('run',14,C.t2) + tx('c',C.t2,'From Apple Health' + (h.src?' · '+h.src:''))));
  const selfCard = (s) => d(`margin-top:4px;border-radius:12px;background:${C.surf};padding:14px;display:flex;align-items:center;gap:10px;`, doneDot(28) + flex('flex-direction:column;', tx('h',C.t1,s.task) + tx('s',C.t2,s.line)));
  const media = (p) => p.ph ? d(`position:relative;width:100%;aspect-ratio:4/5;border-radius:12px;overflow:hidden;background:${C.surf};margin-top:4px;`, img(p.ph[p.idx||0]) + d('position:absolute;left:10px;top:10px;', seal()) +
      (p.ph.length>1 ? d(`position:absolute;right:10px;top:10px;height:26px;padding:0 10px;border-radius:999px;background:rgba(15,15,15,0.62);${T.c}color:${C.t1};display:flex;align-items:center;`, `${(p.idx||0)+1} of ${p.ph.length}`) + d('position:absolute;left:10px;right:10px;bottom:10px;display:flex;gap:4px;', p.ph.map((x,i)=>d(`flex:1;height:2px;border-radius:1px;background:${i===(p.idx||0)?C.t1:'rgba(242,240,235,0.35)'};`)).join('')) : ''))
    : p.ah ? healthCard(p.ah) : p.self ? selfCard(p.self) : '';
  const nameRow = (p) => flex('align-items:center;gap:4px;min-width:0;', sp(T.h+`color:${C.t1};white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:0 1 auto;min-width:0;`, PPL[p.who][0]) + sp(T.s+`color:${C.t2};white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex:0 100 auto;min-width:0;`, '@'+HD[p.who]) + sp(T.s+`color:${C.t2};flex:none;white-space:nowrap;`, '· '+p.time) + d('flex:1') + d('width:44px;height:44px;margin:-12px -12px -12px 0;display:flex;align-items:center;justify-content:center;flex:none;', ic('more',18,C.t2)));
  const xPost = (p) => d(`display:flex;gap:12px;padding:12px 16px 2px;border-bottom:1px solid ${C.hair};`,
    flex('flex-direction:column;align-items:center;flex:none;', av(p.who,40)) +
    d('flex:1;min-width:0;display:flex;flex-direction:column;gap:3px;', nameRow(p) + ctxLine(p) + (p.cap?tx('b',C.t1,p.cap,'margin-top:2px;text-wrap:pretty;'):'') + media(p) + actX(p)));
  const actLine = (ks, text, time) => d(`display:flex;align-items:center;gap:12px;padding:8px 16px;min-height:44px;box-sizing:border-box;border-bottom:1px solid ${C.hair};`, flex('width:40px;justify-content:flex-end;flex:none;', ks.slice(0,3).map((k,i)=>d(i?'margin-left:-6px;':'', av(k,18,C.ink))).join('')) + d(`font-size:13px;line-height:18px;color:${C.t2};flex:1;`, text) + tx('c',C.t2,time));
  const P1 = { who:'khalid', time:'12m', ch:'Read 30', day:'Day 15 of 30', task:'Read 10 pages', cap:'Before work. Chapter 9 is where it turns.', ph:['book1'], r:'12', c:'3', s:'1' };
  const P2 = { who:'omar', time:'28m', ch:'Up by 5', day:'Day 5 of 7', task:'Out of bed', cap:'Cold floor. Still up.', self:{ task:'Out of bed', line:'Self-reported · 4:52 am' }, r:'8', c:'1', s:'' };
  const P3 = { who:'hamza', time:'1h', ch:'Run 21', day:'Day 9 of 21', task:'Run 5 km', cap:'Legs were heavy for the first two.', ah:{ dist:'5.2', unit:'km', time:'27:41', pace:'5:19 /km', start:'6:12 am', src:'Strava' }, r:'21', c:'4', s:'2', rOn:true };
  const P4 = { who:'bilal', time:'2h', ch:'Lift 3×', day:'Week 3 of 8', task:'Train', cap:'Squats, then the part nobody likes.', ph:['gym1','gym3'], r:'15', c:'2', s:'' };
  const P5 = { who:'abd', time:'3h', ch:'Fajr 30', day:'Day 30 of 30', task:'Pray Fajr on time', cap:'Thirty mornings. Some of them were ugly: two alarms and a cold floor. Still here.', ph:['pray1'], r:'44', c:'9', s:'3' };
  const ACT = actLine(['bilal','zayd','sami'], 'Bilal, Zayd and 2 others started Up by 5.', '1h');
  const feedMid = xPost(P2) + ACT + xPost(P3) + xPost(P4);
  const feedEnd = xPost(P4) + xPost(P5) + d('height:24px');
  const FD = [];
  const fFields = 'name ← profiles.display_name · @ ← profiles.username · time ← proofs.shared_at · line ← challenges.title · enrollment.day_index/duration · tasks.title · counts ← posts.respect_count, comment_count, share_count';
  FD.push(F7('xFeed0', { route:'(tabs)/index · feed', comp:'FeedPost v49', state:'Realistic feed, top · Home scrolled to Feed', src:'v48 5 Feed', fields:fFields }, phone({ time:'9:41', tab:'home', body: feedHead(0) + xPost(P1) + xPost(P2) })));
  FD.push(F7('xFeed1', { route:'(tabs)/index · feed', comp:'FeedPost v49', state:'Same feed, scrolled · self-reported card, grouped activity, Apple Health run', src:'new' }, phone({ time:'9:41', tab:'home', body: feedMid })));
  FD.push(F7('xFeed2', { route:'(tabs)/index · feed', comp:'FeedPost v49', state:'Same feed, end · two-photo post, 32-char name truncates the handle first', src:'new' }, phone({ time:'9:41', tab:'home', scroll:380, body: feedEnd })));
  const pop = d(`position:absolute;left:150px;top:150px;z-index:30;display:flex;flex-direction:column;align-items:flex-start;`, d(`width:0;height:0;margin-left:62px;border-left:7px solid transparent;border-right:7px solid transparent;border-bottom:7px solid ${C.t1};`) + d(`padding:8px 12px;border-radius:10px;background:${C.t1};${T.h}color:${C.ink};white-space:nowrap;box-shadow:0 8px 24px rgba(0,0,0,0.5);`, '9:29 am · Wed, Oct 7, 2026'));
  FD.push(F7('xDate', { route:'(tabs)/index · feed', comp:'FeedPost v49', state:'Tap the time → full date', src:'new', fields:'proofs.shared_at in the viewer’s locale; closes on any tap or scroll' }, phone({ time:'9:41', tab:'home', body: feedHead(0) + xPost(P1), overlay: pop })));
  // thread
  const reply = (k, text, time, o={}) => d(`display:flex;gap:12px;padding:${o.top?'0':'12px'} 16px 0;`, flex('flex-direction:column;align-items:center;flex:none;width:40px;', (o.top?d(`width:2px;height:12px;background:${C.raised};`):'') + av(k,o.s||32) + (o.line?d(`width:2px;flex:1;min-height:12px;background:${C.raised};margin-top:4px;`):'')) +
    d('flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;padding-bottom:4px;', flex('align-items:center;gap:4px;', sp(T.h+'color:'+C.t1+';white-space:nowrap;', PPL[k][0]) + sp(T.s+'color:'+C.t2+';', '@'+HD[k]+' · '+time)) + (o.to?tx('s',C.t2,'Replying to @'+HD[o.to]):'') + tx('b',C.t1,text) + flex('align-items:center;margin-left:-10px;', [['heart',o.r||''],['msg','']].map(([i,n])=>flex('align-items:center;gap:6px;min-height:40px;min-width:60px;padding:0 10px;', ic(i,18,C.t2) + sp('font-size:13px;color:'+C.t2+';', n))).join(''))));
  const threadBody = stepHead('Post','',{back:true}) + d('padding:4px 16px 0;display:flex;flex-direction:column;gap:8px;',
      flex('align-items:center;gap:12px;', av('khalid',40) + flex('flex-direction:column;flex:1;min-width:0;', tx('h',C.t1,PPL.khalid[0]) + tx('s',C.t2,'@khalidnoor')) + ic('more',18,C.t2)) +
      ctxLine(P1) + tx('b',C.t1,P1.cap,'font-size:17px;line-height:23px;') + d(`position:relative;width:100%;aspect-ratio:4/5;border-radius:12px;overflow:hidden;`, img('book1') + d('position:absolute;left:10px;top:10px;', seal())) +
      tx('s',C.t2,'9:29 am · Wed, Oct 7, 2026 · Camera') +
      d(`display:flex;gap:16px;padding:10px 0;border-top:1px solid ${C.hair};border-bottom:1px solid ${C.hair};${T.s}color:${C.t2};`, [['12','Respect'],['3','Comments'],['1','Share']].map(([n,l])=>sp('', sp(`color:${C.t1};font-weight:600;`, n) + ' ' + l)).join('')) +
      flex('justify-content:space-around;', [['heart',1],['msg'],['share']].map(([i,on])=>d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic(i,22,C.t1,on?{fill:C.t1}:{}))).join(''))) +
    d(`border-top:1px solid ${C.hair};`) +
    reply('omar','Same book. Chapter 9 is the turn.','9m',{r:'2'}) + reply('yaseen','Which edition are you reading?','4m',{line:true}) + reply('khalid','Penguin. Footnotes at the back.','2m',{top:true,to:'yaseen',r:'1'}) + d('height:70px');
  const composerX = d(`position:absolute;left:0;right:0;bottom:34px;z-index:14;padding:8px 12px;background:${C.ink};border-top:1px solid ${C.hair};display:flex;align-items:center;gap:10px;`, av('yaseen',32) + d(`flex:1;height:40px;border-radius:20px;background:${C.surf};display:flex;align-items:center;padding:0 14px;${T.b}color:${C.t2};`, 'Reply to Khalid'));
  FD.push(F7('xThread', { route:'post/[id]', comp:'PostThread', state:'Thread · full date, counts, replies with thread lines', src:'v12 39', fields:'replies ← comments(post_id) oldest first, parent_id threads one level; respect toggles posts.respected_by_me' }, phone({ time:'9:41', scroll:330, body: threadBody, overlay: composerX })));
  FD.push(F7('xThreadTop', { route:'post/[id]', comp:'PostThread', state:'Thread opened · top', src:'new' }, phone({ time:'9:41', body: threadBody, overlay: composerX })));
  const sugg = (k, sub) => flex('align-items:center;gap:12px;min-height:56px;', av(k,40) + flex('flex-direction:column;flex:1;min-width:0;', tx('h',C.t1,PPL[k][0]) + tx('s',C.t2,sub)) + btnS('Follow'));
  FD.push(F7('xEmpty', { route:'(tabs)/index · feed', comp:'FeedEmpty', state:'Empty · follows no one yet', src:'v48 5 Feed', fields:'suggestions ← members of my challenges first, then active people in my challenges’ categories' }, phone({ time:'9:41', tab:'home', body: feedHead(0) + d('padding:28px 16px 0;display:flex;flex-direction:column;gap:6px;', tx('t',C.t1,'Your feed fills up when people post proof.') + tx('b',C.t2,'Follow people from your challenges to see their days here.')) + d('padding:16px 16px 0;display:flex;flex-direction:column;gap:4px;', tx('l',C.t2,'In Read 30 with you','padding-bottom:4px;') + sugg('khalid','Day 15 of 30 · 14-day streak') + sugg('omar','Day 9 of 30 · 9-day streak') + sugg('sami','Day 3 of 30')) + d('padding:12px 16px;', btnS('Find people',{icon:'userplus'})) })));
  FD.push(F7('xSparse', { route:'(tabs)/index · feed', comp:'FeedPost v49', state:'Sparse · one post today, end of feed', src:'new' }, phone({ time:'9:41', tab:'home', body: feedHead(0) + xPost(P1) + actLine(['omar'], 'Omar started Up by 5.', '2h') + d('padding:20px 16px 0;display:flex;flex-direction:column;gap:4px;', tx('h',C.t1,'That’s everything from today.') + tx('s',C.t2,'Follow more people to see more days.') + d('height:8px') + sugg('sami','In Read 30 with you')) })));
  NEXT = 1031;
  const zTop = (n) => d(`position:absolute;left:0;right:0;top:59px;height:52px;z-index:22;display:flex;align-items:center;justify-content:space-between;padding:0 6px;`, d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('x',24)) + (n?d(`height:28px;padding:0 12px;border-radius:999px;background:rgba(15,15,15,0.62);${T.c}color:${C.t1};display:flex;align-items:center;`, n):'') + d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic('more',20)));
  const zFoot = (p) => d(`position:absolute;left:0;right:0;bottom:34px;z-index:22;padding:20px 16px 4px;display:flex;flex-direction:column;gap:4px;background:linear-gradient(transparent,rgba(15,15,15,0.9) 30%);`, flex('align-items:center;gap:8px;', av(p.who,24) + tx('h',C.t1,PPL[p.who][0])) + ctxLine(p) + flex('gap:20px;', [['heart',p.r],['msg',p.c],['share',p.s]].map(([i,n])=>flex('align-items:center;gap:6px;min-height:44px;', ic(i,22) + sp(T.c+'color:'+C.t1+';', n||''))).join('')));
  const zPh = (ph, x=0, y=0, sc=1) => d(`position:absolute;left:0;top:${170+y}px;width:393px;height:491px;transform:translateX(${x}px) scale(${sc});`, img(ph));
  const zDots = (n, i) => d('position:absolute;left:0;right:0;top:670px;z-index:21;display:flex;justify-content:center;gap:6px;', Array.from({length:n},(_,k)=>d(`width:6px;height:6px;border-radius:999px;background:${k===i?C.t1:C.t3};`)).join(''));
  const ZM = [];
  ZM.push(F7('zOne', { route:'post/[id]/photo', comp:'PhotoZoom', state:'Tap a photo → full screen · single photo, no counter', src:'new', fields:'pinch up to 3×, double-tap 2× · tap toggles the caption and actions' }, phone({ time:'9:41', full: zPh('book1') + zTop('') + zFoot(P1) })));
  ZM.push(F7('zDown', { route:'post/[id]/photo', comp:'PhotoZoom', state:'Swipe down to dismiss · photo shrinks, feed shows through', src:'new', fields:'dismiss past 120pt or a fast flick; otherwise springs back' }, phone({ time:'9:41', full: d('position:absolute;left:0;right:0;top:59px;bottom:0;overflow:hidden;', feedHead(0) + xPost(P1)) + d('position:absolute;inset:0;background:rgba(15,15,15,0.55);z-index:5;') + d('position:absolute;inset:0;z-index:6;', zPh('book1',0,150,0.8)) + d(`position:absolute;left:0;right:0;top:120px;z-index:22;display:flex;justify-content:center;`, d(`height:28px;padding:0 12px;border-radius:999px;background:${C.raised};${T.c}color:${C.t1};display:flex;align-items:center;gap:6px;`, ic('cd',14) + 'Release to close')) })));
  ZM.push(F7('zMulti1', { route:'post/[id]/photo', comp:'PhotoZoom', state:'Two-photo post · 1 of 2', src:'new' }, phone({ time:'9:41', full: zPh('gym1') + zTop('1 of 2') + zDots(2,0) + zFoot(P4) })));
  ZM.push(F7('zMulti2', { route:'post/[id]/photo', comp:'PhotoZoom', state:'Swiping to photo 2 · counter reads 2 of 2 once past halfway', src:'new' }, phone({ time:'9:41', full: zPh('gym1',-230) + zPh('gym3',163) + zTop('2 of 2') + zDots(2,1) + zFoot(P4) })));
  const zRules = panelR(560, 'Photo zoom rules', [['Open','Tap the photo in the feed or thread. The photo grows from its spot in the feed.'],['Close','Swipe down past 120pt or flick; X top left. Returns to the same scroll spot.'],['Several','Swipe sideways. “1 of 2” top centre plus dots; the feed post opens on the photo you tapped.'],['Chrome','Name, context line and actions sit on a bottom fade. Tap the photo to hide them.'],['Zoom','Pinch up to 3×, double-tap 2×. Sideways swipe is off while zoomed in.']], '90px 1fr');
  NEXT = 1009;
  const fRules = panelR(560, 'Feed post rules', [
    ['Header','Avatar 40 · name (Headline) · @handle · time. The handle truncates before the name. Tap the time for the full date; the thread always shows it.'],
    ['Context','One line: challenge (Text 1) · Day n of N · task. Tap opens the challenge.'],
    ['Body','Caption, then a 4:5 photo with the camera seal, a self-reported card, or an Apple Health card. Never a bare text post.'],
    ['Actions','Respect · Comment · Share with counts. Zero shows no number. Respected = filled icon in Text 1, never orange.'],
    ['Open','Tapping anywhere except an action opens the thread.'],
    ['Activity','“Started X”, “joined X” lines are grouped per challenge per hour, 13pt Text 2 with 18pt faces. Never a card, never above a proof.'],
    ['Share count','Counts card shares and copied links. Decision 218.'] ]);

  // ================= 2 · YOUR DATA =================
  CUR = FL7.data;
  const pTop = (o) => d('display:flex;align-items:center;justify-content:space-between;height:44px;padding:0 6px 0 16px;', tx('h',C.t1,'@yaseen') + flex('', ['share','gear'].map(i=>d('width:44px;height:44px;display:flex;align-items:center;justify-content:center;', ic(i,20))).join(''))) +
    d('padding:8px 16px 0;display:flex;flex-direction:column;gap:12px;', flex('align-items:center;gap:16px;', av('yaseen',80) + d('flex:1;display:grid;grid-template-columns:repeat(3,1fr);gap:4px;', [[o.streak,'Streak'],[o.best,'Best'],[o.sec,'Days secured']].map(([n,l])=>flex('flex-direction:column;', sp(NUM+`font-size:24px;line-height:28px;color:${C.t1};`, n) + tx('c',C.t2,l))).join(''))) +
      flex('flex-direction:column;gap:2px;', tx('h',C.t1,PPL.yaseen[0]) + tx('b',C.t1,'Reading before work. Up before the city.') + tx('s',C.t2,o.fol||'128 followers · 96 following')) +
      flex('gap:8px;', btnS('Edit profile',{flex:1}) + btnS('Find people',{flex:1,icon:'userplus'})));
  const pTabs = (sel) => d(`display:flex;background:${C.ink};border-bottom:1px solid ${C.hair};`, [['grid','Proofs'],['bar','Your data'],['flag','Challenges'],['award','Badges']].map(([i,l],k)=>d(`flex:1;height:44px;display:flex;align-items:center;justify-content:center;gap:5px;border-bottom:2px solid ${k===sel?C.t1:'transparent'};margin-bottom:-1px;`, ic(i,16,k===sel?C.t1:C.t2) + tx('c',k===sel?C.t1:C.t2,l,'white-space:nowrap;'))).join(''));
  const card = (title, inner, right) => d(`background:${C.surf};border-radius:16px;padding:14px 16px 16px;display:flex;flex-direction:column;gap:12px;`, flex('align-items:baseline;justify-content:space-between;gap:8px;', tx('l',C.t2,title) + (right?tx('c',C.t2,right):'')) + inner);
  // day states, Jul 20 (Mon) .. Oct 11 (Sun); idx 48 = Sep 6, 79 = Oct 7 (today)
  const stA = (i) => i<48?'none':i<58?'S':i===58?'H':i<67?'S':i===67?'M':i<71?'S':i===71?'M':i<79?'S':i===79?'today':'fut';
  const stN = (i) => i<78?'none':i===78?'S':i===79?'today':'fut';
  const cnt = (f) => { const c = {S:0,H:0,M:0}; for (let i=0;i<84;i++){ const s=f(i); if (c[s]!==undefined) c[s]++; } return c; };
  const CA = cnt(stA); const dueA = CA.S+CA.H+CA.M; const pctA = Math.round(CA.S/dueA*100);
  const cell = (s, z=21) => { const b = `width:${z}px;height:${z}px;border-radius:4px;box-sizing:border-box;`;
    return s==='S'?d(b+`background:${C.t1};`):s==='H'?d(b+`background:${C.raised};box-shadow:inset 0 0 0 1.5px ${C.miss};display:flex;align-items:center;justify-content:center;`, ic('snow',11,C.t2)):s==='M'?d(b+`box-shadow:inset 0 0 0 1.5px ${C.miss};`):s==='today'?d(b+`box-shadow:inset 0 0 0 2px ${C.t1};`):s==='fut'?d(b+`border:1px dashed ${C.t3};`):d(b+`background:${C.hair};`); };
  const heat = (f) => { const mon = {0:'Jul',2:'Aug',6:'Sep',10:'Oct'};
    return flex('flex-direction:column;gap:4px;', flex('gap:4px;padding-left:20px;', Array.from({length:12},(_,c)=>d(`width:21px;${T.c}font-size:11px;line-height:13px;color:${C.t2};white-space:nowrap;overflow:visible;`, mon[c]||'')).join('')) +
      flex('gap:4px;', d('display:flex;flex-direction:column;gap:4px;width:16px;', 'MTWTFSS'.split('').map((l,r)=>d(`height:21px;${T.c}font-size:11px;line-height:21px;color:${C.t2};`, r%2?'':l)).join('')) + Array.from({length:12},(_,c)=>d('display:flex;flex-direction:column;gap:4px;', Array.from({length:7},(_,r)=>cell(f(c*7+r))).join(''))).join(''))) +
      flex('gap:12px;flex-wrap:wrap;padding-top:4px;', [['S','Secured'],['H','Held'],['M','Missed'],['none','Not due']].map(([s,l])=>flex('align-items:center;gap:6px;', cell(s,12) + tx('c',C.t2,l))).join('')); };
  const chBar = (name, a, b, sub) => flex('flex-direction:column;gap:6px;', flex('justify-content:space-between;align-items:baseline;', tx('h',C.t1,name) + d(T.s+`color:${C.t1};font-variant-numeric:tabular-nums;`, `${a} of ${b}`)) + d(`height:6px;border-radius:3px;background:${C.raised};overflow:hidden;`, d(`width:${a/b*100}%;height:100%;background:${C.t1};border-radius:3px;`)) + tx('c',C.t2,sub));
  const split = (parts) => { const tot = parts.reduce((s,p)=>s+p[1],0);
    return d(`display:flex;height:10px;border-radius:5px;overflow:hidden;background:${C.raised};gap:2px;`, parts.filter(p=>p[1]).map(p=>d(`width:${p[1]/tot*100}%;background:${p[2]};`)).join('')) +
      flex('flex-direction:column;gap:6px;', parts.map(([l,n,c,note])=>flex('align-items:center;gap:8px;min-height:22px;', d(`width:10px;height:10px;border-radius:3px;flex:none;${n?`background:${c};`:`box-shadow:inset 0 0 0 1px ${C.t3};`}`) + tx('s',C.t1,l,'flex:1;') + (note?tx('c',C.t2,note):'') + d(T.s+`color:${C.t1};font-variant-numeric:tabular-nums;width:72px;text-align:right;`, n ? `${n} · ${Math.round(n/tot*100)}%` : '0'))).join('')); };
  const HIST = [0,0,0,0,5,24,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
  const hist = (h) => { const mx = Math.max(...h);
    return flex('align-items:flex-end;gap:2px;height:72px;', h.map((n,i)=>d(`flex:1;height:${n?Math.max(4,n/mx*72):2}px;border-radius:2px;background:${i===5?C.t1:n?C.t3:C.raised};`)).join('')) +
      d(`display:grid;grid-template-columns:repeat(4,1fr) auto;${T.c}font-size:11px;line-height:13px;color:${C.t2};`, ['12 am','6 am','12 pm','6 pm','11 pm'].map(l=>d('', l)).join('')); };
  const dataA = d('padding:16px 16px 24px;display:flex;flex-direction:column;gap:12px;', tx('c',C.t2,'Since you joined on Sep 6. Today counts once it ends.') +
    card('Consistency', flex('align-items:baseline;gap:2px;', sp(NUM+`font-size:64px;line-height:64px;color:${C.t1};`, pctA) + sp(NUM+`font-size:28px;color:${C.t2};`, '%')) + tx('b',C.t1,`${CA.S} of ${dueA} due days secured`) + tx('s',C.t2,`Held (${CA.H}) and missed (${CA.M}) days count as due.`)) +
    d('display:grid;grid-template-columns:1fr 1fr;gap:12px;', card('Current streak', flex('align-items:center;gap:6px;', flame(22) + sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '7')) + tx('c',C.t2,'days in a row')) + card('Best streak', sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '18') + tx('c',C.t2,'Sep 6 – Sep 24'))) +
    card('Last 12 weeks', heat(stA)) +
    card('By challenge', chBar('Up by 5', 4, 4, 'Due days secured · Day 5 of 7, running') + chBar('Read 30', 1, 1, 'Due days secured · Day 2 of 30, running') + chBar('Fajr 30', 27, 30, 'Days secured · finished Oct 5'), 'secured of due') +
    card('How you prove it', split([['Camera', 28, C.t1],['Self-reported', 4, C.t2],['Apple Health', 0, C.t3, 'Not connected']]), '32 proofs') +
    card('When you post', tx('b',C.t1,'Usually 5–6 am') + hist(HIST) + tx('c',C.t2,'24 of 32 proofs landed between 5 and 6 am.')));
  const dataN = d('padding:16px 16px 24px;display:flex;flex-direction:column;gap:12px;', tx('c',C.t2,'Since you joined yesterday. Today counts once it ends.') +
    card('Consistency', flex('align-items:baseline;gap:6px;', sp(NUM+`font-size:64px;line-height:64px;color:${C.t1};`, '1') + tx('t',C.t2,'of 1 due day')) + tx('b',C.t1,'secured') + tx('s',C.t2,'Your percentage shows after 7 due days. 6 to go.')) +
    d('display:grid;grid-template-columns:1fr 1fr;gap:12px;', card('Current streak', flex('align-items:center;gap:6px;', flame(22) + sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '1')) + tx('c',C.t2,'day in a row')) + card('Best streak', sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '1') + tx('c',C.t2,'Oct 6'))) +
    card('Last 12 weeks', heat(stN), 'Joined Oct 6') +
    card('By challenge', chBar('Read 30', 1, 1, 'Due days secured · Day 2 of 30, running'), 'secured of due') +
    card('How you prove it', split([['Camera', 1, C.t1],['Self-reported', 0, C.t2],['Apple Health', 0, C.t3, 'Not connected']]), '1 proof') +
    card('When you post', tx('s',C.t2,'Shows after 5 proofs. 4 to go.')));
  const stickyTabs = (sel) => d(`position:absolute;left:0;right:0;top:59px;z-index:14;`, pTabs(sel));
  const PA = { streak:'7', best:'18', sec:String(CA.S) }, PN = { streak:'1', best:'1', sec:'1', fol:'3 followers · 12 following' };
  const dFields = `${pctA}% ← user_stats.secured_days ÷ user_stats.due_days (${CA.S} ÷ ${dueA}) · streaks ← current_streak, best_streak (+ best_streak_start, _end)`;
  const DT = [];
  DT.push(F7('dA0', { route:'(tabs)/profile', comp:'YourDataTab', state:'Active user · top', src:'new', fields:dFields }, phone({ time:'9:41', tab:'profile', body: pTop(PA) + d('height:14px') + pTabs(1) + dataA })));
  DT.push(F7('dA1', { route:'(tabs)/profile', comp:'YourDataTab', state:'Active user · heat map and challenges', src:'new', fields:'heat map ← day_secures[date].state (secured | held | missed | none), 84 days · bars ← enrollments[].secured_days ÷ due_days, status' }, phone({ time:'9:41', tab:'profile', scroll:0, body: d('height:44px') + dataA.replace(/^<div style="padding:16px 16px 24px;/, '<div style="margin-top:-220px;padding:16px 16px 24px;'), overlay: stickyTabs(1) })));
  DT.push(F7('dA2', { route:'(tabs)/profile', comp:'YourDataTab', state:'Active user · method split and time of day', src:'new', fields:'split ← user_stats.proofs_by_method {camera, self_reported, apple_health} · time ← user_stats.proof_hour_histogram[24] (local), usual_window = modal hour' }, phone({ time:'9:41', tab:'profile', scroll:0, body: d('height:44px') + dataA.replace(/^<div style="padding:16px 16px 24px;/, '<div style="margin-top:-660px;padding:16px 16px 24px;'), overlay: stickyTabs(1) })));
  DT.push(F7('dN0', { route:'(tabs)/profile', comp:'YourDataTab', state:'New user · 1 day secured · no % until 7 due days', src:'new', fields:'percent hidden while user_stats.due_days < 7' }, phone({ time:'9:41', tab:'profile', body: pTop(PN) + d('height:14px') + pTabs(1) + dataN })));
  DT.push(F7('dN1', { route:'(tabs)/profile', comp:'YourDataTab', state:'New user · scrolled', src:'new', fields:'time of day hidden while proofs < 5' }, phone({ time:'9:41', tab:'profile', scroll:0, body: d('height:44px') + dataN.replace(/^<div style="padding:16px 16px 24px;/, '<div style="margin-top:-220px;padding:16px 16px 24px;'), overlay: stickyTabs(1) })));
  // challenges tab
  const segBar = (states) => flex('gap:2px;', states.map(s=>d(`flex:1;height:10px;border-radius:2px;box-sizing:border-box;${s==='S'?`background:${C.t1};`:s==='H'?`background:${C.raised};box-shadow:inset 0 0 0 1px ${C.miss};`:s==='M'?`box-shadow:inset 0 0 0 1px ${C.miss};`:s==='today'?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:`background:${C.raised};`}`)).join(''));
  const rng = (a,b,f) => Array.from({length:b-a+1},(_,i)=>f(a+i));
  const chCard = (o) => d(`background:${C.surf};border-radius:16px;padding:14px 16px;display:flex;flex-direction:column;gap:10px;`, flex('align-items:baseline;justify-content:space-between;gap:8px;', tx('h',C.t1,o.name) + tx('s',C.t2,o.when)) + segBar(o.bar) + tx('s',C.t1,o.line) + ic('cr',0));
  const chList = d('padding:16px 16px 24px;display:flex;flex-direction:column;gap:12px;', tx('c',C.t2,'Each bar is one challenge, one block per day. Filled = secured.') +
    flex('align-items:baseline;justify-content:space-between;padding-top:4px;', tx('t',C.t1,'Running') + tx('s',C.t2,'2')) +
    chCard({ name:'Up by 5', when:'Day 5 of 7', bar: rng(75,81,stA), line:'4 of 4 days so far secured. 2 days to go.' }) +
    chCard({ name:'Read 30', when:'Day 2 of 30', bar: rng(78,107,i=>i<80?stA(i):'fut'), line:'1 of 1 day so far secured. 28 days to go.' }) +
    flex('align-items:baseline;justify-content:space-between;padding-top:8px;', tx('t',C.t1,'Finished') + tx('s',C.t2,'1')) +
    chCard({ name:'Fajr 30', when:'Finished Oct 5', bar: rng(48,77,stA), line:'27 of 30 days secured. Longest streak 18. 1 day held by a freeze.' }));
  DT.push(F7('dCh', { route:'(tabs)/profile', comp:'ProfileChallengesTab', state:'Running / finished, one plain line per challenge', src:'v48 8 Profile', fields:'enrollments[] status running|finished · day_index/duration · secured_days, held_days, missed_days · longest_streak' }, phone({ time:'9:41', tab:'profile', body: d('height:44px') + chList, overlay: stickyTabs(2) })));
  NEXT = 1041;
  const inR = (a,b) => (i) => i>=a && i<=b;
  const cntR = (a,b) => { const c = {S:0,H:0,M:0}; for (let i=a;i<=b;i++){ const x=stA(i); if (c[x]!==undefined) c[x]++; } return c; };
  const R7 = cntR(72,78), R30 = cntR(49,78);
  const RG = {
    '7d': { c:R7, note:'Sep 30 – Oct 6', ch:[['Up by 5',4,4],['Read 30',1,1],['Fajr 30',6,6,'finished Oct 5']], sp:[7,4], hist:[0,0,0,0,2,8,0,1].concat(Array(16).fill(0)), usual:'8 of 11', tot:11 },
    '30d': { c:R30, note:'Sep 7 – Oct 6', ch:[['Up by 5',4,4],['Read 30',1,1],['Fajr 30',cntR(49,77).S,cntR(49,77).S+cntR(49,77).H+cntR(49,77).M,'finished Oct 5']], sp:[cntR(49,77).S+1,4], hist:[0,0,0,0,5,23,2,1].concat(Array(16).fill(0)), usual:'23 of 31', tot:31 },
    'All': { c:CA, note:'Since Sep 6', ch:[['Up by 5',4,4],['Read 30',1,1],['Fajr 30',27,30,'finished Oct 5']], sp:[28,4], hist:HIST, usual:'24 of 32', tot:32 } };
  const dueOf = (c) => c.S+c.H+c.M;
  const segRow = (sel, note) => flex('align-items:center;gap:10px;', seg(['7d','30d','All'], sel) + d('flex:1') + tx('c',C.t2,note));
  const heatR = (k) => k==='7d'
    ? flex('gap:6px;', rng(72,78,i=>flex('flex:1;flex-direction:column;align-items:center;gap:4px;', tx('c',C.t2,'MTWTFSS'[i%7]) + cell(stA(i),36))).join(''))
    : flex('gap:4px;', d('display:flex;flex-direction:column;gap:4px;width:16px;', 'MTWTFSS'.split('').map((l,r)=>d(`height:28px;${T.c}font-size:11px;line-height:28px;color:${C.t2};`, r%2?'':l)).join('')) + rng(k==='30d'?7:6, 11, c=>d('display:flex;flex-direction:column;gap:4px;', Array.from({length:7},(_,r)=>{ const i=c*7+r; const ok = k==='30d' ? (i>=49) : true; return cell(ok?stA(i):'none', 28); }).join(''))).join(''));
  const cardsR = (k) => { const r = RG[k], due = dueOf(r.c), pct = Math.round(r.c.S/due*100);
    return { cons: card('Consistency', flex('align-items:baseline;gap:2px;', sp(NUM+`font-size:64px;line-height:64px;color:${C.t1};`, pct) + sp(NUM+`font-size:28px;color:${C.t2};`, '%')) + tx('b',C.t1,`${r.c.S} of ${due} due days secured`) + tx('s',C.t2, r.c.H+r.c.M ? `Held (${r.c.H}) and missed (${r.c.M}) days count as due.` : 'No held or missed days in this range.'), r.note),
      heat: card(k==='7d'?'Last 7 days':k==='30d'?'Last 30 days':'Since you joined', heatR(k)),
      ch: card('By challenge', r.ch.map(([n,a,b,f])=>chBar(n,a,b, f ? 'Days secured · '+f : 'Due days secured · running')).join(''), 'secured of due'),
      split: card('How you prove it', split([['Camera', r.sp[0], C.t1],['Self-reported', r.sp[1], C.t2],['Apple Health', 0, C.t3, 'Not connected']]), r.tot+' proofs'),
      time: card('When you post', tx('b',C.t1,'Usually 5–6 am') + hist(r.hist) + tx('c',C.t2, r.usual+' proofs landed between 5 and 6 am.')) }; };
  const cardsE = { cons: card('Consistency', tx('t',C.t1,'No due days yet') + tx('s',C.t2,'Your first day counts tonight, once it ends.')), heat: card('Since you joined', flex('gap:6px;', rng(77,83,i=>flex('flex:1;flex-direction:column;align-items:center;gap:4px;', tx('c',C.t2,'MTWTFSS'[i%7]) + cell(i===79?'today':i>79?'fut':'none',36))).join('')) + tx('c',C.t2,'Joined today.')),
    ch: card('By challenge', chBar('Read 30', 0, 1, 'Day 1 of 30 · first day ends tonight').replace('0 of 1','0 of 0'), 'secured of due'), split: card('How you prove it', tx('s',C.t2,'No proofs yet. Your first one shows here.')), time: card('When you post', tx('s',C.t2,'Shows after 5 proofs.')) };
  const CR = { '7d':cardsR('7d'), '30d':cardsR('30d'), 'All':cardsR('All'), 'Empty · 0 days':cardsE };
  const matrix = panel(4*361+3*16+40, tx('l',C.t2,'Every chart in every range, plus the empty state (new user, 0 days). Streaks ignore the range; they are all-time.') +
    d('display:grid;grid-template-columns:repeat(4,361px);gap:16px;align-items:start;', Object.keys(CR).map(k=>tx('h',C.t1,k)).join('') + ['cons','heat','ch','split','time'].map(row=>Object.keys(CR).map(k=>CR[k][row]).join('')).join('')));
  const RF = [];
  const rangeTop = (k, sel) => { const c = CR[k]; return d('padding:12px 16px 24px;display:flex;flex-direction:column;gap:12px;', segRow(sel, 'Streaks are all-time') + c.cons + d('display:grid;grid-template-columns:1fr 1fr;gap:12px;', card('Current streak', flex('align-items:center;gap:6px;', flame(22) + sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '7')) + tx('c',C.t2,'days in a row')) + card('Best streak', sp(NUM+`font-size:36px;line-height:40px;color:${C.t1};`, '18') + tx('c',C.t2,'Sep 6 – Sep 24'))) + c.heat); };
  [['7d',0],['30d',1],['All',2]].forEach(([k,sel])=>RF.push(F7('dR'+k, { route:'(tabs)/profile', comp:'YourDataTab', state:`Range ${k} selected · inverted segment, no orange`, src:'new', fields:'GET /me/stats?range=7d|30d|all · streaks unaffected' }, phone({ time:'9:41', tab:'profile', body: d('height:44px') + rangeTop(k, sel), overlay: stickyTabs(1) }))));
  RF.push(F7('dR0', { route:'(tabs)/profile', comp:'YourDataTab', state:'Empty · new user, 0 days', src:'new', fields:'user_stats.due_days = 0 → no %, no bars, no histogram' }, phone({ time:'9:41', tab:'profile', body: pTop({ streak:'0', best:'0', sec:'0', fol:'0 followers · 4 following' }) + d('height:14px') + pTabs(1) + d('padding:12px 16px 24px;display:flex;flex-direction:column;gap:12px;', segRow(2, '') + cardsE.cons + cardsE.heat) })));
  NEXT = 1015;
  const fieldTable = panel(620, tx('l',C.t2,'Every number → its server field') + `<div style="display:grid;grid-template-columns:150px 1fr;">` + [
    [`${pctA}%`, 'user_stats.secured_days ÷ user_stats.due_days, rounded. Hidden while due_days < 7.'],
    [`${CA.S} of ${dueA}`, 'user_stats.secured_days · user_stats.due_days (secured + held + missed; today excluded until it ends)'],
    ['7 · 18', 'user_stats.current_streak · user_stats.best_streak, with best_streak_start / best_streak_end'],
    ['Heat map', 'day_secures[date].state for the last 84 days: secured, held, missed, none (before joining or no task due)'],
    ['4 of 4 · 27 of 30', 'enrollments[].secured_days of enrollments[].due_days; status running | finished; finished_at'],
    ['28 · 4 · 0', 'user_stats.proofs_by_method.camera / self_reported / apple_health; % computed client-side'],
    ['5–6 am · 24 of 32', 'user_stats.proof_hour_histogram[0..23] in the user’s time zone; window = modal hour. Hidden while proofs < 5.'],
    [`Days secured ${CA.S}`, 'Profile header = user_stats.secured_days, the same field as the data tab'] ].map(([a,b],i)=>d(`${T.h}color:${C.t1};padding:8px 12px 8px 0;border-top:${i?`1px solid ${C.raised}`:'none'};`, a) + d(`${T.s}color:${C.t2};padding:8px 0;border-top:${i?`1px solid ${C.raised}`:'none'};`, b)).join('') + '</div>' +
    tx('s',C.t2,'One endpoint, GET /me/stats, returns user_stats + day_secures + enrollments. Only you see your data tab; other people’s profiles keep Proofs, Challenges and Badges (decision 219).'));

  // ================= 3 · APPLE HEALTH =================
  CUR = FL7.health;
  const AH = [];
  const setBase = (healthRow, extra='') => page('Settings', lab('Connections') + grp([healthRow]) + extra + lab('Notifications') + grp([{ i:'bell', l:'Reminders', v:'7:00 am' }, { i:'users', l:'Respect and comments', v:'On' }]) + lab('Account') + grp([{ i:'user', l:'Edit profile' }, { i:'lock', l:'Privacy' }]));
  const viaNote = tx('c',C.t2,'Strava, Garmin Connect and Nike Run Club write workouts to Apple Health. Connect it once and GRIIT reads them from there.','padding:0 4px;');
  AH.push(F7('ahOff', { route:'settings', comp:'SettingsScreen', state:'Apple Health row · not connected', src:'v48 12 Settings', fields:'health.status ← local: not_requested | requested | has_data' }, phone({ time:'9:41', body: setBase({ i:'run', l:'Apple Health', s:'Runs, workouts and steps', v:'Connect' }, viaNote) })));
  const bullet = (i, t, s) => flex('gap:12px;align-items:flex-start;', d(`width:36px;height:36px;border-radius:999px;background:${C.surf};display:flex;align-items:center;justify-content:center;flex:none;`, ic(i,18)) + flex('flex-direction:column;gap:2px;flex:1;', tx('h',C.t1,t) + tx('s',C.t2,s)));
  AH.push(F7('ahPre', { route:'settings/health', comp:'HealthPrePrompt', state:'Pre-prompt · one Continue', src:'new', fields:'Continue → HKHealthStore.requestAuthorization(read: workouts, distanceWalkingRunning, stepCount, activeEnergy)' }, phone({ time:'9:41', body: stepHead('','') + d('padding:12px 24px 0;display:flex;flex-direction:column;gap:20px;', d(`width:64px;height:64px;border-radius:18px;background:${C.surf};display:flex;align-items:center;justify-content:center;`, ic('run',30)) + tx('tl',C.t1,'Let your runs complete tasks') + flex('flex-direction:column;gap:18px;', bullet('run','Reads workouts, distance and steps','Nothing else. Heart rate and sleep stay private.') + bullet('lock','Never writes to Apple Health','GRIIT only reads.') + bullet('check','Labelled “From Apple Health”','GRIIT reads the numbers. It doesn’t check them.'))), sticky: btnP('Continue') + tx('c',C.t2,'Next, iOS asks which data to share.','text-align:center;padding-top:4px;'), stickyH:96 })));
  AH.push(F7('ahOn', { route:'settings', comp:'SettingsScreen', state:'Connected · last workout read', src:'new', fields:'last ← most recent HKWorkout matched, with sourceRevision.source.name' }, phone({ time:'9:41', body: setBase({ i:'run', l:'Apple Health', s:'Reading workouts, distance and steps', v:'On' }, d(`background:${C.surf};border-radius:16px;padding:12px 14px;display:flex;flex-direction:column;gap:4px;`, tx('c',C.t2,'Last workout read') + tx('h',C.t1,'Run · 5.2 km · 27:41') + tx('s',C.t2,'Today 6:12 am · from Strava')) + viaNote) })));
  AH.push(F7('ahDenied', { route:'settings', comp:'SettingsScreen', state:'Denied / no data · how to turn it on', src:'new', fields:'iOS hides read denial: shown when authorization was requested but no workout or step sample is readable' }, phone({ time:'9:41', body: setBase({ i:'run', l:'Apple Health', s:'No data readable', v:'Off' }, d(`background:${C.surf};border-radius:16px;padding:14px;display:flex;flex-direction:column;gap:10px;`, flex('align-items:center;gap:8px;', ic('alert',18) + tx('h',C.t1,'GRIIT can’t see your workouts')) + tx('s',C.t2,'Turn it on in the Health app: your profile → Apps → GRIIT → Turn On All. Run tasks need a photo until then.') + btnS('Open Health',{icon:'arrow'}))) })));
  const runSec = (st) => ({ name:'Run 21', day:'Day 9 of 21', done: st==='done'?1:0, total:1, tasks:[{ name:'Run 5 km', gate:[['run','Apple Health'],[null,'5 km']], st, right: st==='done' ? tx('c',C.t2,'5.2 km') : tx('c',C.t2,'Waiting for a run') }] });
  AH.push(F7('ahWait', { route:'(tabs)/index', comp:'HomeScreen', state:'Run task waiting for a recorded run', src:'new', fields:'task.verify = apple_health · target 5 km · window = the task day' }, phone({ time:'5:58', tab:'home', body: home({ streak:7, week:W_B, prog:0, line:'3 tasks left today.', primary:btnP('Out of bed',{icon:'check'}), sections:[runSec('open'), secBed('open'), secRead('open')] }) })));
  const ahToast = d(`position:absolute;left:10px;right:10px;bottom:95px;z-index:16;background:${C.raised};border-radius:18px;padding:12px 12px 4px;display:flex;flex-direction:column;gap:10px;box-shadow:0 8px 24px rgba(0,0,0,0.5);`,
    flex('gap:12px;align-items:center;', d(`width:44px;height:44px;border-radius:12px;background:${C.surf};display:flex;align-items:center;justify-content:center;flex:none;`, ic('run',22)) + flex('flex:1;flex-direction:column;gap:2px;', tx('h',C.t1,'Run 5 km is done') + tx('s',C.t2,'From Apple Health · 5.2 km in 27:41'))) +
    d(`height:52px;border-radius:999px;background:${C.surf};box-shadow:inset 0 0 0 1.5px ${C.t1};display:flex;align-items:center;justify-content:center;gap:10px;`, sp(T.h+'color:'+C.t1+';','Share this run to the feed') + ic('share',18)) +
    flex('align-items:center;justify-content:space-between;', tx('c',C.t2,'No answer keeps it private.') + btnT('Keep it to the record', C.t2)));
  AH.push(F7('ahDone', { route:'(tabs)/index', comp:'TaskCompleteToast', state:'Completed from a recorded workout', src:'v48.1 scToast', fields:'match: HKWorkoutActivityType.running, distance ≥ target, start inside the task window, first match only · proof.method = apple_health' }, phone({ time:'6:41', tab:'home', body: home({ streak:7, week:W_B, prog:0.33, line:'2 tasks left today.', primary:btnP('Out of bed',{icon:'check'}), sections:[runSec('done'), secBed('open'), secRead('open')] }), toast: ahToast })));
  const proofBody = stepHead('Run 5 km','Run 21 · Day 9 of 21',{back:true}) + d('padding:16px 16px 0;display:flex;flex-direction:column;gap:16px;',
    flex('align-items:center;gap:10px;', av('hamza',40) + flex('flex-direction:column;flex:1;', tx('h',C.t1,PPL.hamza[0]) + tx('s',C.t2,'6:41 am · Wed, Oct 7, 2026'))) +
    d(`background:${C.surf};border-radius:16px;padding:18px 16px;display:flex;flex-direction:column;gap:16px;`, flex('align-items:baseline;gap:8px;', sp(NUM+`font-size:64px;line-height:64px;color:${C.t1};`, '5.2') + tx('t',C.t2,'km')) +
      d('display:grid;grid-template-columns:repeat(3,1fr);gap:8px;', [['27:41','Time'],['5:19 /km','Avg pace'],['6:12 am','Started']].map(([v,l])=>flex('flex-direction:column;', sp(NUM+`font-size:20px;line-height:24px;font-weight:700;color:${C.t1};`, v) + tx('c',C.t2,l))).join(''))) +
    d(`border-radius:16px;box-shadow:inset 0 0 0 1px ${C.raised};padding:14px 16px;display:flex;flex-direction:column;gap:6px;`, flex('align-items:center;gap:8px;', ic('run',18) + tx('h',C.t1,'From Apple Health')) + tx('s',C.t2,'Workout from Strava, read at 6:41 am. GRIIT reads the distance and time; it doesn’t check them.')) +
    tx('b',C.t1,'Legs were heavy for the first two.'));
  AH.push(F7('ahProof', { route:'proof/[id]', comp:'ProofViewer · health', state:'Proof view · From Apple Health, never “Verified”', src:'v39 viewer', fields:'distance, duration, start ← HKWorkout · source ← sourceRevision.source.name · read_at ← proofs.created_at' }, phone({ time:'9:41', body: proofBody, sticky: flex('gap:12px;', [['heart','21'],['msg','4'],['share','2']].map(([i,n])=>btnS(n,{icon:i,flex:1})).join('')), stickyH:68 })));
  NEXT = 1061;
  const radio = (on) => d(`width:22px;height:22px;border-radius:999px;box-sizing:border-box;flex:none;${on?`background:${C.t1};display:flex;align-items:center;justify-content:center;`:`border:1.5px solid ${C.t3};`}`, on?d(`width:8px;height:8px;border-radius:999px;background:${C.ink};`):'');
  const opt = (on, i, l, sub, extra='') => d(`background:${C.surf};border-radius:14px;padding:12px 14px;display:flex;flex-direction:column;gap:10px;${on?`box-shadow:inset 0 0 0 1.5px ${C.t1};`:''}`, flex('align-items:center;gap:12px;min-height:32px;', ic(i,20) + flex('flex-direction:column;flex:1;', tx('h',C.t1,l) + tx('c',C.t2,sub)) + radio(on)) + extra);
  const metric = (sel) => flex('flex-direction:column;gap:2px;padding-top:4px;border-top:1px solid '+C.raised+';', [['Steps','Daily total'],['Workout minutes','Any workout, added up for the day'],['Distance','One run or walk']].map(([l,sub],k)=>flex('align-items:center;gap:12px;min-height:44px;', flex('flex-direction:column;flex:1;', tx('b',C.t1,l) + tx('c',C.t2,sub)) + radio(k===sel))).join(''));
  const target = (v, unit, line) => flex('flex-direction:column;gap:6px;', flex('align-items:center;gap:10px;', d(`width:120px;height:48px;border-radius:12px;background:${C.raised};display:flex;align-items:center;padding:0 14px;${T.h}color:${C.t1};font-size:17px;`, v) + tx('b',C.t2,unit)) + tx('c',C.t2,line));
  const createTask = (o) => stepHead('Add a task','Step 2 of 3') + d(`margin:0 16px;height:3px;border-radius:2px;background:${C.raised};`, d(`width:66%;height:100%;background:${C.t1};border-radius:2px;`)) + d('padding:16px 16px 0;display:flex;flex-direction:column;gap:10px;',
    tx('c',C.t2,'Task name') + d(`min-height:48px;border-radius:12px;background:${C.surf};display:flex;align-items:center;padding:0 14px;${T.b}color:${C.t1};`, o.name) + lab('How it’s proved') +
    opt(false,'camera','Camera','A live photo') + opt(false,'check','Self-reported','Tap to mark it done') + opt(true,'run','From Apple Health', o.sub || 'Steps, workout minutes or distance', o.inner||''));
  const CT = [];
  CT.push(F7('cMetric', { route:'create/tasks', comp:'TaskProofPicker', state:'From Apple Health · pick a metric and target', src:'v48 11 Create', fields:'task.verify = apple_health · task.metric = steps | workout_minutes | distance · task.target' }, phone({ time:'9:41', body: createTask({ name:'Walk 8,000 steps', inner: metric(0) + target('8,000','steps a day','Done when Apple Health shows 8,000 steps between 12 am and 11:59 pm. The proof reads “From Apple Health”.') }), sticky: btnP('Continue'), stickyH:72 })));
  CT.push(F7('cMetricDist', { route:'create/tasks', comp:'TaskProofPicker', state:'Distance metric · one run or walk', src:'new' }, phone({ time:'9:41', body: createTask({ name:'Run 5 km', inner: metric(2) + target('5','km in one go','Done when one run or walk of 5 km lands in Apple Health that day.') }), sticky: btnP('Continue'), stickyH:72 })));
  const preSheet = sheet(d(`width:56px;height:56px;border-radius:16px;background:${C.raised};display:flex;align-items:center;justify-content:center;`, ic('run',26)) + tx('t',C.t1,'Read steps and workouts from Apple Health') + bullet('run','Steps, workouts and distance only','Nothing else is read.') + bullet('lock','Never writes to Apple Health','GRIIT only reads.') + bullet('check','Labelled “From Apple Health”','Never “Verified”.') + btnP('Continue') + tx('c',C.t2,'Next, iOS asks which data to share.','text-align:center;'));
  CT.push(F7('cPre', { route:'create/tasks', comp:'HealthPrePrompt · sheet', state:'First time choosing From Apple Health · one Continue', src:'v49 ahPre', fields:'shown once, while health.status = not_requested' }, phone({ time:'9:41', body: createTask({ name:'Walk 8,000 steps' }), overlay: preSheet })));
  CT.push(F7('cDenied', { route:'create/tasks', comp:'TaskProofPicker', state:'Asked, but nothing readable · Continue off', src:'new', fields:'health.status = requested and no readable samples (iOS hides denial)' }, phone({ time:'9:41', body: createTask({ name:'Walk 8,000 steps', sub:'Not sharing with GRIIT', inner: d(`border-top:1px solid ${C.raised};padding-top:10px;display:flex;flex-direction:column;gap:8px;`, flex('align-items:center;gap:8px;', ic('alert',18) + tx('h',C.t1,'Apple Health isn’t sharing data with GRIIT')) + tx('s',C.t2,'Turn it on in the Health app: your profile → Apps → GRIIT → Turn On All.') + flex('gap:8px;', btnS('Open Health',{icon:'arrow'}) + btnS('Use a photo instead'))) }), sticky: btnP('Continue',{off:true}), stickyH:72 })));
  const moveSec = (right) => ({ name:'Move 14', day:'Day 3 of 14', done:0, total:1, tasks:[{ name:'Walk 8,000 steps', gate:[['run','From Apple Health'],[null,'8,000 steps']], st:'open', right }] });
  CT.push(F7('cNoDataHome', { route:'(tabs)/index', comp:'HomeScreen', state:'Health has no data for today yet', src:'new', fields:'today_total ← HKStatisticsQuery(stepCount, today) = 0 or none' }, phone({ time:'7:40', tab:'home', body: home({ streak:7, week:W_B, prog:0, line:'3 tasks left today.', primary:btnP('Read 10 pages',{icon:'camera'}), sections:[moveSec(tx('c',C.t2,'No data yet')), secRead('open'), secBed('open')] }) })));
  CT.push(F7('cNoData', { route:'task/[id]', comp:'HealthTaskDetail', state:'No data today · what to check', src:'new', fields:'re-checked on app open and by HKObserverQuery background delivery' }, phone({ time:'7:40', body: stepHead('Walk 8,000 steps','Move 14 · Day 3 of 14',{back:true}) + d('padding:40px 24px 0;display:flex;flex-direction:column;align-items:center;gap:8px;text-align:center;', flex('align-items:baseline;gap:8px;', sp(NUM+`font-size:64px;line-height:64px;color:${C.t1};`, '0') + tx('t',C.t2,'of 8,000 steps')) + tx('b',C.t1,'Apple Health has no steps for today yet.') + tx('s',C.t2,'If you’ve been walking, open Health and check your iPhone or Watch is counting steps. GRIIT checks again when you come back.','max-width:300px;') + d('height:8px') + btnS('Open Health',{icon:'arrow'}) + tx('c',C.t2,'From Apple Health · the day stays open until 11:59 pm','padding-top:12px;')) })));
  const cRules = panelR(620, 'Create rules for Apple Health tasks', [['Metric','Steps (daily total) · Workout minutes (any type, added up) · Distance (one run or walk, km or mi from Region).'],['Target','One number. Steps 1,000–50,000 · minutes 5–300 · distance 0.5–100.'],['Permission','Choosing From Apple Health the first time opens the sheet; Continue → iOS. Later choices skip it.'],['Not sharing','Continue stays off; offer Open Health or Use a photo instead.'],['No data today','The task stays open with “No data yet”; never a miss before 11:59 pm.'],['Copy','“From Apple Health” everywhere. Never “Verified”.']], '110px 1fr');
  const ahRules = panelR(620, 'Apple Health rules', [
    ['Label','“From Apple Health”, plus the source app when known (“From Apple Health · Strava”). Never “Verified”, never the camera seal.'],
    ['Sources','No direct Strava, Garmin or Nike connection. They write into Apple Health; GRIIT reads Apple Health only.'],
    ['Metrics','Steps (daily total) · Workout minutes (any type, summed for the day) · Distance (one run or walk). Chosen in Create.'],
    ['Matching','First qualifying workout inside the task window completes the task once. Steps complete when the day’s total passes the target, checked on app open and by background delivery.'],
    ['Permission','Pre-prompt, then iOS. iOS never tells apps that read access was denied, so “Off” means “asked, but nothing readable”.'],
    ['Fallback','While it’s off or nothing is readable, the task asks for a photo instead. The day stays securable.'],
    ['Feed','A recorded run shares as a card with distance, time, pace and the label. Photo optional.'] ], '110px 1fr');

  // ================= 4 · HOME TOP =================
  CUR = FL7.home;
  const band = (o) => d(`display:flex;align-items:center;gap:12px;min-height:56px;padding:8px 12px 8px 8px;border-radius:14px;background:${C.surf};`, d('position:relative;width:44px;height:55px;border-radius:8px;overflow:hidden;flex:none;', img('book1') + d('position:absolute;left:3px;top:3px;transform:scale(0.55);transform-origin:0 0;', seal())) + flex('flex:1;min-width:0;flex-direction:column;gap:2px;', d(T.s+'color:'+C.t2+';', sp(T.h+'color:'+C.t1+';','Khalid') + ' posted 12m ago') + tx('c',C.t2, o&&o.few ? 'Read 10 pages · Read 30' : 'Omar and 3 others too')) + (o&&o.few?'':flex('', ['omar','abd','bilal'].map((k,i)=>d(i?'margin-left:-7px;':'', av(k,24,C.surf))).join(''))) + ic('cd',18,C.t2));
  const W1 = ['pre','sec','today','fut','fut','fut','fut'];
  const gA = (t) => d('padding:12px 16px 0;', tx('h',C.t2,t));
  const gB = (t, sub) => d('padding:14px 16px 2px;display:flex;flex-direction:column;gap:2px;', tx('t',C.t1,t) + tx('s',C.t2,sub));
  const H4 = { A:[], B:[] };
  const gF = 'greeting ← local hour (4–11 morning · 12–16 afternoon · 17–21 evening · 22–3 “Still up”) + first word of profiles.display_name';
  NEXT = 1025; // 1022–1024 were option 4a, removed from the handoff
  const homeNoLine = (o) => home({ ...o, line:'' });
  H4.B.push(F7('gB_mid', { route:'(tabs)/index', comp:'HomeTop', state:'9:41 mid-day · greeting carries today’s move', src:'v48.2 909', fields:gF + ' · sub ← next open task' }, phone({ time:'9:41', tab:'home', body: gB('Good morning, Yaseen','Read 10 pages is all that’s left today.') + homeNoLine({ streak:7, week:W_B, prog:0.5, banner:band(), primary:btnP('Read 10 pages',{icon:'camera'}), sections:[secRead('open'), secBed('done')] }) })));
  H4.B.push(F7('gB_new', { route:'(tabs)/index', comp:'HomeTop', state:'1 day secured · strip counts your first 7 days', src:'new', fields:'first week: strip = days 1–7 from enrollments.min(started_on); calendar week from day 8' }, phone({ time:'9:41', tab:'home', body: gB('Good morning, Yaseen','Day 2 of your first week.') + d('padding:4px 16px 0;display:flex;flex-direction:column;gap:12px;', streakBlock(1, ['sec','today','fut','fut','fut','fut','fut'], { prog:0 }).replace(/>M</,'>1<') + band({few:true}) + btnP('Read 10 pages',{icon:'camera'})) + d('padding:22px 16px 0;display:flex;flex-direction:column;gap:8px;', tx('t',C.t1,'Today') + section(secRead('open'))) })));
  H4.B.push(F7('gB_eve', { route:'(tabs)/index', comp:'HomeTop', state:'Evening · day secured', src:'new' }, phone({ time:'8:10', tab:'home', body: gB('Good evening, Yaseen','Day secured. See you tomorrow.') + homeNoLine({ streak:8, week:['sec','sec','sec','sec','sec','sec','todayDone'], banner:band(), primary:btnS('Share today',{icon:'share'}), sections:[secRead('done',{collapsed:true}), secBed('done',undefined,{collapsed:true})] }) })));
  // first-week strip letters: patch the strip HTML for gB_new and gA_new
  const fixStrip = (k, letters) => { const f = REG[k]; let i = 0; f.html = f.html.replace(/(font-size:11px;line-height:13px;color:#[0-9A-F]{6};">)([MTWFS])(<\/div>)/g, (m,a,b,c)=> i<7 ? a + letters[i++] + c : m); };
  fixStrip('gB_new', '1234567');
  const gRules = panelR(560, 'Greeting rules', [
    ['Where','Above the streak block. The streak stays the first number on screen.'],
    ['Copy','“Good morning / afternoon / evening, Yaseen”. 22:00–3:59: “Still up, Yaseen”. First name only; falls back to @handle. No emoji, no exclamation marks.'],
        ['Layout','20pt title + one line that says today’s move; it replaces the “1 of 2 left today” line, so Home gains only 24pt.'],
    ['First week','Days before you joined never show as misses. The strip counts days 1–7 until day 8.'] ], '90px 1fr');

  // ================= page =================
  const badge = (id) => d(`height:28px;min-width:28px;padding:0 10px;border-radius:999px;background:${C.t1};display:flex;align-items:center;justify-content:center;${T.h}color:${C.ink};flex:none;`, id);
  const optBox = (id, title, why, frames) => `<div id="${id}" data-screen-label="Option ${id}" style="display:flex;flex-direction:column;gap:18px;padding:24px;border-radius:24px;box-shadow:inset 0 0 0 1px ${C.raised};">` + flex('align-items:center;gap:12px;', badge(id) + tx('t',C.t1,title)) + tx('s',C.t2,why,'max-width:900px;text-wrap:pretty;') + wrapRow(frames) + '</div>';
  const sec = (id, eyebrow, title, purpose, body, score) => `<div style="display:flex;flex-direction:column;gap:22px;">` + areaHead(id, eyebrow, title, purpose, '') + d(`align-self:flex-start;display:flex;align-items:baseline;gap:10px;padding:8px 14px;border-radius:12px;background:${C.surf};`, sp(NUM+`font-size:22px;color:${C.t1};`, score[0]) + tx('s',C.t2,score[1])) + body + '</div>';
  const SC = {
    feed:['9.0','/10 · X-style column, counts, quiet activity, photo zoom with swipe-down and 1 of 2.'],
    data:['9.0','/10 · one source per number; 7d / 30d / All for every chart; empty state at 0 days.'],
    health:['8.9','/10 · Create step, permission, not sharing and no data drawn. Limit: iOS can’t report read denial.'],
    home:['8.9','/10 · Option B: streak-first, the greeting names the move, the first week counts up.'] };
  const pages = [['v1', FL7.feed, '1 Feed post'], ['v2', FL7.data, '2 Your data'], ['v3', FL7.health, '3 Apple Health'], ['v4', FL7.home, '4 Home top']];
  const navOf = (cur) => flex('flex-wrap:wrap;gap:8px;', [[encodeURI(FL7.page),'v49 overview']].concat(pages.map(([id,f,l])=>[encodeURI(f)+'#'+id, l])).concat([[encodeURI(FL7.page)+'#dec','Decisions'],[encodeURI(FL7.b4)+'#indexAll','Full atlas index']]).map(([h,l])=>`<a href="${h}" style="${T.s}padding:8px 14px;border-radius:999px;background:${l===cur?C.t1:C.surf};color:${l===cur?C.ink:C.t1};">${l}</a>`).join(''));
  const intro = d('display:flex;flex-direction:column;gap:14px;max-width:1100px;', tx('l',C.t2,'GRIIT v49 · on the approved v48 system') + d(T.tl+'font-size:40px;line-height:46px;color:'+C.t1+';', 'Feed post, your data, Apple Health, Home top') + tx('b',C.t2,`Same tokens, laws, check strips, safe areas and seeded people. ${B7.length} new frames from 1001 across four part pages, all in the full index. Build 77 screenshots aren’t in the project yet (uploads hold build 64 and older), so every strip reads “Built in 77: pending”.`) + navOf('v49 overview'));
  const dec = `<div id="dec" style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Decisions · approved', 'All six approved as drawn.') + panelR(900, 'Approved', [
    ['216 · Seed','Days secured on Profile becomes 28 (was 23). Best 18 + current 7 can’t fit in 23; 28 is what the heat map adds up to.'],
    ['217 · Counts','Respect, comment and share counts are public on every post. Zero shows no number.'],
    ['218 · Share','Share count = card shares + copied links, not views.'],
    ['219 · Data','Your data is visible only to you. Percent hidden until 7 due days; time of day until 5 proofs.'],
    ['220 · Health','Steps, workout minutes and distance can be Apple Health tasks. While Health isn’t sharing, they ask for a photo.'],
    ['221 · Home','Option B ships: the greeting carries today’s move. Option A removed.'] ], '130px 1fr') + '</div>';
  const scoreCards = d('display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px;max-width:1200px;', [['feed','v1',FL7.feed,'1 · Feed post'],['data','v2',FL7.data,'2 · Your data'],['health','v3',FL7.health,'3 · Apple Health'],['home','v4',FL7.home,'4 · Home top']].map(([k,id,f,l])=>`<a href="${encodeURI(f)}#${id}" style="display:flex;flex-direction:column;gap:6px;padding:18px;border-radius:20px;background:${C.surf};color:${C.t1};">` + tx('l',C.t2,l) + sp(NUM+'font-size:40px;line-height:44px;color:'+C.t1+';', SC[k][0]) + tx('s',C.t2,SC[k][1].replace('/10 · ','')) + '</a>').join(''));
  const wrapB = (inner) => `<div style="filter:{{ filt }};font-family:${FONT};color:${C.t1};padding:48px;display:flex;flex-direction:column;gap:64px;background:${C.ink};">` + inner + '</div>';
  const partHead = (l) => d('display:flex;flex-direction:column;gap:12px;', tx('l',C.t2,'GRIIT v49') + navOf(l));
  const bodies = {
    [FL7.page]: wrapB([intro, scoreCards, dec].join('\n')),
    [FL7.feed]: wrapB(partHead('1 Feed post') + sec('v1','Part 1 · Feed post','A post like X or Threads','More to react to, less bland. Within 3 seconds: who, which challenge and day, what they did, and how to respond.', wrapRow(FD.slice(0,3)) + wrapRow(FD.slice(3,6).concat([fRules])) + wrapRow(FD.slice(6)) + `<div style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Photo zoom','Tap a photo: full screen, swipe down to close, swipe sideways between photos.') + wrapRow(ZM.concat([zRules])) + '</div>', SC.feed)),
    [FL7.data]: wrapB(partHead('2 Your data') + sec('v2','Part 2 · Profile → Your data','Your data, WHOOP / Garmin style','How consistent am I, really? Within 3 seconds: one percentage, the streaks behind it, and where the gaps were.', wrapRow(DT.slice(0,3).concat([fieldTable])) + wrapRow(DT.slice(3,5)) + `<div style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Range: 7d / 30d / All','Inverted segment (Text 1 fill, ink label), no orange. Streaks stay all-time.') + wrapRow(RF) + matrix + '</div>' + `<div style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Challenges tab, clearer','Running first, then finished. One block per day, one plain sentence per challenge.') + wrapRow([DT[5]]) + '</div>', SC.data)),
    [FL7.health]: wrapB(partHead('3 Apple Health') + sec('v3','Part 3 · Apple Health','Runs that complete themselves','Connect once; recorded workouts complete run, workout and steps tasks. Within 3 seconds: it was recorded, by what, and nothing more is claimed.', wrapRow(AH.slice(0,4)) + wrapRow(AH.slice(4).concat([ahRules])) + `<div style="display:flex;flex-direction:column;gap:14px;">` + stripHead('Create: a task proved from Apple Health','Pick the metric, see the permission sheet once, and what happens when Health isn’t sharing or has nothing for today.') + wrapRow(CT.concat([cRules])) + '</div>', SC.health)),
    [FL7.home]: wrapB(partHead('4 Home top') + sec('v4','Part 4 · Home top','Personal, still streak-first · Option B','A greeting above the streak, and a first week that doesn’t read as failure. Option B ships.', wrapRow(H4.B) + gRules, SC.home)) };
  // index
  const all = ORDER.filter(k => REG[k].n >= 301).sort((a,b)=>REG[a].n-REG[b].n);
  const batchOf = (n) => n>=1001?'v49':n>=901?'4.2':n>=801?'4.1':n>=701?'4':n>=601?'3':n>=501?'2':'1R';
  const counts = {}; all.forEach(k=>{ const b = batchOf(REG[k].n); counts[b]=(counts[b]||0)+1; });
  const summary = flex('gap:12px;flex-wrap:wrap;', [['Frames', all.length],['1R',counts['1R']],['2',counts['2']],['3',counts['3']],['4',counts['4']],['4.1',counts['4.1']],['4.2',counts['4.2']],['v49',counts['v49']]].map(([l,n])=>d(`background:${C.surf};border-radius:14px;padding:12px 16px;display:flex;flex-direction:column;min-width:96px;`, sp(NUM+'font-size:28px;color:'+C.t1+';', n) + tx('c',C.t2,l))).join(''));
  const rows = all.map(k=>{ const f = REG[k]; const b = batchOf(f.n); return [`<a href="${href(k)}" style="color:${C.t1};">${f.n}</a>`, b, f.route, f.comp, f.state, f.src||'new', (b==='v49'?'77: ':'75: ') + (f.b75||'pending')]; });
  const idxAll = `<div id="indexAll" data-screen-label="Full atlas index" style="display:flex;flex-direction:column;gap:14px;">` + stripHead(`The atlas index · every frame, batches 1R–4, patches 4.1–4.2 and v49 (${all.length})`, 'Frame · batch · route · component · state · source frame · built in (75 for v48, 77 for v49). Every number links to its frame.') + summary +
    panel(1500, `<div style="display:grid;grid-template-columns:56px 44px 200px 230px 1fr 150px 230px;max-width:1460px;">` + [['#','Batch','Route','Component','State','Source','Built in']].concat(rows).map((r,ri)=>r.map((c,i)=>d(`${ri===0?T.c+'color:'+C.t2+';':(i===0?T.h:T.s)+'color:'+C.t1+';'}padding:8px 12px 8px 0;border-top:${ri?`1px solid ${C.raised}`:'none'};`, c)).join('')).join('') + '</div>') + '</div>';
  let hub = pages6[FL7.b4];
  hub = hub.slice(0, hub.indexOf('<div id="indexAll"')) + idxAll + '\n</div>';
  hub = hub.replace('>Patch 4.2</a>', `>Patch 4.2</a><a href="${encodeURI(FL7.page)}" style="${T.s}padding:8px 14px;border-radius:999px;background:${C.surf};color:${C.t1};">v49</a>`);
  return { ...pages6, [FL7.b4]: hub, ...bodies };
}
