import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";
import Typography from "@/constants/typography";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  flex: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
  },
  stepperWrap: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  headerTitle: {
    ...Typography.pageTitle,
    color: Colors.text.primary,
    marginBottom: 16,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    ...Typography.sectionHeader,
    color: Colors.text.primary,
    marginBottom: 4,
  },
  stepSubtitle: {
    ...Typography.body,
    color: Colors.text.secondary,
    marginBottom: 8,
  },
  stepHelper: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    marginBottom: 20,
  },
  fieldGroup: {
    marginBottom: 20,
  },
  label: {
    ...Typography.meta,
    color: Colors.text.secondary,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  labelOptional: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    marginBottom: 6,
  },
  optionalPurposeTrigger: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: "dashed",
    backgroundColor: Colors.card,
  },
  optionalPurposeTriggerText: {
    ...Typography.body,
    color: Colors.text.tertiary,
  },
  categoryGroupSecondary: {
    marginTop: 4,
  },
  input: {
    backgroundColor: Colors.card,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Typography.body,
    color: Colors.text.primary,
  },
  textArea: {
    minHeight: 80,
    paddingTop: 14,
  },
  durationRow: {
    flexDirection: "row",
    gap: 8,
  },
  durationChip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  durationChipActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  durationChipText: {
    ...Typography.meta,
    color: Colors.text.secondary,
    fontWeight: "600" as const,
  },
  durationChipTextActive: {
    color: "#fff",
  },
  durationInput: {
    flex: 1,
    backgroundColor: Colors.card,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Typography.meta,
    color: Colors.text.primary,
    textAlign: "center",
  },
  durationInputActive: {
    borderColor: Colors.accent,
  },
  durationHint: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    marginTop: 6,
  },
  categoryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  categoryChipActive: {
    backgroundColor: Colors.accentLight,
    borderColor: Colors.accent,
  },
  categoryChipText: {
    ...Typography.meta,
    color: Colors.text.secondary,
  },
  categoryChipTextActive: {
    color: Colors.accent,
  },
  taskList: {
    gap: 8,
    marginBottom: 16,
  },
  taskCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.card,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  taskCardLeft: {
    marginRight: 8,
  },
  taskCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  taskCardContent: {
    flex: 1,
  },
  taskCardTitle: {
    ...Typography.cardTitle,
    color: Colors.text.primary,
    fontSize: 15,
  },
  taskCardMeta: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    marginTop: 2,
  },
  taskCardAction: {
    padding: 8,
  },
  taskCardEdit: {
    ...Typography.meta,
    color: Colors.accent,
  },
  addTaskCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.accentLight,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.accent,
    borderStyle: "dashed",
  },
  addTaskIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  addTaskText: {
    ...Typography.cardTitle,
    color: Colors.accent,
  },
  taskBuilderOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  taskBuilderSafeArea: {
    flex: 1,
    justifyContent: "flex-end",
  },
  taskBuilderKeyboardView: {
    width: "100%",
  },
  taskBuilderSheet: {
    backgroundColor: Colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "85%",
  },
  sheetHandle: {
    alignItems: "center",
    paddingVertical: 8,
  },
  sheetHandleBar: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.border,
  },
  taskBuilderHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  taskBuilderTitle: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: Colors.text.primary,
  },
  taskBuilderClose: {
    padding: 4,
  },
  fixedSection: {
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  compactFieldGroup: {
    marginBottom: 12,
  },
  compactLabel: {
    fontSize: 11,
    fontWeight: "600" as const,
    color: Colors.text.secondary,
    marginBottom: 6,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  compactInput: {
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    fontSize: 15,
    color: Colors.text.primary,
  },
  taskBuilderScroll: {
    flex: 1,
  },
  taskBuilderScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 16,
  },
  taskTypeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  taskTypeCard: {
    width: "31%",
    backgroundColor: Colors.background,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.border,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: "center",
    gap: 6,
  },
  taskTypeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  taskTypeLabel: {
    fontSize: 11,
    fontWeight: "500" as const,
    color: Colors.text.primary,
    textAlign: "center",
  },
  verificationSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  verificationLabel: {
    ...Typography.meta,
    color: Colors.text.secondary,
    marginBottom: 8,
  },
  verificationInput: {
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Typography.body,
    color: Colors.text.primary,
    marginBottom: 8,
  },
  verificationHint: {
    ...Typography.meta,
    color: Colors.text.tertiary,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  toggleBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  toggleBoxActive: {
    backgroundColor: Colors.success,
    borderColor: Colors.success,
  },
  toggleLabel: {
    ...Typography.body,
    color: Colors.text.secondary,
    fontSize: 14,
  },
  lockedOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.background,
    padding: 12,
    borderRadius: 8,
  },
  lockedOptionText: {
    ...Typography.body,
    color: Colors.text.secondary,
    fontSize: 14,
  },
  stickyActions: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.card,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: Colors.background,
    alignItems: "center",
  },
  cancelButtonText: {
    ...Typography.cardTitle,
    color: Colors.text.secondary,
  },
  addTaskButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: Colors.accent,
    alignItems: "center",
  },
  addTaskButtonDisabled: {
    backgroundColor: Colors.pill,
    opacity: 0.5,
  },
  addTaskButtonText: {
    ...Typography.cardTitle,
    color: "#fff",
  },
  trackingModeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  trackingModeBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
  },
  trackingModeBtnActive: {
    backgroundColor: Colors.accentLight,
    borderColor: Colors.accent,
  },
  trackingModeText: {
    ...Typography.body,
    color: Colors.text.secondary,
    fontWeight: "600" as const,
  },
  trackingModeTextActive: {
    color: Colors.accent,
  },
  distanceRow: {
    gap: 8,
  },
  distanceInput: {
    marginBottom: 0,
  },
  unitSelector: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  unitBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
  },
  unitBtnActive: {
    backgroundColor: Colors.accentLight,
    borderColor: Colors.accent,
  },
  unitBtnText: {
    ...Typography.meta,
    color: Colors.text.secondary,
    fontWeight: "600" as const,
  },
  unitBtnTextActive: {
    color: Colors.accent,
  },
  reviewCard: {
    backgroundColor: Colors.card,
    padding: 20,
    borderRadius: 16,
    marginBottom: 24,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  reviewTitle: {
    ...Typography.sectionHeader,
    color: Colors.text.primary,
    flex: 1,
  },
  reviewDescription: {
    ...Typography.body,
    color: Colors.text.secondary,
    marginBottom: 12,
  },
  reviewMeta: {
    flexDirection: "row",
    gap: 8,
  },
  reviewBadge: {
    backgroundColor: Colors.pill,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  reviewBadgeText: {
    ...Typography.meta,
    color: Colors.text.secondary,
  },
  reviewSummaryCard: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  reviewSummaryTitle: {
    ...Typography.sectionHeader,
    color: Colors.text.primary,
    marginBottom: 6,
  },
  reviewSummaryMeta: {
    gap: 4,
    marginBottom: 8,
  },
  reviewSummaryMetaText: {
    ...Typography.meta,
    color: Colors.text.secondary,
  },
  reviewSummaryDesc: {
    ...Typography.body,
    color: Colors.text.secondary,
    fontSize: 14,
    lineHeight: 20,
  },
  reviewSectionTitle: {
    ...Typography.cardTitle,
    color: Colors.text.primary,
    marginBottom: 12,
  },
  reviewTaskList: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 24,
  },
  reviewTaskRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  reviewTaskIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  reviewTaskTitle: {
    ...Typography.body,
    color: Colors.text.primary,
    flex: 1,
  },
  reviewTaskMeta: {
    ...Typography.meta,
    color: Colors.text.tertiary,
  },
  reviewNote: {
    backgroundColor: Colors.successLight,
    padding: 14,
    borderRadius: 10,
  },
  reviewNoteText: {
    ...Typography.body,
    color: Colors.success,
    textAlign: "center",
    fontSize: 14,
  },
  reviewBadgeDaily: {
    backgroundColor: "#FF6B3515",
  },
  reviewBadgeTextDaily: {
    color: "#FF6B35",
  },
  reviewLiveDate: {
    ...Typography.meta,
    color: Colors.text.secondary,
    marginTop: 12,
  },
  challengeTypeRow: {
    flexDirection: "row",
    gap: 10,
  },
  challengeTypeCard: {
    flex: 1,
    backgroundColor: Colors.card,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  challengeTypeCardActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentLight,
  },
  challengeTypeLabel: {
    ...Typography.cardTitle,
    color: Colors.text.primary,
    marginBottom: 4,
  },
  challengeTypeLabelActive: {
    color: Colors.accent,
  },
  challengeTypeDesc: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    fontSize: 12,
  },
  replayPolicyRow: {
    flexDirection: "row",
    gap: 10,
  },
  replayPolicyCard: {
    flex: 1,
    backgroundColor: Colors.card,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  replayPolicyCardActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accentLight,
  },
  replayPolicyLabel: {
    ...Typography.cardTitle,
    color: Colors.text.primary,
    marginBottom: 4,
    fontSize: 14,
  },
  replayPolicyLabelActive: {
    color: Colors.accent,
  },
  replayPolicyDesc: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    fontSize: 11,
  },
  replayToggleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
    paddingVertical: 4,
  },
  replayToggleBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
  },
  replayToggleBoxActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  replayToggleContent: {
    flex: 1,
  },
  replayToggleLabel: {
    ...Typography.body,
    color: Colors.text.primary,
    fontSize: 15,
    marginBottom: 2,
  },
  replayToggleDesc: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    fontSize: 13,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.card,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  backButtonText: {
    ...Typography.body,
    color: Colors.text.secondary,
  },
  footerSpacer: {
    flex: 1,
  },
  nextButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.accent,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    gap: 4,
  },
  nextButtonDisabled: {
    opacity: 0.5,
  },
  nextButtonText: {
    ...Typography.cardTitle,
    color: "#fff",
  },
  createButton: {
    backgroundColor: Colors.success,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  createButtonDisabled: {
    opacity: 0.5,
  },
  createButtonText: {
    ...Typography.cardTitle,
    color: "#fff",
  },
  locationChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#0EA5E915",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  locationChipText: {
    ...Typography.body,
    color: "#0EA5E9",
    flex: 1,
    fontSize: 14,
  },
  locationInputRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  locationInput: {
    flex: 1,
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Typography.body,
    color: Colors.text.primary,
  },
  locationAddBtn: {
    backgroundColor: "#0EA5E9",
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  locationAddBtnText: {
    ...Typography.cardTitle,
    color: "#fff",
    fontSize: 14,
  },
  addLocationBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
  },
  addLocationBtnText: {
    ...Typography.body,
    color: "#0EA5E9",
    fontSize: 14,
  },
  timeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  timeInput: {
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Typography.body,
    color: Colors.text.primary,
    width: 100,
  },
  timeHint: {
    ...Typography.meta,
    color: Colors.text.tertiary,
  },
  strictTogglesSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  strictTogglesTitle: {
    ...Typography.cardTitle,
    color: Colors.text.primary,
    marginBottom: 4,
  },
  strictTogglesHint: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    marginBottom: 12,
  },
  strictToggleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
    paddingVertical: 4,
  },
  strictToggleBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
  },
  strictToggleBoxActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  strictToggleContent: {
    flex: 1,
  },
  strictToggleLabel: {
    ...Typography.body,
    color: Colors.text.primary,
    fontSize: 15,
    marginBottom: 2,
  },
  strictToggleDesc: {
    ...Typography.meta,
    color: Colors.text.tertiary,
    fontSize: 13,
  },
});
