import { StyleSheet } from "react-native";
import * as t from "@/src/theme/tokens";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9F6F1",
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: "700" as const,
    color: "#1A1A2E",
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "400" as const,
    color: "#8A8A8A",
    marginTop: 4,
  },
  searchRow: {
    paddingHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
  },
  categoryRow: {
    marginTop: 12,
    marginBottom: 12,
  },
  categoryScroll: {
    paddingHorizontal: 16,
    gap: 8,
  },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 20,
    marginBottom: 10,
    paddingVertical: 6,
    gap: 6,
  },
  errorBannerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  errorBannerText: {
    fontSize: 11,
    fontWeight: "500" as const,
    color: t.colors.chipText,
  },
  retryPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  retryPillText: {
    fontSize: 11,
    fontWeight: "600" as const,
    color: t.colors.chipText,
    textDecorationLine: "underline" as const,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: t.colors.chipFill,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: t.colors.textPrimary,
    marginBottom: 6,
  },
  emptySubtext: {
    fontSize: 14,
    color: t.colors.textSecondary,
    textAlign: "center",
    lineHeight: 20,
  },
  clearButton: {
    marginTop: 16,
    paddingHorizontal: t.spacing.screenHorizontal,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: t.colors.textPrimary,
  },
  clearButtonText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#fff",
  },
  emptyRefreshButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 14,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: t.colors.accentOrange,
  },
  emptyRefreshText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: t.colors.accentOrange,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 8,
  },
  section: {
    marginTop: 24,
    marginBottom: t.spacing.sectionVertical,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: t.colors.textPrimary,
    letterSpacing: -0.2,
  },
  sectionCaption: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
    marginLeft: "auto" as const,
  },
  featuredList: {
    paddingHorizontal: t.spacing.screenHorizontal,
    gap: 16,
  },
  featuredCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0EDE8",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  featuredAccent: {
    width: 3,
    alignSelf: "stretch",
  },
  featuredContent: {
    flex: 1,
    padding: 18,
    minWidth: 0,
  },
  featuredTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  featuredBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
  },
  featuredBadgeText: {
    fontSize: 10,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  difficultyPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  difficultyText: {
    fontSize: 10,
    fontWeight: "800" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.4,
  },
  featuredTitle: {
    fontSize: 20,
    fontWeight: "800" as const,
    color: t.colors.textPrimary,
    letterSpacing: -0.4,
    marginBottom: 6,
  },
  featuredHook: {
    fontSize: 14,
    color: t.colors.textSecondary,
    lineHeight: 20,
    marginBottom: 12,
  },
  featuredTaskPreview: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  taskChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: t.colors.chipFill,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  taskChipEmoji: {
    fontSize: 12,
  },
  taskChipText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
    maxWidth: 120,
  },
  featuredBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
  },
  featuredStats: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  statText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
  },
  statDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: t.colors.textSecondary,
  },
  activeTodayText: {
    fontSize: 12,
    fontWeight: "600" as const,
    color: t.colors.successGreenText,
  },
  featuredArrowWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: t.colors.chipFill,
    alignItems: "center",
    justifyContent: "center",
  },
  compactList: {
    paddingHorizontal: t.spacing.screenHorizontal,
    gap: 10,
  },
  compactCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0EDE8",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  compactColorBar: {
    width: 3,
    alignSelf: "stretch",
  },
  compactContent: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    minWidth: 0,
  },
  compactHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  compactTitle: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: t.colors.textPrimary,
    flex: 1,
    letterSpacing: -0.2,
  },
  difficultyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  compactDesc: {
    fontSize: 13,
    color: t.colors.textSecondary,
    lineHeight: 18,
    marginBottom: 8,
  },
  compactMeta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 4,
  },
  compactMetaText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
  },
  compactParticipants: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
  },
  compactArrowWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: t.colors.chipFill,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  bottomSpacer: {
    height: 32,
  },
  loadMoreWrap: {
    paddingVertical: 20,
    alignItems: "center",
  },
  loadMoreBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: t.colors.accentOrange,
    minWidth: 120,
    alignItems: "center",
    justifyContent: "center",
  },
  loadMoreText: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: "#fff",
  },

  dailyScrollContent: {
    paddingHorizontal: t.spacing.screenHorizontal,
    gap: t.spacing.listItemGap,
    paddingBottom: 4,
  },
  dailyCard: {
    width: 240,
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: t.colors.borderSubtle,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  dailyColorBar: {
    width: 5,
    alignSelf: "stretch",
  },
  dailyCardBody: {
    flex: 1,
    padding: 16,
    minWidth: 0,
  },
  dailyCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  dailyCountdownPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: t.colors.badgeRedBg,
  },
  dailyCountdownText: {
    fontSize: 11,
    fontWeight: "700" as const,
    color: t.colors.badgeRedText,
    letterSpacing: 0.3,
  },
  dailyDiffPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  dailyDiffText: {
    fontSize: 10,
    fontWeight: "700" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  dailyTitle: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: t.colors.textPrimary,
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  dailyHook: {
    fontSize: 12,
    color: t.colors.textSecondary,
    lineHeight: 17,
    marginBottom: 10,
  },
  dailyChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginBottom: 10,
  },
  dailyChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: t.colors.chipFill,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 6,
  },
  dailyChipEmoji: {
    fontSize: 10,
  },
  dailyChipText: {
    fontSize: 11,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
    maxWidth: 80,
  },
  dailyFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dailyParticipants: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dailyParticipantsText: {
    fontSize: 11,
    fontWeight: "500" as const,
    color: t.colors.textSecondary,
  },
  dailyArrow: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: t.colors.chipFill,
    alignItems: "center",
    justifyContent: "center",
  },

  skeletonFeaturedCard: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: t.colors.borderSubtle,
  },
  skeletonAccent: {
    width: 4,
    backgroundColor: "#E5E5E5",
  },
  skeletonFeaturedContent: {
    flex: 1,
    padding: 16,
    gap: 10,
  },
  skeletonTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  skeletonBadge: {
    width: 72,
    height: 20,
    borderRadius: 6,
    backgroundColor: t.colors.chipFill,
  },
  skeletonDiffPill: {
    width: 52,
    height: 20,
    borderRadius: 6,
    backgroundColor: t.colors.chipFill,
  },
  skeletonTitle: {
    width: "75%" as const,
    height: 20,
    borderRadius: 6,
    backgroundColor: t.colors.chipFill,
  },
  skeletonHook: {
    width: "90%" as const,
    height: 14,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonChipsRow: {
    flexDirection: "row",
    gap: 8,
  },
  skeletonChip: {
    width: 80,
    height: 24,
    borderRadius: 8,
    backgroundColor: t.colors.chipFill,
  },
  skeletonChipMed: {
    width: 100,
    height: 24,
    borderRadius: 8,
    backgroundColor: t.colors.chipFill,
  },
  skeletonMeta: {
    width: "50%" as const,
    height: 14,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonCompactCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: t.colors.borderSubtle,
  },
  skeletonCompactBar: {
    width: 4,
    alignSelf: "stretch",
    backgroundColor: "#E5E5E5",
  },
  skeletonCompactContent: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 6,
  },
  skeletonCompactTitle: {
    width: "60%" as const,
    height: 16,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonCompactDesc: {
    width: "80%" as const,
    height: 13,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonCompactMeta: {
    width: "40%" as const,
    height: 12,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonSectionIcon: {
    width: 16,
    height: 16,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonSectionLabel: {
    width: 80,
    height: 16,
    borderRadius: 4,
    backgroundColor: t.colors.chipFill,
  },
  skeletonDailyScroll: {
    paddingHorizontal: t.spacing.screenHorizontal,
    gap: 12,
  },
  skeletonDailyCard: {
    width: 220,
    height: 180,
    borderRadius: 16,
    backgroundColor: t.colors.chipFill,
  },
});
