import { StyleSheet } from "react-native";
import { DS_COLORS } from "@/lib/design-system";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DS_COLORS.background,
  },
  keyboardView: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginBottom: 20,
  },
  modeSelector: {
    flexDirection: "row",
    backgroundColor: DS_COLORS.surface,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  modeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 10,
  },
  modeButtonActive: {
    backgroundColor: DS_COLORS.accent,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textSecondary,
  },
  modeButtonTextActive: {
    color: DS_COLORS.white,
  },
  requirementCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.darkSurface,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 12,
  },
  requirementText: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: DS_COLORS.white,
    flex: 1,
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.warningLight,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginBottom: 20,
  },
  warningText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.amberDarkText,
    flex: 1,
  },
  statsContainer: {
    alignItems: "center",
  },
  mainStat: {
    alignItems: "center",
    marginBottom: 24,
  },
  distanceValue: {
    fontSize: 64,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
  },
  distanceComplete: {
    color: DS_COLORS.success,
  },
  distanceLabel: {
    fontSize: 16,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
    marginTop: 4,
  },
  secondaryStats: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DS_COLORS.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    width: "100%",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  statValue: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: DS_COLORS.border,
    marginHorizontal: 16,
  },
  progressBarContainer: {
    width: "100%",
    marginBottom: 24,
  },
  progressBar: {
    height: 8,
    backgroundColor: DS_COLORS.grayLight,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: DS_COLORS.accent,
    borderRadius: 4,
  },
  progressFillComplete: {
    backgroundColor: DS_COLORS.success,
  },
  progressFillError: {
    backgroundColor: DS_COLORS.dangerMid,
  },
  progressText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center",
  },
  controlsContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  startButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: DS_COLORS.accent,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 30,
  },
  startButtonComplete: {
    backgroundColor: DS_COLORS.success,
  },
  startButtonError: {
    backgroundColor: DS_COLORS.silverRank,
  },
  startButtonText: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
  },
  stopButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: DS_COLORS.dangerMid,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 30,
  },
  stopButtonText: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
  },
  resetButton: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  resetButtonText: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: DS_COLORS.textSecondary,
  },
  trackingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 20,
  },
  trackingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: DS_COLORS.success,
  },
  trackingDotTimer: {
    backgroundColor: DS_COLORS.taskAmber,
  },
  trackingText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.success,
  },
  trackingTextTimer: {
    color: DS_COLORS.taskAmber,
  },
  treadmillContainer: {
    flex: 1,
  },
  stepsIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  stepDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: DS_COLORS.grayLight,
  },
  stepDotActive: {
    backgroundColor: DS_COLORS.accent,
  },
  stepDotComplete: {
    backgroundColor: DS_COLORS.success,
  },
  stepLine: {
    width: 40,
    height: 2,
    backgroundColor: DS_COLORS.grayLight,
  },
  stepLineComplete: {
    backgroundColor: DS_COLORS.success,
  },
  stepsLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    marginBottom: 24,
  },
  stepLabel: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.textMuted,
  },
  stepLabelActive: {
    color: DS_COLORS.accent,
    fontWeight: "600" as const,
  },
  timerSection: {
    alignItems: "center",
  },
  violationBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.dangerLightBg,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 16,
    width: "100%",
  },
  violationText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.dangerMid,
  },
  lockNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: DS_COLORS.warningLight,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 16,
  },
  lockNoticeText: {
    fontSize: 13,
    fontWeight: "600" as const,
    color: DS_COLORS.amberDarkText,
    textAlign: "center",
  },
  proofSection: {
    alignItems: "center",
  },
  proofTitle: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
  },
  proofSubtitle: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  captureButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: DS_COLORS.accent,
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 16,
  },
  captureButtonText: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
  },
  proofPreview: {
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  proofImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    backgroundColor: DS_COLORS.surface,
    marginBottom: 12,
  },
  retakeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  retakeButtonText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
  },
  continueButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: DS_COLORS.accent,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
  },
  continueButtonText: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
  },
  distanceSection: {
    alignItems: "center",
  },
  proofThumbnail: {
    position: "relative",
    marginBottom: 20,
  },
  thumbnailImage: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: DS_COLORS.surface,
  },
  proofCheck: {
    position: "absolute",
    bottom: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: DS_COLORS.success,
    alignItems: "center",
    justifyContent: "center",
  },
  inputGroup: {
    width: "100%",
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
  },
  input: {
    backgroundColor: DS_COLORS.surface,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    color: DS_COLORS.textPrimary,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  inputError: {
    borderColor: DS_COLORS.dangerMid,
  },
  inputErrorText: {
    fontSize: 12,
    fontWeight: "500" as const,
    color: DS_COLORS.dangerMid,
    marginTop: 6,
  },
  summaryCard: {
    width: "100%",
    backgroundColor: DS_COLORS.surface,
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
  },
  summaryTitle: {
    fontSize: 14,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  summaryLabel: {
    fontSize: 14,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
  },
  summaryValue: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  summaryValueText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
  },
  footer: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: DS_COLORS.border,
    backgroundColor: DS_COLORS.background,
  },
  verifyButton: {
    backgroundColor: DS_COLORS.darkSurface,
    paddingVertical: 18,
    borderRadius: 14,
    alignItems: "center",
  },
  verifyButtonDisabled: {
    backgroundColor: DS_COLORS.grayLight,
  },
  verifyButtonText: {
    fontSize: 15,
    fontWeight: "700" as const,
    color: DS_COLORS.white,
    letterSpacing: 0.5,
  },
  verifyButtonTextDisabled: {
    color: DS_COLORS.textMuted,
  },
  verifiedContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  verifiedBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: DS_COLORS.successSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  verifiedTitle: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: DS_COLORS.textPrimary,
    marginBottom: 8,
  },
  verifiedSubtitle: {
    fontSize: 15,
    fontWeight: "500" as const,
    color: DS_COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 32,
  },
  backButton: {
    backgroundColor: DS_COLORS.surface,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: DS_COLORS.border,
  },
  backButtonText: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: DS_COLORS.textPrimary,
  },
});
