import { StyleSheet } from "react-native";
import { DS_COLORS_V2, DS_V3 } from "@/lib/design-system";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: DS_COLORS_V2.surface.canvas },
  body: { flex: 1, paddingHorizontal: 24, paddingBottom: 34, gap: 12 },
  title: { fontSize: 28, fontWeight: "500", color: DS_COLORS_V2.text.primary, letterSpacing: -0.8 },
  bodyText: { fontSize: 15, color: DS_COLORS_V2.text.body, lineHeight: 22 },
  gate: { fontSize: 15, color: DS_COLORS_V2.text.body },
  eyebrowInk: { fontSize: 11, letterSpacing: 1.6, color: DS_COLORS_V2.text.mutedWarm },
  switchCard: {
    backgroundColor: DS_COLORS_V2.surface.card,
    borderRadius: 20,
    paddingHorizontal: 20,
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  switchLabel: { fontSize: 15, color: DS_COLORS_V2.text.primary },
  switchSub: { fontSize: 12, color: DS_COLORS_V2.text.mutedWarm },
  card: { backgroundColor: DS_COLORS_V2.surface.card, borderRadius: 18, padding: 14 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  rowWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  bigNum: { fontSize: 32, fontWeight: "500", letterSpacing: -1.3, color: DS_COLORS_V2.text.primary, fontVariant: ["tabular-nums"] },
  countLine: { flexDirection: "row", alignItems: "baseline", flexWrap: "wrap" },
  huge: { fontSize: 84, fontWeight: "500", letterSpacing: -3.5, color: DS_COLORS_V2.text.primary, fontVariant: ["tabular-nums"] },
  unit: {
    fontSize: DS_V3.type.caption.fontSize,
    lineHeight: DS_V3.type.caption.lineHeight,
    fontWeight: DS_V3.type.caption.fontWeight,
    color: DS_V3.color.textSecondary,
  },
  statLabel: { fontSize: 11, letterSpacing: 0.8, color: DS_COLORS_V2.text.mutedWarm },
  unitBtn: { minWidth: 52, height: 44, borderRadius: 12, backgroundColor: DS_COLORS_V2.surface.sunken, alignItems: "center", justifyContent: "center" },
  unitBtnText: { fontSize: 13, color: DS_COLORS_V2.text.primary },
  chip: { paddingHorizontal: 12, minHeight: 44, borderRadius: 12, backgroundColor: DS_COLORS_V2.surface.sunken, justifyContent: "center" },
  chipOn: { backgroundColor: DS_COLORS_V2.brand.primarySoft },
  chipText: { fontSize: 13, color: DS_COLORS_V2.text.primary },
  dashBtn: { height: 48, borderRadius: 14, borderWidth: 1.5, borderStyle: "dashed", borderColor: DS_COLORS_V2.surface.borderDashed, alignItems: "center", justifyContent: "center" },
  dashText: { fontSize: 14, color: DS_COLORS_V2.text.body },
  disclosure: { fontSize: 13, color: DS_COLORS_V2.text.mutedDark },
  tiny: { fontSize: 11, color: DS_COLORS_V2.text.mutedDark },
  orangeBtn: { height: 56, borderRadius: 16, backgroundColor: DS_COLORS_V2.brand.primary, alignItems: "center", justifyContent: "center" },
  inkBtn: { height: 56, borderRadius: 16, backgroundColor: DS_COLORS_V2.text.primary, alignItems: "center", justifyContent: "center" },
  disabledBtn: { backgroundColor: DS_COLORS_V2.surface.track },
  btnText: { color: DS_COLORS_V2.brand.primaryText, fontSize: 16, fontWeight: "500" },
  inkBtnText: { color: DS_COLORS_V2.text.onDark, fontSize: 16, fontWeight: "500" },
  outlineBtn: { height: 52, borderRadius: 16, borderWidth: 1.5, borderColor: DS_COLORS_V2.surface.borderStrong, alignItems: "center", justifyContent: "center" },
  outlineText: { fontSize: 15, color: DS_COLORS_V2.text.primary },
  textBtn: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  shareText: { fontSize: 15, color: DS_COLORS_V2.text.body },
  pill: { alignSelf: "flex-start", backgroundColor: DS_COLORS_V2.surface.sunken, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12, fontSize: 13, color: DS_COLORS_V2.text.body },
  editor: { flex: 1, fontSize: 17, lineHeight: 25.5, color: DS_COLORS_V2.text.primary, textAlignVertical: "top" },
  addOne: { width: 132, height: 132, borderRadius: 66, backgroundColor: DS_COLORS_V2.text.primary, alignItems: "center", justifyContent: "center", alignSelf: "center" },
  addOneText: { color: DS_COLORS_V2.text.onDark, fontSize: 16, fontWeight: "500" },
  finder: { width: "100%", aspectRatio: 4 / 5, backgroundColor: DS_COLORS_V2.surface.camera, overflow: "hidden" },
  retake: { position: "absolute", top: 14, right: 14, minHeight: 44, paddingHorizontal: 16, borderRadius: 18, backgroundColor: "rgba(10,10,10,0.6)", justifyContent: "center" },
  retakeText: { color: DS_COLORS_V2.text.onDark, fontSize: 13 },
  capOverlay: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 18, paddingTop: 44, paddingBottom: 16 },
  cap70: { color: "rgba(255,255,255,0.7)", fontSize: 13 },
  cap92: { color: "rgba(255,255,255,0.92)", fontSize: 15, marginTop: 2 },
  cap100: { color: DS_COLORS_V2.text.onDark, fontSize: 15, marginTop: 2 },
  reviewDeck: { flex: 1, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 34, justifyContent: "space-between" },
  capRow: { flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: DS_COLORS_V2.surface.borderStrong, height: 44 },
  capInput: { flex: 1, fontSize: 15, color: DS_V3.color.textPrimary },
  counter: { fontSize: 12, color: DS_COLORS_V2.text.mutedDark },
  modal: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,10,0.4)", alignItems: "center", justifyContent: "center", padding: 24 },
  modalCard: { width: "100%", backgroundColor: DS_COLORS_V2.surface.card, borderRadius: 22, padding: 24, gap: 12 },
});
